/* DialogUtils.c generated by valac 0.50.2, the Vala compiler
 * generated from DialogUtils.vala, do not modify */

/*
 * Copyright (C) 2017-2021 Lains
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <glib-object.h>
#include <handy.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG (quilter_services_dialog_utils_dialog_get_type ())
#define QUILTER_SERVICES_DIALOG_UTILS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG, QuilterServicesDialogUtilsDialog))
#define QUILTER_SERVICES_DIALOG_UTILS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG, QuilterServicesDialogUtilsDialogClass))
#define QUILTER_SERVICES_DIALOG_UTILS_IS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG))
#define QUILTER_SERVICES_DIALOG_UTILS_IS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG))
#define QUILTER_SERVICES_DIALOG_UTILS_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG, QuilterServicesDialogUtilsDialogClass))

typedef struct _QuilterServicesDialogUtilsDialog QuilterServicesDialogUtilsDialog;
typedef struct _QuilterServicesDialogUtilsDialogClass QuilterServicesDialogUtilsDialogClass;
typedef struct _QuilterServicesDialogUtilsDialogPrivate QuilterServicesDialogUtilsDialogPrivate;

#define QUILTER_TYPE_MAIN_WINDOW (quilter_main_window_get_type ())
#define QUILTER_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindow))
#define QUILTER_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindowClass))
#define QUILTER_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_MAIN_WINDOW))
#define QUILTER_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_MAIN_WINDOW))
#define QUILTER_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindowClass))

typedef struct _QuilterMainWindow QuilterMainWindow;
typedef struct _QuilterMainWindowClass QuilterMainWindowClass;
enum  {
	QUILTER_SERVICES_DIALOG_UTILS_DIALOG_0_PROPERTY,
	QUILTER_SERVICES_DIALOG_UTILS_DIALOG_NUM_PROPERTIES
};
static GParamSpec* quilter_services_dialog_utils_dialog_properties[QUILTER_SERVICES_DIALOG_UTILS_DIALOG_NUM_PROPERTIES];

#define QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG2 (quilter_services_dialog_utils_dialog2_get_type ())
#define QUILTER_SERVICES_DIALOG_UTILS_DIALOG2(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG2, QuilterServicesDialogUtilsDialog2))
#define QUILTER_SERVICES_DIALOG_UTILS_DIALOG2_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG2, QuilterServicesDialogUtilsDialog2Class))
#define QUILTER_SERVICES_DIALOG_UTILS_IS_DIALOG2(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG2))
#define QUILTER_SERVICES_DIALOG_UTILS_IS_DIALOG2_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG2))
#define QUILTER_SERVICES_DIALOG_UTILS_DIALOG2_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG2, QuilterServicesDialogUtilsDialog2Class))

typedef struct _QuilterServicesDialogUtilsDialog2 QuilterServicesDialogUtilsDialog2;
typedef struct _QuilterServicesDialogUtilsDialog2Class QuilterServicesDialogUtilsDialog2Class;
typedef struct _QuilterServicesDialogUtilsDialog2Private QuilterServicesDialogUtilsDialog2Private;
enum  {
	QUILTER_SERVICES_DIALOG_UTILS_DIALOG2_0_PROPERTY,
	QUILTER_SERVICES_DIALOG_UTILS_DIALOG2_NUM_PROPERTIES
};
static GParamSpec* quilter_services_dialog_utils_dialog2_properties[QUILTER_SERVICES_DIALOG_UTILS_DIALOG2_NUM_PROPERTIES];

struct _QuilterServicesDialogUtilsDialog {
	GtkMessageDialog parent_instance;
	QuilterServicesDialogUtilsDialogPrivate * priv;
	QuilterMainWindow* win;
};

struct _QuilterServicesDialogUtilsDialogClass {
	GtkMessageDialogClass parent_class;
};

struct _QuilterServicesDialogUtilsDialog2 {
	GtkMessageDialog parent_instance;
	QuilterServicesDialogUtilsDialog2Private * priv;
	QuilterMainWindow* win;
};

struct _QuilterServicesDialogUtilsDialog2Class {
	GtkMessageDialogClass parent_class;
};

static gpointer quilter_services_dialog_utils_dialog_parent_class = NULL;
static gpointer quilter_services_dialog_utils_dialog2_parent_class = NULL;

GtkFileChooserNative* quilter_services_dialog_utils_create_file_chooser (const gchar* title,
                                                                         GtkFileChooserAction action);
GType quilter_services_dialog_utils_dialog_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterServicesDialogUtilsDialog, g_object_unref)
GType quilter_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterMainWindow, g_object_unref)
QuilterServicesDialogUtilsDialog* quilter_services_dialog_utils_dialog_new (void);
QuilterServicesDialogUtilsDialog* quilter_services_dialog_utils_dialog_construct (GType object_type);
static GObject * quilter_services_dialog_utils_dialog_constructor (GType type,
                                                            guint n_construct_properties,
                                                            GObjectConstructParam * construct_properties);
static void _quilter_services_dialog_utils_dialog___lambda26_ (QuilterServicesDialogUtilsDialog* self);
static void __quilter_services_dialog_utils_dialog___lambda26__gtk_button_clicked (GtkButton* _sender,
                                                                            gpointer self);
static void quilter_services_dialog_utils_dialog_finalize (GObject * obj);
static GType quilter_services_dialog_utils_dialog_get_type_once (void);
GType quilter_services_dialog_utils_dialog2_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterServicesDialogUtilsDialog2, g_object_unref)
QuilterServicesDialogUtilsDialog2* quilter_services_dialog_utils_dialog2_new (void);
QuilterServicesDialogUtilsDialog2* quilter_services_dialog_utils_dialog2_construct (GType object_type);
static GObject * quilter_services_dialog_utils_dialog2_constructor (GType type,
                                                             guint n_construct_properties,
                                                             GObjectConstructParam * construct_properties);
static void _quilter_services_dialog_utils_dialog2___lambda51_ (QuilterServicesDialogUtilsDialog2* self);
static void __quilter_services_dialog_utils_dialog2___lambda51__gtk_button_clicked (GtkButton* _sender,
                                                                             gpointer self);
static void quilter_services_dialog_utils_dialog2_finalize (GObject * obj);
static GType quilter_services_dialog_utils_dialog2_get_type_once (void);

static gpointer
_g_object_ref0 (gpointer self)
{
#line 23 "../src/Services/DialogUtils.vala"
	return self ? g_object_ref (self) : NULL;
#line 131 "DialogUtils.c"
}

GtkFileChooserNative*
quilter_services_dialog_utils_create_file_chooser (const gchar* title,
                                                   GtkFileChooserAction action)
{
	GtkFileChooserNative* chooser = NULL;
	GtkFileChooserNative* _tmp0_;
	GtkFileFilter* filter1 = NULL;
	GtkFileFilter* _tmp1_;
	GtkFileFilter* _tmp2_;
	GtkFileFilter* filter = NULL;
	GtkFileFilter* _tmp3_;
	GtkFileFilter* _tmp4_;
	GtkFileChooserNative* result = NULL;
#line 18 "../src/Services/DialogUtils.vala"
	g_return_val_if_fail (title != NULL, NULL);
#line 19 "../src/Services/DialogUtils.vala"
	_tmp0_ = gtk_file_chooser_native_new (title, NULL, action, NULL, NULL);
#line 19 "../src/Services/DialogUtils.vala"
	chooser = _tmp0_;
#line 20 "../src/Services/DialogUtils.vala"
	_tmp1_ = gtk_file_filter_new ();
#line 20 "../src/Services/DialogUtils.vala"
	g_object_ref_sink (_tmp1_);
#line 20 "../src/Services/DialogUtils.vala"
	filter1 = _tmp1_;
#line 21 "../src/Services/DialogUtils.vala"
	gtk_file_filter_set_name (filter1, _ ("Markdown files"));
#line 22 "../src/Services/DialogUtils.vala"
	gtk_file_filter_add_pattern (filter1, "*.md");
#line 23 "../src/Services/DialogUtils.vala"
	_tmp2_ = _g_object_ref0 (filter1);
#line 23 "../src/Services/DialogUtils.vala"
	gtk_file_chooser_add_filter ((GtkFileChooser*) chooser, _tmp2_);
#line 24 "../src/Services/DialogUtils.vala"
	_tmp3_ = gtk_file_filter_new ();
#line 24 "../src/Services/DialogUtils.vala"
	g_object_ref_sink (_tmp3_);
#line 24 "../src/Services/DialogUtils.vala"
	filter = _tmp3_;
#line 25 "../src/Services/DialogUtils.vala"
	gtk_file_filter_set_name (filter, _ ("All files"));
#line 26 "../src/Services/DialogUtils.vala"
	gtk_file_filter_add_pattern (filter, "*");
#line 27 "../src/Services/DialogUtils.vala"
	_tmp4_ = _g_object_ref0 (filter);
#line 27 "../src/Services/DialogUtils.vala"
	gtk_file_chooser_add_filter ((GtkFileChooser*) chooser, _tmp4_);
#line 28 "../src/Services/DialogUtils.vala"
	gtk_file_chooser_set_select_multiple ((GtkFileChooser*) chooser, TRUE);
#line 29 "../src/Services/DialogUtils.vala"
	result = chooser;
#line 29 "../src/Services/DialogUtils.vala"
	_g_object_unref0 (filter);
#line 29 "../src/Services/DialogUtils.vala"
	_g_object_unref0 (filter1);
#line 29 "../src/Services/DialogUtils.vala"
	return result;
#line 191 "DialogUtils.c"
}

QuilterServicesDialogUtilsDialog*
quilter_services_dialog_utils_dialog_construct (GType object_type)
{
	QuilterServicesDialogUtilsDialog * self = NULL;
#line 35 "../src/Services/DialogUtils.vala"
	self = (QuilterServicesDialogUtilsDialog*) g_object_new (object_type, "text", _ ("Save Open File?"), "secondary-text", _ ("There are unsaved changes to the file, any changes will be lost if not" \
" saved."), NULL);
#line 34 "../src/Services/DialogUtils.vala"
	return self;
#line 202 "DialogUtils.c"
}

QuilterServicesDialogUtilsDialog*
quilter_services_dialog_utils_dialog_new (void)
{
#line 34 "../src/Services/DialogUtils.vala"
	return quilter_services_dialog_utils_dialog_construct (QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG);
#line 210 "DialogUtils.c"
}

static void
_quilter_services_dialog_utils_dialog___lambda26_ (QuilterServicesDialogUtilsDialog* self)
{
#line 44 "../src/Services/DialogUtils.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 218 "DialogUtils.c"
}

static void
__quilter_services_dialog_utils_dialog___lambda26__gtk_button_clicked (GtkButton* _sender,
                                                                       gpointer self)
{
#line 44 "../src/Services/DialogUtils.vala"
	_quilter_services_dialog_utils_dialog___lambda26_ ((QuilterServicesDialogUtilsDialog*) self);
#line 227 "DialogUtils.c"
}

static GObject *
quilter_services_dialog_utils_dialog_constructor (GType type,
                                                  guint n_construct_properties,
                                                  GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	QuilterServicesDialogUtilsDialog * self;
	GtkWidget* save = NULL;
	GtkWidget* _tmp0_;
	GtkWidget* _tmp1_;
	GtkWidget* cws = NULL;
	GtkWidget* _tmp2_;
	GtkWidget* _tmp3_;
	GtkButton* cancel = NULL;
	GtkWidget* _tmp4_;
	GtkButton* _tmp5_;
	GtkButton* _tmp6_;
#line 40 "../src/Services/DialogUtils.vala"
	parent_class = G_OBJECT_CLASS (quilter_services_dialog_utils_dialog_parent_class);
#line 40 "../src/Services/DialogUtils.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 40 "../src/Services/DialogUtils.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG, QuilterServicesDialogUtilsDialog);
#line 41 "../src/Services/DialogUtils.vala"
	_tmp0_ = gtk_dialog_add_button ((GtkDialog*) self, _ ("Save"), (gint) GTK_RESPONSE_OK);
#line 41 "../src/Services/DialogUtils.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 41 "../src/Services/DialogUtils.vala"
	save = _tmp1_;
#line 42 "../src/Services/DialogUtils.vala"
	_tmp2_ = gtk_dialog_add_button ((GtkDialog*) self, _ ("Close Without Saving"), (gint) GTK_RESPONSE_NO);
#line 42 "../src/Services/DialogUtils.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 42 "../src/Services/DialogUtils.vala"
	cws = _tmp3_;
#line 43 "../src/Services/DialogUtils.vala"
	_tmp4_ = gtk_dialog_add_button ((GtkDialog*) self, _ ("Cancel"), (gint) GTK_RESPONSE_CANCEL);
#line 43 "../src/Services/DialogUtils.vala"
	_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp4_, gtk_button_get_type ()) ? ((GtkButton*) _tmp4_) : NULL);
#line 43 "../src/Services/DialogUtils.vala"
	cancel = _tmp5_;
#line 44 "../src/Services/DialogUtils.vala"
	_tmp6_ = cancel;
#line 44 "../src/Services/DialogUtils.vala"
	g_signal_connect_object (_tmp6_, "clicked", (GCallback) __quilter_services_dialog_utils_dialog___lambda26__gtk_button_clicked, self, 0);
#line 40 "../src/Services/DialogUtils.vala"
	_g_object_unref0 (cancel);
#line 40 "../src/Services/DialogUtils.vala"
	_g_object_unref0 (cws);
#line 40 "../src/Services/DialogUtils.vala"
	_g_object_unref0 (save);
#line 40 "../src/Services/DialogUtils.vala"
	return obj;
#line 284 "DialogUtils.c"
}

static void
quilter_services_dialog_utils_dialog_class_init (QuilterServicesDialogUtilsDialogClass * klass,
                                                 gpointer klass_data)
{
#line 32 "../src/Services/DialogUtils.vala"
	quilter_services_dialog_utils_dialog_parent_class = g_type_class_peek_parent (klass);
#line 32 "../src/Services/DialogUtils.vala"
	G_OBJECT_CLASS (klass)->constructor = quilter_services_dialog_utils_dialog_constructor;
#line 32 "../src/Services/DialogUtils.vala"
	G_OBJECT_CLASS (klass)->finalize = quilter_services_dialog_utils_dialog_finalize;
#line 297 "DialogUtils.c"
}

static void
quilter_services_dialog_utils_dialog_instance_init (QuilterServicesDialogUtilsDialog * self,
                                                    gpointer klass)
{
}

static void
quilter_services_dialog_utils_dialog_finalize (GObject * obj)
{
	QuilterServicesDialogUtilsDialog * self;
#line 32 "../src/Services/DialogUtils.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG, QuilterServicesDialogUtilsDialog);
#line 33 "../src/Services/DialogUtils.vala"
	_g_object_unref0 (self->win);
#line 32 "../src/Services/DialogUtils.vala"
	G_OBJECT_CLASS (quilter_services_dialog_utils_dialog_parent_class)->finalize (obj);
#line 316 "DialogUtils.c"
}

static GType
quilter_services_dialog_utils_dialog_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (QuilterServicesDialogUtilsDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_services_dialog_utils_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterServicesDialogUtilsDialog), 0, (GInstanceInitFunc) quilter_services_dialog_utils_dialog_instance_init, NULL };
	GType quilter_services_dialog_utils_dialog_type_id;
	quilter_services_dialog_utils_dialog_type_id = g_type_register_static (gtk_message_dialog_get_type (), "QuilterServicesDialogUtilsDialog", &g_define_type_info, 0);
	return quilter_services_dialog_utils_dialog_type_id;
}

GType
quilter_services_dialog_utils_dialog_get_type (void)
{
	static volatile gsize quilter_services_dialog_utils_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_services_dialog_utils_dialog_type_id__volatile)) {
		GType quilter_services_dialog_utils_dialog_type_id;
		quilter_services_dialog_utils_dialog_type_id = quilter_services_dialog_utils_dialog_get_type_once ();
		g_once_init_leave (&quilter_services_dialog_utils_dialog_type_id__volatile, quilter_services_dialog_utils_dialog_type_id);
	}
	return quilter_services_dialog_utils_dialog_type_id__volatile;
}

QuilterServicesDialogUtilsDialog2*
quilter_services_dialog_utils_dialog2_construct (GType object_type)
{
	QuilterServicesDialogUtilsDialog2 * self = NULL;
#line 51 "../src/Services/DialogUtils.vala"
	self = (QuilterServicesDialogUtilsDialog2*) g_object_new (object_type, "text", _ ("Remove File From Sidebar?"), "secondary-text", _ ("By removing this file from the Sidebar, any changes will be lost if no" \
"t saved."), NULL);
#line 50 "../src/Services/DialogUtils.vala"
	return self;
#line 348 "DialogUtils.c"
}

QuilterServicesDialogUtilsDialog2*
quilter_services_dialog_utils_dialog2_new (void)
{
#line 50 "../src/Services/DialogUtils.vala"
	return quilter_services_dialog_utils_dialog2_construct (QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG2);
#line 356 "DialogUtils.c"
}

static void
_quilter_services_dialog_utils_dialog2___lambda51_ (QuilterServicesDialogUtilsDialog2* self)
{
#line 60 "../src/Services/DialogUtils.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 364 "DialogUtils.c"
}

static void
__quilter_services_dialog_utils_dialog2___lambda51__gtk_button_clicked (GtkButton* _sender,
                                                                        gpointer self)
{
#line 60 "../src/Services/DialogUtils.vala"
	_quilter_services_dialog_utils_dialog2___lambda51_ ((QuilterServicesDialogUtilsDialog2*) self);
#line 373 "DialogUtils.c"
}

static GObject *
quilter_services_dialog_utils_dialog2_constructor (GType type,
                                                   guint n_construct_properties,
                                                   GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	QuilterServicesDialogUtilsDialog2 * self;
	GtkWidget* save = NULL;
	GtkWidget* _tmp0_;
	GtkWidget* _tmp1_;
	GtkWidget* cws = NULL;
	GtkWidget* _tmp2_;
	GtkWidget* _tmp3_;
	GtkButton* cancel = NULL;
	GtkWidget* _tmp4_;
	GtkButton* _tmp5_;
	GtkButton* _tmp6_;
#line 56 "../src/Services/DialogUtils.vala"
	parent_class = G_OBJECT_CLASS (quilter_services_dialog_utils_dialog2_parent_class);
#line 56 "../src/Services/DialogUtils.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 56 "../src/Services/DialogUtils.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG2, QuilterServicesDialogUtilsDialog2);
#line 57 "../src/Services/DialogUtils.vala"
	_tmp0_ = gtk_dialog_add_button ((GtkDialog*) self, _ ("Save"), (gint) GTK_RESPONSE_OK);
#line 57 "../src/Services/DialogUtils.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 57 "../src/Services/DialogUtils.vala"
	save = _tmp1_;
#line 58 "../src/Services/DialogUtils.vala"
	_tmp2_ = gtk_dialog_add_button ((GtkDialog*) self, _ ("Remove Without Saving"), (gint) GTK_RESPONSE_NO);
#line 58 "../src/Services/DialogUtils.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 58 "../src/Services/DialogUtils.vala"
	cws = _tmp3_;
#line 59 "../src/Services/DialogUtils.vala"
	_tmp4_ = gtk_dialog_add_button ((GtkDialog*) self, _ ("Cancel"), (gint) GTK_RESPONSE_CANCEL);
#line 59 "../src/Services/DialogUtils.vala"
	_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp4_, gtk_button_get_type ()) ? ((GtkButton*) _tmp4_) : NULL);
#line 59 "../src/Services/DialogUtils.vala"
	cancel = _tmp5_;
#line 60 "../src/Services/DialogUtils.vala"
	_tmp6_ = cancel;
#line 60 "../src/Services/DialogUtils.vala"
	g_signal_connect_object (_tmp6_, "clicked", (GCallback) __quilter_services_dialog_utils_dialog2___lambda51__gtk_button_clicked, self, 0);
#line 56 "../src/Services/DialogUtils.vala"
	_g_object_unref0 (cancel);
#line 56 "../src/Services/DialogUtils.vala"
	_g_object_unref0 (cws);
#line 56 "../src/Services/DialogUtils.vala"
	_g_object_unref0 (save);
#line 56 "../src/Services/DialogUtils.vala"
	return obj;
#line 430 "DialogUtils.c"
}

static void
quilter_services_dialog_utils_dialog2_class_init (QuilterServicesDialogUtilsDialog2Class * klass,
                                                  gpointer klass_data)
{
#line 48 "../src/Services/DialogUtils.vala"
	quilter_services_dialog_utils_dialog2_parent_class = g_type_class_peek_parent (klass);
#line 48 "../src/Services/DialogUtils.vala"
	G_OBJECT_CLASS (klass)->constructor = quilter_services_dialog_utils_dialog2_constructor;
#line 48 "../src/Services/DialogUtils.vala"
	G_OBJECT_CLASS (klass)->finalize = quilter_services_dialog_utils_dialog2_finalize;
#line 443 "DialogUtils.c"
}

static void
quilter_services_dialog_utils_dialog2_instance_init (QuilterServicesDialogUtilsDialog2 * self,
                                                     gpointer klass)
{
}

static void
quilter_services_dialog_utils_dialog2_finalize (GObject * obj)
{
	QuilterServicesDialogUtilsDialog2 * self;
#line 48 "../src/Services/DialogUtils.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_SERVICES_DIALOG_UTILS_TYPE_DIALOG2, QuilterServicesDialogUtilsDialog2);
#line 49 "../src/Services/DialogUtils.vala"
	_g_object_unref0 (self->win);
#line 48 "../src/Services/DialogUtils.vala"
	G_OBJECT_CLASS (quilter_services_dialog_utils_dialog2_parent_class)->finalize (obj);
#line 462 "DialogUtils.c"
}

static GType
quilter_services_dialog_utils_dialog2_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (QuilterServicesDialogUtilsDialog2Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_services_dialog_utils_dialog2_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterServicesDialogUtilsDialog2), 0, (GInstanceInitFunc) quilter_services_dialog_utils_dialog2_instance_init, NULL };
	GType quilter_services_dialog_utils_dialog2_type_id;
	quilter_services_dialog_utils_dialog2_type_id = g_type_register_static (gtk_message_dialog_get_type (), "QuilterServicesDialogUtilsDialog2", &g_define_type_info, 0);
	return quilter_services_dialog_utils_dialog2_type_id;
}

GType
quilter_services_dialog_utils_dialog2_get_type (void)
{
	static volatile gsize quilter_services_dialog_utils_dialog2_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_services_dialog_utils_dialog2_type_id__volatile)) {
		GType quilter_services_dialog_utils_dialog2_type_id;
		quilter_services_dialog_utils_dialog2_type_id = quilter_services_dialog_utils_dialog2_get_type_once ();
		g_once_init_leave (&quilter_services_dialog_utils_dialog2_type_id__volatile, quilter_services_dialog_utils_dialog2_type_id);
	}
	return quilter_services_dialog_utils_dialog2_type_id__volatile;
}

