/* ExportUtils.c generated by valac 0.50.2, the Vala compiler
 * generated from ExportUtils.vala, do not modify */

/*
 * Copyright (C) 2017-2021 Lains
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#include <handy.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <webkit2/webkit2.h>
#include <gtksourceview/gtksource.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>

#define QUILTER_TYPE_MAIN_WINDOW (quilter_main_window_get_type ())
#define QUILTER_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindow))
#define QUILTER_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindowClass))
#define QUILTER_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_MAIN_WINDOW))
#define QUILTER_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_MAIN_WINDOW))
#define QUILTER_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindowClass))

typedef struct _QuilterMainWindow QuilterMainWindow;
typedef struct _QuilterMainWindowClass QuilterMainWindowClass;

#define QUILTER_WIDGETS_TYPE_PREVIEW (quilter_widgets_preview_get_type ())
#define QUILTER_WIDGETS_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_PREVIEW, QuilterWidgetsPreview))
#define QUILTER_WIDGETS_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_PREVIEW, QuilterWidgetsPreviewClass))
#define QUILTER_WIDGETS_IS_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_PREVIEW))
#define QUILTER_WIDGETS_IS_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_PREVIEW))
#define QUILTER_WIDGETS_PREVIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_PREVIEW, QuilterWidgetsPreviewClass))

typedef struct _QuilterWidgetsPreview QuilterWidgetsPreview;
typedef struct _QuilterWidgetsPreviewClass QuilterWidgetsPreviewClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _QuilterWidgetsPreviewPrivate QuilterWidgetsPreviewPrivate;

#define QUILTER_WIDGETS_TYPE_EDIT_VIEW (quilter_widgets_edit_view_get_type ())
#define QUILTER_WIDGETS_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_EDIT_VIEW, QuilterWidgetsEditView))
#define QUILTER_WIDGETS_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_EDIT_VIEW, QuilterWidgetsEditViewClass))
#define QUILTER_WIDGETS_IS_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_EDIT_VIEW))
#define QUILTER_WIDGETS_IS_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_EDIT_VIEW))
#define QUILTER_WIDGETS_EDIT_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_EDIT_VIEW, QuilterWidgetsEditViewClass))

typedef struct _QuilterWidgetsEditView QuilterWidgetsEditView;
typedef struct _QuilterWidgetsEditViewClass QuilterWidgetsEditViewClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define __vala_GtkPaperSize_free0(var) ((var == NULL) ? NULL : (var = (_vala_GtkPaperSize_free (var), NULL)))
typedef struct _Block6Data Block6Data;

struct _QuilterWidgetsPreview {
	WebKitWebView parent_instance;
	QuilterWidgetsPreviewPrivate * priv;
	QuilterWidgetsEditView* buf;
	gchar* html;
};

struct _QuilterWidgetsPreviewClass {
	WebKitWebViewClass parent_class;
};

struct _Block6Data {
	int _ref_count_;
	GFile* file;
	gchar* contents;
};

extern QuilterMainWindow* quilter_services_export_utils_window;
QuilterMainWindow* quilter_services_export_utils_window = NULL;
extern GSettings* quilter_application_gsettings;

GType quilter_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterMainWindow, g_object_unref)
GFile* quilter_services_export_utils_export_html (const gchar* file_path);
GType quilter_widgets_preview_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsPreview, g_object_unref)
QuilterWidgetsPreview* quilter_widgets_preview_get_instance (void);
void quilter_widgets_preview_update_html_view (QuilterWidgetsPreview* self);
GFile* quilter_services_export_utils_get_html_from_user (void);
void quilter_services_export_utils_write_file (GFile* file,
                                               const gchar* contents,
                                               gboolean overwrite,
                                               GError** error);
GType quilter_widgets_edit_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsEditView, g_object_unref)
GFile* quilter_services_export_utils_export_pdf (const gchar* file_path);
void quilter_main_window_render_func (QuilterMainWindow* self);
GFile* quilter_services_export_utils_get_pdf_from_user (void);
static void _vala_GtkPaperSize_free (GtkPaperSize* self);
static Block6Data* block6_data_ref (Block6Data* _data6_);
static void block6_data_unref (void * _userdata_);
static void __lambda19_ (Block6Data* _data6_,
                  GObject* obj,
                  GAsyncResult* res);
static void ___lambda19__gasync_ready_callback (GObject* source_object,
                                         GAsyncResult* res,
                                         gpointer self);
static void _g_object_unref0_ (gpointer var);
static inline void _g_list_free__g_object_unref0_ (GList* self);

GFile*
quilter_services_export_utils_export_html (const gchar* file_path)
{
	QuilterWidgetsPreview* _tmp0_;
	QuilterWidgetsPreview* _tmp1_;
	GFile* file = NULL;
	GFile* _tmp16_;
	GError* _inner_error0_ = NULL;
	GFile* result = NULL;
#line 21 "../src/Services/ExportUtils.vala"
	_tmp0_ = quilter_widgets_preview_get_instance ();
#line 21 "../src/Services/ExportUtils.vala"
	_tmp1_ = _tmp0_;
#line 21 "../src/Services/ExportUtils.vala"
	quilter_widgets_preview_update_html_view (_tmp1_);
#line 21 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (_tmp1_);
#line 24 "../src/Services/ExportUtils.vala"
	if (file_path == NULL) {
#line 138 "ExportUtils.c"
		GFile* _tmp2_;
		GFile* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		gchar* _tmp7_;
		gboolean _tmp8_;
#line 25 "../src/Services/ExportUtils.vala"
		_tmp2_ = quilter_services_export_utils_get_html_from_user ();
#line 25 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (file);
#line 25 "../src/Services/ExportUtils.vala"
		file = _tmp2_;
#line 26 "../src/Services/ExportUtils.vala"
		_tmp3_ = file;
#line 26 "../src/Services/ExportUtils.vala"
		_tmp4_ = g_file_get_basename (_tmp3_);
#line 26 "../src/Services/ExportUtils.vala"
		_tmp5_ = _tmp4_;
#line 26 "../src/Services/ExportUtils.vala"
		_tmp6_ = g_utf8_strdown (_tmp5_, (gssize) -1);
#line 26 "../src/Services/ExportUtils.vala"
		_tmp7_ = _tmp6_;
#line 26 "../src/Services/ExportUtils.vala"
		_tmp8_ = !g_str_has_suffix (_tmp7_, ".html");
#line 26 "../src/Services/ExportUtils.vala"
		_g_free0 (_tmp7_);
#line 26 "../src/Services/ExportUtils.vala"
		_g_free0 (_tmp5_);
#line 26 "../src/Services/ExportUtils.vala"
		if (_tmp8_) {
#line 170 "ExportUtils.c"
			GFile* _tmp9_;
			gchar* _tmp10_;
			gchar* _tmp11_;
			gchar* _tmp12_;
			gchar* _tmp13_;
			GFile* _tmp14_;
#line 27 "../src/Services/ExportUtils.vala"
			_tmp9_ = file;
#line 27 "../src/Services/ExportUtils.vala"
			_tmp10_ = g_file_get_path (_tmp9_);
#line 27 "../src/Services/ExportUtils.vala"
			_tmp11_ = _tmp10_;
#line 27 "../src/Services/ExportUtils.vala"
			_tmp12_ = g_strconcat (_tmp11_, ".html", NULL);
#line 27 "../src/Services/ExportUtils.vala"
			_tmp13_ = _tmp12_;
#line 27 "../src/Services/ExportUtils.vala"
			_tmp14_ = g_file_new_for_path (_tmp13_);
#line 27 "../src/Services/ExportUtils.vala"
			_g_object_unref0 (file);
#line 27 "../src/Services/ExportUtils.vala"
			file = _tmp14_;
#line 27 "../src/Services/ExportUtils.vala"
			_g_free0 (_tmp13_);
#line 27 "../src/Services/ExportUtils.vala"
			_g_free0 (_tmp11_);
#line 197 "ExportUtils.c"
		}
	} else {
		GFile* _tmp15_;
#line 30 "../src/Services/ExportUtils.vala"
		_tmp15_ = g_file_new_for_path (file_path);
#line 30 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (file);
#line 30 "../src/Services/ExportUtils.vala"
		file = _tmp15_;
#line 207 "ExportUtils.c"
	}
#line 33 "../src/Services/ExportUtils.vala"
	_tmp16_ = file;
#line 33 "../src/Services/ExportUtils.vala"
	if (_tmp16_ == NULL) {
#line 34 "../src/Services/ExportUtils.vala"
		result = NULL;
#line 34 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (file);
#line 34 "../src/Services/ExportUtils.vala"
		return result;
#line 219 "ExportUtils.c"
	}
	{
		GFile* _tmp17_;
		QuilterWidgetsPreview* _tmp18_;
		QuilterWidgetsPreview* _tmp19_;
		const gchar* _tmp20_;
#line 38 "../src/Services/ExportUtils.vala"
		_tmp17_ = file;
#line 38 "../src/Services/ExportUtils.vala"
		_tmp18_ = quilter_widgets_preview_get_instance ();
#line 38 "../src/Services/ExportUtils.vala"
		_tmp19_ = _tmp18_;
#line 38 "../src/Services/ExportUtils.vala"
		_tmp20_ = _tmp19_->html;
#line 38 "../src/Services/ExportUtils.vala"
		quilter_services_export_utils_write_file (_tmp17_, _tmp20_, FALSE, &_inner_error0_);
#line 38 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (_tmp19_);
#line 38 "../src/Services/ExportUtils.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 240 "ExportUtils.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp21_;
		const gchar* _tmp22_;
#line 37 "../src/Services/ExportUtils.vala"
		e = _inner_error0_;
#line 37 "../src/Services/ExportUtils.vala"
		_inner_error0_ = NULL;
#line 40 "../src/Services/ExportUtils.vala"
		_tmp21_ = e;
#line 40 "../src/Services/ExportUtils.vala"
		_tmp22_ = _tmp21_->message;
#line 40 "../src/Services/ExportUtils.vala"
		g_warning ("ExportUtils.vala:40: Could not write HTML file: %s", _tmp22_);
#line 41 "../src/Services/ExportUtils.vala"
		result = NULL;
#line 41 "../src/Services/ExportUtils.vala"
		_g_error_free0 (e);
#line 41 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (file);
#line 41 "../src/Services/ExportUtils.vala"
		return result;
#line 268 "ExportUtils.c"
	}
	__finally0:
#line 37 "../src/Services/ExportUtils.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 37 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (file);
#line 37 "../src/Services/ExportUtils.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 37 "../src/Services/ExportUtils.vala"
		g_clear_error (&_inner_error0_);
#line 37 "../src/Services/ExportUtils.vala"
		return NULL;
#line 281 "ExportUtils.c"
	}
#line 44 "../src/Services/ExportUtils.vala"
	result = file;
#line 44 "../src/Services/ExportUtils.vala"
	return result;
#line 287 "ExportUtils.c"
}

static void
_vala_GtkPaperSize_free (GtkPaperSize* self)
{
#line 107 "../src/Services/ExportUtils.vala"
	g_boxed_free (gtk_paper_size_get_type (), self);
#line 295 "ExportUtils.c"
}

GFile*
quilter_services_export_utils_export_pdf (const gchar* file_path)
{
	QuilterMainWindow* _tmp0_;
	gint type_of_mode = 0;
	GSettings* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gboolean _tmp4_;
	QuilterWidgetsPreview* _tmp11_;
	QuilterWidgetsPreview* _tmp12_;
	GFile* file = NULL;
	GFile* _tmp27_;
	WebKitPrintOperation* op = NULL;
	QuilterWidgetsPreview* _tmp31_;
	QuilterWidgetsPreview* _tmp32_;
	WebKitPrintOperation* _tmp33_;
	WebKitPrintOperation* _tmp34_;
	GtkPrintSettings* psettings = NULL;
	GtkPrintSettings* _tmp35_;
	GtkPrintSettings* _tmp36_;
	GtkPaperSize* psize = NULL;
	GtkPaperSize* _tmp37_;
	GtkPageSetup* psetup = NULL;
	GtkPageSetup* _tmp38_;
	GtkPageSetup* _tmp39_;
	GtkPageSetup* _tmp40_;
	GtkPageSetup* _tmp41_;
	GtkPageSetup* _tmp42_;
	GtkPageSetup* _tmp43_;
	GtkPaperSize* _tmp44_;
	GtkPrintSettings* _tmp45_;
	GFile* _tmp46_;
	gchar* _tmp47_;
	gchar* _tmp48_;
	WebKitPrintOperation* _tmp49_;
	GtkPrintSettings* _tmp50_;
	WebKitPrintOperation* _tmp51_;
	GtkPageSetup* _tmp52_;
	WebKitPrintOperation* _tmp53_;
	GError* _inner_error0_ = NULL;
	GFile* result = NULL;
#line 48 "../src/Services/ExportUtils.vala"
	_tmp0_ = quilter_services_export_utils_window;
#line 48 "../src/Services/ExportUtils.vala"
	quilter_main_window_render_func (_tmp0_);
#line 49 "../src/Services/ExportUtils.vala"
	type_of_mode = 0;
#line 51 "../src/Services/ExportUtils.vala"
	_tmp1_ = quilter_application_gsettings;
#line 51 "../src/Services/ExportUtils.vala"
	_tmp2_ = g_settings_get_string (_tmp1_, "visual-mode");
#line 51 "../src/Services/ExportUtils.vala"
	_tmp3_ = _tmp2_;
#line 51 "../src/Services/ExportUtils.vala"
	_tmp4_ = g_strcmp0 (_tmp3_, "dark") == 0;
#line 51 "../src/Services/ExportUtils.vala"
	_g_free0 (_tmp3_);
#line 51 "../src/Services/ExportUtils.vala"
	if (_tmp4_) {
#line 358 "ExportUtils.c"
		GSettings* _tmp5_;
#line 52 "../src/Services/ExportUtils.vala"
		_tmp5_ = quilter_application_gsettings;
#line 52 "../src/Services/ExportUtils.vala"
		g_settings_set_string (_tmp5_, "visual-mode", "light");
#line 53 "../src/Services/ExportUtils.vala"
		type_of_mode = 1;
#line 366 "ExportUtils.c"
	} else {
		GSettings* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		gboolean _tmp9_;
#line 54 "../src/Services/ExportUtils.vala"
		_tmp6_ = quilter_application_gsettings;
#line 54 "../src/Services/ExportUtils.vala"
		_tmp7_ = g_settings_get_string (_tmp6_, "visual-mode");
#line 54 "../src/Services/ExportUtils.vala"
		_tmp8_ = _tmp7_;
#line 54 "../src/Services/ExportUtils.vala"
		_tmp9_ = g_strcmp0 (_tmp8_, "sepia") == 0;
#line 54 "../src/Services/ExportUtils.vala"
		_g_free0 (_tmp8_);
#line 54 "../src/Services/ExportUtils.vala"
		if (_tmp9_) {
#line 384 "ExportUtils.c"
			GSettings* _tmp10_;
#line 55 "../src/Services/ExportUtils.vala"
			_tmp10_ = quilter_application_gsettings;
#line 55 "../src/Services/ExportUtils.vala"
			g_settings_set_string (_tmp10_, "visual-mode", "light");
#line 56 "../src/Services/ExportUtils.vala"
			type_of_mode = 2;
#line 392 "ExportUtils.c"
		}
	}
#line 59 "../src/Services/ExportUtils.vala"
	_tmp11_ = quilter_widgets_preview_get_instance ();
#line 59 "../src/Services/ExportUtils.vala"
	_tmp12_ = _tmp11_;
#line 59 "../src/Services/ExportUtils.vala"
	quilter_widgets_preview_update_html_view (_tmp12_);
#line 59 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (_tmp12_);
#line 62 "../src/Services/ExportUtils.vala"
	if (file_path == NULL) {
#line 405 "ExportUtils.c"
		GFile* _tmp13_;
		GFile* _tmp14_;
		gchar* _tmp15_;
		gchar* _tmp16_;
		gchar* _tmp17_;
		gchar* _tmp18_;
		gboolean _tmp19_;
#line 63 "../src/Services/ExportUtils.vala"
		_tmp13_ = quilter_services_export_utils_get_pdf_from_user ();
#line 63 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (file);
#line 63 "../src/Services/ExportUtils.vala"
		file = _tmp13_;
#line 64 "../src/Services/ExportUtils.vala"
		_tmp14_ = file;
#line 64 "../src/Services/ExportUtils.vala"
		_tmp15_ = g_file_get_basename (_tmp14_);
#line 64 "../src/Services/ExportUtils.vala"
		_tmp16_ = _tmp15_;
#line 64 "../src/Services/ExportUtils.vala"
		_tmp17_ = g_utf8_strdown (_tmp16_, (gssize) -1);
#line 64 "../src/Services/ExportUtils.vala"
		_tmp18_ = _tmp17_;
#line 64 "../src/Services/ExportUtils.vala"
		_tmp19_ = !g_str_has_suffix (_tmp18_, ".pdf");
#line 64 "../src/Services/ExportUtils.vala"
		_g_free0 (_tmp18_);
#line 64 "../src/Services/ExportUtils.vala"
		_g_free0 (_tmp16_);
#line 64 "../src/Services/ExportUtils.vala"
		if (_tmp19_) {
#line 437 "ExportUtils.c"
			GFile* _tmp20_;
			gchar* _tmp21_;
			gchar* _tmp22_;
			gchar* _tmp23_;
			gchar* _tmp24_;
			GFile* _tmp25_;
#line 65 "../src/Services/ExportUtils.vala"
			_tmp20_ = file;
#line 65 "../src/Services/ExportUtils.vala"
			_tmp21_ = g_file_get_path (_tmp20_);
#line 65 "../src/Services/ExportUtils.vala"
			_tmp22_ = _tmp21_;
#line 65 "../src/Services/ExportUtils.vala"
			_tmp23_ = g_strconcat (_tmp22_, ".pdf", NULL);
#line 65 "../src/Services/ExportUtils.vala"
			_tmp24_ = _tmp23_;
#line 65 "../src/Services/ExportUtils.vala"
			_tmp25_ = g_file_new_for_path (_tmp24_);
#line 65 "../src/Services/ExportUtils.vala"
			_g_object_unref0 (file);
#line 65 "../src/Services/ExportUtils.vala"
			file = _tmp25_;
#line 65 "../src/Services/ExportUtils.vala"
			_g_free0 (_tmp24_);
#line 65 "../src/Services/ExportUtils.vala"
			_g_free0 (_tmp22_);
#line 464 "ExportUtils.c"
		}
	} else {
		GFile* _tmp26_;
#line 68 "../src/Services/ExportUtils.vala"
		_tmp26_ = g_file_new_for_path (file_path);
#line 68 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (file);
#line 68 "../src/Services/ExportUtils.vala"
		file = _tmp26_;
#line 474 "ExportUtils.c"
	}
#line 71 "../src/Services/ExportUtils.vala"
	_tmp27_ = file;
#line 71 "../src/Services/ExportUtils.vala"
	if (_tmp27_ == NULL) {
#line 72 "../src/Services/ExportUtils.vala"
		result = NULL;
#line 72 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (file);
#line 72 "../src/Services/ExportUtils.vala"
		return result;
#line 486 "ExportUtils.c"
	}
	{
		GFile* _tmp28_;
#line 76 "../src/Services/ExportUtils.vala"
		_tmp28_ = file;
#line 76 "../src/Services/ExportUtils.vala"
		quilter_services_export_utils_write_file (_tmp28_, "", FALSE, &_inner_error0_);
#line 76 "../src/Services/ExportUtils.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 496 "ExportUtils.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp29_;
		const gchar* _tmp30_;
#line 75 "../src/Services/ExportUtils.vala"
		e = _inner_error0_;
#line 75 "../src/Services/ExportUtils.vala"
		_inner_error0_ = NULL;
#line 78 "../src/Services/ExportUtils.vala"
		_tmp29_ = e;
#line 78 "../src/Services/ExportUtils.vala"
		_tmp30_ = _tmp29_->message;
#line 78 "../src/Services/ExportUtils.vala"
		g_warning ("ExportUtils.vala:78: Could not write initial PDF file: %s", _tmp30_);
#line 79 "../src/Services/ExportUtils.vala"
		result = NULL;
#line 79 "../src/Services/ExportUtils.vala"
		_g_error_free0 (e);
#line 79 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (file);
#line 79 "../src/Services/ExportUtils.vala"
		return result;
#line 524 "ExportUtils.c"
	}
	__finally0:
#line 75 "../src/Services/ExportUtils.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 75 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (file);
#line 75 "../src/Services/ExportUtils.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 75 "../src/Services/ExportUtils.vala"
		g_clear_error (&_inner_error0_);
#line 75 "../src/Services/ExportUtils.vala"
		return NULL;
#line 537 "ExportUtils.c"
	}
#line 82 "../src/Services/ExportUtils.vala"
	_tmp31_ = quilter_widgets_preview_get_instance ();
#line 82 "../src/Services/ExportUtils.vala"
	_tmp32_ = _tmp31_;
#line 82 "../src/Services/ExportUtils.vala"
	_tmp33_ = webkit_print_operation_new ((WebKitWebView*) _tmp32_);
#line 82 "../src/Services/ExportUtils.vala"
	_tmp34_ = _tmp33_;
#line 82 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (_tmp32_);
#line 82 "../src/Services/ExportUtils.vala"
	op = _tmp34_;
#line 83 "../src/Services/ExportUtils.vala"
	_tmp35_ = gtk_print_settings_new ();
#line 83 "../src/Services/ExportUtils.vala"
	psettings = _tmp35_;
#line 84 "../src/Services/ExportUtils.vala"
	_tmp36_ = psettings;
#line 84 "../src/Services/ExportUtils.vala"
	gtk_print_settings_set_printer (_tmp36_, _ ("Print to File"));
#line 86 "../src/Services/ExportUtils.vala"
	_tmp37_ = gtk_paper_size_new (GTK_PAPER_NAME_A4);
#line 86 "../src/Services/ExportUtils.vala"
	psize = _tmp37_;
#line 87 "../src/Services/ExportUtils.vala"
	_tmp38_ = gtk_page_setup_new ();
#line 87 "../src/Services/ExportUtils.vala"
	psetup = _tmp38_;
#line 88 "../src/Services/ExportUtils.vala"
	_tmp39_ = psetup;
#line 88 "../src/Services/ExportUtils.vala"
	gtk_page_setup_set_top_margin (_tmp39_, 0.75, GTK_UNIT_INCH);
#line 89 "../src/Services/ExportUtils.vala"
	_tmp40_ = psetup;
#line 89 "../src/Services/ExportUtils.vala"
	gtk_page_setup_set_bottom_margin (_tmp40_, 0.75, GTK_UNIT_INCH);
#line 90 "../src/Services/ExportUtils.vala"
	_tmp41_ = psetup;
#line 90 "../src/Services/ExportUtils.vala"
	gtk_page_setup_set_left_margin (_tmp41_, 0.75, GTK_UNIT_INCH);
#line 91 "../src/Services/ExportUtils.vala"
	_tmp42_ = psetup;
#line 91 "../src/Services/ExportUtils.vala"
	gtk_page_setup_set_right_margin (_tmp42_, 0.75, GTK_UNIT_INCH);
#line 92 "../src/Services/ExportUtils.vala"
	_tmp43_ = psetup;
#line 92 "../src/Services/ExportUtils.vala"
	_tmp44_ = psize;
#line 92 "../src/Services/ExportUtils.vala"
	gtk_page_setup_set_paper_size (_tmp43_, _tmp44_);
#line 94 "../src/Services/ExportUtils.vala"
	_tmp45_ = psettings;
#line 94 "../src/Services/ExportUtils.vala"
	_tmp46_ = file;
#line 94 "../src/Services/ExportUtils.vala"
	_tmp47_ = g_file_get_uri (_tmp46_);
#line 94 "../src/Services/ExportUtils.vala"
	_tmp48_ = _tmp47_;
#line 94 "../src/Services/ExportUtils.vala"
	gtk_print_settings_set (_tmp45_, GTK_PRINT_SETTINGS_OUTPUT_URI, _tmp48_);
#line 94 "../src/Services/ExportUtils.vala"
	_g_free0 (_tmp48_);
#line 95 "../src/Services/ExportUtils.vala"
	_tmp49_ = op;
#line 95 "../src/Services/ExportUtils.vala"
	_tmp50_ = psettings;
#line 95 "../src/Services/ExportUtils.vala"
	webkit_print_operation_set_print_settings (_tmp49_, _tmp50_);
#line 96 "../src/Services/ExportUtils.vala"
	_tmp51_ = op;
#line 96 "../src/Services/ExportUtils.vala"
	_tmp52_ = psetup;
#line 96 "../src/Services/ExportUtils.vala"
	webkit_print_operation_set_page_setup (_tmp51_, _tmp52_);
#line 97 "../src/Services/ExportUtils.vala"
	_tmp53_ = op;
#line 97 "../src/Services/ExportUtils.vala"
	webkit_print_operation_print (_tmp53_);
#line 99 "../src/Services/ExportUtils.vala"
	if (type_of_mode == 1) {
#line 619 "ExportUtils.c"
		GSettings* _tmp54_;
#line 100 "../src/Services/ExportUtils.vala"
		_tmp54_ = quilter_application_gsettings;
#line 100 "../src/Services/ExportUtils.vala"
		g_settings_set_string (_tmp54_, "visual-mode", "dark");
#line 101 "../src/Services/ExportUtils.vala"
		type_of_mode = 0;
#line 627 "ExportUtils.c"
	} else {
#line 102 "../src/Services/ExportUtils.vala"
		if (type_of_mode == 2) {
#line 631 "ExportUtils.c"
			GSettings* _tmp55_;
#line 103 "../src/Services/ExportUtils.vala"
			_tmp55_ = quilter_application_gsettings;
#line 103 "../src/Services/ExportUtils.vala"
			g_settings_set_string (_tmp55_, "visual-mode", "sepia");
#line 104 "../src/Services/ExportUtils.vala"
			type_of_mode = 0;
#line 639 "ExportUtils.c"
		}
	}
#line 107 "../src/Services/ExportUtils.vala"
	result = file;
#line 107 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (psetup);
#line 107 "../src/Services/ExportUtils.vala"
	__vala_GtkPaperSize_free0 (psize);
#line 107 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (psettings);
#line 107 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (op);
#line 107 "../src/Services/ExportUtils.vala"
	return result;
#line 654 "ExportUtils.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 110 "../src/Services/ExportUtils.vala"
	return self ? g_object_ref (self) : NULL;
#line 662 "ExportUtils.c"
}

static Block6Data*
block6_data_ref (Block6Data* _data6_)
{
#line 110 "../src/Services/ExportUtils.vala"
	g_atomic_int_inc (&_data6_->_ref_count_);
#line 110 "../src/Services/ExportUtils.vala"
	return _data6_;
#line 672 "ExportUtils.c"
}

static void
block6_data_unref (void * _userdata_)
{
	Block6Data* _data6_;
	_data6_ = (Block6Data*) _userdata_;
#line 110 "../src/Services/ExportUtils.vala"
	if (g_atomic_int_dec_and_test (&_data6_->_ref_count_)) {
#line 110 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (_data6_->file);
#line 110 "../src/Services/ExportUtils.vala"
		_g_free0 (_data6_->contents);
#line 110 "../src/Services/ExportUtils.vala"
		g_slice_free (Block6Data, _data6_);
#line 688 "ExportUtils.c"
	}
}

static guint8*
string_get_data (const gchar* self,
                 gint* result_length1)
{
	guint8* result;
	guint8* res = NULL;
	gint res_length1;
	gint _res_size_;
	gint _tmp0_;
	gint _tmp1_;
	guint8* _tmp2_;
	gint _tmp2__length1;
#line 1555 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1556 "glib-2.0.vapi"
	res = (guint8*) self;
#line 1556 "glib-2.0.vapi"
	res_length1 = -1;
#line 1556 "glib-2.0.vapi"
	_res_size_ = res_length1;
#line 1557 "glib-2.0.vapi"
	_tmp0_ = strlen (self);
#line 1557 "glib-2.0.vapi"
	_tmp1_ = _tmp0_;
#line 1557 "glib-2.0.vapi"
	res_length1 = (gint) _tmp1_;
#line 1558 "glib-2.0.vapi"
	_tmp2_ = res;
#line 1558 "glib-2.0.vapi"
	_tmp2__length1 = res_length1;
#line 1558 "glib-2.0.vapi"
	if (result_length1) {
#line 1558 "glib-2.0.vapi"
		*result_length1 = _tmp2__length1;
#line 726 "ExportUtils.c"
	}
#line 1558 "glib-2.0.vapi"
	result = _tmp2_;
#line 1558 "glib-2.0.vapi"
	return result;
#line 732 "ExportUtils.c"
}

static void
__lambda19_ (Block6Data* _data6_,
             GObject* obj,
             GAsyncResult* res)
{
	GError* _inner_error0_ = NULL;
#line 123 "../src/Services/ExportUtils.vala"
	g_return_if_fail (res != NULL);
#line 743 "ExportUtils.c"
	{
		GFileIOStream* iostream = NULL;
		GFileIOStream* _tmp0_;
		GOutputStream* ostream = NULL;
		GFileIOStream* _tmp1_;
		GOutputStream* _tmp2_;
		GOutputStream* _tmp3_;
		GOutputStream* _tmp4_;
		GOutputStream* _tmp5_;
		guint8* _tmp6_;
		gint _tmp6__length1;
		gint _tmp7_ = 0;
		guint8* _tmp8_;
		gint _tmp8__length1;
#line 125 "../src/Services/ExportUtils.vala"
		_tmp0_ = g_file_open_readwrite_finish (_data6_->file, res, &_inner_error0_);
#line 125 "../src/Services/ExportUtils.vala"
		iostream = _tmp0_;
#line 125 "../src/Services/ExportUtils.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 764 "ExportUtils.c"
			goto __catch0_g_error;
		}
#line 126 "../src/Services/ExportUtils.vala"
		_tmp1_ = iostream;
#line 126 "../src/Services/ExportUtils.vala"
		_tmp2_ = g_io_stream_get_output_stream ((GIOStream*) _tmp1_);
#line 126 "../src/Services/ExportUtils.vala"
		_tmp3_ = _tmp2_;
#line 126 "../src/Services/ExportUtils.vala"
		_tmp4_ = _g_object_ref0 (_tmp3_);
#line 126 "../src/Services/ExportUtils.vala"
		ostream = _tmp4_;
#line 127 "../src/Services/ExportUtils.vala"
		_tmp5_ = ostream;
#line 127 "../src/Services/ExportUtils.vala"
		_tmp6_ = string_get_data (_data6_->contents, &_tmp7_);
#line 127 "../src/Services/ExportUtils.vala"
		_tmp6__length1 = _tmp7_;
#line 127 "../src/Services/ExportUtils.vala"
		_tmp8_ = _tmp6_;
#line 127 "../src/Services/ExportUtils.vala"
		_tmp8__length1 = _tmp6__length1;
#line 127 "../src/Services/ExportUtils.vala"
		g_output_stream_write_all (_tmp5_, _tmp8_, (gsize) _tmp8__length1, NULL, NULL, &_inner_error0_);
#line 127 "../src/Services/ExportUtils.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 127 "../src/Services/ExportUtils.vala"
			_g_object_unref0 (ostream);
#line 127 "../src/Services/ExportUtils.vala"
			_g_object_unref0 (iostream);
#line 795 "ExportUtils.c"
			goto __catch0_g_error;
		}
#line 124 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (ostream);
#line 124 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (iostream);
#line 802 "ExportUtils.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		gchar* _tmp9_;
		gchar* _tmp10_;
		GError* _tmp11_;
		const gchar* _tmp12_;
#line 124 "../src/Services/ExportUtils.vala"
		e = _inner_error0_;
#line 124 "../src/Services/ExportUtils.vala"
		_inner_error0_ = NULL;
#line 129 "../src/Services/ExportUtils.vala"
		_tmp9_ = g_file_get_basename (_data6_->file);
#line 129 "../src/Services/ExportUtils.vala"
		_tmp10_ = _tmp9_;
#line 129 "../src/Services/ExportUtils.vala"
		_tmp11_ = e;
#line 129 "../src/Services/ExportUtils.vala"
		_tmp12_ = _tmp11_->message;
#line 129 "../src/Services/ExportUtils.vala"
		g_warning ("ExportUtils.vala:129: Could not write file \"%s\": %s", _tmp10_, _tmp12_);
#line 129 "../src/Services/ExportUtils.vala"
		_g_free0 (_tmp10_);
#line 124 "../src/Services/ExportUtils.vala"
		_g_error_free0 (e);
#line 830 "ExportUtils.c"
	}
	__finally0:
#line 124 "../src/Services/ExportUtils.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 124 "../src/Services/ExportUtils.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 124 "../src/Services/ExportUtils.vala"
		g_clear_error (&_inner_error0_);
#line 124 "../src/Services/ExportUtils.vala"
		return;
#line 841 "ExportUtils.c"
	}
}

static void
___lambda19__gasync_ready_callback (GObject* source_object,
                                    GAsyncResult* res,
                                    gpointer self)
{
#line 123 "../src/Services/ExportUtils.vala"
	__lambda19_ (self, source_object, res);
#line 123 "../src/Services/ExportUtils.vala"
	block6_data_unref (self);
#line 854 "ExportUtils.c"
}

void
quilter_services_export_utils_write_file (GFile* file,
                                          const gchar* contents,
                                          gboolean overwrite,
                                          GError** error)
{
	Block6Data* _data6_;
	GFile* _tmp0_;
	gchar* _tmp1_;
	gboolean _tmp2_ = FALSE;
	GError* _inner_error0_ = NULL;
#line 110 "../src/Services/ExportUtils.vala"
	g_return_if_fail (file != NULL);
#line 110 "../src/Services/ExportUtils.vala"
	g_return_if_fail (contents != NULL);
#line 110 "../src/Services/ExportUtils.vala"
	_data6_ = g_slice_new0 (Block6Data);
#line 110 "../src/Services/ExportUtils.vala"
	_data6_->_ref_count_ = 1;
#line 110 "../src/Services/ExportUtils.vala"
	_tmp0_ = _g_object_ref0 (file);
#line 110 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (_data6_->file);
#line 110 "../src/Services/ExportUtils.vala"
	_data6_->file = _tmp0_;
#line 110 "../src/Services/ExportUtils.vala"
	_tmp1_ = g_strdup (contents);
#line 110 "../src/Services/ExportUtils.vala"
	_g_free0 (_data6_->contents);
#line 110 "../src/Services/ExportUtils.vala"
	_data6_->contents = _tmp1_;
#line 111 "../src/Services/ExportUtils.vala"
	if (g_file_query_exists (_data6_->file, NULL)) {
#line 111 "../src/Services/ExportUtils.vala"
		_tmp2_ = overwrite;
#line 892 "ExportUtils.c"
	} else {
#line 111 "../src/Services/ExportUtils.vala"
		_tmp2_ = FALSE;
#line 896 "ExportUtils.c"
	}
#line 111 "../src/Services/ExportUtils.vala"
	if (_tmp2_) {
#line 112 "../src/Services/ExportUtils.vala"
		g_file_delete (_data6_->file, NULL, &_inner_error0_);
#line 112 "../src/Services/ExportUtils.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 112 "../src/Services/ExportUtils.vala"
			g_propagate_error (error, _inner_error0_);
#line 112 "../src/Services/ExportUtils.vala"
			block6_data_unref (_data6_);
#line 112 "../src/Services/ExportUtils.vala"
			_data6_ = NULL;
#line 112 "../src/Services/ExportUtils.vala"
			return;
#line 912 "ExportUtils.c"
		}
	}
#line 115 "../src/Services/ExportUtils.vala"
	if (!g_file_query_exists (_data6_->file, NULL)) {
#line 917 "ExportUtils.c"
		{
			GFileOutputStream* _tmp3_;
			GFileOutputStream* _tmp4_;
#line 117 "../src/Services/ExportUtils.vala"
			_tmp3_ = g_file_create (_data6_->file, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_inner_error0_);
#line 117 "../src/Services/ExportUtils.vala"
			_tmp4_ = _tmp3_;
#line 117 "../src/Services/ExportUtils.vala"
			_g_object_unref0 (_tmp4_);
#line 117 "../src/Services/ExportUtils.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 929 "ExportUtils.c"
				goto __catch0_g_error;
			}
		}
		goto __finally0;
		__catch0_g_error:
		{
			GError* e = NULL;
			GError* _tmp5_;
			const gchar* _tmp6_;
			GError* _tmp7_;
#line 116 "../src/Services/ExportUtils.vala"
			e = _inner_error0_;
#line 116 "../src/Services/ExportUtils.vala"
			_inner_error0_ = NULL;
#line 119 "../src/Services/ExportUtils.vala"
			_tmp5_ = e;
#line 119 "../src/Services/ExportUtils.vala"
			_tmp6_ = _tmp5_->message;
#line 119 "../src/Services/ExportUtils.vala"
			_tmp7_ = g_error_new (g_quark_from_string (""), -1, "Could not write file: %s", _tmp6_);
#line 119 "../src/Services/ExportUtils.vala"
			_inner_error0_ = _tmp7_;
#line 119 "../src/Services/ExportUtils.vala"
			_g_error_free0 (e);
#line 954 "ExportUtils.c"
			goto __finally0;
		}
		__finally0:
#line 116 "../src/Services/ExportUtils.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 116 "../src/Services/ExportUtils.vala"
			g_propagate_error (error, _inner_error0_);
#line 116 "../src/Services/ExportUtils.vala"
			block6_data_unref (_data6_);
#line 116 "../src/Services/ExportUtils.vala"
			_data6_ = NULL;
#line 116 "../src/Services/ExportUtils.vala"
			return;
#line 968 "ExportUtils.c"
		}
	}
#line 123 "../src/Services/ExportUtils.vala"
	g_file_open_readwrite_async (_data6_->file, G_PRIORITY_DEFAULT, NULL, ___lambda19__gasync_ready_callback, block6_data_ref (_data6_));
#line 110 "../src/Services/ExportUtils.vala"
	block6_data_unref (_data6_);
#line 110 "../src/Services/ExportUtils.vala"
	_data6_ = NULL;
#line 977 "ExportUtils.c"
}

static void
_g_object_unref0_ (gpointer var)
{
#line 178 "../src/Services/ExportUtils.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 985 "ExportUtils.c"
}

static inline void
_g_list_free__g_object_unref0_ (GList* self)
{
#line 178 "../src/Services/ExportUtils.vala"
	g_list_free_full (self, (GDestroyNotify) _g_object_unref0_);
#line 993 "ExportUtils.c"
}

GFile*
quilter_services_export_utils_get_pdf_from_user (void)
{
	GFile* _result_ = NULL;
	gchar* title = NULL;
	gchar* _tmp0_;
	GtkFileChooserAction chooser_action = 0;
	gchar* accept_button_label = NULL;
	gchar* _tmp1_;
	GList* filters = NULL;
	gchar* _tmp2_;
	gchar* _tmp3_;
	GtkFileFilter* pdf_filter = NULL;
	GtkFileFilter* _tmp4_;
	GtkFileFilter* _tmp5_;
	GtkFileFilter* _tmp6_;
	GtkFileFilter* _tmp7_;
	GtkFileFilter* _tmp8_;
	GtkFileFilter* _tmp9_;
	GtkFileFilter* all_filter = NULL;
	GtkFileFilter* _tmp10_;
	GtkFileFilter* _tmp11_;
	GtkFileFilter* _tmp12_;
	GtkFileFilter* _tmp13_;
	GtkFileFilter* _tmp14_;
	GtkFileChooserDialog* dialog = NULL;
	const gchar* _tmp15_;
	QuilterMainWindow* _tmp16_;
	GtkFileChooserAction _tmp17_;
	const gchar* _tmp18_;
	GtkFileChooserDialog* _tmp19_;
	GtkFileChooserDialog* _tmp20_;
	GtkFileFilter* _tmp21_;
	GtkFileFilter* _tmp22_;
	GtkFileChooserDialog* _tmp23_;
	GtkFileFilter* _tmp24_;
	GtkFileFilter* _tmp25_;
	GtkFileChooserDialog* _tmp26_;
	GtkFileChooserDialog* _tmp29_;
	GFile* result = NULL;
#line 135 "../src/Services/ExportUtils.vala"
	_result_ = NULL;
#line 137 "../src/Services/ExportUtils.vala"
	_tmp0_ = g_strdup ("");
#line 137 "../src/Services/ExportUtils.vala"
	title = _tmp0_;
#line 138 "../src/Services/ExportUtils.vala"
	chooser_action = GTK_FILE_CHOOSER_ACTION_SAVE;
#line 139 "../src/Services/ExportUtils.vala"
	_tmp1_ = g_strdup ("");
#line 139 "../src/Services/ExportUtils.vala"
	accept_button_label = _tmp1_;
#line 140 "../src/Services/ExportUtils.vala"
	filters = NULL;
#line 142 "../src/Services/ExportUtils.vala"
	_tmp2_ = g_strdup (_ ("Select Destination PDF File"));
#line 142 "../src/Services/ExportUtils.vala"
	_g_free0 (title);
#line 142 "../src/Services/ExportUtils.vala"
	title = _tmp2_;
#line 143 "../src/Services/ExportUtils.vala"
	chooser_action = GTK_FILE_CHOOSER_ACTION_SAVE;
#line 144 "../src/Services/ExportUtils.vala"
	_tmp3_ = g_strdup (_ ("Save"));
#line 144 "../src/Services/ExportUtils.vala"
	_g_free0 (accept_button_label);
#line 144 "../src/Services/ExportUtils.vala"
	accept_button_label = _tmp3_;
#line 146 "../src/Services/ExportUtils.vala"
	_tmp4_ = gtk_file_filter_new ();
#line 146 "../src/Services/ExportUtils.vala"
	g_object_ref_sink (_tmp4_);
#line 146 "../src/Services/ExportUtils.vala"
	pdf_filter = _tmp4_;
#line 147 "../src/Services/ExportUtils.vala"
	_tmp5_ = pdf_filter;
#line 147 "../src/Services/ExportUtils.vala"
	gtk_file_filter_set_name (_tmp5_, _ ("PDF File"));
#line 149 "../src/Services/ExportUtils.vala"
	_tmp6_ = pdf_filter;
#line 149 "../src/Services/ExportUtils.vala"
	gtk_file_filter_add_mime_type (_tmp6_, "application/pdf");
#line 150 "../src/Services/ExportUtils.vala"
	_tmp7_ = pdf_filter;
#line 150 "../src/Services/ExportUtils.vala"
	gtk_file_filter_add_pattern (_tmp7_, "*.pdf");
#line 152 "../src/Services/ExportUtils.vala"
	_tmp8_ = pdf_filter;
#line 152 "../src/Services/ExportUtils.vala"
	_tmp9_ = _g_object_ref0 (_tmp8_);
#line 152 "../src/Services/ExportUtils.vala"
	filters = g_list_append (filters, _tmp9_);
#line 154 "../src/Services/ExportUtils.vala"
	_tmp10_ = gtk_file_filter_new ();
#line 154 "../src/Services/ExportUtils.vala"
	g_object_ref_sink (_tmp10_);
#line 154 "../src/Services/ExportUtils.vala"
	all_filter = _tmp10_;
#line 155 "../src/Services/ExportUtils.vala"
	_tmp11_ = all_filter;
#line 155 "../src/Services/ExportUtils.vala"
	gtk_file_filter_set_name (_tmp11_, _ ("All Files"));
#line 156 "../src/Services/ExportUtils.vala"
	_tmp12_ = all_filter;
#line 156 "../src/Services/ExportUtils.vala"
	gtk_file_filter_add_pattern (_tmp12_, "*");
#line 158 "../src/Services/ExportUtils.vala"
	_tmp13_ = all_filter;
#line 158 "../src/Services/ExportUtils.vala"
	_tmp14_ = _g_object_ref0 (_tmp13_);
#line 158 "../src/Services/ExportUtils.vala"
	filters = g_list_append (filters, _tmp14_);
#line 160 "../src/Services/ExportUtils.vala"
	_tmp15_ = title;
#line 160 "../src/Services/ExportUtils.vala"
	_tmp16_ = quilter_services_export_utils_window;
#line 160 "../src/Services/ExportUtils.vala"
	_tmp17_ = chooser_action;
#line 160 "../src/Services/ExportUtils.vala"
	_tmp18_ = accept_button_label;
#line 160 "../src/Services/ExportUtils.vala"
	_tmp19_ = (GtkFileChooserDialog*) gtk_file_chooser_dialog_new (_tmp15_, (GtkWindow*) _tmp16_, _tmp17_, _ ("Cancel"), GTK_RESPONSE_CANCEL, _tmp18_, GTK_RESPONSE_ACCEPT, NULL);
#line 160 "../src/Services/ExportUtils.vala"
	g_object_ref_sink (_tmp19_);
#line 160 "../src/Services/ExportUtils.vala"
	dialog = _tmp19_;
#line 168 "../src/Services/ExportUtils.vala"
	_tmp20_ = dialog;
#line 168 "../src/Services/ExportUtils.vala"
	_tmp21_ = pdf_filter;
#line 168 "../src/Services/ExportUtils.vala"
	_tmp22_ = _g_object_ref0 (_tmp21_);
#line 168 "../src/Services/ExportUtils.vala"
	gtk_file_chooser_add_filter ((GtkFileChooser*) _tmp20_, _tmp22_);
#line 169 "../src/Services/ExportUtils.vala"
	_tmp23_ = dialog;
#line 169 "../src/Services/ExportUtils.vala"
	_tmp24_ = all_filter;
#line 169 "../src/Services/ExportUtils.vala"
	_tmp25_ = _g_object_ref0 (_tmp24_);
#line 169 "../src/Services/ExportUtils.vala"
	gtk_file_chooser_add_filter ((GtkFileChooser*) _tmp23_, _tmp25_);
#line 172 "../src/Services/ExportUtils.vala"
	_tmp26_ = dialog;
#line 172 "../src/Services/ExportUtils.vala"
	if (gtk_dialog_run ((GtkDialog*) _tmp26_) == ((gint) GTK_RESPONSE_ACCEPT)) {
#line 1142 "ExportUtils.c"
		GtkFileChooserDialog* _tmp27_;
		GFile* _tmp28_;
#line 173 "../src/Services/ExportUtils.vala"
		_tmp27_ = dialog;
#line 173 "../src/Services/ExportUtils.vala"
		_tmp28_ = gtk_file_chooser_get_file ((GtkFileChooser*) _tmp27_);
#line 173 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (_result_);
#line 173 "../src/Services/ExportUtils.vala"
		_result_ = _tmp28_;
#line 1153 "ExportUtils.c"
	}
#line 176 "../src/Services/ExportUtils.vala"
	_tmp29_ = dialog;
#line 176 "../src/Services/ExportUtils.vala"
	g_signal_emit_by_name ((GtkDialog*) _tmp29_, "close");
#line 178 "../src/Services/ExportUtils.vala"
	result = _result_;
#line 178 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (dialog);
#line 178 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (all_filter);
#line 178 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (pdf_filter);
#line 178 "../src/Services/ExportUtils.vala"
	(filters == NULL) ? NULL : (filters = (_g_list_free__g_object_unref0_ (filters), NULL));
#line 178 "../src/Services/ExportUtils.vala"
	_g_free0 (accept_button_label);
#line 178 "../src/Services/ExportUtils.vala"
	_g_free0 (title);
#line 178 "../src/Services/ExportUtils.vala"
	return result;
#line 1175 "ExportUtils.c"
}

GFile*
quilter_services_export_utils_get_html_from_user (void)
{
	QuilterWidgetsPreview* _tmp0_;
	QuilterWidgetsPreview* _tmp1_;
	GFile* result2 = NULL;
	gchar* title = NULL;
	gchar* _tmp2_;
	GtkFileChooserAction chooser_action = 0;
	gchar* accept_button_label = NULL;
	gchar* _tmp3_;
	GList* filters = NULL;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GtkFileFilter* html_filter = NULL;
	GtkFileFilter* _tmp6_;
	GtkFileFilter* _tmp7_;
	GtkFileFilter* _tmp8_;
	GtkFileFilter* _tmp9_;
	GtkFileFilter* _tmp10_;
	GtkFileFilter* _tmp11_;
	GtkFileFilter* all_filter = NULL;
	GtkFileFilter* _tmp12_;
	GtkFileFilter* _tmp13_;
	GtkFileFilter* _tmp14_;
	GtkFileFilter* _tmp15_;
	GtkFileFilter* _tmp16_;
	GtkFileChooserDialog* dialog2 = NULL;
	const gchar* _tmp17_;
	QuilterMainWindow* _tmp18_;
	GtkFileChooserAction _tmp19_;
	const gchar* _tmp20_;
	GtkFileChooserDialog* _tmp21_;
	GtkFileChooserDialog* _tmp22_;
	GtkFileFilter* _tmp23_;
	GtkFileFilter* _tmp24_;
	GtkFileChooserDialog* _tmp25_;
	GtkFileFilter* _tmp26_;
	GtkFileFilter* _tmp27_;
	GtkFileChooserDialog* _tmp28_;
	GtkFileChooserDialog* _tmp31_;
	GFile* result = NULL;
#line 182 "../src/Services/ExportUtils.vala"
	_tmp0_ = quilter_widgets_preview_get_instance ();
#line 182 "../src/Services/ExportUtils.vala"
	_tmp1_ = _tmp0_;
#line 182 "../src/Services/ExportUtils.vala"
	quilter_widgets_preview_update_html_view (_tmp1_);
#line 182 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (_tmp1_);
#line 184 "../src/Services/ExportUtils.vala"
	result2 = NULL;
#line 186 "../src/Services/ExportUtils.vala"
	_tmp2_ = g_strdup ("");
#line 186 "../src/Services/ExportUtils.vala"
	title = _tmp2_;
#line 187 "../src/Services/ExportUtils.vala"
	chooser_action = GTK_FILE_CHOOSER_ACTION_SAVE;
#line 188 "../src/Services/ExportUtils.vala"
	_tmp3_ = g_strdup ("");
#line 188 "../src/Services/ExportUtils.vala"
	accept_button_label = _tmp3_;
#line 189 "../src/Services/ExportUtils.vala"
	filters = NULL;
#line 191 "../src/Services/ExportUtils.vala"
	_tmp4_ = g_strdup (_ ("Select Destination HTML File"));
#line 191 "../src/Services/ExportUtils.vala"
	_g_free0 (title);
#line 191 "../src/Services/ExportUtils.vala"
	title = _tmp4_;
#line 192 "../src/Services/ExportUtils.vala"
	chooser_action = GTK_FILE_CHOOSER_ACTION_SAVE;
#line 193 "../src/Services/ExportUtils.vala"
	_tmp5_ = g_strdup (_ ("Save"));
#line 193 "../src/Services/ExportUtils.vala"
	_g_free0 (accept_button_label);
#line 193 "../src/Services/ExportUtils.vala"
	accept_button_label = _tmp5_;
#line 195 "../src/Services/ExportUtils.vala"
	_tmp6_ = gtk_file_filter_new ();
#line 195 "../src/Services/ExportUtils.vala"
	g_object_ref_sink (_tmp6_);
#line 195 "../src/Services/ExportUtils.vala"
	html_filter = _tmp6_;
#line 196 "../src/Services/ExportUtils.vala"
	_tmp7_ = html_filter;
#line 196 "../src/Services/ExportUtils.vala"
	gtk_file_filter_set_name (_tmp7_, _ ("HTML File"));
#line 198 "../src/Services/ExportUtils.vala"
	_tmp8_ = html_filter;
#line 198 "../src/Services/ExportUtils.vala"
	gtk_file_filter_add_mime_type (_tmp8_, "document/html");
#line 199 "../src/Services/ExportUtils.vala"
	_tmp9_ = html_filter;
#line 199 "../src/Services/ExportUtils.vala"
	gtk_file_filter_add_pattern (_tmp9_, "*.html");
#line 201 "../src/Services/ExportUtils.vala"
	_tmp10_ = html_filter;
#line 201 "../src/Services/ExportUtils.vala"
	_tmp11_ = _g_object_ref0 (_tmp10_);
#line 201 "../src/Services/ExportUtils.vala"
	filters = g_list_append (filters, _tmp11_);
#line 202 "../src/Services/ExportUtils.vala"
	_tmp12_ = gtk_file_filter_new ();
#line 202 "../src/Services/ExportUtils.vala"
	g_object_ref_sink (_tmp12_);
#line 202 "../src/Services/ExportUtils.vala"
	all_filter = _tmp12_;
#line 203 "../src/Services/ExportUtils.vala"
	_tmp13_ = all_filter;
#line 203 "../src/Services/ExportUtils.vala"
	gtk_file_filter_set_name (_tmp13_, _ ("All Files"));
#line 204 "../src/Services/ExportUtils.vala"
	_tmp14_ = all_filter;
#line 204 "../src/Services/ExportUtils.vala"
	gtk_file_filter_add_pattern (_tmp14_, "*");
#line 206 "../src/Services/ExportUtils.vala"
	_tmp15_ = all_filter;
#line 206 "../src/Services/ExportUtils.vala"
	_tmp16_ = _g_object_ref0 (_tmp15_);
#line 206 "../src/Services/ExportUtils.vala"
	filters = g_list_append (filters, _tmp16_);
#line 208 "../src/Services/ExportUtils.vala"
	_tmp17_ = title;
#line 208 "../src/Services/ExportUtils.vala"
	_tmp18_ = quilter_services_export_utils_window;
#line 208 "../src/Services/ExportUtils.vala"
	_tmp19_ = chooser_action;
#line 208 "../src/Services/ExportUtils.vala"
	_tmp20_ = accept_button_label;
#line 208 "../src/Services/ExportUtils.vala"
	_tmp21_ = (GtkFileChooserDialog*) gtk_file_chooser_dialog_new (_tmp17_, (GtkWindow*) _tmp18_, _tmp19_, _ ("Cancel"), GTK_RESPONSE_CANCEL, _tmp20_, GTK_RESPONSE_ACCEPT, NULL);
#line 208 "../src/Services/ExportUtils.vala"
	g_object_ref_sink (_tmp21_);
#line 208 "../src/Services/ExportUtils.vala"
	dialog2 = _tmp21_;
#line 216 "../src/Services/ExportUtils.vala"
	_tmp22_ = dialog2;
#line 216 "../src/Services/ExportUtils.vala"
	_tmp23_ = html_filter;
#line 216 "../src/Services/ExportUtils.vala"
	_tmp24_ = _g_object_ref0 (_tmp23_);
#line 216 "../src/Services/ExportUtils.vala"
	gtk_file_chooser_add_filter ((GtkFileChooser*) _tmp22_, _tmp24_);
#line 217 "../src/Services/ExportUtils.vala"
	_tmp25_ = dialog2;
#line 217 "../src/Services/ExportUtils.vala"
	_tmp26_ = all_filter;
#line 217 "../src/Services/ExportUtils.vala"
	_tmp27_ = _g_object_ref0 (_tmp26_);
#line 217 "../src/Services/ExportUtils.vala"
	gtk_file_chooser_add_filter ((GtkFileChooser*) _tmp25_, _tmp27_);
#line 219 "../src/Services/ExportUtils.vala"
	_tmp28_ = dialog2;
#line 219 "../src/Services/ExportUtils.vala"
	if (gtk_dialog_run ((GtkDialog*) _tmp28_) == ((gint) GTK_RESPONSE_ACCEPT)) {
#line 1334 "ExportUtils.c"
		GtkFileChooserDialog* _tmp29_;
		GFile* _tmp30_;
#line 220 "../src/Services/ExportUtils.vala"
		_tmp29_ = dialog2;
#line 220 "../src/Services/ExportUtils.vala"
		_tmp30_ = gtk_file_chooser_get_file ((GtkFileChooser*) _tmp29_);
#line 220 "../src/Services/ExportUtils.vala"
		_g_object_unref0 (result2);
#line 220 "../src/Services/ExportUtils.vala"
		result2 = _tmp30_;
#line 1345 "ExportUtils.c"
	}
#line 223 "../src/Services/ExportUtils.vala"
	_tmp31_ = dialog2;
#line 223 "../src/Services/ExportUtils.vala"
	g_signal_emit_by_name ((GtkDialog*) _tmp31_, "close");
#line 225 "../src/Services/ExportUtils.vala"
	result = result2;
#line 225 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (dialog2);
#line 225 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (all_filter);
#line 225 "../src/Services/ExportUtils.vala"
	_g_object_unref0 (html_filter);
#line 225 "../src/Services/ExportUtils.vala"
	(filters == NULL) ? NULL : (filters = (_g_list_free__g_object_unref0_ (filters), NULL));
#line 225 "../src/Services/ExportUtils.vala"
	_g_free0 (accept_button_label);
#line 225 "../src/Services/ExportUtils.vala"
	_g_free0 (title);
#line 225 "../src/Services/ExportUtils.vala"
	return result;
#line 1367 "ExportUtils.c"
}

