import Foundation

@MainActor
extension MarkdownStyleCheckerExpressions {
        static let fillerPhrases: [String] = [
            "actually",
            "basically",
            "in my opinion",
            "in order to",
            "it is important to note that",
            "just",
            "kind of",
            "literally",
            "really",
            "simply",
            "somewhat",
            "sort of",
            "very",
            "you know",
            "at this point",
            "as you know",
            "by the way",
            "for example",
            "for instance",
            "in a sense",
            "in general",
            "in particular",
            "in other words",
            "in some ways",
            "in terms of",
            "it seems",
            "it appears",
            "of course",
            "needless to say",
            "more or less",
            "to be honest",
            "to be clear",
            "to be fair",
            "to be sure",
            "that said",
            "with that said",
            "having said that",
            "I think",
            "I believe",
            "I feel",
            "I would say",
            "I suppose",
            "I guess",
            "I mean",
            "you could say",
            "as a matter of fact",
            "as far as I know",
            "as far as I can tell",
            "as it were",
            "at the end of the day",
            "at the same time",
            "at this stage",
            "at this moment",
            "at this time",
            "by and large",
            "for the most part",
            "for what it is worth",
            "generally speaking",
            "in a way",
            "in any case",
            "in any event",
            "in essence",
            "in effect",
            "in fact",
            "in reality",
            "in truth",
            "more importantly",
            "on the other hand",
            "on the whole",
            "overall",
            "perhaps",
            "possibly",
            "probably",
            "rather",
            "quite",
            "relatively",
            "somehow",
            "technically",
            "ultimately",
            "usually",
            "whatever",
            "where possible",
            "as mentioned before",
            "as previously mentioned",
            "as noted above",
            "as noted earlier",
            "as stated above",
            "as stated earlier",
            "as we have seen",
            "as you can see",
            "as you might expect",
            "as a reminder",
            "for clarity",
            "for completeness",
            "for context",
            "for reference",
            "for now",
            "for the moment",
            "in conclusion",
            "in summary",
            "in short",
            "in brief",
            "in closing",
            "to conclude",
            "to summarize",
            "to sum up",
            "first of all",
            "to begin with",
            "to start with",
            "before we begin",
            "at the outset",
            "in the beginning",
            "last but not least",
            "finally",
            "secondly",
            "thirdly",
            "next",
            "then",
            "after all",
            "again",
            "also",
            "additionally",
            "besides",
            "furthermore",
            "moreover",
            "nevertheless",
            "nonetheless",
            "still",
            "however",
            "therefore",
            "thus",
            "so",
            "well",
            "okay",
            "alright",
            "look",
            "listen",
            "now",
            "anyway",
            "anyhow",
            "indeed",
            "obviously",
            "clearly",
            "naturally",
            "as expected",
            "it goes without saying",
            "it should be noted that",
            "it is worth noting that",
            "it is worth mentioning that",
            "one might argue",
            "one could argue",
            "it could be argued",
            "it is possible that",
            "it is likely that",
            "there is a chance that",
            "in my view",
            "from my perspective",
            "from my point of view",
            "in my experience",
            "as I see it",
            "if you will",
            "so to speak",
            "so-called",
            "in a manner of speaking",
            "in some respects",
            "in this regard",
            "in this case",
            "in that case",
            "in the meantime",
            "at the moment",
            "for the time being",
            "until then",
            "just about",
            "almost",
            "nearly",
            "kindly",
            "perhaps maybe",
            "maybe perhaps",
            "a little bit",
            "a bit",
            "in a little while",
            "as soon as possible",
            "at your earliest convenience",
            "if possible",
            "if necessary",
            "when possible",
            "where appropriate",
            "as needed",
            "and so on",
            "and so forth",
            "et cetera",
            "etcetera",
            "or something",
            "or whatever",
            "and things like that",
            "and the like",
            "for lack of a better word",
            "for want of a better word",
            "to put it simply",
            "to put it another way",
            "what I mean is",
            "what I am saying is",
            "the fact is",
            "the thing is",
            "the point is",
            "the truth is",
            "as a result",
            "because of this",
            "due to this",
            "in light of this",
            "with regard to",
            "with respect to",
            "in relation to",
            "in connection with",
            "on account of",
            "for this reason",
            "under these circumstances",
            "in the event that",
            "in the case of",
            "in the process of",
            "for the purpose of",
            "in an effort to",
            "with the aim of",
            "in an attempt to",
            "in the interest of",
            "at the present time",
            "at this point in time"
        ]
}
