import Foundation

@MainActor
extension MarkdownStyleCheckerExpressions {
        static let redundancyPhrases: [String] = [
            "absolutely essential",
            "actual fact",
            "advance planning",
            "basic fundamentals",
            "close proximity",
            "each and every",
            "end result",
            "final outcome",
            "free gift",
            "future plans",
            "new innovation",
            "past experience",
            "past history",
            "PIN number",
            "revert back",
            "repeat again",
            "sudden surprise",
            "unexpected surprise",
            "added bonus",
            "advance warning",
            "all of",
            "as for example",
            "assembled together",
            "at the present time",
            "attach together",
            "autobiography of my life",
            "bare bones",
            "biography of her life",
            "brief moment",
            "brief summary",
            "burning fire",
            "cease and desist",
            "circle around",
            "classify into groups",
            "collaborate together",
            "combine together",
            "consensus of opinion",
            "continue on",
            "currently being",
            "currently now",
            "depreciate in value",
            "descend down",
            "different variations",
            "divide up",
            "down below",
            "drop down",
            "empty space",
            "enclosed inside",
            "equally as",
            "estimated roughly",
            "exact same",
            "export out",
            "fall down",
            "few in number",
            "filled to capacity",
            "first and foremost",
            "for a period of",
            "for the purpose of",
            "foreign imports",
            "former ex",
            "freeze up",
            "gather together",
            "general consensus",
            "general public",
            "go back",
            "go forward",
            "grow in size",
            "had done previously",
            "has got",
            "he is a person who",
            "hear with one's own ears",
            "honest truth",
            "how to",
            "in close proximity",
            "in close quarters",
            "in the process of",
            "input into",
            "join together",
            "joint collaboration",
            "keep on",
            "located in",
            "look back in retrospect",
            "major breakthrough",
            "merge together",
            "mix together",
            "mutual cooperation",
            "mutual agreement",
            "natural instinct",
            "new beginning",
            "new creation",
            "new recruit",
            "null and void",
            "off of",
            "one and the same",
            "period of time",
            "personally, I",
            "plan ahead",
            "planned ahead",
            "positive benefit",
            "postpone until later",
            "preplan in advance",
            "present incumbent",
            "previously before",
            "protest against",
            "protrude out",
            "reason why",
            "refer back",
            "return back",
            "rise up",
            "safe haven",
            "same identical",
            "separate entities",
            "separate out",
            "shorter in length",
            "shout out",
            "skilled expert",
            "small in size",
            "still remains",
            "sum total",
            "surrounded all around",
            "surrounding circumstances",
            "temporary reprieve",
            "three a.m. in the morning",
            "tiny little",
            "true facts",
            "twelve midnight",
            "twelve noon",
            "ultimate end",
            "unanimous agreement",
            "usual custom",
            "visible to the eye",
            "wait for",
            "whether or not",
            "written down",
            "your own personal",
            "absolutely certain",
            "advance forward",
            "annual anniversary",
            "at this point in time",
            "basic necessity",
            "blatantly obvious",
            "brief in duration",
            "completely unanimous",
            "cooperate together",
            "could possibly",
            "currently existing",
            "each separate",
            "earlier before",
            "entirely complete",
            "exactly identical",
            "first began",
            "fully satisfy",
            "important essentials",
            "individual person",
            "integrate together",
            "introductory opening",
            "invited guests",
            "last final",
            "later on",
            "new and innovative",
            "original source",
            "outward appearance",
            "over and above",
            "past memories",
            "perfectly clear",
            "private industry",
            "proceed forward",
            "raise up",
            "regular routine",
            "reliable dependability",
            "return again",
            "revolve around",
            "round in shape",
            "sufficient enough",
            "surrounded on all sides",
            "very unique",
            "visible eyesight",
            "whole entire",
            "written record",
            "yet still",
            "adequate enough",
            "alternative choice",
            "as a matter of fact",
            "completely eliminate",
            "continue to remain",
            "eliminate altogether",
            "empty void",
            "exactly the same",
            "finished completely",
            "full and complete",
            "in the affirmative",
            "may perhaps",
            "never before",
            "new release",
            "one single",
            "originally created",
            "reassemble again",
            "recur again",
            "reflected back",
            "repeat the same",
            "still continue",
            "still persists",
            "unexpected emergency",
            "with reference to",
            "young child"
        ]
}
