import Foundation

@MainActor
extension MarkdownStyleCheckerExpressions {
        static let clichePhrases: [String] = [
            "all walks of life",
            "at the end of the day",
            "avoid like the plague",
            "better late than never",
            "calm before the storm",
            "diamond in the rough",
            "easy as pie",
            "few and far between",
            "fit as a fiddle",
            "in the nick of time",
            "in this day and age",
            "last but not least",
            "light at the end of the tunnel",
            "needle in a haystack",
            "read between the lines",
            "the rest is history",
            "think outside the box",
            "time will tell",
            "tip of the iceberg",
            "when all is said and done",
            "a dime a dozen",
            "a picture is worth a thousand words",
            "a word to the wise",
            "actions speak louder than words",
            "add insult to injury",
            "all things considered",
            "an ounce of prevention",
            "another day another dollar",
            "back to square one",
            "back to the drawing board",
            "barking up the wrong tree",
            "beat around the bush",
            "bend over backwards",
            "best of both worlds",
            "bite the bullet",
            "blessing in disguise",
            "boil the ocean",
            "break a leg",
            "break the ice",
            "bring to the table",
            "burn the midnight oil",
            "by the same token",
            "call it a day",
            "can of worms",
            "chip on your shoulder",
            "close but no cigar",
            "cold hard facts",
            "come full circle",
            "common ground",
            "compare apples to oranges",
            "cover all the bases",
            "cross that bridge when we come to it",
            "crystal clear",
            "cut to the chase",
            "deep dive",
            "devil's advocate",
            "don't put all your eggs in one basket",
            "down to the wire",
            "drop in the bucket",
            "elephant in the room",
            "every cloud has a silver lining",
            "face the music",
            "fair and square",
            "from the ground up",
            "get the ball rolling",
            "get your ducks in a row",
            "give it a shot",
            "go the extra mile",
            "grass is always greener",
            "green light",
            "hands down",
            "hang in there",
            "hard pill to swallow",
            "head over heels",
            "hear it through the grapevine",
            "hit the ground running",
            "hit the nail on the head",
            "in a nutshell",
            "in broad daylight",
            "in hot water",
            "in the driver's seat",
            "in the long run",
            "in the same boat",
            "it takes two to tango",
            "jump on the bandwagon",
            "keep an eye on",
            "keep your eyes peeled",
            "kick the can down the road",
            "kill two birds with one stone",
            "know the ropes",
            "leave no stone unturned",
            "let the cat out of the bag",
            "level playing field",
            "low-hanging fruit",
            "make a long story short",
            "miss the boat",
            "move the needle",
            "once in a blue moon",
            "on the same page",
            "open a can of worms",
            "out of the blue",
            "outside the box",
            "par for the course",
            "piece of cake",
            "play devil's advocate",
            "put a spin on",
            "put your best foot forward",
            "raise the bar",
            "read the writing on the wall",
            "reinvent the wheel",
            "rock the boat",
            "run like clockwork",
            "rule of thumb",
            "safe and sound",
            "see eye to eye",
            "speak of the devil",
            "stand the test of time",
            "state of the art",
            "steal someone's thunder",
            "step up to the plate",
            "straight from the horse's mouth",
            "sweep under the rug",
            "take it to the next level",
            "take the bull by the horns",
            "the bottom line",
            "the best thing since sliced bread",
            "the big picture",
            "the calm before the storm",
            "the elephant in the room",
            "the last straw",
            "the powers that be",
            "the tip of the iceberg",
            "throw in the towel",
            "throw out the baby with the bathwater",
            "through thick and thin",
            "toe the line",
            "touch base",
            "turn over a new leaf",
            "under the weather",
            "up in the air",
            "walk a fine line",
            "water under the bridge",
            "weather the storm",
            "whole nine yards",
            "wild goose chase",
            "win-win situation",
            "you can't judge a book by its cover",
            "a level playing field",
            "a match made in heaven",
            "a needle in a haystack",
            "a perfect storm",
            "a recipe for disaster",
            "a rough patch",
            "a shot in the dark",
            "a slippery slope",
            "a step in the right direction",
            "a storm in a teacup",
            "a taste of your own medicine",
            "a tough nut to crack",
            "a turning point",
            "a wake-up call",
            "all in the same boat",
            "all roads lead to Rome",
            "at the drop of a hat",
            "at your fingertips",
            "back against the wall",
            "behind the scenes",
            "bigger fish to fry",
            "by leaps and bounds",
            "change of heart",
            "clear as mud",
            "come rain or shine",
            "cost an arm and a leg",
            "cut corners",
            "dead in the water",
            "draw a line in the sand",
            "easier said than done",
            "every now and then",
            "fit the bill",
            "fly under the radar",
            "from time to time",
            "go down in history",
            "go with the flow",
            "in full swing",
            "in the same vein",
            "jump through hoops",
            "keep the wolves from the door",
            "know it like the back of your hand",
            "leave well enough alone",
            "make ends meet",
            "on thin ice",
            "pull out all the stops",
            "put two and two together",
            "rise to the occasion",
            "see the light",
            "sit on the fence",
            "speak volumes",
            "the writing on the wall",
            "throw caution to the wind",
            "turn a blind eye",
            "up to speed",
            "wear many hats",
            "when push comes to shove",
            "you name it"
        ]
}
