/* Highlighter.c generated by valac 0.50.2, the Vala compiler
 * generated from Highlighter.vala, do not modify */

/*
* Copyright (c) 2019-2020 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 59 Temple Place - Suite 330,
* Boston, MA 02111-1307, USA.
*
* Co-authored by: Felipe Escoto <felescoto95@hotmail.com>
*/

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>

#define QUILTER_PLUGINS_TYPE_PLUGIN (quilter_plugins_plugin_get_type ())
#define QUILTER_PLUGINS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPlugin))
#define QUILTER_PLUGINS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPluginClass))
#define QUILTER_PLUGINS_IS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_PLUGINS_TYPE_PLUGIN))
#define QUILTER_PLUGINS_IS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_PLUGINS_TYPE_PLUGIN))
#define QUILTER_PLUGINS_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPluginClass))

typedef struct _QuilterPluginsPlugin QuilterPluginsPlugin;
typedef struct _QuilterPluginsPluginClass QuilterPluginsPluginClass;
typedef struct _QuilterPluginsPluginPrivate QuilterPluginsPluginPrivate;

#define QUILTER_TYPE_HIGHLIGHTER (quilter_highlighter_get_type ())
#define QUILTER_HIGHLIGHTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_HIGHLIGHTER, QuilterHighlighter))
#define QUILTER_HIGHLIGHTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_HIGHLIGHTER, QuilterHighlighterClass))
#define QUILTER_IS_HIGHLIGHTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_HIGHLIGHTER))
#define QUILTER_IS_HIGHLIGHTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_HIGHLIGHTER))
#define QUILTER_HIGHLIGHTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_HIGHLIGHTER, QuilterHighlighterClass))

typedef struct _QuilterHighlighter QuilterHighlighter;
typedef struct _QuilterHighlighterClass QuilterHighlighterClass;
typedef struct _QuilterHighlighterPrivate QuilterHighlighterPrivate;
enum  {
	QUILTER_HIGHLIGHTER_0_PROPERTY,
	QUILTER_HIGHLIGHTER_NUM_PROPERTIES
};
static GParamSpec* quilter_highlighter_properties[QUILTER_HIGHLIGHTER_NUM_PROPERTIES];
#define _g_pattern_spec_free0(var) ((var == NULL) ? NULL : (var = (g_pattern_spec_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))

struct _QuilterPluginsPlugin {
	GObject parent_instance;
	QuilterPluginsPluginPrivate * priv;
	GSettings* settings;
	gboolean state;
	gchar* code_name;
};

struct _QuilterPluginsPluginClass {
	GObjectClass parent_class;
	gboolean (*is_active) (QuilterPluginsPlugin* self);
	void (*set_active) (QuilterPluginsPlugin* self, gboolean active);
	gchar* (*get_desctiption) (QuilterPluginsPlugin* self);
	gchar* (*get_name) (QuilterPluginsPlugin* self);
	gboolean (*has_match) (QuilterPluginsPlugin* self, const gchar* text);
	gchar* (*convert) (QuilterPluginsPlugin* self, const gchar* line);
	GtkWidget* (*editor_button) (QuilterPluginsPlugin* self);
	gchar* (*get_button_desctiption) (QuilterPluginsPlugin* self);
	gchar* (*request_string) (QuilterPluginsPlugin* self, const gchar* selection);
};

struct _QuilterHighlighter {
	QuilterPluginsPlugin parent_instance;
	QuilterHighlighterPrivate * priv;
};

struct _QuilterHighlighterClass {
	QuilterPluginsPluginClass parent_class;
};

struct _QuilterHighlighterPrivate {
	GPatternSpec* spec;
};

static gint QuilterHighlighter_private_offset;
static gpointer quilter_highlighter_parent_class = NULL;
extern GSettings* quilter_application_gsettings;

GType quilter_plugins_plugin_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterPluginsPlugin, g_object_unref)
GType quilter_highlighter_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterHighlighter, g_object_unref)
gchar* quilter_plugins_plugin_get_desctiption (QuilterPluginsPlugin* self);
gchar* quilter_plugins_plugin_get_name (QuilterPluginsPlugin* self);
GtkWidget* quilter_plugins_plugin_editor_button (QuilterPluginsPlugin* self);
gchar* quilter_plugins_plugin_request_string (QuilterPluginsPlugin* self,
                                              const gchar* selection);
gchar* quilter_plugins_plugin_get_button_desctiption (QuilterPluginsPlugin* self);
gboolean quilter_plugins_plugin_has_match (QuilterPluginsPlugin* self,
                                           const gchar* text);
gchar* quilter_plugins_plugin_convert (QuilterPluginsPlugin* self,
                                       const gchar* line);
static gchar* quilter_highlighter_real_get_desctiption (QuilterPluginsPlugin* base);
static gchar* quilter_highlighter_real_get_name (QuilterPluginsPlugin* base);
static GtkWidget* quilter_highlighter_real_editor_button (QuilterPluginsPlugin* base);
static gchar* quilter_highlighter_real_request_string (QuilterPluginsPlugin* base,
                                                const gchar* selection);
static gchar* quilter_highlighter_real_get_button_desctiption (QuilterPluginsPlugin* base);
static gboolean quilter_highlighter_real_has_match (QuilterPluginsPlugin* base,
                                             const gchar* text);
static gchar* quilter_highlighter_real_convert (QuilterPluginsPlugin* base,
                                         const gchar* line_);
QuilterHighlighter* quilter_highlighter_new (void);
QuilterHighlighter* quilter_highlighter_construct (GType object_type);
QuilterPluginsPlugin* quilter_plugins_plugin_construct (GType object_type);
static GObject * quilter_highlighter_constructor (GType type,
                                           guint n_construct_properties,
                                           GObjectConstructParam * construct_properties);
static void quilter_highlighter_finalize (GObject * obj);
static GType quilter_highlighter_get_type_once (void);

static inline gpointer
quilter_highlighter_get_instance_private (QuilterHighlighter* self)
{
	return G_STRUCT_MEMBER_P (self, QuilterHighlighter_private_offset);
}

static gchar*
quilter_highlighter_real_get_desctiption (QuilterPluginsPlugin* base)
{
	QuilterHighlighter * self;
	gchar* _tmp0_;
	gchar* result = NULL;
#line 27 "../src/Plugins/Highlighter.vala"
	self = (QuilterHighlighter*) base;
#line 28 "../src/Plugins/Highlighter.vala"
	_tmp0_ = g_strdup (_ ("Highlight text in marker yellow."));
#line 28 "../src/Plugins/Highlighter.vala"
	result = _tmp0_;
#line 28 "../src/Plugins/Highlighter.vala"
	return result;
#line 155 "Highlighter.c"
}

static gchar*
quilter_highlighter_real_get_name (QuilterPluginsPlugin* base)
{
	QuilterHighlighter * self;
	gchar* _tmp0_;
	gchar* result = NULL;
#line 31 "../src/Plugins/Highlighter.vala"
	self = (QuilterHighlighter*) base;
#line 32 "../src/Plugins/Highlighter.vala"
	_tmp0_ = g_strdup (_ ("Highlight"));
#line 32 "../src/Plugins/Highlighter.vala"
	result = _tmp0_;
#line 32 "../src/Plugins/Highlighter.vala"
	return result;
#line 172 "Highlighter.c"
}

static GtkWidget*
quilter_highlighter_real_editor_button (QuilterPluginsPlugin* base)
{
	QuilterHighlighter * self;
	GtkWidget* result = NULL;
#line 35 "../src/Plugins/Highlighter.vala"
	self = (QuilterHighlighter*) base;
#line 36 "../src/Plugins/Highlighter.vala"
	result = NULL;
#line 36 "../src/Plugins/Highlighter.vala"
	return result;
#line 186 "Highlighter.c"
}

static gchar*
quilter_highlighter_real_request_string (QuilterPluginsPlugin* base,
                                         const gchar* selection)
{
	QuilterHighlighter * self;
	gchar* _tmp0_;
	gchar* result = NULL;
#line 39 "../src/Plugins/Highlighter.vala"
	self = (QuilterHighlighter*) base;
#line 39 "../src/Plugins/Highlighter.vala"
	g_return_val_if_fail (selection != NULL, NULL);
#line 40 "../src/Plugins/Highlighter.vala"
	_tmp0_ = g_strdup (selection);
#line 40 "../src/Plugins/Highlighter.vala"
	result = _tmp0_;
#line 40 "../src/Plugins/Highlighter.vala"
	return result;
#line 206 "Highlighter.c"
}

static gchar*
quilter_highlighter_real_get_button_desctiption (QuilterPluginsPlugin* base)
{
	QuilterHighlighter * self;
	gchar* _tmp0_;
	gchar* result = NULL;
#line 43 "../src/Plugins/Highlighter.vala"
	self = (QuilterHighlighter*) base;
#line 44 "../src/Plugins/Highlighter.vala"
	_tmp0_ = g_strdup ("");
#line 44 "../src/Plugins/Highlighter.vala"
	result = _tmp0_;
#line 44 "../src/Plugins/Highlighter.vala"
	return result;
#line 223 "Highlighter.c"
}

static gboolean
quilter_highlighter_real_has_match (QuilterPluginsPlugin* base,
                                    const gchar* text)
{
	QuilterHighlighter * self;
	GPatternSpec* _tmp0_;
	gboolean result = FALSE;
#line 47 "../src/Plugins/Highlighter.vala"
	self = (QuilterHighlighter*) base;
#line 47 "../src/Plugins/Highlighter.vala"
	g_return_val_if_fail (text != NULL, FALSE);
#line 48 "../src/Plugins/Highlighter.vala"
	_tmp0_ = self->priv->spec;
#line 48 "../src/Plugins/Highlighter.vala"
	result = g_pattern_match_string (_tmp0_, text);
#line 48 "../src/Plugins/Highlighter.vala"
	return result;
#line 243 "Highlighter.c"
}

static gint
string_index_of (const gchar* self,
                 const gchar* needle,
                 gint start_index)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gint result = 0;
#line 1133 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 1133 "glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, 0);
#line 1134 "glib-2.0.vapi"
	_tmp0_ = strstr (((gchar*) self) + start_index, (gchar*) needle);
#line 1134 "glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1136 "glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1136 "glib-2.0.vapi"
	if (_tmp1_ != NULL) {
#line 267 "Highlighter.c"
		gchar* _tmp2_;
#line 1137 "glib-2.0.vapi"
		_tmp2_ = _result_;
#line 1137 "glib-2.0.vapi"
		result = (gint) (_tmp2_ - ((gchar*) self));
#line 1137 "glib-2.0.vapi"
		return result;
#line 275 "Highlighter.c"
	} else {
#line 1139 "glib-2.0.vapi"
		result = -1;
#line 1139 "glib-2.0.vapi"
		return result;
#line 281 "Highlighter.c"
	}
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result = 0L;
#line 1447 "glib-2.0.vapi"
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
#line 1447 "glib-2.0.vapi"
	end = _tmp0_;
#line 1448 "glib-2.0.vapi"
	_tmp1_ = end;
#line 1448 "glib-2.0.vapi"
	if (_tmp1_ == NULL) {
#line 1449 "glib-2.0.vapi"
		result = maxlen;
#line 1449 "glib-2.0.vapi"
		return result;
#line 305 "Highlighter.c"
	} else {
		gchar* _tmp2_;
#line 1451 "glib-2.0.vapi"
		_tmp2_ = end;
#line 1451 "glib-2.0.vapi"
		result = (glong) (_tmp2_ - str);
#line 1451 "glib-2.0.vapi"
		return result;
#line 314 "Highlighter.c"
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result = NULL;
#line 1458 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1460 "glib-2.0.vapi"
	if (offset >= ((glong) 0)) {
#line 1460 "glib-2.0.vapi"
		_tmp0_ = len >= ((glong) 0);
#line 333 "Highlighter.c"
	} else {
#line 1460 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 337 "Highlighter.c"
	}
#line 1460 "glib-2.0.vapi"
	if (_tmp0_) {
#line 1462 "glib-2.0.vapi"
		string_length = string_strnlen ((gchar*) self, offset + len);
#line 343 "Highlighter.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 1464 "glib-2.0.vapi"
		_tmp1_ = strlen (self);
#line 1464 "glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1464 "glib-2.0.vapi"
		string_length = (glong) _tmp2_;
#line 353 "Highlighter.c"
	}
#line 1467 "glib-2.0.vapi"
	if (offset < ((glong) 0)) {
#line 1468 "glib-2.0.vapi"
		offset = string_length + offset;
#line 1469 "glib-2.0.vapi"
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
#line 361 "Highlighter.c"
	} else {
#line 1471 "glib-2.0.vapi"
		g_return_val_if_fail (offset <= string_length, NULL);
#line 365 "Highlighter.c"
	}
#line 1473 "glib-2.0.vapi"
	if (len < ((glong) 0)) {
#line 1474 "glib-2.0.vapi"
		len = string_length - offset;
#line 371 "Highlighter.c"
	}
#line 1476 "glib-2.0.vapi"
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
#line 1477 "glib-2.0.vapi"
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
#line 1477 "glib-2.0.vapi"
	result = _tmp3_;
#line 1477 "glib-2.0.vapi"
	return result;
#line 381 "Highlighter.c"
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result = NULL;
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (old != NULL, NULL);
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 1535 "glib-2.0.vapi"
	if ((*((gchar*) self)) == '\0') {
#line 1535 "glib-2.0.vapi"
		_tmp1_ = TRUE;
#line 403 "Highlighter.c"
	} else {
#line 1535 "glib-2.0.vapi"
		_tmp1_ = (*((gchar*) old)) == '\0';
#line 407 "Highlighter.c"
	}
#line 1535 "glib-2.0.vapi"
	if (_tmp1_) {
#line 1535 "glib-2.0.vapi"
		_tmp0_ = TRUE;
#line 413 "Highlighter.c"
	} else {
#line 1535 "glib-2.0.vapi"
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
#line 417 "Highlighter.c"
	}
#line 1535 "glib-2.0.vapi"
	if (_tmp0_) {
#line 421 "Highlighter.c"
		gchar* _tmp2_;
#line 1536 "glib-2.0.vapi"
		_tmp2_ = g_strdup (self);
#line 1536 "glib-2.0.vapi"
		result = _tmp2_;
#line 1536 "glib-2.0.vapi"
		return result;
#line 429 "Highlighter.c"
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
#line 1539 "glib-2.0.vapi"
		_tmp3_ = g_regex_escape_string (old, -1);
#line 1539 "glib-2.0.vapi"
		_tmp4_ = _tmp3_;
#line 1539 "glib-2.0.vapi"
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
#line 1539 "glib-2.0.vapi"
		_tmp6_ = _tmp5_;
#line 1539 "glib-2.0.vapi"
		_g_free0 (_tmp4_);
#line 1539 "glib-2.0.vapi"
		regex = _tmp6_;
#line 1539 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1539 "glib-2.0.vapi"
			_g_free0 (_tmp7_);
#line 1539 "glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1539 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 461 "Highlighter.c"
				goto __catch0_g_regex_error;
			}
#line 1539 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1539 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1539 "glib-2.0.vapi"
			return NULL;
#line 470 "Highlighter.c"
		}
#line 1540 "glib-2.0.vapi"
		_tmp8_ = regex;
#line 1540 "glib-2.0.vapi"
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
#line 1540 "glib-2.0.vapi"
		_tmp7_ = _tmp9_;
#line 1540 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1540 "glib-2.0.vapi"
			_g_free0 (_tmp7_);
#line 1540 "glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1540 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 486 "Highlighter.c"
				goto __catch0_g_regex_error;
			}
#line 1540 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1540 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1540 "glib-2.0.vapi"
			return NULL;
#line 495 "Highlighter.c"
		}
#line 1540 "glib-2.0.vapi"
		_tmp10_ = _tmp7_;
#line 1540 "glib-2.0.vapi"
		_tmp7_ = NULL;
#line 1540 "glib-2.0.vapi"
		result = _tmp10_;
#line 1540 "glib-2.0.vapi"
		_g_free0 (_tmp7_);
#line 1540 "glib-2.0.vapi"
		_g_regex_unref0 (regex);
#line 1540 "glib-2.0.vapi"
		return result;
#line 509 "Highlighter.c"
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
#line 1538 "glib-2.0.vapi"
		g_clear_error (&_inner_error0_);
#line 1542 "glib-2.0.vapi"
		g_assert_not_reached ();
#line 518 "Highlighter.c"
	}
	__finally0:
#line 1538 "glib-2.0.vapi"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1538 "glib-2.0.vapi"
	g_clear_error (&_inner_error0_);
#line 1538 "glib-2.0.vapi"
	return NULL;
#line 527 "Highlighter.c"
}

static gchar*
quilter_highlighter_real_convert (QuilterPluginsPlugin* base,
                                  const gchar* line_)
{
	QuilterHighlighter * self;
	gint initial = 0;
	gint last = 0;
	gchar* subline = NULL;
	gchar* _tmp0_;
	GSettings* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gboolean _tmp4_;
	GSettings* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gboolean _tmp16_;
	gchar* result = NULL;
#line 51 "../src/Plugins/Highlighter.vala"
	self = (QuilterHighlighter*) base;
#line 51 "../src/Plugins/Highlighter.vala"
	g_return_val_if_fail (line_ != NULL, NULL);
#line 52 "../src/Plugins/Highlighter.vala"
	initial = string_index_of (line_, "==", 0) + 2;
#line 53 "../src/Plugins/Highlighter.vala"
	last = string_index_of (line_, "==", initial);
#line 54 "../src/Plugins/Highlighter.vala"
	_tmp0_ = string_substring (line_, (glong) initial, (glong) (last - initial));
#line 54 "../src/Plugins/Highlighter.vala"
	subline = _tmp0_;
#line 55 "../src/Plugins/Highlighter.vala"
	_tmp1_ = quilter_application_gsettings;
#line 55 "../src/Plugins/Highlighter.vala"
	_tmp2_ = g_settings_get_string (_tmp1_, "visual-mode");
#line 55 "../src/Plugins/Highlighter.vala"
	_tmp3_ = _tmp2_;
#line 55 "../src/Plugins/Highlighter.vala"
	_tmp4_ = g_strcmp0 (_tmp3_, "dark") == 0;
#line 55 "../src/Plugins/Highlighter.vala"
	_g_free0 (_tmp3_);
#line 55 "../src/Plugins/Highlighter.vala"
	if (_tmp4_) {
#line 572 "Highlighter.c"
		const gchar* _tmp5_;
		gchar* _tmp6_;
		gchar* _tmp7_;
		const gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
#line 56 "../src/Plugins/Highlighter.vala"
		_tmp5_ = subline;
#line 56 "../src/Plugins/Highlighter.vala"
		_tmp6_ = g_strdup_printf ("==%s==", _tmp5_);
#line 56 "../src/Plugins/Highlighter.vala"
		_tmp7_ = _tmp6_;
#line 56 "../src/Plugins/Highlighter.vala"
		_tmp8_ = subline;
#line 56 "../src/Plugins/Highlighter.vala"
		_tmp9_ = g_strdup_printf ("<span style=\"background-color:#0DBCEE; color:#000; border: 3px solid " \
"#0DBCEE; border-radius: 4px;\">%s</span>", _tmp8_);
#line 56 "../src/Plugins/Highlighter.vala"
		_tmp10_ = _tmp9_;
#line 56 "../src/Plugins/Highlighter.vala"
		_tmp11_ = string_replace (line_, _tmp7_, _tmp10_);
#line 56 "../src/Plugins/Highlighter.vala"
		_tmp12_ = _tmp11_;
#line 56 "../src/Plugins/Highlighter.vala"
		_g_free0 (_tmp10_);
#line 56 "../src/Plugins/Highlighter.vala"
		_g_free0 (_tmp7_);
#line 56 "../src/Plugins/Highlighter.vala"
		result = _tmp12_;
#line 56 "../src/Plugins/Highlighter.vala"
		_g_free0 (subline);
#line 56 "../src/Plugins/Highlighter.vala"
		return result;
#line 607 "Highlighter.c"
	}
#line 57 "../src/Plugins/Highlighter.vala"
	_tmp13_ = quilter_application_gsettings;
#line 57 "../src/Plugins/Highlighter.vala"
	_tmp14_ = g_settings_get_string (_tmp13_, "visual-mode");
#line 57 "../src/Plugins/Highlighter.vala"
	_tmp15_ = _tmp14_;
#line 57 "../src/Plugins/Highlighter.vala"
	_tmp16_ = g_strcmp0 (_tmp15_, "sepia") == 0;
#line 57 "../src/Plugins/Highlighter.vala"
	_g_free0 (_tmp15_);
#line 57 "../src/Plugins/Highlighter.vala"
	if (_tmp16_) {
#line 621 "Highlighter.c"
		const gchar* _tmp17_;
		gchar* _tmp18_;
		gchar* _tmp19_;
		const gchar* _tmp20_;
		gchar* _tmp21_;
		gchar* _tmp22_;
		gchar* _tmp23_;
		gchar* _tmp24_;
#line 58 "../src/Plugins/Highlighter.vala"
		_tmp17_ = subline;
#line 58 "../src/Plugins/Highlighter.vala"
		_tmp18_ = g_strdup_printf ("==%s==", _tmp17_);
#line 58 "../src/Plugins/Highlighter.vala"
		_tmp19_ = _tmp18_;
#line 58 "../src/Plugins/Highlighter.vala"
		_tmp20_ = subline;
#line 58 "../src/Plugins/Highlighter.vala"
		_tmp21_ = g_strdup_printf ("<span style=\"background-color:#00897B; color:#FFF; border: 3px solid " \
"#00897b; border-radius: 4px;\">%s</span>", _tmp20_);
#line 58 "../src/Plugins/Highlighter.vala"
		_tmp22_ = _tmp21_;
#line 58 "../src/Plugins/Highlighter.vala"
		_tmp23_ = string_replace (line_, _tmp19_, _tmp22_);
#line 58 "../src/Plugins/Highlighter.vala"
		_tmp24_ = _tmp23_;
#line 58 "../src/Plugins/Highlighter.vala"
		_g_free0 (_tmp22_);
#line 58 "../src/Plugins/Highlighter.vala"
		_g_free0 (_tmp19_);
#line 58 "../src/Plugins/Highlighter.vala"
		result = _tmp24_;
#line 58 "../src/Plugins/Highlighter.vala"
		_g_free0 (subline);
#line 58 "../src/Plugins/Highlighter.vala"
		return result;
#line 656 "Highlighter.c"
	} else {
		const gchar* _tmp25_;
		gchar* _tmp26_;
		gchar* _tmp27_;
		const gchar* _tmp28_;
		gchar* _tmp29_;
		gchar* _tmp30_;
		gchar* _tmp31_;
		gchar* _tmp32_;
#line 60 "../src/Plugins/Highlighter.vala"
		_tmp25_ = subline;
#line 60 "../src/Plugins/Highlighter.vala"
		_tmp26_ = g_strdup_printf ("==%s==", _tmp25_);
#line 60 "../src/Plugins/Highlighter.vala"
		_tmp27_ = _tmp26_;
#line 60 "../src/Plugins/Highlighter.vala"
		_tmp28_ = subline;
#line 60 "../src/Plugins/Highlighter.vala"
		_tmp29_ = g_strdup_printf ("<span style=\"background-color:#0EBAFB; color:#FFF; border: 3px solid " \
"#0EBAFB; border-radius: 4px;\">%s</span>", _tmp28_);
#line 60 "../src/Plugins/Highlighter.vala"
		_tmp30_ = _tmp29_;
#line 60 "../src/Plugins/Highlighter.vala"
		_tmp31_ = string_replace (line_, _tmp27_, _tmp30_);
#line 60 "../src/Plugins/Highlighter.vala"
		_tmp32_ = _tmp31_;
#line 60 "../src/Plugins/Highlighter.vala"
		_g_free0 (_tmp30_);
#line 60 "../src/Plugins/Highlighter.vala"
		_g_free0 (_tmp27_);
#line 60 "../src/Plugins/Highlighter.vala"
		result = _tmp32_;
#line 60 "../src/Plugins/Highlighter.vala"
		_g_free0 (subline);
#line 60 "../src/Plugins/Highlighter.vala"
		return result;
#line 692 "Highlighter.c"
	}
#line 51 "../src/Plugins/Highlighter.vala"
	_g_free0 (subline);
#line 696 "Highlighter.c"
}

QuilterHighlighter*
quilter_highlighter_construct (GType object_type)
{
	QuilterHighlighter * self = NULL;
#line 22 "../src/Plugins/Highlighter.vala"
	self = (QuilterHighlighter*) quilter_plugins_plugin_construct (object_type);
#line 22 "../src/Plugins/Highlighter.vala"
	return self;
#line 707 "Highlighter.c"
}

QuilterHighlighter*
quilter_highlighter_new (void)
{
#line 22 "../src/Plugins/Highlighter.vala"
	return quilter_highlighter_construct (QUILTER_TYPE_HIGHLIGHTER);
#line 715 "Highlighter.c"
}

static GObject *
quilter_highlighter_constructor (GType type,
                                 guint n_construct_properties,
                                 GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	QuilterHighlighter * self;
#line 25 "../src/Plugins/Highlighter.vala"
	parent_class = G_OBJECT_CLASS (quilter_highlighter_parent_class);
#line 25 "../src/Plugins/Highlighter.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 25 "../src/Plugins/Highlighter.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_TYPE_HIGHLIGHTER, QuilterHighlighter);
#line 25 "../src/Plugins/Highlighter.vala"
	return obj;
#line 734 "Highlighter.c"
}

static void
quilter_highlighter_class_init (QuilterHighlighterClass * klass,
                                gpointer klass_data)
{
#line 22 "../src/Plugins/Highlighter.vala"
	quilter_highlighter_parent_class = g_type_class_peek_parent (klass);
#line 22 "../src/Plugins/Highlighter.vala"
	g_type_class_adjust_private_offset (klass, &QuilterHighlighter_private_offset);
#line 22 "../src/Plugins/Highlighter.vala"
	((QuilterPluginsPluginClass *) klass)->get_desctiption = (gchar* (*) (QuilterPluginsPlugin*)) quilter_highlighter_real_get_desctiption;
#line 22 "../src/Plugins/Highlighter.vala"
	((QuilterPluginsPluginClass *) klass)->get_name = (gchar* (*) (QuilterPluginsPlugin*)) quilter_highlighter_real_get_name;
#line 22 "../src/Plugins/Highlighter.vala"
	((QuilterPluginsPluginClass *) klass)->editor_button = (GtkWidget* (*) (QuilterPluginsPlugin*)) quilter_highlighter_real_editor_button;
#line 22 "../src/Plugins/Highlighter.vala"
	((QuilterPluginsPluginClass *) klass)->request_string = (gchar* (*) (QuilterPluginsPlugin*, const gchar*)) quilter_highlighter_real_request_string;
#line 22 "../src/Plugins/Highlighter.vala"
	((QuilterPluginsPluginClass *) klass)->get_button_desctiption = (gchar* (*) (QuilterPluginsPlugin*)) quilter_highlighter_real_get_button_desctiption;
#line 22 "../src/Plugins/Highlighter.vala"
	((QuilterPluginsPluginClass *) klass)->has_match = (gboolean (*) (QuilterPluginsPlugin*, const gchar*)) quilter_highlighter_real_has_match;
#line 22 "../src/Plugins/Highlighter.vala"
	((QuilterPluginsPluginClass *) klass)->convert = (gchar* (*) (QuilterPluginsPlugin*, const gchar*)) quilter_highlighter_real_convert;
#line 22 "../src/Plugins/Highlighter.vala"
	G_OBJECT_CLASS (klass)->constructor = quilter_highlighter_constructor;
#line 22 "../src/Plugins/Highlighter.vala"
	G_OBJECT_CLASS (klass)->finalize = quilter_highlighter_finalize;
#line 763 "Highlighter.c"
}

static void
quilter_highlighter_instance_init (QuilterHighlighter * self,
                                   gpointer klass)
{
	GPatternSpec* _tmp0_;
#line 22 "../src/Plugins/Highlighter.vala"
	self->priv = quilter_highlighter_get_instance_private (self);
#line 23 "../src/Plugins/Highlighter.vala"
	_tmp0_ = g_pattern_spec_new ("*==*==*");
#line 23 "../src/Plugins/Highlighter.vala"
	self->priv->spec = _tmp0_;
#line 777 "Highlighter.c"
}

static void
quilter_highlighter_finalize (GObject * obj)
{
	QuilterHighlighter * self;
#line 22 "../src/Plugins/Highlighter.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_TYPE_HIGHLIGHTER, QuilterHighlighter);
#line 23 "../src/Plugins/Highlighter.vala"
	_g_pattern_spec_free0 (self->priv->spec);
#line 22 "../src/Plugins/Highlighter.vala"
	G_OBJECT_CLASS (quilter_highlighter_parent_class)->finalize (obj);
#line 790 "Highlighter.c"
}

static GType
quilter_highlighter_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (QuilterHighlighterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_highlighter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterHighlighter), 0, (GInstanceInitFunc) quilter_highlighter_instance_init, NULL };
	GType quilter_highlighter_type_id;
	quilter_highlighter_type_id = g_type_register_static (QUILTER_PLUGINS_TYPE_PLUGIN, "QuilterHighlighter", &g_define_type_info, 0);
	QuilterHighlighter_private_offset = g_type_add_instance_private (quilter_highlighter_type_id, sizeof (QuilterHighlighterPrivate));
	return quilter_highlighter_type_id;
}

GType
quilter_highlighter_get_type (void)
{
	static volatile gsize quilter_highlighter_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_highlighter_type_id__volatile)) {
		GType quilter_highlighter_type_id;
		quilter_highlighter_type_id = quilter_highlighter_get_type_once ();
		g_once_init_leave (&quilter_highlighter_type_id__volatile, quilter_highlighter_type_id);
	}
	return quilter_highlighter_type_id__volatile;
}

