/* PluginManager.c generated by valac 0.50.2, the Vala compiler
 * generated from PluginManager.vala, do not modify */

/*
* Copyright (c) 2017-2020 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*
* Co-authored by: Felipe Escoto <felescoto95@hotmail.com>
*/

#include <glib-object.h>
#include <glib.h>

#define QUILTER_PLUGINS_TYPE_PLUGIN_MANAGER (quilter_plugins_plugin_manager_get_type ())
#define QUILTER_PLUGINS_PLUGIN_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_PLUGINS_TYPE_PLUGIN_MANAGER, QuilterPluginsPluginManager))
#define QUILTER_PLUGINS_PLUGIN_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_PLUGINS_TYPE_PLUGIN_MANAGER, QuilterPluginsPluginManagerClass))
#define QUILTER_PLUGINS_IS_PLUGIN_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_PLUGINS_TYPE_PLUGIN_MANAGER))
#define QUILTER_PLUGINS_IS_PLUGIN_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_PLUGINS_TYPE_PLUGIN_MANAGER))
#define QUILTER_PLUGINS_PLUGIN_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_PLUGINS_TYPE_PLUGIN_MANAGER, QuilterPluginsPluginManagerClass))

typedef struct _QuilterPluginsPluginManager QuilterPluginsPluginManager;
typedef struct _QuilterPluginsPluginManagerClass QuilterPluginsPluginManagerClass;
typedef struct _QuilterPluginsPluginManagerPrivate QuilterPluginsPluginManagerPrivate;

#define QUILTER_PLUGINS_TYPE_PLUGIN (quilter_plugins_plugin_get_type ())
#define QUILTER_PLUGINS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPlugin))
#define QUILTER_PLUGINS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPluginClass))
#define QUILTER_PLUGINS_IS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_PLUGINS_TYPE_PLUGIN))
#define QUILTER_PLUGINS_IS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_PLUGINS_TYPE_PLUGIN))
#define QUILTER_PLUGINS_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPluginClass))

typedef struct _QuilterPluginsPlugin QuilterPluginsPlugin;
typedef struct _QuilterPluginsPluginClass QuilterPluginsPluginClass;
enum  {
	QUILTER_PLUGINS_PLUGIN_MANAGER_0_PROPERTY,
	QUILTER_PLUGINS_PLUGIN_MANAGER_NUM_PROPERTIES
};
static GParamSpec* quilter_plugins_plugin_manager_properties[QUILTER_PLUGINS_PLUGIN_MANAGER_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define QUILTER_TYPE_IMAGE (quilter_image_get_type ())
#define QUILTER_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_IMAGE, QuilterImage))
#define QUILTER_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_IMAGE, QuilterImageClass))
#define QUILTER_IS_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_IMAGE))
#define QUILTER_IS_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_IMAGE))
#define QUILTER_IMAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_IMAGE, QuilterImageClass))

typedef struct _QuilterImage QuilterImage;
typedef struct _QuilterImageClass QuilterImageClass;

#define QUILTER_TYPE_FILEP (quilter_filep_get_type ())
#define QUILTER_FILEP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_FILEP, QuilterFilep))
#define QUILTER_FILEP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_FILEP, QuilterFilepClass))
#define QUILTER_IS_FILEP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_FILEP))
#define QUILTER_IS_FILEP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_FILEP))
#define QUILTER_FILEP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_FILEP, QuilterFilepClass))

typedef struct _QuilterFilep QuilterFilep;
typedef struct _QuilterFilepClass QuilterFilepClass;

#define QUILTER_TYPE_CHECKBOX (quilter_checkbox_get_type ())
#define QUILTER_CHECKBOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_CHECKBOX, QuilterCheckbox))
#define QUILTER_CHECKBOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_CHECKBOX, QuilterCheckboxClass))
#define QUILTER_IS_CHECKBOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_CHECKBOX))
#define QUILTER_IS_CHECKBOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_CHECKBOX))
#define QUILTER_CHECKBOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_CHECKBOX, QuilterCheckboxClass))

typedef struct _QuilterCheckbox QuilterCheckbox;
typedef struct _QuilterCheckboxClass QuilterCheckboxClass;

#define QUILTER_TYPE_CHECKBOX_CHECKED (quilter_checkbox_checked_get_type ())
#define QUILTER_CHECKBOX_CHECKED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_CHECKBOX_CHECKED, QuilterCheckboxChecked))
#define QUILTER_CHECKBOX_CHECKED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_CHECKBOX_CHECKED, QuilterCheckboxCheckedClass))
#define QUILTER_IS_CHECKBOX_CHECKED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_CHECKBOX_CHECKED))
#define QUILTER_IS_CHECKBOX_CHECKED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_CHECKBOX_CHECKED))
#define QUILTER_CHECKBOX_CHECKED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_CHECKBOX_CHECKED, QuilterCheckboxCheckedClass))

typedef struct _QuilterCheckboxChecked QuilterCheckboxChecked;
typedef struct _QuilterCheckboxCheckedClass QuilterCheckboxCheckedClass;

#define QUILTER_TYPE_HIGHLIGHTER (quilter_highlighter_get_type ())
#define QUILTER_HIGHLIGHTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_HIGHLIGHTER, QuilterHighlighter))
#define QUILTER_HIGHLIGHTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_HIGHLIGHTER, QuilterHighlighterClass))
#define QUILTER_IS_HIGHLIGHTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_HIGHLIGHTER))
#define QUILTER_IS_HIGHLIGHTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_HIGHLIGHTER))
#define QUILTER_HIGHLIGHTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_HIGHLIGHTER, QuilterHighlighterClass))

typedef struct _QuilterHighlighter QuilterHighlighter;
typedef struct _QuilterHighlighterClass QuilterHighlighterClass;

#define QUILTER_TYPE_SUPERSCRIPT (quilter_superscript_get_type ())
#define QUILTER_SUPERSCRIPT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_SUPERSCRIPT, QuilterSuperscript))
#define QUILTER_SUPERSCRIPT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_SUPERSCRIPT, QuilterSuperscriptClass))
#define QUILTER_IS_SUPERSCRIPT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_SUPERSCRIPT))
#define QUILTER_IS_SUPERSCRIPT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_SUPERSCRIPT))
#define QUILTER_SUPERSCRIPT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_SUPERSCRIPT, QuilterSuperscriptClass))

typedef struct _QuilterSuperscript QuilterSuperscript;
typedef struct _QuilterSuperscriptClass QuilterSuperscriptClass;

#define QUILTER_TYPE_SUBSCRIPT (quilter_subscript_get_type ())
#define QUILTER_SUBSCRIPT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_SUBSCRIPT, QuilterSubscript))
#define QUILTER_SUBSCRIPT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_SUBSCRIPT, QuilterSubscriptClass))
#define QUILTER_IS_SUBSCRIPT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_SUBSCRIPT))
#define QUILTER_IS_SUBSCRIPT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_SUBSCRIPT))
#define QUILTER_SUBSCRIPT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_SUBSCRIPT, QuilterSubscriptClass))

typedef struct _QuilterSubscript QuilterSubscript;
typedef struct _QuilterSubscriptClass QuilterSubscriptClass;

struct _QuilterPluginsPluginManager {
	GObject parent_instance;
	QuilterPluginsPluginManagerPrivate * priv;
};

struct _QuilterPluginsPluginManagerClass {
	GObjectClass parent_class;
};

struct _QuilterPluginsPluginManagerPrivate {
	QuilterPluginsPlugin** plug_list;
	gint plug_list_length1;
	gint _plug_list_size_;
};

static gint QuilterPluginsPluginManager_private_offset;
static gpointer quilter_plugins_plugin_manager_parent_class = NULL;
static QuilterPluginsPluginManager* quilter_plugins_plugin_manager_instance;
static QuilterPluginsPluginManager* quilter_plugins_plugin_manager_instance = NULL;

GType quilter_plugins_plugin_manager_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterPluginsPluginManager, g_object_unref)
GType quilter_plugins_plugin_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterPluginsPlugin, g_object_unref)
static QuilterPluginsPluginManager* quilter_plugins_plugin_manager_new (void);
static QuilterPluginsPluginManager* quilter_plugins_plugin_manager_construct (GType object_type);
QuilterPluginsPluginManager* quilter_plugins_plugin_manager_get_instance (void);
static void quilter_plugins_plugin_manager_load_plugins (QuilterPluginsPluginManager* self);
QuilterImage* quilter_image_new (void);
QuilterImage* quilter_image_construct (GType object_type);
GType quilter_image_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterImage, g_object_unref)
static void _vala_array_add8 (QuilterPluginsPlugin** * array,
                       gint* length,
                       gint* size,
                       QuilterPluginsPlugin* value);
QuilterFilep* quilter_filep_new (void);
QuilterFilep* quilter_filep_construct (GType object_type);
GType quilter_filep_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterFilep, g_object_unref)
static void _vala_array_add9 (QuilterPluginsPlugin** * array,
                       gint* length,
                       gint* size,
                       QuilterPluginsPlugin* value);
QuilterCheckbox* quilter_checkbox_new (void);
QuilterCheckbox* quilter_checkbox_construct (GType object_type);
GType quilter_checkbox_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterCheckbox, g_object_unref)
static void _vala_array_add10 (QuilterPluginsPlugin** * array,
                        gint* length,
                        gint* size,
                        QuilterPluginsPlugin* value);
QuilterCheckboxChecked* quilter_checkbox_checked_new (void);
QuilterCheckboxChecked* quilter_checkbox_checked_construct (GType object_type);
GType quilter_checkbox_checked_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterCheckboxChecked, g_object_unref)
static void _vala_array_add11 (QuilterPluginsPlugin** * array,
                        gint* length,
                        gint* size,
                        QuilterPluginsPlugin* value);
QuilterHighlighter* quilter_highlighter_new (void);
QuilterHighlighter* quilter_highlighter_construct (GType object_type);
GType quilter_highlighter_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterHighlighter, g_object_unref)
static void _vala_array_add12 (QuilterPluginsPlugin** * array,
                        gint* length,
                        gint* size,
                        QuilterPluginsPlugin* value);
QuilterSuperscript* quilter_superscript_new (void);
QuilterSuperscript* quilter_superscript_construct (GType object_type);
GType quilter_superscript_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterSuperscript, g_object_unref)
static void _vala_array_add13 (QuilterPluginsPlugin** * array,
                        gint* length,
                        gint* size,
                        QuilterPluginsPlugin* value);
QuilterSubscript* quilter_subscript_new (void);
QuilterSubscript* quilter_subscript_construct (GType object_type);
GType quilter_subscript_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterSubscript, g_object_unref)
static void _vala_array_add14 (QuilterPluginsPlugin** * array,
                        gint* length,
                        gint* size,
                        QuilterPluginsPlugin* value);
GList* quilter_plugins_plugin_manager_get_plugs (QuilterPluginsPluginManager* self);
gboolean quilter_plugins_plugin_is_active (QuilterPluginsPlugin* self);
static void quilter_plugins_plugin_manager_finalize (GObject * obj);
static GType quilter_plugins_plugin_manager_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

static inline gpointer
quilter_plugins_plugin_manager_get_instance_private (QuilterPluginsPluginManager* self)
{
	return G_STRUCT_MEMBER_P (self, QuilterPluginsPluginManager_private_offset);
}

static QuilterPluginsPluginManager*
quilter_plugins_plugin_manager_construct (GType object_type)
{
	QuilterPluginsPluginManager * self = NULL;
#line 28 "../src/Plugins/PluginManager.vala"
	self = (QuilterPluginsPluginManager*) g_object_new (object_type, NULL);
#line 28 "../src/Plugins/PluginManager.vala"
	return self;
#line 235 "PluginManager.c"
}

static QuilterPluginsPluginManager*
quilter_plugins_plugin_manager_new (void)
{
#line 28 "../src/Plugins/PluginManager.vala"
	return quilter_plugins_plugin_manager_construct (QUILTER_PLUGINS_TYPE_PLUGIN_MANAGER);
#line 243 "PluginManager.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 38 "../src/Plugins/PluginManager.vala"
	return self ? g_object_ref (self) : NULL;
#line 251 "PluginManager.c"
}

QuilterPluginsPluginManager*
quilter_plugins_plugin_manager_get_instance (void)
{
	QuilterPluginsPluginManager* _tmp0_;
	QuilterPluginsPluginManager* _tmp3_;
	QuilterPluginsPluginManager* _tmp4_;
	QuilterPluginsPluginManager* result = NULL;
#line 33 "../src/Plugins/PluginManager.vala"
	_tmp0_ = quilter_plugins_plugin_manager_instance;
#line 33 "../src/Plugins/PluginManager.vala"
	if (_tmp0_ == NULL) {
#line 265 "PluginManager.c"
		QuilterPluginsPluginManager* _tmp1_;
		QuilterPluginsPluginManager* _tmp2_;
#line 34 "../src/Plugins/PluginManager.vala"
		_tmp1_ = quilter_plugins_plugin_manager_new ();
#line 34 "../src/Plugins/PluginManager.vala"
		_g_object_unref0 (quilter_plugins_plugin_manager_instance);
#line 34 "../src/Plugins/PluginManager.vala"
		quilter_plugins_plugin_manager_instance = _tmp1_;
#line 35 "../src/Plugins/PluginManager.vala"
		_tmp2_ = quilter_plugins_plugin_manager_instance;
#line 35 "../src/Plugins/PluginManager.vala"
		quilter_plugins_plugin_manager_load_plugins (_tmp2_);
#line 278 "PluginManager.c"
	}
#line 38 "../src/Plugins/PluginManager.vala"
	_tmp3_ = quilter_plugins_plugin_manager_instance;
#line 38 "../src/Plugins/PluginManager.vala"
	_tmp4_ = _g_object_ref0 (_tmp3_);
#line 38 "../src/Plugins/PluginManager.vala"
	result = _tmp4_;
#line 38 "../src/Plugins/PluginManager.vala"
	return result;
#line 288 "PluginManager.c"
}

static void
_vala_array_add8 (QuilterPluginsPlugin** * array,
                  gint* length,
                  gint* size,
                  QuilterPluginsPlugin* value)
{
#line 42 "../src/Plugins/PluginManager.vala"
	if ((*length) == (*size)) {
#line 42 "../src/Plugins/PluginManager.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 42 "../src/Plugins/PluginManager.vala"
		*array = g_renew (QuilterPluginsPlugin*, *array, (*size) + 1);
#line 303 "PluginManager.c"
	}
#line 42 "../src/Plugins/PluginManager.vala"
	(*array)[(*length)++] = value;
#line 42 "../src/Plugins/PluginManager.vala"
	(*array)[*length] = NULL;
#line 309 "PluginManager.c"
}

static void
_vala_array_add9 (QuilterPluginsPlugin** * array,
                  gint* length,
                  gint* size,
                  QuilterPluginsPlugin* value)
{
#line 43 "../src/Plugins/PluginManager.vala"
	if ((*length) == (*size)) {
#line 43 "../src/Plugins/PluginManager.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 43 "../src/Plugins/PluginManager.vala"
		*array = g_renew (QuilterPluginsPlugin*, *array, (*size) + 1);
#line 324 "PluginManager.c"
	}
#line 43 "../src/Plugins/PluginManager.vala"
	(*array)[(*length)++] = value;
#line 43 "../src/Plugins/PluginManager.vala"
	(*array)[*length] = NULL;
#line 330 "PluginManager.c"
}

static void
_vala_array_add10 (QuilterPluginsPlugin** * array,
                   gint* length,
                   gint* size,
                   QuilterPluginsPlugin* value)
{
#line 44 "../src/Plugins/PluginManager.vala"
	if ((*length) == (*size)) {
#line 44 "../src/Plugins/PluginManager.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 44 "../src/Plugins/PluginManager.vala"
		*array = g_renew (QuilterPluginsPlugin*, *array, (*size) + 1);
#line 345 "PluginManager.c"
	}
#line 44 "../src/Plugins/PluginManager.vala"
	(*array)[(*length)++] = value;
#line 44 "../src/Plugins/PluginManager.vala"
	(*array)[*length] = NULL;
#line 351 "PluginManager.c"
}

static void
_vala_array_add11 (QuilterPluginsPlugin** * array,
                   gint* length,
                   gint* size,
                   QuilterPluginsPlugin* value)
{
#line 45 "../src/Plugins/PluginManager.vala"
	if ((*length) == (*size)) {
#line 45 "../src/Plugins/PluginManager.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 45 "../src/Plugins/PluginManager.vala"
		*array = g_renew (QuilterPluginsPlugin*, *array, (*size) + 1);
#line 366 "PluginManager.c"
	}
#line 45 "../src/Plugins/PluginManager.vala"
	(*array)[(*length)++] = value;
#line 45 "../src/Plugins/PluginManager.vala"
	(*array)[*length] = NULL;
#line 372 "PluginManager.c"
}

static void
_vala_array_add12 (QuilterPluginsPlugin** * array,
                   gint* length,
                   gint* size,
                   QuilterPluginsPlugin* value)
{
#line 46 "../src/Plugins/PluginManager.vala"
	if ((*length) == (*size)) {
#line 46 "../src/Plugins/PluginManager.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 46 "../src/Plugins/PluginManager.vala"
		*array = g_renew (QuilterPluginsPlugin*, *array, (*size) + 1);
#line 387 "PluginManager.c"
	}
#line 46 "../src/Plugins/PluginManager.vala"
	(*array)[(*length)++] = value;
#line 46 "../src/Plugins/PluginManager.vala"
	(*array)[*length] = NULL;
#line 393 "PluginManager.c"
}

static void
_vala_array_add13 (QuilterPluginsPlugin** * array,
                   gint* length,
                   gint* size,
                   QuilterPluginsPlugin* value)
{
#line 47 "../src/Plugins/PluginManager.vala"
	if ((*length) == (*size)) {
#line 47 "../src/Plugins/PluginManager.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 47 "../src/Plugins/PluginManager.vala"
		*array = g_renew (QuilterPluginsPlugin*, *array, (*size) + 1);
#line 408 "PluginManager.c"
	}
#line 47 "../src/Plugins/PluginManager.vala"
	(*array)[(*length)++] = value;
#line 47 "../src/Plugins/PluginManager.vala"
	(*array)[*length] = NULL;
#line 414 "PluginManager.c"
}

static void
_vala_array_add14 (QuilterPluginsPlugin** * array,
                   gint* length,
                   gint* size,
                   QuilterPluginsPlugin* value)
{
#line 48 "../src/Plugins/PluginManager.vala"
	if ((*length) == (*size)) {
#line 48 "../src/Plugins/PluginManager.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 48 "../src/Plugins/PluginManager.vala"
		*array = g_renew (QuilterPluginsPlugin*, *array, (*size) + 1);
#line 429 "PluginManager.c"
	}
#line 48 "../src/Plugins/PluginManager.vala"
	(*array)[(*length)++] = value;
#line 48 "../src/Plugins/PluginManager.vala"
	(*array)[*length] = NULL;
#line 435 "PluginManager.c"
}

static void
quilter_plugins_plugin_manager_load_plugins (QuilterPluginsPluginManager* self)
{
	QuilterImage* _tmp0_;
	QuilterFilep* _tmp1_;
	QuilterCheckbox* _tmp2_;
	QuilterCheckboxChecked* _tmp3_;
	QuilterHighlighter* _tmp4_;
	QuilterSuperscript* _tmp5_;
	QuilterSubscript* _tmp6_;
#line 41 "../src/Plugins/PluginManager.vala"
	g_return_if_fail (self != NULL);
#line 42 "../src/Plugins/PluginManager.vala"
	_tmp0_ = quilter_image_new ();
#line 42 "../src/Plugins/PluginManager.vala"
	_vala_array_add8 (&self->priv->plug_list, &self->priv->plug_list_length1, &self->priv->_plug_list_size_, (QuilterPluginsPlugin*) _tmp0_);
#line 43 "../src/Plugins/PluginManager.vala"
	_tmp1_ = quilter_filep_new ();
#line 43 "../src/Plugins/PluginManager.vala"
	_vala_array_add9 (&self->priv->plug_list, &self->priv->plug_list_length1, &self->priv->_plug_list_size_, (QuilterPluginsPlugin*) _tmp1_);
#line 44 "../src/Plugins/PluginManager.vala"
	_tmp2_ = quilter_checkbox_new ();
#line 44 "../src/Plugins/PluginManager.vala"
	_vala_array_add10 (&self->priv->plug_list, &self->priv->plug_list_length1, &self->priv->_plug_list_size_, (QuilterPluginsPlugin*) _tmp2_);
#line 45 "../src/Plugins/PluginManager.vala"
	_tmp3_ = quilter_checkbox_checked_new ();
#line 45 "../src/Plugins/PluginManager.vala"
	_vala_array_add11 (&self->priv->plug_list, &self->priv->plug_list_length1, &self->priv->_plug_list_size_, (QuilterPluginsPlugin*) _tmp3_);
#line 46 "../src/Plugins/PluginManager.vala"
	_tmp4_ = quilter_highlighter_new ();
#line 46 "../src/Plugins/PluginManager.vala"
	_vala_array_add12 (&self->priv->plug_list, &self->priv->plug_list_length1, &self->priv->_plug_list_size_, (QuilterPluginsPlugin*) _tmp4_);
#line 47 "../src/Plugins/PluginManager.vala"
	_tmp5_ = quilter_superscript_new ();
#line 47 "../src/Plugins/PluginManager.vala"
	_vala_array_add13 (&self->priv->plug_list, &self->priv->plug_list_length1, &self->priv->_plug_list_size_, (QuilterPluginsPlugin*) _tmp5_);
#line 48 "../src/Plugins/PluginManager.vala"
	_tmp6_ = quilter_subscript_new ();
#line 48 "../src/Plugins/PluginManager.vala"
	_vala_array_add14 (&self->priv->plug_list, &self->priv->plug_list_length1, &self->priv->_plug_list_size_, (QuilterPluginsPlugin*) _tmp6_);
#line 478 "PluginManager.c"
}

GList*
quilter_plugins_plugin_manager_get_plugs (QuilterPluginsPluginManager* self)
{
	GList* plugs = NULL;
	QuilterPluginsPlugin** _tmp0_;
	gint _tmp0__length1;
	GList* result = NULL;
#line 51 "../src/Plugins/PluginManager.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 52 "../src/Plugins/PluginManager.vala"
	plugs = NULL;
#line 54 "../src/Plugins/PluginManager.vala"
	_tmp0_ = self->priv->plug_list;
#line 54 "../src/Plugins/PluginManager.vala"
	_tmp0__length1 = self->priv->plug_list_length1;
#line 496 "PluginManager.c"
	{
		QuilterPluginsPlugin** plugin_collection = NULL;
		gint plugin_collection_length1 = 0;
		gint _plugin_collection_size_ = 0;
		gint plugin_it = 0;
#line 54 "../src/Plugins/PluginManager.vala"
		plugin_collection = _tmp0_;
#line 54 "../src/Plugins/PluginManager.vala"
		plugin_collection_length1 = _tmp0__length1;
#line 54 "../src/Plugins/PluginManager.vala"
		for (plugin_it = 0; plugin_it < plugin_collection_length1; plugin_it = plugin_it + 1) {
#line 508 "PluginManager.c"
			QuilterPluginsPlugin* _tmp1_;
			QuilterPluginsPlugin* plugin = NULL;
#line 54 "../src/Plugins/PluginManager.vala"
			_tmp1_ = _g_object_ref0 (plugin_collection[plugin_it]);
#line 54 "../src/Plugins/PluginManager.vala"
			plugin = _tmp1_;
#line 515 "PluginManager.c"
			{
				QuilterPluginsPlugin* _tmp2_;
#line 55 "../src/Plugins/PluginManager.vala"
				_tmp2_ = plugin;
#line 55 "../src/Plugins/PluginManager.vala"
				if (quilter_plugins_plugin_is_active (_tmp2_)) {
#line 522 "PluginManager.c"
					QuilterPluginsPlugin* _tmp3_;
					QuilterPluginsPlugin* _tmp4_;
#line 56 "../src/Plugins/PluginManager.vala"
					_tmp3_ = plugin;
#line 56 "../src/Plugins/PluginManager.vala"
					_tmp4_ = _g_object_ref0 (_tmp3_);
#line 56 "../src/Plugins/PluginManager.vala"
					plugs = g_list_append (plugs, _tmp4_);
#line 531 "PluginManager.c"
				}
#line 54 "../src/Plugins/PluginManager.vala"
				_g_object_unref0 (plugin);
#line 535 "PluginManager.c"
			}
		}
	}
#line 60 "../src/Plugins/PluginManager.vala"
	result = plugs;
#line 60 "../src/Plugins/PluginManager.vala"
	return result;
#line 543 "PluginManager.c"
}

static void
quilter_plugins_plugin_manager_class_init (QuilterPluginsPluginManagerClass * klass,
                                           gpointer klass_data)
{
#line 23 "../src/Plugins/PluginManager.vala"
	quilter_plugins_plugin_manager_parent_class = g_type_class_peek_parent (klass);
#line 23 "../src/Plugins/PluginManager.vala"
	g_type_class_adjust_private_offset (klass, &QuilterPluginsPluginManager_private_offset);
#line 23 "../src/Plugins/PluginManager.vala"
	G_OBJECT_CLASS (klass)->finalize = quilter_plugins_plugin_manager_finalize;
#line 556 "PluginManager.c"
}

static void
quilter_plugins_plugin_manager_instance_init (QuilterPluginsPluginManager * self,
                                              gpointer klass)
{
	QuilterPluginsPlugin** _tmp0_;
#line 23 "../src/Plugins/PluginManager.vala"
	self->priv = quilter_plugins_plugin_manager_get_instance_private (self);
#line 26 "../src/Plugins/PluginManager.vala"
	_tmp0_ = g_new0 (QuilterPluginsPlugin*, 0 + 1);
#line 26 "../src/Plugins/PluginManager.vala"
	self->priv->plug_list = _tmp0_;
#line 26 "../src/Plugins/PluginManager.vala"
	self->priv->plug_list_length1 = 0;
#line 26 "../src/Plugins/PluginManager.vala"
	self->priv->_plug_list_size_ = self->priv->plug_list_length1;
#line 574 "PluginManager.c"
}

static void
quilter_plugins_plugin_manager_finalize (GObject * obj)
{
	QuilterPluginsPluginManager * self;
#line 23 "../src/Plugins/PluginManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_PLUGINS_TYPE_PLUGIN_MANAGER, QuilterPluginsPluginManager);
#line 26 "../src/Plugins/PluginManager.vala"
	self->priv->plug_list = (_vala_array_free (self->priv->plug_list, self->priv->plug_list_length1, (GDestroyNotify) g_object_unref), NULL);
#line 23 "../src/Plugins/PluginManager.vala"
	G_OBJECT_CLASS (quilter_plugins_plugin_manager_parent_class)->finalize (obj);
#line 587 "PluginManager.c"
}

static GType
quilter_plugins_plugin_manager_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (QuilterPluginsPluginManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_plugins_plugin_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterPluginsPluginManager), 0, (GInstanceInitFunc) quilter_plugins_plugin_manager_instance_init, NULL };
	GType quilter_plugins_plugin_manager_type_id;
	quilter_plugins_plugin_manager_type_id = g_type_register_static (G_TYPE_OBJECT, "QuilterPluginsPluginManager", &g_define_type_info, 0);
	QuilterPluginsPluginManager_private_offset = g_type_add_instance_private (quilter_plugins_plugin_manager_type_id, sizeof (QuilterPluginsPluginManagerPrivate));
	return quilter_plugins_plugin_manager_type_id;
}

GType
quilter_plugins_plugin_manager_get_type (void)
{
	static volatile gsize quilter_plugins_plugin_manager_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_plugins_plugin_manager_type_id__volatile)) {
		GType quilter_plugins_plugin_manager_type_id;
		quilter_plugins_plugin_manager_type_id = quilter_plugins_plugin_manager_get_type_once ();
		g_once_init_leave (&quilter_plugins_plugin_manager_type_id__volatile, quilter_plugins_plugin_manager_type_id);
	}
	return quilter_plugins_plugin_manager_type_id__volatile;
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gint i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

