/* Plugin.c generated by valac 0.50.2, the Vala compiler
 * generated from Plugin.vala, do not modify */

/*
* Copyright (c) 2017-2020 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*
* Co-authored by: Felipe Escoto <felescoto95@hotmail.com>
*/

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>

#define QUILTER_PLUGINS_TYPE_PLUGIN (quilter_plugins_plugin_get_type ())
#define QUILTER_PLUGINS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPlugin))
#define QUILTER_PLUGINS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPluginClass))
#define QUILTER_PLUGINS_IS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_PLUGINS_TYPE_PLUGIN))
#define QUILTER_PLUGINS_IS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_PLUGINS_TYPE_PLUGIN))
#define QUILTER_PLUGINS_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPluginClass))

typedef struct _QuilterPluginsPlugin QuilterPluginsPlugin;
typedef struct _QuilterPluginsPluginClass QuilterPluginsPluginClass;
typedef struct _QuilterPluginsPluginPrivate QuilterPluginsPluginPrivate;
enum  {
	QUILTER_PLUGINS_PLUGIN_0_PROPERTY,
	QUILTER_PLUGINS_PLUGIN_NUM_PROPERTIES
};
static GParamSpec* quilter_plugins_plugin_properties[QUILTER_PLUGINS_PLUGIN_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
enum  {
	QUILTER_PLUGINS_PLUGIN_STRING_COOKED_SIGNAL,
	QUILTER_PLUGINS_PLUGIN_NUM_SIGNALS
};
static guint quilter_plugins_plugin_signals[QUILTER_PLUGINS_PLUGIN_NUM_SIGNALS] = {0};

struct _QuilterPluginsPlugin {
	GObject parent_instance;
	QuilterPluginsPluginPrivate * priv;
	GSettings* settings;
	gboolean state;
	gchar* code_name;
};

struct _QuilterPluginsPluginClass {
	GObjectClass parent_class;
	gboolean (*is_active) (QuilterPluginsPlugin* self);
	void (*set_active) (QuilterPluginsPlugin* self, gboolean active);
	gchar* (*get_desctiption) (QuilterPluginsPlugin* self);
	gchar* (*get_name) (QuilterPluginsPlugin* self);
	gboolean (*has_match) (QuilterPluginsPlugin* self, const gchar* text);
	gchar* (*convert) (QuilterPluginsPlugin* self, const gchar* line);
	GtkWidget* (*editor_button) (QuilterPluginsPlugin* self);
	gchar* (*get_button_desctiption) (QuilterPluginsPlugin* self);
	gchar* (*request_string) (QuilterPluginsPlugin* self, const gchar* selection);
};

static gpointer quilter_plugins_plugin_parent_class = NULL;
extern GSettings* quilter_application_gsettings;

GType quilter_plugins_plugin_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterPluginsPlugin, g_object_unref)
gboolean quilter_plugins_plugin_is_active (QuilterPluginsPlugin* self);
void quilter_plugins_plugin_set_active (QuilterPluginsPlugin* self,
                                        gboolean active);
gchar* quilter_plugins_plugin_get_desctiption (QuilterPluginsPlugin* self);
gchar* quilter_plugins_plugin_get_name (QuilterPluginsPlugin* self);
gboolean quilter_plugins_plugin_has_match (QuilterPluginsPlugin* self,
                                           const gchar* text);
gchar* quilter_plugins_plugin_convert (QuilterPluginsPlugin* self,
                                       const gchar* line);
GtkWidget* quilter_plugins_plugin_editor_button (QuilterPluginsPlugin* self);
gchar* quilter_plugins_plugin_get_button_desctiption (QuilterPluginsPlugin* self);
gchar* quilter_plugins_plugin_request_string (QuilterPluginsPlugin* self,
                                              const gchar* selection);
#define QUILTER_PLUGINS_PLUGIN_CHILD_SCHEMA_ID "com.github.lainsce.quilter.plugin_data.plugin"
#define QUILTER_PLUGINS_PLUGIN_CHILD_PATH "/com/github/lainsce/quilter/plugin_data/plugin/%s"
static gboolean quilter_plugins_plugin_real_is_active (QuilterPluginsPlugin* self);
static void quilter_plugins_plugin_real_set_active (QuilterPluginsPlugin* self,
                                             gboolean active);
static gchar* quilter_plugins_plugin_real_get_desctiption (QuilterPluginsPlugin* self);
static gchar* quilter_plugins_plugin_real_get_name (QuilterPluginsPlugin* self);
static gboolean quilter_plugins_plugin_real_has_match (QuilterPluginsPlugin* self,
                                                const gchar* text);
static gchar* quilter_plugins_plugin_real_convert (QuilterPluginsPlugin* self,
                                            const gchar* line);
static GtkWidget* quilter_plugins_plugin_real_editor_button (QuilterPluginsPlugin* self);
static gchar* quilter_plugins_plugin_real_get_button_desctiption (QuilterPluginsPlugin* self);
static gchar* quilter_plugins_plugin_real_request_string (QuilterPluginsPlugin* self,
                                                   const gchar* selection);
void quilter_plugins_plugin_connect_settings (QuilterPluginsPlugin* self,
                                              const gchar* setting);
QuilterPluginsPlugin* quilter_plugins_plugin_construct (GType object_type);
static void quilter_plugins_plugin_finalize (GObject * obj);
static GType quilter_plugins_plugin_get_type_once (void);

static gboolean
quilter_plugins_plugin_real_is_active (QuilterPluginsPlugin* self)
{
	gboolean result = FALSE;
#line 35 "../src/Plugins/Plugin.vala"
	result = self->state;
#line 35 "../src/Plugins/Plugin.vala"
	return result;
#line 124 "Plugin.c"
}

gboolean
quilter_plugins_plugin_is_active (QuilterPluginsPlugin* self)
{
	QuilterPluginsPluginClass* _klass_;
#line 34 "../src/Plugins/Plugin.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 34 "../src/Plugins/Plugin.vala"
	_klass_ = QUILTER_PLUGINS_PLUGIN_GET_CLASS (self);
#line 34 "../src/Plugins/Plugin.vala"
	if (_klass_->is_active) {
#line 34 "../src/Plugins/Plugin.vala"
		return _klass_->is_active (self);
#line 139 "Plugin.c"
	}
#line 34 "../src/Plugins/Plugin.vala"
	return FALSE;
#line 143 "Plugin.c"
}

static void
quilter_plugins_plugin_real_set_active (QuilterPluginsPlugin* self,
                                        gboolean active)
{
	GSettings* _tmp0_;
#line 39 "../src/Plugins/Plugin.vala"
	_tmp0_ = self->settings;
#line 39 "../src/Plugins/Plugin.vala"
	if (_tmp0_ != NULL) {
#line 155 "Plugin.c"
		GSettings* _tmp1_;
#line 40 "../src/Plugins/Plugin.vala"
		_tmp1_ = self->settings;
#line 40 "../src/Plugins/Plugin.vala"
		g_settings_set_boolean (_tmp1_, "active", active);
#line 161 "Plugin.c"
	}
}

void
quilter_plugins_plugin_set_active (QuilterPluginsPlugin* self,
                                   gboolean active)
{
	QuilterPluginsPluginClass* _klass_;
#line 38 "../src/Plugins/Plugin.vala"
	g_return_if_fail (self != NULL);
#line 38 "../src/Plugins/Plugin.vala"
	_klass_ = QUILTER_PLUGINS_PLUGIN_GET_CLASS (self);
#line 38 "../src/Plugins/Plugin.vala"
	if (_klass_->set_active) {
#line 38 "../src/Plugins/Plugin.vala"
		_klass_->set_active (self, active);
#line 178 "Plugin.c"
	}
}

static gchar*
quilter_plugins_plugin_real_get_desctiption (QuilterPluginsPlugin* self)
{
#line 45 "../src/Plugins/Plugin.vala"
	g_critical ("Type `%s' does not implement abstract method `quilter_plugins_plugin_get_desctiption'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 45 "../src/Plugins/Plugin.vala"
	return NULL;
#line 189 "Plugin.c"
}

gchar*
quilter_plugins_plugin_get_desctiption (QuilterPluginsPlugin* self)
{
	QuilterPluginsPluginClass* _klass_;
#line 45 "../src/Plugins/Plugin.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 45 "../src/Plugins/Plugin.vala"
	_klass_ = QUILTER_PLUGINS_PLUGIN_GET_CLASS (self);
#line 45 "../src/Plugins/Plugin.vala"
	if (_klass_->get_desctiption) {
#line 45 "../src/Plugins/Plugin.vala"
		return _klass_->get_desctiption (self);
#line 204 "Plugin.c"
	}
#line 45 "../src/Plugins/Plugin.vala"
	return NULL;
#line 208 "Plugin.c"
}

static gchar*
quilter_plugins_plugin_real_get_name (QuilterPluginsPlugin* self)
{
#line 48 "../src/Plugins/Plugin.vala"
	g_critical ("Type `%s' does not implement abstract method `quilter_plugins_plugin_get_name'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 48 "../src/Plugins/Plugin.vala"
	return NULL;
#line 218 "Plugin.c"
}

gchar*
quilter_plugins_plugin_get_name (QuilterPluginsPlugin* self)
{
	QuilterPluginsPluginClass* _klass_;
#line 48 "../src/Plugins/Plugin.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 48 "../src/Plugins/Plugin.vala"
	_klass_ = QUILTER_PLUGINS_PLUGIN_GET_CLASS (self);
#line 48 "../src/Plugins/Plugin.vala"
	if (_klass_->get_name) {
#line 48 "../src/Plugins/Plugin.vala"
		return _klass_->get_name (self);
#line 233 "Plugin.c"
	}
#line 48 "../src/Plugins/Plugin.vala"
	return NULL;
#line 237 "Plugin.c"
}

static gboolean
quilter_plugins_plugin_real_has_match (QuilterPluginsPlugin* self,
                                       const gchar* text)
{
	gboolean _tmp0_ = FALSE;
#line 51 "../src/Plugins/Plugin.vala"
	g_critical ("Type `%s' does not implement abstract method `quilter_plugins_plugin_has_match'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 51 "../src/Plugins/Plugin.vala"
	return _tmp0_;
#line 249 "Plugin.c"
}

gboolean
quilter_plugins_plugin_has_match (QuilterPluginsPlugin* self,
                                  const gchar* text)
{
	QuilterPluginsPluginClass* _klass_;
#line 51 "../src/Plugins/Plugin.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 51 "../src/Plugins/Plugin.vala"
	_klass_ = QUILTER_PLUGINS_PLUGIN_GET_CLASS (self);
#line 51 "../src/Plugins/Plugin.vala"
	if (_klass_->has_match) {
#line 51 "../src/Plugins/Plugin.vala"
		return _klass_->has_match (self, text);
#line 265 "Plugin.c"
	}
#line 51 "../src/Plugins/Plugin.vala"
	return FALSE;
#line 269 "Plugin.c"
}

static gchar*
quilter_plugins_plugin_real_convert (QuilterPluginsPlugin* self,
                                     const gchar* line)
{
#line 54 "../src/Plugins/Plugin.vala"
	g_critical ("Type `%s' does not implement abstract method `quilter_plugins_plugin_convert'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 54 "../src/Plugins/Plugin.vala"
	return NULL;
#line 280 "Plugin.c"
}

gchar*
quilter_plugins_plugin_convert (QuilterPluginsPlugin* self,
                                const gchar* line)
{
	QuilterPluginsPluginClass* _klass_;
#line 54 "../src/Plugins/Plugin.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 54 "../src/Plugins/Plugin.vala"
	_klass_ = QUILTER_PLUGINS_PLUGIN_GET_CLASS (self);
#line 54 "../src/Plugins/Plugin.vala"
	if (_klass_->convert) {
#line 54 "../src/Plugins/Plugin.vala"
		return _klass_->convert (self, line);
#line 296 "Plugin.c"
	}
#line 54 "../src/Plugins/Plugin.vala"
	return NULL;
#line 300 "Plugin.c"
}

static GtkWidget*
quilter_plugins_plugin_real_editor_button (QuilterPluginsPlugin* self)
{
#line 57 "../src/Plugins/Plugin.vala"
	g_critical ("Type `%s' does not implement abstract method `quilter_plugins_plugin_editor_button'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 57 "../src/Plugins/Plugin.vala"
	return NULL;
#line 310 "Plugin.c"
}

GtkWidget*
quilter_plugins_plugin_editor_button (QuilterPluginsPlugin* self)
{
	QuilterPluginsPluginClass* _klass_;
#line 57 "../src/Plugins/Plugin.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 57 "../src/Plugins/Plugin.vala"
	_klass_ = QUILTER_PLUGINS_PLUGIN_GET_CLASS (self);
#line 57 "../src/Plugins/Plugin.vala"
	if (_klass_->editor_button) {
#line 57 "../src/Plugins/Plugin.vala"
		return _klass_->editor_button (self);
#line 325 "Plugin.c"
	}
#line 57 "../src/Plugins/Plugin.vala"
	return NULL;
#line 329 "Plugin.c"
}

static gchar*
quilter_plugins_plugin_real_get_button_desctiption (QuilterPluginsPlugin* self)
{
	gchar* _tmp0_;
	gchar* result = NULL;
#line 60 "../src/Plugins/Plugin.vala"
	_tmp0_ = quilter_plugins_plugin_get_desctiption (self);
#line 60 "../src/Plugins/Plugin.vala"
	result = _tmp0_;
#line 60 "../src/Plugins/Plugin.vala"
	return result;
#line 343 "Plugin.c"
}

gchar*
quilter_plugins_plugin_get_button_desctiption (QuilterPluginsPlugin* self)
{
	QuilterPluginsPluginClass* _klass_;
#line 59 "../src/Plugins/Plugin.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 59 "../src/Plugins/Plugin.vala"
	_klass_ = QUILTER_PLUGINS_PLUGIN_GET_CLASS (self);
#line 59 "../src/Plugins/Plugin.vala"
	if (_klass_->get_button_desctiption) {
#line 59 "../src/Plugins/Plugin.vala"
		return _klass_->get_button_desctiption (self);
#line 358 "Plugin.c"
	}
#line 59 "../src/Plugins/Plugin.vala"
	return NULL;
#line 362 "Plugin.c"
}

static gchar*
quilter_plugins_plugin_real_request_string (QuilterPluginsPlugin* self,
                                            const gchar* selection)
{
	gchar* _tmp0_;
	gchar* result = NULL;
#line 64 "../src/Plugins/Plugin.vala"
	g_return_val_if_fail (selection != NULL, NULL);
#line 65 "../src/Plugins/Plugin.vala"
	_tmp0_ = g_strdup (selection);
#line 65 "../src/Plugins/Plugin.vala"
	result = _tmp0_;
#line 65 "../src/Plugins/Plugin.vala"
	return result;
#line 379 "Plugin.c"
}

gchar*
quilter_plugins_plugin_request_string (QuilterPluginsPlugin* self,
                                       const gchar* selection)
{
	QuilterPluginsPluginClass* _klass_;
#line 64 "../src/Plugins/Plugin.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 64 "../src/Plugins/Plugin.vala"
	_klass_ = QUILTER_PLUGINS_PLUGIN_GET_CLASS (self);
#line 64 "../src/Plugins/Plugin.vala"
	if (_klass_->request_string) {
#line 64 "../src/Plugins/Plugin.vala"
		return _klass_->request_string (self, selection);
#line 395 "Plugin.c"
	}
#line 64 "../src/Plugins/Plugin.vala"
	return NULL;
#line 399 "Plugin.c"
}

void
quilter_plugins_plugin_connect_settings (QuilterPluginsPlugin* self,
                                         const gchar* setting)
{
	GSettings* _tmp0_;
#line 68 "../src/Plugins/Plugin.vala"
	g_return_if_fail (self != NULL);
#line 68 "../src/Plugins/Plugin.vala"
	g_return_if_fail (setting != NULL);
#line 69 "../src/Plugins/Plugin.vala"
	_tmp0_ = quilter_application_gsettings;
#line 69 "../src/Plugins/Plugin.vala"
	g_settings_bind (_tmp0_, setting, (GObject*) self, "active", G_SETTINGS_BIND_DEFAULT);
#line 415 "Plugin.c"
}

QuilterPluginsPlugin*
quilter_plugins_plugin_construct (GType object_type)
{
	QuilterPluginsPlugin * self = NULL;
#line 22 "../src/Plugins/Plugin.vala"
	self = (QuilterPluginsPlugin*) g_object_new (object_type, NULL);
#line 22 "../src/Plugins/Plugin.vala"
	return self;
#line 426 "Plugin.c"
}

static void
quilter_plugins_plugin_class_init (QuilterPluginsPluginClass * klass,
                                   gpointer klass_data)
{
#line 22 "../src/Plugins/Plugin.vala"
	quilter_plugins_plugin_parent_class = g_type_class_peek_parent (klass);
#line 22 "../src/Plugins/Plugin.vala"
	((QuilterPluginsPluginClass *) klass)->is_active = (gboolean (*) (QuilterPluginsPlugin*)) quilter_plugins_plugin_real_is_active;
#line 22 "../src/Plugins/Plugin.vala"
	((QuilterPluginsPluginClass *) klass)->set_active = (void (*) (QuilterPluginsPlugin*, gboolean)) quilter_plugins_plugin_real_set_active;
#line 22 "../src/Plugins/Plugin.vala"
	((QuilterPluginsPluginClass *) klass)->get_desctiption = (gchar* (*) (QuilterPluginsPlugin*)) quilter_plugins_plugin_real_get_desctiption;
#line 22 "../src/Plugins/Plugin.vala"
	((QuilterPluginsPluginClass *) klass)->get_name = (gchar* (*) (QuilterPluginsPlugin*)) quilter_plugins_plugin_real_get_name;
#line 22 "../src/Plugins/Plugin.vala"
	((QuilterPluginsPluginClass *) klass)->has_match = (gboolean (*) (QuilterPluginsPlugin*, const gchar*)) quilter_plugins_plugin_real_has_match;
#line 22 "../src/Plugins/Plugin.vala"
	((QuilterPluginsPluginClass *) klass)->convert = (gchar* (*) (QuilterPluginsPlugin*, const gchar*)) quilter_plugins_plugin_real_convert;
#line 22 "../src/Plugins/Plugin.vala"
	((QuilterPluginsPluginClass *) klass)->editor_button = (GtkWidget* (*) (QuilterPluginsPlugin*)) quilter_plugins_plugin_real_editor_button;
#line 22 "../src/Plugins/Plugin.vala"
	((QuilterPluginsPluginClass *) klass)->get_button_desctiption = (gchar* (*) (QuilterPluginsPlugin*)) quilter_plugins_plugin_real_get_button_desctiption;
#line 22 "../src/Plugins/Plugin.vala"
	((QuilterPluginsPluginClass *) klass)->request_string = (gchar* (*) (QuilterPluginsPlugin*, const gchar*)) quilter_plugins_plugin_real_request_string;
#line 22 "../src/Plugins/Plugin.vala"
	G_OBJECT_CLASS (klass)->finalize = quilter_plugins_plugin_finalize;
#line 22 "../src/Plugins/Plugin.vala"
	quilter_plugins_plugin_signals[QUILTER_PLUGINS_PLUGIN_STRING_COOKED_SIGNAL] = g_signal_new ("string-cooked", QUILTER_PLUGINS_TYPE_PLUGIN, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
#line 457 "Plugin.c"
}

static void
quilter_plugins_plugin_instance_init (QuilterPluginsPlugin * self,
                                      gpointer klass)
{
	gchar* _tmp0_;
#line 26 "../src/Plugins/Plugin.vala"
	self->settings = NULL;
#line 27 "../src/Plugins/Plugin.vala"
	self->state = TRUE;
#line 29 "../src/Plugins/Plugin.vala"
	_tmp0_ = g_strdup ("");
#line 29 "../src/Plugins/Plugin.vala"
	self->code_name = _tmp0_;
#line 473 "Plugin.c"
}

static void
quilter_plugins_plugin_finalize (GObject * obj)
{
	QuilterPluginsPlugin * self;
#line 22 "../src/Plugins/Plugin.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPlugin);
#line 26 "../src/Plugins/Plugin.vala"
	_g_object_unref0 (self->settings);
#line 29 "../src/Plugins/Plugin.vala"
	_g_free0 (self->code_name);
#line 22 "../src/Plugins/Plugin.vala"
	G_OBJECT_CLASS (quilter_plugins_plugin_parent_class)->finalize (obj);
#line 488 "Plugin.c"
}

static GType
quilter_plugins_plugin_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (QuilterPluginsPluginClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_plugins_plugin_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterPluginsPlugin), 0, (GInstanceInitFunc) quilter_plugins_plugin_instance_init, NULL };
	GType quilter_plugins_plugin_type_id;
	quilter_plugins_plugin_type_id = g_type_register_static (G_TYPE_OBJECT, "QuilterPluginsPlugin", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
	return quilter_plugins_plugin_type_id;
}

GType
quilter_plugins_plugin_get_type (void)
{
	static volatile gsize quilter_plugins_plugin_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_plugins_plugin_type_id__volatile)) {
		GType quilter_plugins_plugin_type_id;
		quilter_plugins_plugin_type_id = quilter_plugins_plugin_get_type_once ();
		g_once_init_leave (&quilter_plugins_plugin_type_id__volatile, quilter_plugins_plugin_type_id);
	}
	return quilter_plugins_plugin_type_id__volatile;
}

