/* Superscript.c generated by valac 0.50.2, the Vala compiler
 * generated from Superscript.vala, do not modify */

/*
* Copyright (c) 2019-2020 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 59 Temple Place - Suite 330,
* Boston, MA 02111-1307, USA.
*
* Co-authored by: Felipe Escoto <felescoto95@hotmail.com>
*/

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>

#define QUILTER_PLUGINS_TYPE_PLUGIN (quilter_plugins_plugin_get_type ())
#define QUILTER_PLUGINS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPlugin))
#define QUILTER_PLUGINS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPluginClass))
#define QUILTER_PLUGINS_IS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_PLUGINS_TYPE_PLUGIN))
#define QUILTER_PLUGINS_IS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_PLUGINS_TYPE_PLUGIN))
#define QUILTER_PLUGINS_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_PLUGINS_TYPE_PLUGIN, QuilterPluginsPluginClass))

typedef struct _QuilterPluginsPlugin QuilterPluginsPlugin;
typedef struct _QuilterPluginsPluginClass QuilterPluginsPluginClass;
typedef struct _QuilterPluginsPluginPrivate QuilterPluginsPluginPrivate;

#define QUILTER_TYPE_SUPERSCRIPT (quilter_superscript_get_type ())
#define QUILTER_SUPERSCRIPT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_SUPERSCRIPT, QuilterSuperscript))
#define QUILTER_SUPERSCRIPT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_SUPERSCRIPT, QuilterSuperscriptClass))
#define QUILTER_IS_SUPERSCRIPT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_SUPERSCRIPT))
#define QUILTER_IS_SUPERSCRIPT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_SUPERSCRIPT))
#define QUILTER_SUPERSCRIPT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_SUPERSCRIPT, QuilterSuperscriptClass))

typedef struct _QuilterSuperscript QuilterSuperscript;
typedef struct _QuilterSuperscriptClass QuilterSuperscriptClass;
typedef struct _QuilterSuperscriptPrivate QuilterSuperscriptPrivate;
enum  {
	QUILTER_SUPERSCRIPT_0_PROPERTY,
	QUILTER_SUPERSCRIPT_NUM_PROPERTIES
};
static GParamSpec* quilter_superscript_properties[QUILTER_SUPERSCRIPT_NUM_PROPERTIES];
#define _g_pattern_spec_free0(var) ((var == NULL) ? NULL : (var = (g_pattern_spec_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))

struct _QuilterPluginsPlugin {
	GObject parent_instance;
	QuilterPluginsPluginPrivate * priv;
	GSettings* settings;
	gboolean state;
	gchar* code_name;
};

struct _QuilterPluginsPluginClass {
	GObjectClass parent_class;
	gboolean (*is_active) (QuilterPluginsPlugin* self);
	void (*set_active) (QuilterPluginsPlugin* self, gboolean active);
	gchar* (*get_desctiption) (QuilterPluginsPlugin* self);
	gchar* (*get_name) (QuilterPluginsPlugin* self);
	gboolean (*has_match) (QuilterPluginsPlugin* self, const gchar* text);
	gchar* (*convert) (QuilterPluginsPlugin* self, const gchar* line);
	GtkWidget* (*editor_button) (QuilterPluginsPlugin* self);
	gchar* (*get_button_desctiption) (QuilterPluginsPlugin* self);
	gchar* (*request_string) (QuilterPluginsPlugin* self, const gchar* selection);
};

struct _QuilterSuperscript {
	QuilterPluginsPlugin parent_instance;
	QuilterSuperscriptPrivate * priv;
};

struct _QuilterSuperscriptClass {
	QuilterPluginsPluginClass parent_class;
};

struct _QuilterSuperscriptPrivate {
	GPatternSpec* spec;
};

static gint QuilterSuperscript_private_offset;
static gpointer quilter_superscript_parent_class = NULL;

GType quilter_plugins_plugin_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterPluginsPlugin, g_object_unref)
GType quilter_superscript_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterSuperscript, g_object_unref)
gchar* quilter_plugins_plugin_get_desctiption (QuilterPluginsPlugin* self);
gchar* quilter_plugins_plugin_get_name (QuilterPluginsPlugin* self);
GtkWidget* quilter_plugins_plugin_editor_button (QuilterPluginsPlugin* self);
gchar* quilter_plugins_plugin_request_string (QuilterPluginsPlugin* self,
                                              const gchar* selection);
gchar* quilter_plugins_plugin_get_button_desctiption (QuilterPluginsPlugin* self);
gboolean quilter_plugins_plugin_has_match (QuilterPluginsPlugin* self,
                                           const gchar* text);
gchar* quilter_plugins_plugin_convert (QuilterPluginsPlugin* self,
                                       const gchar* line);
static gchar* quilter_superscript_real_get_desctiption (QuilterPluginsPlugin* base);
static gchar* quilter_superscript_real_get_name (QuilterPluginsPlugin* base);
static GtkWidget* quilter_superscript_real_editor_button (QuilterPluginsPlugin* base);
static gchar* quilter_superscript_real_request_string (QuilterPluginsPlugin* base,
                                                const gchar* selection);
static gchar* quilter_superscript_real_get_button_desctiption (QuilterPluginsPlugin* base);
static gboolean quilter_superscript_real_has_match (QuilterPluginsPlugin* base,
                                             const gchar* text);
static gchar* quilter_superscript_real_convert (QuilterPluginsPlugin* base,
                                         const gchar* line_);
QuilterSuperscript* quilter_superscript_new (void);
QuilterSuperscript* quilter_superscript_construct (GType object_type);
QuilterPluginsPlugin* quilter_plugins_plugin_construct (GType object_type);
static GObject * quilter_superscript_constructor (GType type,
                                           guint n_construct_properties,
                                           GObjectConstructParam * construct_properties);
static void quilter_superscript_finalize (GObject * obj);
static GType quilter_superscript_get_type_once (void);

static inline gpointer
quilter_superscript_get_instance_private (QuilterSuperscript* self)
{
	return G_STRUCT_MEMBER_P (self, QuilterSuperscript_private_offset);
}

static gchar*
quilter_superscript_real_get_desctiption (QuilterPluginsPlugin* base)
{
	QuilterSuperscript * self;
	gchar* _tmp0_;
	gchar* result = NULL;
#line 27 "../src/Plugins/Superscript.vala"
	self = (QuilterSuperscript*) base;
#line 28 "../src/Plugins/Superscript.vala"
	_tmp0_ = g_strdup (_ ("Make text float."));
#line 28 "../src/Plugins/Superscript.vala"
	result = _tmp0_;
#line 28 "../src/Plugins/Superscript.vala"
	return result;
#line 154 "Superscript.c"
}

static gchar*
quilter_superscript_real_get_name (QuilterPluginsPlugin* base)
{
	QuilterSuperscript * self;
	gchar* _tmp0_;
	gchar* result = NULL;
#line 31 "../src/Plugins/Superscript.vala"
	self = (QuilterSuperscript*) base;
#line 32 "../src/Plugins/Superscript.vala"
	_tmp0_ = g_strdup (_ ("Superscript"));
#line 32 "../src/Plugins/Superscript.vala"
	result = _tmp0_;
#line 32 "../src/Plugins/Superscript.vala"
	return result;
#line 171 "Superscript.c"
}

static GtkWidget*
quilter_superscript_real_editor_button (QuilterPluginsPlugin* base)
{
	QuilterSuperscript * self;
	GtkWidget* result = NULL;
#line 35 "../src/Plugins/Superscript.vala"
	self = (QuilterSuperscript*) base;
#line 36 "../src/Plugins/Superscript.vala"
	result = NULL;
#line 36 "../src/Plugins/Superscript.vala"
	return result;
#line 185 "Superscript.c"
}

static gchar*
quilter_superscript_real_request_string (QuilterPluginsPlugin* base,
                                         const gchar* selection)
{
	QuilterSuperscript * self;
	gchar* _tmp0_;
	gchar* result = NULL;
#line 39 "../src/Plugins/Superscript.vala"
	self = (QuilterSuperscript*) base;
#line 39 "../src/Plugins/Superscript.vala"
	g_return_val_if_fail (selection != NULL, NULL);
#line 40 "../src/Plugins/Superscript.vala"
	_tmp0_ = g_strdup (selection);
#line 40 "../src/Plugins/Superscript.vala"
	result = _tmp0_;
#line 40 "../src/Plugins/Superscript.vala"
	return result;
#line 205 "Superscript.c"
}

static gchar*
quilter_superscript_real_get_button_desctiption (QuilterPluginsPlugin* base)
{
	QuilterSuperscript * self;
	gchar* _tmp0_;
	gchar* result = NULL;
#line 43 "../src/Plugins/Superscript.vala"
	self = (QuilterSuperscript*) base;
#line 44 "../src/Plugins/Superscript.vala"
	_tmp0_ = g_strdup ("");
#line 44 "../src/Plugins/Superscript.vala"
	result = _tmp0_;
#line 44 "../src/Plugins/Superscript.vala"
	return result;
#line 222 "Superscript.c"
}

static gboolean
quilter_superscript_real_has_match (QuilterPluginsPlugin* base,
                                    const gchar* text)
{
	QuilterSuperscript * self;
	GPatternSpec* _tmp0_;
	gboolean result = FALSE;
#line 47 "../src/Plugins/Superscript.vala"
	self = (QuilterSuperscript*) base;
#line 47 "../src/Plugins/Superscript.vala"
	g_return_val_if_fail (text != NULL, FALSE);
#line 48 "../src/Plugins/Superscript.vala"
	_tmp0_ = self->priv->spec;
#line 48 "../src/Plugins/Superscript.vala"
	result = g_pattern_match_string (_tmp0_, text);
#line 48 "../src/Plugins/Superscript.vala"
	return result;
#line 242 "Superscript.c"
}

static gint
string_index_of (const gchar* self,
                 const gchar* needle,
                 gint start_index)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gint result = 0;
#line 1133 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 1133 "glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, 0);
#line 1134 "glib-2.0.vapi"
	_tmp0_ = strstr (((gchar*) self) + start_index, (gchar*) needle);
#line 1134 "glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1136 "glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1136 "glib-2.0.vapi"
	if (_tmp1_ != NULL) {
#line 266 "Superscript.c"
		gchar* _tmp2_;
#line 1137 "glib-2.0.vapi"
		_tmp2_ = _result_;
#line 1137 "glib-2.0.vapi"
		result = (gint) (_tmp2_ - ((gchar*) self));
#line 1137 "glib-2.0.vapi"
		return result;
#line 274 "Superscript.c"
	} else {
#line 1139 "glib-2.0.vapi"
		result = -1;
#line 1139 "glib-2.0.vapi"
		return result;
#line 280 "Superscript.c"
	}
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result = 0L;
#line 1447 "glib-2.0.vapi"
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
#line 1447 "glib-2.0.vapi"
	end = _tmp0_;
#line 1448 "glib-2.0.vapi"
	_tmp1_ = end;
#line 1448 "glib-2.0.vapi"
	if (_tmp1_ == NULL) {
#line 1449 "glib-2.0.vapi"
		result = maxlen;
#line 1449 "glib-2.0.vapi"
		return result;
#line 304 "Superscript.c"
	} else {
		gchar* _tmp2_;
#line 1451 "glib-2.0.vapi"
		_tmp2_ = end;
#line 1451 "glib-2.0.vapi"
		result = (glong) (_tmp2_ - str);
#line 1451 "glib-2.0.vapi"
		return result;
#line 313 "Superscript.c"
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result = NULL;
#line 1458 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1460 "glib-2.0.vapi"
	if (offset >= ((glong) 0)) {
#line 1460 "glib-2.0.vapi"
		_tmp0_ = len >= ((glong) 0);
#line 332 "Superscript.c"
	} else {
#line 1460 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 336 "Superscript.c"
	}
#line 1460 "glib-2.0.vapi"
	if (_tmp0_) {
#line 1462 "glib-2.0.vapi"
		string_length = string_strnlen ((gchar*) self, offset + len);
#line 342 "Superscript.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 1464 "glib-2.0.vapi"
		_tmp1_ = strlen (self);
#line 1464 "glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1464 "glib-2.0.vapi"
		string_length = (glong) _tmp2_;
#line 352 "Superscript.c"
	}
#line 1467 "glib-2.0.vapi"
	if (offset < ((glong) 0)) {
#line 1468 "glib-2.0.vapi"
		offset = string_length + offset;
#line 1469 "glib-2.0.vapi"
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
#line 360 "Superscript.c"
	} else {
#line 1471 "glib-2.0.vapi"
		g_return_val_if_fail (offset <= string_length, NULL);
#line 364 "Superscript.c"
	}
#line 1473 "glib-2.0.vapi"
	if (len < ((glong) 0)) {
#line 1474 "glib-2.0.vapi"
		len = string_length - offset;
#line 370 "Superscript.c"
	}
#line 1476 "glib-2.0.vapi"
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
#line 1477 "glib-2.0.vapi"
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
#line 1477 "glib-2.0.vapi"
	result = _tmp3_;
#line 1477 "glib-2.0.vapi"
	return result;
#line 380 "Superscript.c"
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result = NULL;
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (old != NULL, NULL);
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 1535 "glib-2.0.vapi"
	if ((*((gchar*) self)) == '\0') {
#line 1535 "glib-2.0.vapi"
		_tmp1_ = TRUE;
#line 402 "Superscript.c"
	} else {
#line 1535 "glib-2.0.vapi"
		_tmp1_ = (*((gchar*) old)) == '\0';
#line 406 "Superscript.c"
	}
#line 1535 "glib-2.0.vapi"
	if (_tmp1_) {
#line 1535 "glib-2.0.vapi"
		_tmp0_ = TRUE;
#line 412 "Superscript.c"
	} else {
#line 1535 "glib-2.0.vapi"
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
#line 416 "Superscript.c"
	}
#line 1535 "glib-2.0.vapi"
	if (_tmp0_) {
#line 420 "Superscript.c"
		gchar* _tmp2_;
#line 1536 "glib-2.0.vapi"
		_tmp2_ = g_strdup (self);
#line 1536 "glib-2.0.vapi"
		result = _tmp2_;
#line 1536 "glib-2.0.vapi"
		return result;
#line 428 "Superscript.c"
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
#line 1539 "glib-2.0.vapi"
		_tmp3_ = g_regex_escape_string (old, -1);
#line 1539 "glib-2.0.vapi"
		_tmp4_ = _tmp3_;
#line 1539 "glib-2.0.vapi"
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
#line 1539 "glib-2.0.vapi"
		_tmp6_ = _tmp5_;
#line 1539 "glib-2.0.vapi"
		_g_free0 (_tmp4_);
#line 1539 "glib-2.0.vapi"
		regex = _tmp6_;
#line 1539 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1539 "glib-2.0.vapi"
			_g_free0 (_tmp7_);
#line 1539 "glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1539 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 460 "Superscript.c"
				goto __catch0_g_regex_error;
			}
#line 1539 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1539 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1539 "glib-2.0.vapi"
			return NULL;
#line 469 "Superscript.c"
		}
#line 1540 "glib-2.0.vapi"
		_tmp8_ = regex;
#line 1540 "glib-2.0.vapi"
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
#line 1540 "glib-2.0.vapi"
		_tmp7_ = _tmp9_;
#line 1540 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1540 "glib-2.0.vapi"
			_g_free0 (_tmp7_);
#line 1540 "glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1540 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 485 "Superscript.c"
				goto __catch0_g_regex_error;
			}
#line 1540 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1540 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1540 "glib-2.0.vapi"
			return NULL;
#line 494 "Superscript.c"
		}
#line 1540 "glib-2.0.vapi"
		_tmp10_ = _tmp7_;
#line 1540 "glib-2.0.vapi"
		_tmp7_ = NULL;
#line 1540 "glib-2.0.vapi"
		result = _tmp10_;
#line 1540 "glib-2.0.vapi"
		_g_free0 (_tmp7_);
#line 1540 "glib-2.0.vapi"
		_g_regex_unref0 (regex);
#line 1540 "glib-2.0.vapi"
		return result;
#line 508 "Superscript.c"
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
#line 1538 "glib-2.0.vapi"
		g_clear_error (&_inner_error0_);
#line 1542 "glib-2.0.vapi"
		g_assert_not_reached ();
#line 517 "Superscript.c"
	}
	__finally0:
#line 1538 "glib-2.0.vapi"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1538 "glib-2.0.vapi"
	g_clear_error (&_inner_error0_);
#line 1538 "glib-2.0.vapi"
	return NULL;
#line 526 "Superscript.c"
}

static gchar*
quilter_superscript_real_convert (QuilterPluginsPlugin* base,
                                  const gchar* line_)
{
	QuilterSuperscript * self;
	gint initial = 0;
	gint last = 0;
	gchar* subline = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* result = NULL;
#line 51 "../src/Plugins/Superscript.vala"
	self = (QuilterSuperscript*) base;
#line 51 "../src/Plugins/Superscript.vala"
	g_return_val_if_fail (line_ != NULL, NULL);
#line 52 "../src/Plugins/Superscript.vala"
	initial = string_index_of (line_, "^", 0) + 1;
#line 53 "../src/Plugins/Superscript.vala"
	last = string_index_of (line_, "^", initial);
#line 54 "../src/Plugins/Superscript.vala"
	_tmp0_ = string_substring (line_, (glong) initial, (glong) (last - initial));
#line 54 "../src/Plugins/Superscript.vala"
	subline = _tmp0_;
#line 56 "../src/Plugins/Superscript.vala"
	_tmp1_ = g_strdup_printf ("^%s^", subline);
#line 56 "../src/Plugins/Superscript.vala"
	_tmp2_ = _tmp1_;
#line 56 "../src/Plugins/Superscript.vala"
	_tmp3_ = g_strdup_printf ("<sup>%s</sup>", subline);
#line 56 "../src/Plugins/Superscript.vala"
	_tmp4_ = _tmp3_;
#line 56 "../src/Plugins/Superscript.vala"
	_tmp5_ = string_replace (line_, _tmp2_, _tmp4_);
#line 56 "../src/Plugins/Superscript.vala"
	_tmp6_ = _tmp5_;
#line 56 "../src/Plugins/Superscript.vala"
	_g_free0 (_tmp4_);
#line 56 "../src/Plugins/Superscript.vala"
	_g_free0 (_tmp2_);
#line 56 "../src/Plugins/Superscript.vala"
	result = _tmp6_;
#line 56 "../src/Plugins/Superscript.vala"
	_g_free0 (subline);
#line 56 "../src/Plugins/Superscript.vala"
	return result;
#line 579 "Superscript.c"
}

QuilterSuperscript*
quilter_superscript_construct (GType object_type)
{
	QuilterSuperscript * self = NULL;
#line 22 "../src/Plugins/Superscript.vala"
	self = (QuilterSuperscript*) quilter_plugins_plugin_construct (object_type);
#line 22 "../src/Plugins/Superscript.vala"
	return self;
#line 590 "Superscript.c"
}

QuilterSuperscript*
quilter_superscript_new (void)
{
#line 22 "../src/Plugins/Superscript.vala"
	return quilter_superscript_construct (QUILTER_TYPE_SUPERSCRIPT);
#line 598 "Superscript.c"
}

static GObject *
quilter_superscript_constructor (GType type,
                                 guint n_construct_properties,
                                 GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	QuilterSuperscript * self;
#line 25 "../src/Plugins/Superscript.vala"
	parent_class = G_OBJECT_CLASS (quilter_superscript_parent_class);
#line 25 "../src/Plugins/Superscript.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 25 "../src/Plugins/Superscript.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_TYPE_SUPERSCRIPT, QuilterSuperscript);
#line 25 "../src/Plugins/Superscript.vala"
	return obj;
#line 617 "Superscript.c"
}

static void
quilter_superscript_class_init (QuilterSuperscriptClass * klass,
                                gpointer klass_data)
{
#line 22 "../src/Plugins/Superscript.vala"
	quilter_superscript_parent_class = g_type_class_peek_parent (klass);
#line 22 "../src/Plugins/Superscript.vala"
	g_type_class_adjust_private_offset (klass, &QuilterSuperscript_private_offset);
#line 22 "../src/Plugins/Superscript.vala"
	((QuilterPluginsPluginClass *) klass)->get_desctiption = (gchar* (*) (QuilterPluginsPlugin*)) quilter_superscript_real_get_desctiption;
#line 22 "../src/Plugins/Superscript.vala"
	((QuilterPluginsPluginClass *) klass)->get_name = (gchar* (*) (QuilterPluginsPlugin*)) quilter_superscript_real_get_name;
#line 22 "../src/Plugins/Superscript.vala"
	((QuilterPluginsPluginClass *) klass)->editor_button = (GtkWidget* (*) (QuilterPluginsPlugin*)) quilter_superscript_real_editor_button;
#line 22 "../src/Plugins/Superscript.vala"
	((QuilterPluginsPluginClass *) klass)->request_string = (gchar* (*) (QuilterPluginsPlugin*, const gchar*)) quilter_superscript_real_request_string;
#line 22 "../src/Plugins/Superscript.vala"
	((QuilterPluginsPluginClass *) klass)->get_button_desctiption = (gchar* (*) (QuilterPluginsPlugin*)) quilter_superscript_real_get_button_desctiption;
#line 22 "../src/Plugins/Superscript.vala"
	((QuilterPluginsPluginClass *) klass)->has_match = (gboolean (*) (QuilterPluginsPlugin*, const gchar*)) quilter_superscript_real_has_match;
#line 22 "../src/Plugins/Superscript.vala"
	((QuilterPluginsPluginClass *) klass)->convert = (gchar* (*) (QuilterPluginsPlugin*, const gchar*)) quilter_superscript_real_convert;
#line 22 "../src/Plugins/Superscript.vala"
	G_OBJECT_CLASS (klass)->constructor = quilter_superscript_constructor;
#line 22 "../src/Plugins/Superscript.vala"
	G_OBJECT_CLASS (klass)->finalize = quilter_superscript_finalize;
#line 646 "Superscript.c"
}

static void
quilter_superscript_instance_init (QuilterSuperscript * self,
                                   gpointer klass)
{
	GPatternSpec* _tmp0_;
#line 22 "../src/Plugins/Superscript.vala"
	self->priv = quilter_superscript_get_instance_private (self);
#line 23 "../src/Plugins/Superscript.vala"
	_tmp0_ = g_pattern_spec_new ("*^*^*");
#line 23 "../src/Plugins/Superscript.vala"
	self->priv->spec = _tmp0_;
#line 660 "Superscript.c"
}

static void
quilter_superscript_finalize (GObject * obj)
{
	QuilterSuperscript * self;
#line 22 "../src/Plugins/Superscript.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_TYPE_SUPERSCRIPT, QuilterSuperscript);
#line 23 "../src/Plugins/Superscript.vala"
	_g_pattern_spec_free0 (self->priv->spec);
#line 22 "../src/Plugins/Superscript.vala"
	G_OBJECT_CLASS (quilter_superscript_parent_class)->finalize (obj);
#line 673 "Superscript.c"
}

static GType
quilter_superscript_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (QuilterSuperscriptClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_superscript_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterSuperscript), 0, (GInstanceInitFunc) quilter_superscript_instance_init, NULL };
	GType quilter_superscript_type_id;
	quilter_superscript_type_id = g_type_register_static (QUILTER_PLUGINS_TYPE_PLUGIN, "QuilterSuperscript", &g_define_type_info, 0);
	QuilterSuperscript_private_offset = g_type_add_instance_private (quilter_superscript_type_id, sizeof (QuilterSuperscriptPrivate));
	return quilter_superscript_type_id;
}

GType
quilter_superscript_get_type (void)
{
	static volatile gsize quilter_superscript_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_superscript_type_id__volatile)) {
		GType quilter_superscript_type_id;
		quilter_superscript_type_id = quilter_superscript_get_type_once ();
		g_once_init_leave (&quilter_superscript_type_id__volatile, quilter_superscript_type_id);
	}
	return quilter_superscript_type_id__volatile;
}

