/* HeaderBarButton.c generated by valac 0.50.2, the Vala compiler
 * generated from HeaderBarButton.vala, do not modify */

/*
* Copyright (C) 2017-2021 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#define QUILTER_WIDGETS_TYPE_HEADER_BAR_BUTTON (quilter_widgets_header_bar_button_get_type ())
#define QUILTER_WIDGETS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_HEADER_BAR_BUTTON, QuilterWidgetsHeaderBarButton))
#define QUILTER_WIDGETS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_HEADER_BAR_BUTTON, QuilterWidgetsHeaderBarButtonClass))
#define QUILTER_WIDGETS_IS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define QUILTER_WIDGETS_IS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define QUILTER_WIDGETS_HEADER_BAR_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_HEADER_BAR_BUTTON, QuilterWidgetsHeaderBarButtonClass))

typedef struct _QuilterWidgetsHeaderBarButton QuilterWidgetsHeaderBarButton;
typedef struct _QuilterWidgetsHeaderBarButtonClass QuilterWidgetsHeaderBarButtonClass;
typedef struct _QuilterWidgetsHeaderBarButtonPrivate QuilterWidgetsHeaderBarButtonPrivate;
enum  {
	QUILTER_WIDGETS_HEADER_BAR_BUTTON_0_PROPERTY,
	QUILTER_WIDGETS_HEADER_BAR_BUTTON_TITLE_PROPERTY,
	QUILTER_WIDGETS_HEADER_BAR_BUTTON_SUBTITLE_PROPERTY,
	QUILTER_WIDGETS_HEADER_BAR_BUTTON_NUM_PROPERTIES
};
static GParamSpec* quilter_widgets_header_bar_button_properties[QUILTER_WIDGETS_HEADER_BAR_BUTTON_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
enum  {
	QUILTER_WIDGETS_HEADER_BAR_BUTTON_CLICKED_SIGNAL,
	QUILTER_WIDGETS_HEADER_BAR_BUTTON_NUM_SIGNALS
};
static guint quilter_widgets_header_bar_button_signals[QUILTER_WIDGETS_HEADER_BAR_BUTTON_NUM_SIGNALS] = {0};

struct _QuilterWidgetsHeaderBarButton {
	GtkBin parent_instance;
	QuilterWidgetsHeaderBarButtonPrivate * priv;
	GtkMenuButton* menu;
};

struct _QuilterWidgetsHeaderBarButtonClass {
	GtkBinClass parent_class;
};

struct _QuilterWidgetsHeaderBarButtonPrivate {
	gchar* _title;
	gchar* _subtitle;
};

static gint QuilterWidgetsHeaderBarButton_private_offset;
static gpointer quilter_widgets_header_bar_button_parent_class = NULL;

GType quilter_widgets_header_bar_button_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsHeaderBarButton, g_object_unref)
QuilterWidgetsHeaderBarButton* quilter_widgets_header_bar_button_new (void);
QuilterWidgetsHeaderBarButton* quilter_widgets_header_bar_button_construct (GType object_type);
const gchar* quilter_widgets_header_bar_button_get_title (QuilterWidgetsHeaderBarButton* self);
void quilter_widgets_header_bar_button_set_title (QuilterWidgetsHeaderBarButton* self,
                                                  const gchar* value);
const gchar* quilter_widgets_header_bar_button_get_subtitle (QuilterWidgetsHeaderBarButton* self);
void quilter_widgets_header_bar_button_set_subtitle (QuilterWidgetsHeaderBarButton* self,
                                                     const gchar* value);
static void quilter_widgets_header_bar_button_finalize (GObject * obj);
static GType quilter_widgets_header_bar_button_get_type_once (void);
static void _vala_quilter_widgets_header_bar_button_get_property (GObject * object,
                                                           guint property_id,
                                                           GValue * value,
                                                           GParamSpec * pspec);
static void _vala_quilter_widgets_header_bar_button_set_property (GObject * object,
                                                           guint property_id,
                                                           const GValue * value,
                                                           GParamSpec * pspec);

static inline gpointer
quilter_widgets_header_bar_button_get_instance_private (QuilterWidgetsHeaderBarButton* self)
{
	return G_STRUCT_MEMBER_P (self, QuilterWidgetsHeaderBarButton_private_offset);
}

QuilterWidgetsHeaderBarButton*
quilter_widgets_header_bar_button_construct (GType object_type)
{
	QuilterWidgetsHeaderBarButton * self = NULL;
#line 21 "../src/Widgets/HeaderBarButton.vala"
	self = (QuilterWidgetsHeaderBarButton*) g_object_new (object_type, NULL);
#line 21 "../src/Widgets/HeaderBarButton.vala"
	return self;
#line 108 "HeaderBarButton.c"
}

QuilterWidgetsHeaderBarButton*
quilter_widgets_header_bar_button_new (void)
{
#line 21 "../src/Widgets/HeaderBarButton.vala"
	return quilter_widgets_header_bar_button_construct (QUILTER_WIDGETS_TYPE_HEADER_BAR_BUTTON);
#line 116 "HeaderBarButton.c"
}

const gchar*
quilter_widgets_header_bar_button_get_title (QuilterWidgetsHeaderBarButton* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 23 "../src/Widgets/HeaderBarButton.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 23 "../src/Widgets/HeaderBarButton.vala"
	_tmp0_ = self->priv->_title;
#line 23 "../src/Widgets/HeaderBarButton.vala"
	result = _tmp0_;
#line 23 "../src/Widgets/HeaderBarButton.vala"
	return result;
#line 132 "HeaderBarButton.c"
}

void
quilter_widgets_header_bar_button_set_title (QuilterWidgetsHeaderBarButton* self,
                                             const gchar* value)
{
#line 23 "../src/Widgets/HeaderBarButton.vala"
	g_return_if_fail (self != NULL);
#line 23 "../src/Widgets/HeaderBarButton.vala"
	if (g_strcmp0 (value, quilter_widgets_header_bar_button_get_title (self)) != 0) {
#line 143 "HeaderBarButton.c"
		gchar* _tmp0_;
#line 23 "../src/Widgets/HeaderBarButton.vala"
		_tmp0_ = g_strdup (value);
#line 23 "../src/Widgets/HeaderBarButton.vala"
		_g_free0 (self->priv->_title);
#line 23 "../src/Widgets/HeaderBarButton.vala"
		self->priv->_title = _tmp0_;
#line 23 "../src/Widgets/HeaderBarButton.vala"
		g_object_notify_by_pspec ((GObject *) self, quilter_widgets_header_bar_button_properties[QUILTER_WIDGETS_HEADER_BAR_BUTTON_TITLE_PROPERTY]);
#line 153 "HeaderBarButton.c"
	}
}

const gchar*
quilter_widgets_header_bar_button_get_subtitle (QuilterWidgetsHeaderBarButton* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 24 "../src/Widgets/HeaderBarButton.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 24 "../src/Widgets/HeaderBarButton.vala"
	_tmp0_ = self->priv->_subtitle;
#line 24 "../src/Widgets/HeaderBarButton.vala"
	result = _tmp0_;
#line 24 "../src/Widgets/HeaderBarButton.vala"
	return result;
#line 170 "HeaderBarButton.c"
}

void
quilter_widgets_header_bar_button_set_subtitle (QuilterWidgetsHeaderBarButton* self,
                                                const gchar* value)
{
#line 24 "../src/Widgets/HeaderBarButton.vala"
	g_return_if_fail (self != NULL);
#line 24 "../src/Widgets/HeaderBarButton.vala"
	if (g_strcmp0 (value, quilter_widgets_header_bar_button_get_subtitle (self)) != 0) {
#line 181 "HeaderBarButton.c"
		gchar* _tmp0_;
#line 24 "../src/Widgets/HeaderBarButton.vala"
		_tmp0_ = g_strdup (value);
#line 24 "../src/Widgets/HeaderBarButton.vala"
		_g_free0 (self->priv->_subtitle);
#line 24 "../src/Widgets/HeaderBarButton.vala"
		self->priv->_subtitle = _tmp0_;
#line 24 "../src/Widgets/HeaderBarButton.vala"
		g_object_notify_by_pspec ((GObject *) self, quilter_widgets_header_bar_button_properties[QUILTER_WIDGETS_HEADER_BAR_BUTTON_SUBTITLE_PROPERTY]);
#line 191 "HeaderBarButton.c"
	}
}

static void
quilter_widgets_header_bar_button_class_init (QuilterWidgetsHeaderBarButtonClass * klass,
                                              gpointer klass_data)
{
#line 21 "../src/Widgets/HeaderBarButton.vala"
	quilter_widgets_header_bar_button_parent_class = g_type_class_peek_parent (klass);
#line 21 "../src/Widgets/HeaderBarButton.vala"
	g_type_class_adjust_private_offset (klass, &QuilterWidgetsHeaderBarButton_private_offset);
#line 21 "../src/Widgets/HeaderBarButton.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_quilter_widgets_header_bar_button_get_property;
#line 21 "../src/Widgets/HeaderBarButton.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_quilter_widgets_header_bar_button_set_property;
#line 21 "../src/Widgets/HeaderBarButton.vala"
	G_OBJECT_CLASS (klass)->finalize = quilter_widgets_header_bar_button_finalize;
#line 21 "../src/Widgets/HeaderBarButton.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), QUILTER_WIDGETS_HEADER_BAR_BUTTON_TITLE_PROPERTY, quilter_widgets_header_bar_button_properties[QUILTER_WIDGETS_HEADER_BAR_BUTTON_TITLE_PROPERTY] = g_param_spec_string ("title", "title", "title", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 21 "../src/Widgets/HeaderBarButton.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), QUILTER_WIDGETS_HEADER_BAR_BUTTON_SUBTITLE_PROPERTY, quilter_widgets_header_bar_button_properties[QUILTER_WIDGETS_HEADER_BAR_BUTTON_SUBTITLE_PROPERTY] = g_param_spec_string ("subtitle", "subtitle", "subtitle", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 21 "../src/Widgets/HeaderBarButton.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/io/github/lainsce/Quilter/header_button.ui");
#line 21 "../src/Widgets/HeaderBarButton.vala"
	quilter_widgets_header_bar_button_signals[QUILTER_WIDGETS_HEADER_BAR_BUTTON_CLICKED_SIGNAL] = g_signal_new ("clicked", QUILTER_WIDGETS_TYPE_HEADER_BAR_BUTTON, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "../src/Widgets/HeaderBarButton.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "menu", FALSE, G_STRUCT_OFFSET (QuilterWidgetsHeaderBarButton, menu));
#line 219 "HeaderBarButton.c"
}

static void
quilter_widgets_header_bar_button_instance_init (QuilterWidgetsHeaderBarButton * self,
                                                 gpointer klass)
{
#line 21 "../src/Widgets/HeaderBarButton.vala"
	self->priv = quilter_widgets_header_bar_button_get_instance_private (self);
#line 21 "../src/Widgets/HeaderBarButton.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 230 "HeaderBarButton.c"
}

static void
quilter_widgets_header_bar_button_finalize (GObject * obj)
{
	QuilterWidgetsHeaderBarButton * self;
#line 21 "../src/Widgets/HeaderBarButton.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_WIDGETS_TYPE_HEADER_BAR_BUTTON, QuilterWidgetsHeaderBarButton);
#line 23 "../src/Widgets/HeaderBarButton.vala"
	_g_free0 (self->priv->_title);
#line 24 "../src/Widgets/HeaderBarButton.vala"
	_g_free0 (self->priv->_subtitle);
#line 27 "../src/Widgets/HeaderBarButton.vala"
	_g_object_unref0 (self->menu);
#line 21 "../src/Widgets/HeaderBarButton.vala"
	G_OBJECT_CLASS (quilter_widgets_header_bar_button_parent_class)->finalize (obj);
#line 247 "HeaderBarButton.c"
}

static GType
quilter_widgets_header_bar_button_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (QuilterWidgetsHeaderBarButtonClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_widgets_header_bar_button_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterWidgetsHeaderBarButton), 0, (GInstanceInitFunc) quilter_widgets_header_bar_button_instance_init, NULL };
	GType quilter_widgets_header_bar_button_type_id;
	quilter_widgets_header_bar_button_type_id = g_type_register_static (gtk_bin_get_type (), "QuilterWidgetsHeaderBarButton", &g_define_type_info, 0);
	QuilterWidgetsHeaderBarButton_private_offset = g_type_add_instance_private (quilter_widgets_header_bar_button_type_id, sizeof (QuilterWidgetsHeaderBarButtonPrivate));
	return quilter_widgets_header_bar_button_type_id;
}

GType
quilter_widgets_header_bar_button_get_type (void)
{
	static volatile gsize quilter_widgets_header_bar_button_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_widgets_header_bar_button_type_id__volatile)) {
		GType quilter_widgets_header_bar_button_type_id;
		quilter_widgets_header_bar_button_type_id = quilter_widgets_header_bar_button_get_type_once ();
		g_once_init_leave (&quilter_widgets_header_bar_button_type_id__volatile, quilter_widgets_header_bar_button_type_id);
	}
	return quilter_widgets_header_bar_button_type_id__volatile;
}

static void
_vala_quilter_widgets_header_bar_button_get_property (GObject * object,
                                                      guint property_id,
                                                      GValue * value,
                                                      GParamSpec * pspec)
{
	QuilterWidgetsHeaderBarButton * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QUILTER_WIDGETS_TYPE_HEADER_BAR_BUTTON, QuilterWidgetsHeaderBarButton);
#line 21 "../src/Widgets/HeaderBarButton.vala"
	switch (property_id) {
#line 21 "../src/Widgets/HeaderBarButton.vala"
		case QUILTER_WIDGETS_HEADER_BAR_BUTTON_TITLE_PROPERTY:
#line 21 "../src/Widgets/HeaderBarButton.vala"
		g_value_set_string (value, quilter_widgets_header_bar_button_get_title (self));
#line 21 "../src/Widgets/HeaderBarButton.vala"
		break;
#line 21 "../src/Widgets/HeaderBarButton.vala"
		case QUILTER_WIDGETS_HEADER_BAR_BUTTON_SUBTITLE_PROPERTY:
#line 21 "../src/Widgets/HeaderBarButton.vala"
		g_value_set_string (value, quilter_widgets_header_bar_button_get_subtitle (self));
#line 21 "../src/Widgets/HeaderBarButton.vala"
		break;
#line 294 "HeaderBarButton.c"
		default:
#line 21 "../src/Widgets/HeaderBarButton.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 21 "../src/Widgets/HeaderBarButton.vala"
		break;
#line 300 "HeaderBarButton.c"
	}
}

static void
_vala_quilter_widgets_header_bar_button_set_property (GObject * object,
                                                      guint property_id,
                                                      const GValue * value,
                                                      GParamSpec * pspec)
{
	QuilterWidgetsHeaderBarButton * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QUILTER_WIDGETS_TYPE_HEADER_BAR_BUTTON, QuilterWidgetsHeaderBarButton);
#line 21 "../src/Widgets/HeaderBarButton.vala"
	switch (property_id) {
#line 21 "../src/Widgets/HeaderBarButton.vala"
		case QUILTER_WIDGETS_HEADER_BAR_BUTTON_TITLE_PROPERTY:
#line 21 "../src/Widgets/HeaderBarButton.vala"
		quilter_widgets_header_bar_button_set_title (self, g_value_get_string (value));
#line 21 "../src/Widgets/HeaderBarButton.vala"
		break;
#line 21 "../src/Widgets/HeaderBarButton.vala"
		case QUILTER_WIDGETS_HEADER_BAR_BUTTON_SUBTITLE_PROPERTY:
#line 21 "../src/Widgets/HeaderBarButton.vala"
		quilter_widgets_header_bar_button_set_subtitle (self, g_value_get_string (value));
#line 21 "../src/Widgets/HeaderBarButton.vala"
		break;
#line 326 "HeaderBarButton.c"
		default:
#line 21 "../src/Widgets/HeaderBarButton.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 21 "../src/Widgets/HeaderBarButton.vala"
		break;
#line 332 "HeaderBarButton.c"
	}
}

