/* SearchBar.c generated by valac 0.50.2, the Vala compiler
 * generated from SearchBar.vala, do not modify */

/*
* Copyright (c) 2018-2021 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <gtk/gtk.h>
#include <glib-object.h>
#include <gtksourceview/gtksource.h>
#include <handy.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <webkit2/webkit2.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gio/gio.h>

#define QUILTER_WIDGETS_TYPE_SEARCH_BAR (quilter_widgets_search_bar_get_type ())
#define QUILTER_WIDGETS_SEARCH_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_SEARCH_BAR, QuilterWidgetsSearchBar))
#define QUILTER_WIDGETS_SEARCH_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_SEARCH_BAR, QuilterWidgetsSearchBarClass))
#define QUILTER_WIDGETS_IS_SEARCH_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_SEARCH_BAR))
#define QUILTER_WIDGETS_IS_SEARCH_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_SEARCH_BAR))
#define QUILTER_WIDGETS_SEARCH_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_SEARCH_BAR, QuilterWidgetsSearchBarClass))

typedef struct _QuilterWidgetsSearchBar QuilterWidgetsSearchBar;
typedef struct _QuilterWidgetsSearchBarClass QuilterWidgetsSearchBarClass;
typedef struct _QuilterWidgetsSearchBarPrivate QuilterWidgetsSearchBarPrivate;

#define QUILTER_WIDGETS_TYPE_EDIT_VIEW (quilter_widgets_edit_view_get_type ())
#define QUILTER_WIDGETS_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_EDIT_VIEW, QuilterWidgetsEditView))
#define QUILTER_WIDGETS_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_EDIT_VIEW, QuilterWidgetsEditViewClass))
#define QUILTER_WIDGETS_IS_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_EDIT_VIEW))
#define QUILTER_WIDGETS_IS_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_EDIT_VIEW))
#define QUILTER_WIDGETS_EDIT_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_EDIT_VIEW, QuilterWidgetsEditViewClass))

typedef struct _QuilterWidgetsEditView QuilterWidgetsEditView;
typedef struct _QuilterWidgetsEditViewClass QuilterWidgetsEditViewClass;

#define QUILTER_TYPE_MAIN_WINDOW (quilter_main_window_get_type ())
#define QUILTER_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindow))
#define QUILTER_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindowClass))
#define QUILTER_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_MAIN_WINDOW))
#define QUILTER_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_MAIN_WINDOW))
#define QUILTER_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindowClass))

typedef struct _QuilterMainWindow QuilterMainWindow;
typedef struct _QuilterMainWindowClass QuilterMainWindowClass;
enum  {
	QUILTER_WIDGETS_SEARCH_BAR_0_PROPERTY,
	QUILTER_WIDGETS_SEARCH_BAR_WINDOW_PROPERTY,
	QUILTER_WIDGETS_SEARCH_BAR_NUM_PROPERTIES
};
static GParamSpec* quilter_widgets_search_bar_properties[QUILTER_WIDGETS_SEARCH_BAR_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gtk_widget_path_unref0(var) ((var == NULL) ? NULL : (var = (gtk_widget_path_unref (var), NULL)))
typedef struct _QuilterMainWindowPrivate QuilterMainWindowPrivate;

#define QUILTER_WIDGETS_TYPE_HEADERBAR (quilter_widgets_headerbar_get_type ())
#define QUILTER_WIDGETS_HEADERBAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_HEADERBAR, QuilterWidgetsHeaderbar))
#define QUILTER_WIDGETS_HEADERBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_HEADERBAR, QuilterWidgetsHeaderbarClass))
#define QUILTER_WIDGETS_IS_HEADERBAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_HEADERBAR))
#define QUILTER_WIDGETS_IS_HEADERBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_HEADERBAR))
#define QUILTER_WIDGETS_HEADERBAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_HEADERBAR, QuilterWidgetsHeaderbarClass))

typedef struct _QuilterWidgetsHeaderbar QuilterWidgetsHeaderbar;
typedef struct _QuilterWidgetsHeaderbarClass QuilterWidgetsHeaderbarClass;

#define QUILTER_WIDGETS_TYPE_PREVIEW (quilter_widgets_preview_get_type ())
#define QUILTER_WIDGETS_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_PREVIEW, QuilterWidgetsPreview))
#define QUILTER_WIDGETS_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_PREVIEW, QuilterWidgetsPreviewClass))
#define QUILTER_WIDGETS_IS_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_PREVIEW))
#define QUILTER_WIDGETS_IS_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_PREVIEW))
#define QUILTER_WIDGETS_PREVIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_PREVIEW, QuilterWidgetsPreviewClass))

typedef struct _QuilterWidgetsPreview QuilterWidgetsPreview;
typedef struct _QuilterWidgetsPreviewClass QuilterWidgetsPreviewClass;

#define QUILTER_WIDGETS_TYPE_SIDE_BAR (quilter_widgets_side_bar_get_type ())
#define QUILTER_WIDGETS_SIDE_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_SIDE_BAR, QuilterWidgetsSideBar))
#define QUILTER_WIDGETS_SIDE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_SIDE_BAR, QuilterWidgetsSideBarClass))
#define QUILTER_WIDGETS_IS_SIDE_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_SIDE_BAR))
#define QUILTER_WIDGETS_IS_SIDE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_SIDE_BAR))
#define QUILTER_WIDGETS_SIDE_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_SIDE_BAR, QuilterWidgetsSideBarClass))

typedef struct _QuilterWidgetsSideBar QuilterWidgetsSideBar;
typedef struct _QuilterWidgetsSideBarClass QuilterWidgetsSideBarClass;

#define QUILTER_WIDGETS_TYPE_STATUS_BAR (quilter_widgets_status_bar_get_type ())
#define QUILTER_WIDGETS_STATUS_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_STATUS_BAR, QuilterWidgetsStatusBar))
#define QUILTER_WIDGETS_STATUS_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_STATUS_BAR, QuilterWidgetsStatusBarClass))
#define QUILTER_WIDGETS_IS_STATUS_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_STATUS_BAR))
#define QUILTER_WIDGETS_IS_STATUS_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_STATUS_BAR))
#define QUILTER_WIDGETS_STATUS_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_STATUS_BAR, QuilterWidgetsStatusBarClass))

typedef struct _QuilterWidgetsStatusBar QuilterWidgetsStatusBar;
typedef struct _QuilterWidgetsStatusBarClass QuilterWidgetsStatusBarClass;
#define __vala_GtkTextIter_free0(var) ((var == NULL) ? NULL : (var = (_vala_GtkTextIter_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _QuilterWidgetsEditViewPrivate QuilterWidgetsEditViewPrivate;

#define QUILTER_SERVICES_TYPE_POS_FILES (quilter_services_pos_files_get_type ())
#define QUILTER_SERVICES_POS_FILES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_SERVICES_TYPE_POS_FILES, QuilterServicesPOSFiles))
#define QUILTER_SERVICES_POS_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_SERVICES_TYPE_POS_FILES, QuilterServicesPOSFilesClass))
#define QUILTER_SERVICES_IS_POS_FILES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_SERVICES_TYPE_POS_FILES))
#define QUILTER_SERVICES_IS_POS_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_SERVICES_TYPE_POS_FILES))
#define QUILTER_SERVICES_POS_FILES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_SERVICES_TYPE_POS_FILES, QuilterServicesPOSFilesClass))

typedef struct _QuilterServicesPOSFiles QuilterServicesPOSFiles;
typedef struct _QuilterServicesPOSFilesClass QuilterServicesPOSFilesClass;

struct _QuilterWidgetsSearchBar {
	GtkSearchBar parent_instance;
	QuilterWidgetsSearchBarPrivate * priv;
	GtkGrid* grid;
	GtkGrid* prev_next_grid;
	GtkGrid* replace_grid;
	GtkEntry* replace_entry;
	GtkSearchEntry* search_entry;
	GtkSourceSearchContext* search_context;
};

struct _QuilterWidgetsSearchBarClass {
	GtkSearchBarClass parent_class;
};

struct _QuilterWidgetsSearchBarPrivate {
	QuilterWidgetsEditView* text_view;
	GtkButton* replace_all_tool_button;
	GtkButton* replace_tool_button;
	GtkTextBuffer* text_buffer;
	QuilterMainWindow* _window;
};

struct _QuilterMainWindow {
	HdyApplicationWindow parent_instance;
	QuilterMainWindowPrivate * priv;
	GtkAdjustment* eadj;
	GtkBox* box;
	GtkBox* main_leaf;
	GtkOverlay* overlay_editor;
	GtkButton* focus_overlay_button;
	HdyLeaflet* grid;
	HdyLeaflet* header;
	HdyTitleBar* window_header;
	HdyHeaderBar* welcome_titlebar;
	GtkGrid* main_pane;
	GtkGrid* welcome_view;
	GtkMenuButton* set_font_menu;
	GtkPaned* paned;
	GtkRevealer* titlebar_revealer;
	GtkRevealer* overlay_button_revealer;
	GtkScrolledWindow* edit_view;
	GtkStack* main_stack;
	GtkStack* stack;
	GtkStack* titlebar_stack;
	GtkStack* win_stack;
	GtkSeparator* separator;
	GtkSeparator* separator2;
	QuilterWidgetsEditView* edit_view_content;
	QuilterWidgetsHeaderbar* titlebar;
	QuilterWidgetsPreview* preview_view_content;
	QuilterWidgetsSearchBar* searchbar;
	QuilterWidgetsSideBar* sidebar;
	QuilterWidgetsStatusBar* statusbar;
};

struct _QuilterMainWindowClass {
	HdyApplicationWindowClass parent_class;
};

struct _QuilterWidgetsEditView {
	GtkSourceView parent_instance;
	QuilterWidgetsEditViewPrivate * priv;
	GFile* file;
	GtkSourceSearchContext* search_context;
	GtkSourceStyle* srcstyle;
	GtkTextTag* adjfont;
	GtkTextTag* adverbfont;
	GtkTextTag* conjfont;
	GtkTextTag* verbfont;
	GtkTextTag* error_tag;
	QuilterMainWindow* window;
	QuilterServicesPOSFiles* pos;
	gdouble cursor_position;
	GtkSourceBuffer* buffer;
	gchar* scroll_text;
};

struct _QuilterWidgetsEditViewClass {
	GtkSourceViewClass parent_class;
};

static gint QuilterWidgetsSearchBar_private_offset;
static gpointer quilter_widgets_search_bar_parent_class = NULL;
extern GSettings* quilter_application_gsettings;

GType quilter_widgets_search_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsSearchBar, g_object_unref)
GType quilter_widgets_edit_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsEditView, g_object_unref)
GType quilter_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterMainWindow, g_object_unref)
QuilterWidgetsSearchBar* quilter_widgets_search_bar_new (QuilterMainWindow* window);
QuilterWidgetsSearchBar* quilter_widgets_search_bar_construct (GType object_type,
                                                               QuilterMainWindow* window);
void quilter_widgets_search_bar_search_entry_item (QuilterWidgetsSearchBar* self);
static void __lambda6_ (QuilterWidgetsSearchBar* self);
gboolean quilter_widgets_search_bar_search (QuilterWidgetsSearchBar* self);
static void ___lambda6__gtk_search_entry_search_changed (GtkSearchEntry* _sender,
                                                  gpointer self);
void quilter_widgets_search_bar_search_previous_item (QuilterWidgetsSearchBar* self);
void quilter_widgets_search_bar_search_previous (QuilterWidgetsSearchBar* self);
static void _quilter_widgets_search_bar_search_previous_gtk_button_clicked (GtkButton* _sender,
                                                                     gpointer self);
QuilterMainWindow* quilter_widgets_search_bar_get_window (QuilterWidgetsSearchBar* self);
GType quilter_widgets_headerbar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsHeaderbar, g_object_unref)
GType quilter_widgets_preview_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsPreview, g_object_unref)
GType quilter_widgets_side_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsSideBar, g_object_unref)
GType quilter_widgets_status_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsStatusBar, g_object_unref)
static void _vala_GtkTextIter_free (GtkTextIter* self);
static GtkTextIter* _vala_GtkTextIter_copy (GtkTextIter* self);
gboolean quilter_widgets_search_bar_search_for_iter_backward (QuilterWidgetsSearchBar* self,
                                                              GtkTextIter* start_iter,
                                                              GtkTextIter** end_iter);
void quilter_widgets_search_bar_search_next_item (QuilterWidgetsSearchBar* self);
void quilter_widgets_search_bar_search_next (QuilterWidgetsSearchBar* self);
static void _quilter_widgets_search_bar_search_next_gtk_button_clicked (GtkButton* _sender,
                                                                 gpointer self);
static gboolean quilter_widgets_search_bar_search_for_iter (QuilterWidgetsSearchBar* self,
                                                     GtkTextIter* start_iter,
                                                     GtkTextIter** end_iter);
static void quilter_widgets_search_bar_update_replace_tool_sensitivities (QuilterWidgetsSearchBar* self,
                                                                   const gchar* search_text);
static void quilter_widgets_search_bar_on_replace_entry_activate (QuilterWidgetsSearchBar* self);
static void quilter_widgets_search_bar_on_replace_all_entry_activate (QuilterWidgetsSearchBar* self);
gpointer quilter_services_pos_files_ref (gpointer instance);
void quilter_services_pos_files_unref (gpointer instance);
GParamSpec* quilter_services_param_spec_pos_files (const gchar* name,
                                                   const gchar* nick,
                                                   const gchar* blurb,
                                                   GType object_type,
                                                   GParamFlags flags);
void quilter_services_value_set_pos_files (GValue* value,
                                           gpointer v_object);
void quilter_services_value_take_pos_files (GValue* value,
                                            gpointer v_object);
gpointer quilter_services_value_get_pos_files (const GValue* value);
GType quilter_services_pos_files_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterServicesPOSFiles, quilter_services_pos_files_unref)
static void quilter_widgets_search_bar_set_window (QuilterWidgetsSearchBar* self,
                                            QuilterMainWindow* value);
static GObject * quilter_widgets_search_bar_constructor (GType type,
                                                  guint n_construct_properties,
                                                  GObjectConstructParam * construct_properties);
static void _quilter_widgets_search_bar_on_replace_entry_activate_gtk_entry_activate (GtkEntry* _sender,
                                                                               gpointer self);
static void _quilter_widgets_search_bar_on_replace_entry_activate_gtk_button_clicked (GtkButton* _sender,
                                                                               gpointer self);
static void _quilter_widgets_search_bar_on_replace_all_entry_activate_gtk_button_clicked (GtkButton* _sender,
                                                                                   gpointer self);
static void quilter_widgets_search_bar_finalize (GObject * obj);
static GType quilter_widgets_search_bar_get_type_once (void);
static void _vala_quilter_widgets_search_bar_get_property (GObject * object,
                                                    guint property_id,
                                                    GValue * value,
                                                    GParamSpec * pspec);
static void _vala_quilter_widgets_search_bar_set_property (GObject * object,
                                                    guint property_id,
                                                    const GValue * value,
                                                    GParamSpec * pspec);

static inline gpointer
quilter_widgets_search_bar_get_instance_private (QuilterWidgetsSearchBar* self)
{
	return G_STRUCT_MEMBER_P (self, QuilterWidgetsSearchBar_private_offset);
}

QuilterWidgetsSearchBar*
quilter_widgets_search_bar_construct (GType object_type,
                                      QuilterMainWindow* window)
{
	QuilterWidgetsSearchBar * self = NULL;
#line 33 "../src/Widgets/SearchBar.vala"
	g_return_val_if_fail (window != NULL, NULL);
#line 34 "../src/Widgets/SearchBar.vala"
	self = (QuilterWidgetsSearchBar*) g_object_new (object_type, "window", window, NULL);
#line 33 "../src/Widgets/SearchBar.vala"
	return self;
#line 313 "SearchBar.c"
}

QuilterWidgetsSearchBar*
quilter_widgets_search_bar_new (QuilterMainWindow* window)
{
#line 33 "../src/Widgets/SearchBar.vala"
	return quilter_widgets_search_bar_construct (QUILTER_WIDGETS_TYPE_SEARCH_BAR, window);
#line 321 "SearchBar.c"
}

static void
__lambda6_ (QuilterWidgetsSearchBar* self)
{
#line 102 "../src/Widgets/SearchBar.vala"
	quilter_widgets_search_bar_search (self);
#line 329 "SearchBar.c"
}

static void
___lambda6__gtk_search_entry_search_changed (GtkSearchEntry* _sender,
                                             gpointer self)
{
#line 101 "../src/Widgets/SearchBar.vala"
	__lambda6_ ((QuilterWidgetsSearchBar*) self);
#line 338 "SearchBar.c"
}

void
quilter_widgets_search_bar_search_entry_item (QuilterWidgetsSearchBar* self)
{
	GtkSearchEntry* _tmp0_;
	GtkSearchEntry* _tmp1_;
	GtkSearchEntry* _tmp2_;
	GtkGrid* _tmp3_;
	GtkSearchEntry* _tmp4_;
	GtkWidgetPath* entry_path = NULL;
	GtkWidgetPath* _tmp5_;
	GtkStyleContext* entry_context = NULL;
	GtkStyleContext* _tmp6_;
	GtkSearchEntry* _tmp7_;
#line 88 "../src/Widgets/SearchBar.vala"
	g_return_if_fail (self != NULL);
#line 89 "../src/Widgets/SearchBar.vala"
	_tmp0_ = (GtkSearchEntry*) gtk_search_entry_new ();
#line 89 "../src/Widgets/SearchBar.vala"
	g_object_ref_sink (_tmp0_);
#line 89 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->search_entry);
#line 89 "../src/Widgets/SearchBar.vala"
	self->search_entry = _tmp0_;
#line 90 "../src/Widgets/SearchBar.vala"
	_tmp1_ = self->search_entry;
#line 90 "../src/Widgets/SearchBar.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp1_, TRUE);
#line 91 "../src/Widgets/SearchBar.vala"
	_tmp2_ = self->search_entry;
#line 91 "../src/Widgets/SearchBar.vala"
	gtk_entry_set_placeholder_text ((GtkEntry*) _tmp2_, _ ("Find text…"));
#line 92 "../src/Widgets/SearchBar.vala"
	_tmp3_ = self->prev_next_grid;
#line 92 "../src/Widgets/SearchBar.vala"
	_tmp4_ = self->search_entry;
#line 92 "../src/Widgets/SearchBar.vala"
	gtk_container_add ((GtkContainer*) _tmp3_, (GtkWidget*) _tmp4_);
#line 94 "../src/Widgets/SearchBar.vala"
	_tmp5_ = gtk_widget_path_new ();
#line 94 "../src/Widgets/SearchBar.vala"
	entry_path = _tmp5_;
#line 95 "../src/Widgets/SearchBar.vala"
	gtk_widget_path_append_type (entry_path, gtk_widget_get_type ());
#line 97 "../src/Widgets/SearchBar.vala"
	_tmp6_ = gtk_style_context_new ();
#line 97 "../src/Widgets/SearchBar.vala"
	entry_context = _tmp6_;
#line 98 "../src/Widgets/SearchBar.vala"
	gtk_style_context_set_path (entry_context, entry_path);
#line 99 "../src/Widgets/SearchBar.vala"
	gtk_style_context_add_class (entry_context, "entry");
#line 101 "../src/Widgets/SearchBar.vala"
	_tmp7_ = self->search_entry;
#line 101 "../src/Widgets/SearchBar.vala"
	g_signal_connect_object (_tmp7_, "search-changed", (GCallback) ___lambda6__gtk_search_entry_search_changed, self, 0);
#line 88 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (entry_context);
#line 88 "../src/Widgets/SearchBar.vala"
	_gtk_widget_path_unref0 (entry_path);
#line 400 "SearchBar.c"
}

static void
_quilter_widgets_search_bar_search_previous_gtk_button_clicked (GtkButton* _sender,
                                                                gpointer self)
{
#line 109 "../src/Widgets/SearchBar.vala"
	quilter_widgets_search_bar_search_previous ((QuilterWidgetsSearchBar*) self);
#line 409 "SearchBar.c"
}

void
quilter_widgets_search_bar_search_previous_item (QuilterWidgetsSearchBar* self)
{
	GtkButton* tool_arrow_up = NULL;
	GtkButton* _tmp0_;
	GtkGrid* _tmp1_;
#line 106 "../src/Widgets/SearchBar.vala"
	g_return_if_fail (self != NULL);
#line 107 "../src/Widgets/SearchBar.vala"
	_tmp0_ = (GtkButton*) gtk_button_new_from_icon_name ("go-up-symbolic", (GtkIconSize) GTK_ICON_SIZE_SMALL_TOOLBAR);
#line 107 "../src/Widgets/SearchBar.vala"
	g_object_ref_sink (_tmp0_);
#line 107 "../src/Widgets/SearchBar.vala"
	tool_arrow_up = _tmp0_;
#line 108 "../src/Widgets/SearchBar.vala"
	gtk_button_set_always_show_image (tool_arrow_up, TRUE);
#line 109 "../src/Widgets/SearchBar.vala"
	g_signal_connect_object (tool_arrow_up, "clicked", (GCallback) _quilter_widgets_search_bar_search_previous_gtk_button_clicked, self, 0);
#line 110 "../src/Widgets/SearchBar.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) tool_arrow_up, _ ("Search previous"));
#line 111 "../src/Widgets/SearchBar.vala"
	_tmp1_ = self->prev_next_grid;
#line 111 "../src/Widgets/SearchBar.vala"
	gtk_container_add ((GtkContainer*) _tmp1_, (GtkWidget*) tool_arrow_up);
#line 106 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (tool_arrow_up);
#line 438 "SearchBar.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 115 "../src/Widgets/SearchBar.vala"
	return self ? g_object_ref (self) : NULL;
#line 446 "SearchBar.c"
}

static void
_vala_GtkTextIter_free (GtkTextIter* self)
{
#line 118 "../src/Widgets/SearchBar.vala"
	g_boxed_free (gtk_text_iter_get_type (), self);
#line 454 "SearchBar.c"
}

static GtkTextIter*
_vala_GtkTextIter_copy (GtkTextIter* self)
{
#line 118 "../src/Widgets/SearchBar.vala"
	return g_boxed_copy (gtk_text_iter_get_type (), self);
#line 462 "SearchBar.c"
}

static gpointer
__vala_GtkTextIter_copy0 (gpointer self)
{
#line 118 "../src/Widgets/SearchBar.vala"
	return self ? _vala_GtkTextIter_copy (self) : NULL;
#line 470 "SearchBar.c"
}

void
quilter_widgets_search_bar_search_previous (QuilterWidgetsSearchBar* self)
{
	QuilterMainWindow* _tmp0_;
	QuilterWidgetsEditView* _tmp1_;
	QuilterWidgetsEditView* _tmp2_;
	GtkTextIter* start_iter = NULL;
	GtkTextIter* end_iter = NULL;
	GtkTextBuffer* _tmp3_;
#line 114 "../src/Widgets/SearchBar.vala"
	g_return_if_fail (self != NULL);
#line 115 "../src/Widgets/SearchBar.vala"
	_tmp0_ = self->priv->_window;
#line 115 "../src/Widgets/SearchBar.vala"
	_tmp1_ = _tmp0_->edit_view_content;
#line 115 "../src/Widgets/SearchBar.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 115 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_view);
#line 115 "../src/Widgets/SearchBar.vala"
	self->priv->text_view = _tmp2_;
#line 117 "../src/Widgets/SearchBar.vala"
	_tmp3_ = self->priv->text_buffer;
#line 117 "../src/Widgets/SearchBar.vala"
	if (_tmp3_ != NULL) {
#line 498 "SearchBar.c"
		GtkTextBuffer* _tmp4_;
		GtkTextIter _tmp5_ = {0};
		GtkTextIter _tmp6_ = {0};
		GtkTextIter _tmp7_;
		GtkTextIter* _tmp8_;
		GtkTextIter _tmp9_;
		GtkTextIter* _tmp10_;
		GtkTextIter* _tmp11_;
		GtkTextIter* _tmp12_ = NULL;
		gboolean _tmp13_;
#line 118 "../src/Widgets/SearchBar.vala"
		_tmp4_ = self->priv->text_buffer;
#line 118 "../src/Widgets/SearchBar.vala"
		gtk_text_buffer_get_selection_bounds (_tmp4_, &_tmp5_, &_tmp6_);
#line 118 "../src/Widgets/SearchBar.vala"
		__vala_GtkTextIter_free0 (start_iter);
#line 118 "../src/Widgets/SearchBar.vala"
		_tmp7_ = _tmp5_;
#line 118 "../src/Widgets/SearchBar.vala"
		_tmp8_ = __vala_GtkTextIter_copy0 (&_tmp7_);
#line 118 "../src/Widgets/SearchBar.vala"
		start_iter = _tmp8_;
#line 118 "../src/Widgets/SearchBar.vala"
		__vala_GtkTextIter_free0 (end_iter);
#line 118 "../src/Widgets/SearchBar.vala"
		_tmp9_ = _tmp6_;
#line 118 "../src/Widgets/SearchBar.vala"
		_tmp10_ = __vala_GtkTextIter_copy0 (&_tmp9_);
#line 118 "../src/Widgets/SearchBar.vala"
		end_iter = _tmp10_;
#line 119 "../src/Widgets/SearchBar.vala"
		_tmp11_ = start_iter;
#line 119 "../src/Widgets/SearchBar.vala"
		_tmp13_ = quilter_widgets_search_bar_search_for_iter_backward (self, _tmp11_, &_tmp12_);
#line 119 "../src/Widgets/SearchBar.vala"
		__vala_GtkTextIter_free0 (end_iter);
#line 119 "../src/Widgets/SearchBar.vala"
		end_iter = _tmp12_;
#line 119 "../src/Widgets/SearchBar.vala"
		if (!_tmp13_) {
#line 539 "SearchBar.c"
			GtkTextBuffer* _tmp14_;
			GtkTextIter _tmp15_ = {0};
			GtkTextIter _tmp16_;
			GtkTextIter* _tmp17_;
			GtkTextIter* _tmp18_;
			GtkTextIter* _tmp19_ = NULL;
#line 120 "../src/Widgets/SearchBar.vala"
			_tmp14_ = self->priv->text_buffer;
#line 120 "../src/Widgets/SearchBar.vala"
			gtk_text_buffer_get_end_iter (_tmp14_, &_tmp15_);
#line 120 "../src/Widgets/SearchBar.vala"
			__vala_GtkTextIter_free0 (start_iter);
#line 120 "../src/Widgets/SearchBar.vala"
			_tmp16_ = _tmp15_;
#line 120 "../src/Widgets/SearchBar.vala"
			_tmp17_ = __vala_GtkTextIter_copy0 (&_tmp16_);
#line 120 "../src/Widgets/SearchBar.vala"
			start_iter = _tmp17_;
#line 121 "../src/Widgets/SearchBar.vala"
			_tmp18_ = start_iter;
#line 121 "../src/Widgets/SearchBar.vala"
			quilter_widgets_search_bar_search_for_iter_backward (self, _tmp18_, &_tmp19_);
#line 121 "../src/Widgets/SearchBar.vala"
			__vala_GtkTextIter_free0 (end_iter);
#line 121 "../src/Widgets/SearchBar.vala"
			end_iter = _tmp19_;
#line 566 "SearchBar.c"
		}
	}
#line 114 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (end_iter);
#line 114 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (start_iter);
#line 573 "SearchBar.c"
}

static void
_quilter_widgets_search_bar_search_next_gtk_button_clicked (GtkButton* _sender,
                                                            gpointer self)
{
#line 129 "../src/Widgets/SearchBar.vala"
	quilter_widgets_search_bar_search_next ((QuilterWidgetsSearchBar*) self);
#line 582 "SearchBar.c"
}

void
quilter_widgets_search_bar_search_next_item (QuilterWidgetsSearchBar* self)
{
	GtkButton* tool_arrow_down = NULL;
	GtkButton* _tmp0_;
	GtkGrid* _tmp1_;
#line 126 "../src/Widgets/SearchBar.vala"
	g_return_if_fail (self != NULL);
#line 127 "../src/Widgets/SearchBar.vala"
	_tmp0_ = (GtkButton*) gtk_button_new_from_icon_name ("go-down-symbolic", (GtkIconSize) GTK_ICON_SIZE_SMALL_TOOLBAR);
#line 127 "../src/Widgets/SearchBar.vala"
	g_object_ref_sink (_tmp0_);
#line 127 "../src/Widgets/SearchBar.vala"
	tool_arrow_down = _tmp0_;
#line 128 "../src/Widgets/SearchBar.vala"
	gtk_button_set_always_show_image (tool_arrow_down, TRUE);
#line 129 "../src/Widgets/SearchBar.vala"
	g_signal_connect_object (tool_arrow_down, "clicked", (GCallback) _quilter_widgets_search_bar_search_next_gtk_button_clicked, self, 0);
#line 130 "../src/Widgets/SearchBar.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) tool_arrow_down, _ ("Search next"));
#line 131 "../src/Widgets/SearchBar.vala"
	_tmp1_ = self->prev_next_grid;
#line 131 "../src/Widgets/SearchBar.vala"
	gtk_container_add ((GtkContainer*) _tmp1_, (GtkWidget*) tool_arrow_down);
#line 126 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (tool_arrow_down);
#line 611 "SearchBar.c"
}

void
quilter_widgets_search_bar_search_next (QuilterWidgetsSearchBar* self)
{
	QuilterMainWindow* _tmp0_;
	QuilterWidgetsEditView* _tmp1_;
	QuilterWidgetsEditView* _tmp2_;
	GtkTextIter* start_iter = NULL;
	GtkTextIter* end_iter = NULL;
	GtkTextIter* end_iter_tmp = NULL;
	GtkTextBuffer* _tmp3_;
#line 134 "../src/Widgets/SearchBar.vala"
	g_return_if_fail (self != NULL);
#line 135 "../src/Widgets/SearchBar.vala"
	_tmp0_ = self->priv->_window;
#line 135 "../src/Widgets/SearchBar.vala"
	_tmp1_ = _tmp0_->edit_view_content;
#line 135 "../src/Widgets/SearchBar.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 135 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_view);
#line 135 "../src/Widgets/SearchBar.vala"
	self->priv->text_view = _tmp2_;
#line 137 "../src/Widgets/SearchBar.vala"
	_tmp3_ = self->priv->text_buffer;
#line 137 "../src/Widgets/SearchBar.vala"
	if (_tmp3_ != NULL) {
#line 640 "SearchBar.c"
		GtkTextBuffer* _tmp4_;
		GtkTextIter _tmp5_ = {0};
		GtkTextIter _tmp6_ = {0};
		GtkTextIter _tmp7_;
		GtkTextIter* _tmp8_;
		GtkTextIter _tmp9_;
		GtkTextIter* _tmp10_;
		GtkTextIter* _tmp11_;
		GtkTextIter* _tmp12_ = NULL;
		gboolean _tmp13_;
#line 138 "../src/Widgets/SearchBar.vala"
		_tmp4_ = self->priv->text_buffer;
#line 138 "../src/Widgets/SearchBar.vala"
		gtk_text_buffer_get_selection_bounds (_tmp4_, &_tmp5_, &_tmp6_);
#line 138 "../src/Widgets/SearchBar.vala"
		__vala_GtkTextIter_free0 (start_iter);
#line 138 "../src/Widgets/SearchBar.vala"
		_tmp7_ = _tmp5_;
#line 138 "../src/Widgets/SearchBar.vala"
		_tmp8_ = __vala_GtkTextIter_copy0 (&_tmp7_);
#line 138 "../src/Widgets/SearchBar.vala"
		start_iter = _tmp8_;
#line 138 "../src/Widgets/SearchBar.vala"
		__vala_GtkTextIter_free0 (end_iter);
#line 138 "../src/Widgets/SearchBar.vala"
		_tmp9_ = _tmp6_;
#line 138 "../src/Widgets/SearchBar.vala"
		_tmp10_ = __vala_GtkTextIter_copy0 (&_tmp9_);
#line 138 "../src/Widgets/SearchBar.vala"
		end_iter = _tmp10_;
#line 139 "../src/Widgets/SearchBar.vala"
		_tmp11_ = end_iter;
#line 139 "../src/Widgets/SearchBar.vala"
		_tmp13_ = quilter_widgets_search_bar_search_for_iter (self, _tmp11_, &_tmp12_);
#line 139 "../src/Widgets/SearchBar.vala"
		__vala_GtkTextIter_free0 (end_iter_tmp);
#line 139 "../src/Widgets/SearchBar.vala"
		end_iter_tmp = _tmp12_;
#line 139 "../src/Widgets/SearchBar.vala"
		if (!_tmp13_) {
#line 681 "SearchBar.c"
			GtkTextBuffer* _tmp14_;
			GtkTextIter _tmp15_ = {0};
			GtkTextIter _tmp16_;
			GtkTextIter* _tmp17_;
			GtkTextIter* _tmp18_;
			GtkTextIter* _tmp19_ = NULL;
#line 140 "../src/Widgets/SearchBar.vala"
			_tmp14_ = self->priv->text_buffer;
#line 140 "../src/Widgets/SearchBar.vala"
			gtk_text_buffer_get_start_iter (_tmp14_, &_tmp15_);
#line 140 "../src/Widgets/SearchBar.vala"
			__vala_GtkTextIter_free0 (start_iter);
#line 140 "../src/Widgets/SearchBar.vala"
			_tmp16_ = _tmp15_;
#line 140 "../src/Widgets/SearchBar.vala"
			_tmp17_ = __vala_GtkTextIter_copy0 (&_tmp16_);
#line 140 "../src/Widgets/SearchBar.vala"
			start_iter = _tmp17_;
#line 141 "../src/Widgets/SearchBar.vala"
			_tmp18_ = start_iter;
#line 141 "../src/Widgets/SearchBar.vala"
			quilter_widgets_search_bar_search_for_iter (self, _tmp18_, &_tmp19_);
#line 141 "../src/Widgets/SearchBar.vala"
			__vala_GtkTextIter_free0 (end_iter);
#line 141 "../src/Widgets/SearchBar.vala"
			end_iter = _tmp19_;
#line 708 "SearchBar.c"
		}
	}
#line 134 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (end_iter_tmp);
#line 134 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (end_iter);
#line 134 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (start_iter);
#line 717 "SearchBar.c"
}

static void
quilter_widgets_search_bar_update_replace_tool_sensitivities (QuilterWidgetsSearchBar* self,
                                                              const gchar* search_text)
{
	GtkButton* _tmp0_;
	GtkButton* _tmp1_;
#line 146 "../src/Widgets/SearchBar.vala"
	g_return_if_fail (self != NULL);
#line 146 "../src/Widgets/SearchBar.vala"
	g_return_if_fail (search_text != NULL);
#line 147 "../src/Widgets/SearchBar.vala"
	_tmp0_ = self->priv->replace_tool_button;
#line 147 "../src/Widgets/SearchBar.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp0_, g_strcmp0 (search_text, "") != 0);
#line 148 "../src/Widgets/SearchBar.vala"
	_tmp1_ = self->priv->replace_all_tool_button;
#line 148 "../src/Widgets/SearchBar.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp1_, g_strcmp0 (search_text, "") != 0);
#line 738 "SearchBar.c"
}

static void
quilter_widgets_search_bar_on_replace_entry_activate (QuilterWidgetsSearchBar* self)
{
	QuilterMainWindow* _tmp0_;
	QuilterWidgetsEditView* _tmp1_;
	QuilterWidgetsEditView* _tmp2_;
	QuilterWidgetsEditView* _tmp3_;
	GtkTextBuffer* _tmp4_;
	GtkTextBuffer* _tmp5_;
	GtkTextBuffer* _tmp6_;
	GtkTextIter* start_iter = NULL;
	GtkTextIter* end_iter = NULL;
	GtkTextBuffer* _tmp7_;
	GtkTextBuffer* _tmp8_;
	gint _tmp9_;
	gint _tmp10_;
	GtkTextIter _tmp11_ = {0};
	GtkTextIter _tmp12_;
	GtkTextIter* _tmp13_;
	GtkTextIter* _tmp14_;
	GtkTextIter* _tmp15_ = NULL;
	gboolean _tmp16_;
	GError* _inner_error0_ = NULL;
#line 151 "../src/Widgets/SearchBar.vala"
	g_return_if_fail (self != NULL);
#line 152 "../src/Widgets/SearchBar.vala"
	_tmp0_ = self->priv->_window;
#line 152 "../src/Widgets/SearchBar.vala"
	_tmp1_ = _tmp0_->edit_view_content;
#line 152 "../src/Widgets/SearchBar.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 152 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_view);
#line 152 "../src/Widgets/SearchBar.vala"
	self->priv->text_view = _tmp2_;
#line 153 "../src/Widgets/SearchBar.vala"
	_tmp3_ = self->priv->text_view;
#line 153 "../src/Widgets/SearchBar.vala"
	_tmp4_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp3_);
#line 153 "../src/Widgets/SearchBar.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 153 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_buffer);
#line 153 "../src/Widgets/SearchBar.vala"
	self->priv->text_buffer = _tmp5_;
#line 154 "../src/Widgets/SearchBar.vala"
	_tmp6_ = self->priv->text_buffer;
#line 154 "../src/Widgets/SearchBar.vala"
	if (_tmp6_ == NULL) {
#line 155 "../src/Widgets/SearchBar.vala"
		g_warning ("SearchBar.vala:155: No valid buffer to replace");
#line 156 "../src/Widgets/SearchBar.vala"
		return;
#line 794 "SearchBar.c"
	}
#line 160 "../src/Widgets/SearchBar.vala"
	_tmp7_ = self->priv->text_buffer;
#line 160 "../src/Widgets/SearchBar.vala"
	_tmp8_ = self->priv->text_buffer;
#line 160 "../src/Widgets/SearchBar.vala"
	g_object_get (_tmp8_, "cursor-position", &_tmp9_, NULL);
#line 160 "../src/Widgets/SearchBar.vala"
	_tmp10_ = _tmp9_;
#line 160 "../src/Widgets/SearchBar.vala"
	gtk_text_buffer_get_iter_at_offset (_tmp7_, &_tmp11_, _tmp10_);
#line 160 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (start_iter);
#line 160 "../src/Widgets/SearchBar.vala"
	_tmp12_ = _tmp11_;
#line 160 "../src/Widgets/SearchBar.vala"
	_tmp13_ = __vala_GtkTextIter_copy0 (&_tmp12_);
#line 160 "../src/Widgets/SearchBar.vala"
	start_iter = _tmp13_;
#line 162 "../src/Widgets/SearchBar.vala"
	_tmp14_ = start_iter;
#line 162 "../src/Widgets/SearchBar.vala"
	_tmp16_ = quilter_widgets_search_bar_search_for_iter (self, _tmp14_, &_tmp15_);
#line 162 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (end_iter);
#line 162 "../src/Widgets/SearchBar.vala"
	end_iter = _tmp15_;
#line 162 "../src/Widgets/SearchBar.vala"
	if (_tmp16_) {
#line 824 "SearchBar.c"
		gchar* replace_string = NULL;
		GtkEntry* _tmp17_;
		const gchar* _tmp18_;
		const gchar* _tmp19_;
		gchar* _tmp20_;
#line 163 "../src/Widgets/SearchBar.vala"
		_tmp17_ = self->replace_entry;
#line 163 "../src/Widgets/SearchBar.vala"
		_tmp18_ = gtk_entry_get_text (_tmp17_);
#line 163 "../src/Widgets/SearchBar.vala"
		_tmp19_ = _tmp18_;
#line 163 "../src/Widgets/SearchBar.vala"
		_tmp20_ = g_strdup (_tmp19_);
#line 163 "../src/Widgets/SearchBar.vala"
		replace_string = _tmp20_;
#line 840 "SearchBar.c"
		{
			GtkSourceSearchContext* _tmp21_;
			GtkTextIter* _tmp22_;
			GtkTextIter* _tmp23_;
			const gchar* _tmp24_;
			const gchar* _tmp25_;
			gint _tmp26_;
			gint _tmp27_;
			GtkTextIter _tmp28_;
			GtkTextIter _tmp29_;
			GtkSearchEntry* _tmp30_;
			const gchar* _tmp31_;
			const gchar* _tmp32_;
#line 165 "../src/Widgets/SearchBar.vala"
			_tmp21_ = self->search_context;
#line 165 "../src/Widgets/SearchBar.vala"
			_tmp22_ = start_iter;
#line 165 "../src/Widgets/SearchBar.vala"
			_tmp23_ = end_iter;
#line 165 "../src/Widgets/SearchBar.vala"
			_tmp24_ = replace_string;
#line 165 "../src/Widgets/SearchBar.vala"
			_tmp25_ = replace_string;
#line 165 "../src/Widgets/SearchBar.vala"
			_tmp26_ = strlen (_tmp25_);
#line 165 "../src/Widgets/SearchBar.vala"
			_tmp27_ = _tmp26_;
#line 165 "../src/Widgets/SearchBar.vala"
			_tmp28_ = *_tmp22_;
#line 165 "../src/Widgets/SearchBar.vala"
			_tmp29_ = *_tmp23_;
#line 165 "../src/Widgets/SearchBar.vala"
			gtk_source_search_context_replace (_tmp21_, &_tmp28_, &_tmp29_, _tmp24_, _tmp27_, &_inner_error0_);
#line 165 "../src/Widgets/SearchBar.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 876 "SearchBar.c"
				goto __catch0_g_error;
			}
#line 166 "../src/Widgets/SearchBar.vala"
			_tmp30_ = self->search_entry;
#line 166 "../src/Widgets/SearchBar.vala"
			_tmp31_ = gtk_entry_get_text ((GtkEntry*) _tmp30_);
#line 166 "../src/Widgets/SearchBar.vala"
			_tmp32_ = _tmp31_;
#line 166 "../src/Widgets/SearchBar.vala"
			quilter_widgets_search_bar_update_replace_tool_sensitivities (self, _tmp32_);
#line 887 "SearchBar.c"
		}
		goto __finally0;
		__catch0_g_error:
		{
			GError* e = NULL;
			GError* _tmp33_;
			const gchar* _tmp34_;
#line 164 "../src/Widgets/SearchBar.vala"
			e = _inner_error0_;
#line 164 "../src/Widgets/SearchBar.vala"
			_inner_error0_ = NULL;
#line 168 "../src/Widgets/SearchBar.vala"
			_tmp33_ = e;
#line 168 "../src/Widgets/SearchBar.vala"
			_tmp34_ = _tmp33_->message;
#line 168 "../src/Widgets/SearchBar.vala"
			g_critical ("SearchBar.vala:168: %s", _tmp34_);
#line 164 "../src/Widgets/SearchBar.vala"
			_g_error_free0 (e);
#line 907 "SearchBar.c"
		}
		__finally0:
#line 164 "../src/Widgets/SearchBar.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 164 "../src/Widgets/SearchBar.vala"
			_g_free0 (replace_string);
#line 164 "../src/Widgets/SearchBar.vala"
			__vala_GtkTextIter_free0 (end_iter);
#line 164 "../src/Widgets/SearchBar.vala"
			__vala_GtkTextIter_free0 (start_iter);
#line 164 "../src/Widgets/SearchBar.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 164 "../src/Widgets/SearchBar.vala"
			g_clear_error (&_inner_error0_);
#line 164 "../src/Widgets/SearchBar.vala"
			return;
#line 924 "SearchBar.c"
		}
#line 162 "../src/Widgets/SearchBar.vala"
		_g_free0 (replace_string);
#line 928 "SearchBar.c"
	}
#line 151 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (end_iter);
#line 151 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (start_iter);
#line 934 "SearchBar.c"
}

static void
quilter_widgets_search_bar_on_replace_all_entry_activate (QuilterWidgetsSearchBar* self)
{
	QuilterMainWindow* _tmp0_;
	QuilterWidgetsEditView* _tmp1_;
	QuilterWidgetsEditView* _tmp2_;
	QuilterWidgetsEditView* _tmp3_;
	GtkTextBuffer* _tmp4_;
	GtkTextBuffer* _tmp5_;
	GtkTextBuffer* _tmp6_;
	gchar* replace_string = NULL;
	GtkEntry* _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	gchar* _tmp10_;
	GError* _inner_error0_ = NULL;
#line 173 "../src/Widgets/SearchBar.vala"
	g_return_if_fail (self != NULL);
#line 174 "../src/Widgets/SearchBar.vala"
	_tmp0_ = self->priv->_window;
#line 174 "../src/Widgets/SearchBar.vala"
	_tmp1_ = _tmp0_->edit_view_content;
#line 174 "../src/Widgets/SearchBar.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 174 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_view);
#line 174 "../src/Widgets/SearchBar.vala"
	self->priv->text_view = _tmp2_;
#line 175 "../src/Widgets/SearchBar.vala"
	_tmp3_ = self->priv->text_view;
#line 175 "../src/Widgets/SearchBar.vala"
	_tmp4_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp3_);
#line 175 "../src/Widgets/SearchBar.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 175 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_buffer);
#line 175 "../src/Widgets/SearchBar.vala"
	self->priv->text_buffer = _tmp5_;
#line 176 "../src/Widgets/SearchBar.vala"
	_tmp6_ = self->priv->text_buffer;
#line 176 "../src/Widgets/SearchBar.vala"
	if (_tmp6_ == NULL) {
#line 177 "../src/Widgets/SearchBar.vala"
		g_warning ("SearchBar.vala:177: No valid buffer to replace");
#line 178 "../src/Widgets/SearchBar.vala"
		return;
#line 983 "SearchBar.c"
	}
#line 181 "../src/Widgets/SearchBar.vala"
	_tmp7_ = self->replace_entry;
#line 181 "../src/Widgets/SearchBar.vala"
	_tmp8_ = gtk_entry_get_text (_tmp7_);
#line 181 "../src/Widgets/SearchBar.vala"
	_tmp9_ = _tmp8_;
#line 181 "../src/Widgets/SearchBar.vala"
	_tmp10_ = g_strdup (_tmp9_);
#line 181 "../src/Widgets/SearchBar.vala"
	replace_string = _tmp10_;
#line 995 "SearchBar.c"
	{
		GtkSourceSearchContext* _tmp11_;
		const gchar* _tmp12_;
		const gchar* _tmp13_;
		gint _tmp14_;
		gint _tmp15_;
		GtkSearchEntry* _tmp16_;
		const gchar* _tmp17_;
		const gchar* _tmp18_;
#line 183 "../src/Widgets/SearchBar.vala"
		_tmp11_ = self->search_context;
#line 183 "../src/Widgets/SearchBar.vala"
		_tmp12_ = replace_string;
#line 183 "../src/Widgets/SearchBar.vala"
		_tmp13_ = replace_string;
#line 183 "../src/Widgets/SearchBar.vala"
		_tmp14_ = strlen (_tmp13_);
#line 183 "../src/Widgets/SearchBar.vala"
		_tmp15_ = _tmp14_;
#line 183 "../src/Widgets/SearchBar.vala"
		gtk_source_search_context_replace_all (_tmp11_, _tmp12_, _tmp15_, &_inner_error0_);
#line 183 "../src/Widgets/SearchBar.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1019 "SearchBar.c"
			goto __catch0_g_error;
		}
#line 184 "../src/Widgets/SearchBar.vala"
		_tmp16_ = self->search_entry;
#line 184 "../src/Widgets/SearchBar.vala"
		_tmp17_ = gtk_entry_get_text ((GtkEntry*) _tmp16_);
#line 184 "../src/Widgets/SearchBar.vala"
		_tmp18_ = _tmp17_;
#line 184 "../src/Widgets/SearchBar.vala"
		quilter_widgets_search_bar_update_replace_tool_sensitivities (self, _tmp18_);
#line 1030 "SearchBar.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp19_;
		const gchar* _tmp20_;
#line 182 "../src/Widgets/SearchBar.vala"
		e = _inner_error0_;
#line 182 "../src/Widgets/SearchBar.vala"
		_inner_error0_ = NULL;
#line 186 "../src/Widgets/SearchBar.vala"
		_tmp19_ = e;
#line 186 "../src/Widgets/SearchBar.vala"
		_tmp20_ = _tmp19_->message;
#line 186 "../src/Widgets/SearchBar.vala"
		g_critical ("SearchBar.vala:186: %s", _tmp20_);
#line 182 "../src/Widgets/SearchBar.vala"
		_g_error_free0 (e);
#line 1050 "SearchBar.c"
	}
	__finally0:
#line 182 "../src/Widgets/SearchBar.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 182 "../src/Widgets/SearchBar.vala"
		_g_free0 (replace_string);
#line 182 "../src/Widgets/SearchBar.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 182 "../src/Widgets/SearchBar.vala"
		g_clear_error (&_inner_error0_);
#line 182 "../src/Widgets/SearchBar.vala"
		return;
#line 1063 "SearchBar.c"
	}
#line 173 "../src/Widgets/SearchBar.vala"
	_g_free0 (replace_string);
#line 1067 "SearchBar.c"
}

static gboolean
quilter_widgets_search_bar_search_for_iter (QuilterWidgetsSearchBar* self,
                                            GtkTextIter* start_iter,
                                            GtkTextIter** end_iter)
{
	GtkTextIter* _vala_end_iter = NULL;
	GtkTextIter* _tmp0_;
	gboolean found = FALSE;
	GtkSourceSearchContext* _tmp1_;
	GtkTextIter _tmp2_;
	GtkTextIter _tmp3_ = {0};
	GtkTextIter _tmp4_ = {0};
	gboolean _tmp5_;
	GtkTextIter _tmp6_;
	GtkTextIter _tmp7_;
	GtkTextIter* _tmp8_;
	gboolean result = FALSE;
#line 191 "../src/Widgets/SearchBar.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 192 "../src/Widgets/SearchBar.vala"
	_tmp0_ = __vala_GtkTextIter_copy0 (start_iter);
#line 192 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (_vala_end_iter);
#line 192 "../src/Widgets/SearchBar.vala"
	_vala_end_iter = _tmp0_;
#line 193 "../src/Widgets/SearchBar.vala"
	_tmp1_ = self->search_context;
#line 193 "../src/Widgets/SearchBar.vala"
	_tmp2_ = *start_iter;
#line 193 "../src/Widgets/SearchBar.vala"
	_tmp5_ = gtk_source_search_context_forward (_tmp1_, &_tmp2_, &_tmp3_, &_tmp4_, NULL);
#line 193 "../src/Widgets/SearchBar.vala"
	_tmp6_ = _tmp3_;
#line 193 "../src/Widgets/SearchBar.vala"
	start_iter = &_tmp6_;
#line 193 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (_vala_end_iter);
#line 193 "../src/Widgets/SearchBar.vala"
	_tmp7_ = _tmp4_;
#line 193 "../src/Widgets/SearchBar.vala"
	_tmp8_ = __vala_GtkTextIter_copy0 (&_tmp7_);
#line 193 "../src/Widgets/SearchBar.vala"
	_vala_end_iter = _tmp8_;
#line 193 "../src/Widgets/SearchBar.vala"
	found = _tmp5_;
#line 194 "../src/Widgets/SearchBar.vala"
	if (found) {
#line 1117 "SearchBar.c"
		GtkTextBuffer* _tmp9_;
		GtkTextIter* _tmp10_;
		GtkTextIter _tmp11_;
		GtkTextIter _tmp12_;
		QuilterWidgetsEditView* _tmp13_;
		GtkTextIter _tmp14_;
#line 195 "../src/Widgets/SearchBar.vala"
		_tmp9_ = self->priv->text_buffer;
#line 195 "../src/Widgets/SearchBar.vala"
		_tmp10_ = _vala_end_iter;
#line 195 "../src/Widgets/SearchBar.vala"
		_tmp11_ = *start_iter;
#line 195 "../src/Widgets/SearchBar.vala"
		_tmp12_ = *_tmp10_;
#line 195 "../src/Widgets/SearchBar.vala"
		gtk_text_buffer_select_range (_tmp9_, &_tmp11_, &_tmp12_);
#line 196 "../src/Widgets/SearchBar.vala"
		_tmp13_ = self->priv->text_view;
#line 196 "../src/Widgets/SearchBar.vala"
		_tmp14_ = *start_iter;
#line 196 "../src/Widgets/SearchBar.vala"
		gtk_text_view_scroll_to_iter ((GtkTextView*) _tmp13_, &_tmp14_, (gdouble) 0, FALSE, (gdouble) 0, (gdouble) 0);
#line 1140 "SearchBar.c"
	}
#line 199 "../src/Widgets/SearchBar.vala"
	result = found;
#line 199 "../src/Widgets/SearchBar.vala"
	if (end_iter) {
#line 199 "../src/Widgets/SearchBar.vala"
		*end_iter = _vala_end_iter;
#line 1148 "SearchBar.c"
	} else {
#line 199 "../src/Widgets/SearchBar.vala"
		__vala_GtkTextIter_free0 (_vala_end_iter);
#line 1152 "SearchBar.c"
	}
#line 199 "../src/Widgets/SearchBar.vala"
	return result;
#line 1156 "SearchBar.c"
}

gboolean
quilter_widgets_search_bar_search_for_iter_backward (QuilterWidgetsSearchBar* self,
                                                     GtkTextIter* start_iter,
                                                     GtkTextIter** end_iter)
{
	GtkTextIter* _vala_end_iter = NULL;
	GtkTextIter* _tmp0_;
	gboolean found = FALSE;
	GtkSourceSearchContext* _tmp1_;
	GtkTextIter _tmp2_;
	GtkTextIter _tmp3_ = {0};
	GtkTextIter _tmp4_ = {0};
	gboolean _tmp5_;
	GtkTextIter _tmp6_;
	GtkTextIter _tmp7_;
	GtkTextIter* _tmp8_;
	gboolean result = FALSE;
#line 202 "../src/Widgets/SearchBar.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 203 "../src/Widgets/SearchBar.vala"
	_tmp0_ = __vala_GtkTextIter_copy0 (start_iter);
#line 203 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (_vala_end_iter);
#line 203 "../src/Widgets/SearchBar.vala"
	_vala_end_iter = _tmp0_;
#line 204 "../src/Widgets/SearchBar.vala"
	_tmp1_ = self->search_context;
#line 204 "../src/Widgets/SearchBar.vala"
	_tmp2_ = *start_iter;
#line 204 "../src/Widgets/SearchBar.vala"
	_tmp5_ = gtk_source_search_context_backward (_tmp1_, &_tmp2_, &_tmp3_, &_tmp4_, NULL);
#line 204 "../src/Widgets/SearchBar.vala"
	_tmp6_ = _tmp3_;
#line 204 "../src/Widgets/SearchBar.vala"
	start_iter = &_tmp6_;
#line 204 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (_vala_end_iter);
#line 204 "../src/Widgets/SearchBar.vala"
	_tmp7_ = _tmp4_;
#line 204 "../src/Widgets/SearchBar.vala"
	_tmp8_ = __vala_GtkTextIter_copy0 (&_tmp7_);
#line 204 "../src/Widgets/SearchBar.vala"
	_vala_end_iter = _tmp8_;
#line 204 "../src/Widgets/SearchBar.vala"
	found = _tmp5_;
#line 205 "../src/Widgets/SearchBar.vala"
	if (found) {
#line 1206 "SearchBar.c"
		GtkTextBuffer* _tmp9_;
		GtkTextIter* _tmp10_;
		GtkTextIter _tmp11_;
		GtkTextIter _tmp12_;
		QuilterWidgetsEditView* _tmp13_;
		GtkTextIter _tmp14_;
#line 206 "../src/Widgets/SearchBar.vala"
		_tmp9_ = self->priv->text_buffer;
#line 206 "../src/Widgets/SearchBar.vala"
		_tmp10_ = _vala_end_iter;
#line 206 "../src/Widgets/SearchBar.vala"
		_tmp11_ = *start_iter;
#line 206 "../src/Widgets/SearchBar.vala"
		_tmp12_ = *_tmp10_;
#line 206 "../src/Widgets/SearchBar.vala"
		gtk_text_buffer_select_range (_tmp9_, &_tmp11_, &_tmp12_);
#line 207 "../src/Widgets/SearchBar.vala"
		_tmp13_ = self->priv->text_view;
#line 207 "../src/Widgets/SearchBar.vala"
		_tmp14_ = *start_iter;
#line 207 "../src/Widgets/SearchBar.vala"
		gtk_text_view_scroll_to_iter ((GtkTextView*) _tmp13_, &_tmp14_, (gdouble) 0, FALSE, (gdouble) 0, (gdouble) 0);
#line 1229 "SearchBar.c"
	}
#line 210 "../src/Widgets/SearchBar.vala"
	result = found;
#line 210 "../src/Widgets/SearchBar.vala"
	if (end_iter) {
#line 210 "../src/Widgets/SearchBar.vala"
		*end_iter = _vala_end_iter;
#line 1237 "SearchBar.c"
	} else {
#line 210 "../src/Widgets/SearchBar.vala"
		__vala_GtkTextIter_free0 (_vala_end_iter);
#line 1241 "SearchBar.c"
	}
#line 210 "../src/Widgets/SearchBar.vala"
	return result;
#line 1245 "SearchBar.c"
}

static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gchar* _tmp0_;
	gboolean result = FALSE;
#line 1530 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, FALSE);
#line 1530 "glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, FALSE);
#line 1531 "glib-2.0.vapi"
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
#line 1531 "glib-2.0.vapi"
	result = _tmp0_ != NULL;
#line 1531 "glib-2.0.vapi"
	return result;
#line 1264 "SearchBar.c"
}

gboolean
quilter_widgets_search_bar_search (QuilterWidgetsSearchBar* self)
{
	QuilterMainWindow* _tmp0_;
	QuilterWidgetsEditView* _tmp1_;
	QuilterWidgetsEditView* _tmp2_;
	QuilterWidgetsEditView* _tmp3_;
	GtkTextBuffer* _tmp4_;
	GtkTextBuffer* _tmp5_;
	gchar* search_string = NULL;
	GtkSearchEntry* _tmp6_;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	GtkTextBuffer* _tmp10_;
	GtkSourceSearchContext* _tmp11_;
	GtkSourceSearchContext* _tmp12_;
	GtkSourceSearchSettings* _tmp13_;
	GtkSourceSearchSettings* _tmp14_;
	GtkSourceSearchContext* _tmp15_;
	GtkSourceSearchSettings* _tmp16_;
	GtkSourceSearchSettings* _tmp17_;
	const gchar* _tmp18_;
	gboolean _tmp19_ = FALSE;
	const gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	const gchar* _tmp23_;
	gboolean _tmp24_;
	gboolean case_sensitive = FALSE;
	QuilterWidgetsEditView* _tmp29_;
	GtkSourceSearchContext* _tmp30_;
	GtkSourceSearchSettings* _tmp31_;
	GtkSourceSearchSettings* _tmp32_;
	gboolean _tmp33_ = FALSE;
	GtkTextBuffer* _tmp34_;
	QuilterWidgetsEditView* _tmp39_;
	GtkTextIter* start_iter = NULL;
	GtkTextBuffer* _tmp40_;
	GtkTextBuffer* _tmp41_;
	gint _tmp42_;
	gint _tmp43_;
	GtkTextIter _tmp44_ = {0};
	GtkTextIter _tmp45_;
	GtkTextIter* _tmp46_;
	gboolean _tmp47_ = FALSE;
	GtkSearchEntry* _tmp48_;
	const gchar* _tmp49_;
	const gchar* _tmp50_;
	gboolean found = FALSE;
	gboolean result = FALSE;
#line 213 "../src/Widgets/SearchBar.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 214 "../src/Widgets/SearchBar.vala"
	_tmp0_ = self->priv->_window;
#line 214 "../src/Widgets/SearchBar.vala"
	_tmp1_ = _tmp0_->edit_view_content;
#line 214 "../src/Widgets/SearchBar.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 214 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_view);
#line 214 "../src/Widgets/SearchBar.vala"
	self->priv->text_view = _tmp2_;
#line 215 "../src/Widgets/SearchBar.vala"
	_tmp3_ = self->priv->text_view;
#line 215 "../src/Widgets/SearchBar.vala"
	_tmp4_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp3_);
#line 215 "../src/Widgets/SearchBar.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 215 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_buffer);
#line 215 "../src/Widgets/SearchBar.vala"
	self->priv->text_buffer = _tmp5_;
#line 216 "../src/Widgets/SearchBar.vala"
	_tmp6_ = self->search_entry;
#line 216 "../src/Widgets/SearchBar.vala"
	_tmp7_ = gtk_entry_get_text ((GtkEntry*) _tmp6_);
#line 216 "../src/Widgets/SearchBar.vala"
	_tmp8_ = _tmp7_;
#line 216 "../src/Widgets/SearchBar.vala"
	_tmp9_ = g_strdup (_tmp8_);
#line 216 "../src/Widgets/SearchBar.vala"
	search_string = _tmp9_;
#line 218 "../src/Widgets/SearchBar.vala"
	_tmp10_ = self->priv->text_buffer;
#line 218 "../src/Widgets/SearchBar.vala"
	_tmp11_ = gtk_source_search_context_new (G_TYPE_CHECK_INSTANCE_TYPE (_tmp10_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp10_) : NULL, NULL);
#line 218 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->search_context);
#line 218 "../src/Widgets/SearchBar.vala"
	self->search_context = _tmp11_;
#line 219 "../src/Widgets/SearchBar.vala"
	_tmp12_ = self->search_context;
#line 219 "../src/Widgets/SearchBar.vala"
	_tmp13_ = gtk_source_search_context_get_settings (_tmp12_);
#line 219 "../src/Widgets/SearchBar.vala"
	_tmp14_ = _tmp13_;
#line 219 "../src/Widgets/SearchBar.vala"
	gtk_source_search_settings_set_regex_enabled (_tmp14_, FALSE);
#line 220 "../src/Widgets/SearchBar.vala"
	_tmp15_ = self->search_context;
#line 220 "../src/Widgets/SearchBar.vala"
	_tmp16_ = gtk_source_search_context_get_settings (_tmp15_);
#line 220 "../src/Widgets/SearchBar.vala"
	_tmp17_ = _tmp16_;
#line 220 "../src/Widgets/SearchBar.vala"
	_tmp18_ = search_string;
#line 220 "../src/Widgets/SearchBar.vala"
	gtk_source_search_settings_set_search_text (_tmp17_, _tmp18_);
#line 221 "../src/Widgets/SearchBar.vala"
	_tmp20_ = search_string;
#line 221 "../src/Widgets/SearchBar.vala"
	_tmp21_ = g_utf8_strup (_tmp20_, (gssize) -1);
#line 221 "../src/Widgets/SearchBar.vala"
	_tmp22_ = _tmp21_;
#line 221 "../src/Widgets/SearchBar.vala"
	_tmp23_ = search_string;
#line 221 "../src/Widgets/SearchBar.vala"
	_tmp24_ = g_strcmp0 (_tmp22_, _tmp23_) == 0;
#line 221 "../src/Widgets/SearchBar.vala"
	_g_free0 (_tmp22_);
#line 221 "../src/Widgets/SearchBar.vala"
	if (_tmp24_) {
#line 221 "../src/Widgets/SearchBar.vala"
		_tmp19_ = TRUE;
#line 1392 "SearchBar.c"
	} else {
		const gchar* _tmp25_;
		gchar* _tmp26_;
		gchar* _tmp27_;
		const gchar* _tmp28_;
#line 221 "../src/Widgets/SearchBar.vala"
		_tmp25_ = search_string;
#line 221 "../src/Widgets/SearchBar.vala"
		_tmp26_ = g_utf8_strdown (_tmp25_, (gssize) -1);
#line 221 "../src/Widgets/SearchBar.vala"
		_tmp27_ = _tmp26_;
#line 221 "../src/Widgets/SearchBar.vala"
		_tmp28_ = search_string;
#line 221 "../src/Widgets/SearchBar.vala"
		_tmp19_ = g_strcmp0 (_tmp27_, _tmp28_) == 0;
#line 221 "../src/Widgets/SearchBar.vala"
		_g_free0 (_tmp27_);
#line 1410 "SearchBar.c"
	}
#line 221 "../src/Widgets/SearchBar.vala"
	case_sensitive = !_tmp19_;
#line 222 "../src/Widgets/SearchBar.vala"
	_tmp29_ = self->priv->text_view;
#line 222 "../src/Widgets/SearchBar.vala"
	_tmp30_ = _tmp29_->search_context;
#line 222 "../src/Widgets/SearchBar.vala"
	_tmp31_ = gtk_source_search_context_get_settings (_tmp30_);
#line 222 "../src/Widgets/SearchBar.vala"
	_tmp32_ = _tmp31_;
#line 222 "../src/Widgets/SearchBar.vala"
	gtk_source_search_settings_set_case_sensitive (_tmp32_, case_sensitive);
#line 224 "../src/Widgets/SearchBar.vala"
	_tmp34_ = self->priv->text_buffer;
#line 224 "../src/Widgets/SearchBar.vala"
	if (_tmp34_ == NULL) {
#line 224 "../src/Widgets/SearchBar.vala"
		_tmp33_ = TRUE;
#line 1430 "SearchBar.c"
	} else {
		GtkTextBuffer* _tmp35_;
		gchar* _tmp36_;
		gchar* _tmp37_;
		gchar* _tmp38_;
#line 224 "../src/Widgets/SearchBar.vala"
		_tmp35_ = self->priv->text_buffer;
#line 224 "../src/Widgets/SearchBar.vala"
		g_object_get (_tmp35_, "text", &_tmp36_, NULL);
#line 224 "../src/Widgets/SearchBar.vala"
		_tmp37_ = _tmp36_;
#line 224 "../src/Widgets/SearchBar.vala"
		_tmp38_ = _tmp37_;
#line 224 "../src/Widgets/SearchBar.vala"
		_tmp33_ = g_strcmp0 (_tmp38_, "") == 0;
#line 224 "../src/Widgets/SearchBar.vala"
		_g_free0 (_tmp38_);
#line 1448 "SearchBar.c"
	}
#line 224 "../src/Widgets/SearchBar.vala"
	if (_tmp33_) {
#line 225 "../src/Widgets/SearchBar.vala"
		g_warning ("SearchBar.vala:225: Can't search anything in an inexistant buffer and/" \
"or without anything to search.");
#line 226 "../src/Widgets/SearchBar.vala"
		result = FALSE;
#line 226 "../src/Widgets/SearchBar.vala"
		_g_free0 (search_string);
#line 226 "../src/Widgets/SearchBar.vala"
		return result;
#line 1460 "SearchBar.c"
	}
#line 229 "../src/Widgets/SearchBar.vala"
	_tmp39_ = self->priv->text_view;
#line 229 "../src/Widgets/SearchBar.vala"
	if (_tmp39_ == NULL) {
#line 230 "../src/Widgets/SearchBar.vala"
		g_warning ("SearchBar.vala:230: No SourceView is associated with SearchManager!");
#line 231 "../src/Widgets/SearchBar.vala"
		result = FALSE;
#line 231 "../src/Widgets/SearchBar.vala"
		_g_free0 (search_string);
#line 231 "../src/Widgets/SearchBar.vala"
		return result;
#line 1474 "SearchBar.c"
	}
#line 235 "../src/Widgets/SearchBar.vala"
	_tmp40_ = self->priv->text_buffer;
#line 235 "../src/Widgets/SearchBar.vala"
	_tmp41_ = self->priv->text_buffer;
#line 235 "../src/Widgets/SearchBar.vala"
	g_object_get (_tmp41_, "cursor-position", &_tmp42_, NULL);
#line 235 "../src/Widgets/SearchBar.vala"
	_tmp43_ = _tmp42_;
#line 235 "../src/Widgets/SearchBar.vala"
	gtk_text_buffer_get_iter_at_offset (_tmp40_, &_tmp44_, _tmp43_);
#line 235 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (start_iter);
#line 235 "../src/Widgets/SearchBar.vala"
	_tmp45_ = _tmp44_;
#line 235 "../src/Widgets/SearchBar.vala"
	_tmp46_ = __vala_GtkTextIter_copy0 (&_tmp45_);
#line 235 "../src/Widgets/SearchBar.vala"
	start_iter = _tmp46_;
#line 236 "../src/Widgets/SearchBar.vala"
	_tmp48_ = self->search_entry;
#line 236 "../src/Widgets/SearchBar.vala"
	_tmp49_ = gtk_entry_get_text ((GtkEntry*) _tmp48_);
#line 236 "../src/Widgets/SearchBar.vala"
	_tmp50_ = _tmp49_;
#line 236 "../src/Widgets/SearchBar.vala"
	if (g_strcmp0 (_tmp50_, "") != 0) {
#line 1502 "SearchBar.c"
		GtkTextBuffer* _tmp51_;
		gchar* _tmp52_;
		gchar* _tmp53_;
		gchar* _tmp54_;
		GtkSearchEntry* _tmp55_;
		const gchar* _tmp56_;
		const gchar* _tmp57_;
#line 236 "../src/Widgets/SearchBar.vala"
		_tmp51_ = self->priv->text_buffer;
#line 236 "../src/Widgets/SearchBar.vala"
		g_object_get (_tmp51_, "text", &_tmp52_, NULL);
#line 236 "../src/Widgets/SearchBar.vala"
		_tmp53_ = _tmp52_;
#line 236 "../src/Widgets/SearchBar.vala"
		_tmp54_ = _tmp53_;
#line 236 "../src/Widgets/SearchBar.vala"
		_tmp55_ = self->search_entry;
#line 236 "../src/Widgets/SearchBar.vala"
		_tmp56_ = gtk_entry_get_text ((GtkEntry*) _tmp55_);
#line 236 "../src/Widgets/SearchBar.vala"
		_tmp57_ = _tmp56_;
#line 236 "../src/Widgets/SearchBar.vala"
		_tmp47_ = string_contains (_tmp54_, _tmp57_);
#line 236 "../src/Widgets/SearchBar.vala"
		_g_free0 (_tmp54_);
#line 1528 "SearchBar.c"
	} else {
#line 236 "../src/Widgets/SearchBar.vala"
		_tmp47_ = FALSE;
#line 1532 "SearchBar.c"
	}
#line 236 "../src/Widgets/SearchBar.vala"
	found = _tmp47_;
#line 237 "../src/Widgets/SearchBar.vala"
	if (found) {
#line 1538 "SearchBar.c"
		GtkSearchEntry* _tmp58_;
		GtkStyleContext* _tmp59_;
		GtkTextBuffer* _tmp60_;
		GtkTextIter* _tmp61_;
		GtkTextIter* _tmp62_;
		GtkTextIter _tmp63_;
		GtkTextIter _tmp64_;
#line 238 "../src/Widgets/SearchBar.vala"
		_tmp58_ = self->search_entry;
#line 238 "../src/Widgets/SearchBar.vala"
		_tmp59_ = gtk_widget_get_style_context ((GtkWidget*) _tmp58_);
#line 238 "../src/Widgets/SearchBar.vala"
		gtk_style_context_remove_class (_tmp59_, GTK_STYLE_CLASS_ERROR);
#line 239 "../src/Widgets/SearchBar.vala"
		_tmp60_ = self->priv->text_buffer;
#line 239 "../src/Widgets/SearchBar.vala"
		_tmp61_ = start_iter;
#line 239 "../src/Widgets/SearchBar.vala"
		_tmp62_ = start_iter;
#line 239 "../src/Widgets/SearchBar.vala"
		_tmp63_ = *_tmp61_;
#line 239 "../src/Widgets/SearchBar.vala"
		_tmp64_ = *_tmp62_;
#line 239 "../src/Widgets/SearchBar.vala"
		gtk_text_buffer_select_range (_tmp60_, &_tmp63_, &_tmp64_);
#line 1564 "SearchBar.c"
	} else {
		GtkSearchEntry* _tmp65_;
		const gchar* _tmp66_;
		const gchar* _tmp67_;
#line 240 "../src/Widgets/SearchBar.vala"
		_tmp65_ = self->search_entry;
#line 240 "../src/Widgets/SearchBar.vala"
		_tmp66_ = gtk_entry_get_text ((GtkEntry*) _tmp65_);
#line 240 "../src/Widgets/SearchBar.vala"
		_tmp67_ = _tmp66_;
#line 240 "../src/Widgets/SearchBar.vala"
		if (g_strcmp0 (_tmp67_, "") != 0) {
#line 1577 "SearchBar.c"
			GtkSearchEntry* _tmp68_;
			GtkStyleContext* _tmp69_;
#line 241 "../src/Widgets/SearchBar.vala"
			_tmp68_ = self->search_entry;
#line 241 "../src/Widgets/SearchBar.vala"
			_tmp69_ = gtk_widget_get_style_context ((GtkWidget*) _tmp68_);
#line 241 "../src/Widgets/SearchBar.vala"
			gtk_style_context_add_class (_tmp69_, GTK_STYLE_CLASS_ERROR);
#line 1586 "SearchBar.c"
		}
	}
#line 244 "../src/Widgets/SearchBar.vala"
	result = TRUE;
#line 244 "../src/Widgets/SearchBar.vala"
	__vala_GtkTextIter_free0 (start_iter);
#line 244 "../src/Widgets/SearchBar.vala"
	_g_free0 (search_string);
#line 244 "../src/Widgets/SearchBar.vala"
	return result;
#line 1597 "SearchBar.c"
}

QuilterMainWindow*
quilter_widgets_search_bar_get_window (QuilterWidgetsSearchBar* self)
{
	QuilterMainWindow* result;
	QuilterMainWindow* _tmp0_;
#line 31 "../src/Widgets/SearchBar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 31 "../src/Widgets/SearchBar.vala"
	_tmp0_ = self->priv->_window;
#line 31 "../src/Widgets/SearchBar.vala"
	result = _tmp0_;
#line 31 "../src/Widgets/SearchBar.vala"
	return result;
#line 1613 "SearchBar.c"
}

static void
quilter_widgets_search_bar_set_window (QuilterWidgetsSearchBar* self,
                                       QuilterMainWindow* value)
{
#line 31 "../src/Widgets/SearchBar.vala"
	g_return_if_fail (self != NULL);
#line 31 "../src/Widgets/SearchBar.vala"
	if (quilter_widgets_search_bar_get_window (self) != value) {
#line 31 "../src/Widgets/SearchBar.vala"
		self->priv->_window = value;
#line 31 "../src/Widgets/SearchBar.vala"
		g_object_notify_by_pspec ((GObject *) self, quilter_widgets_search_bar_properties[QUILTER_WIDGETS_SEARCH_BAR_WINDOW_PROPERTY]);
#line 1628 "SearchBar.c"
	}
}

static void
_quilter_widgets_search_bar_on_replace_entry_activate_gtk_entry_activate (GtkEntry* _sender,
                                                                          gpointer self)
{
#line 41 "../src/Widgets/SearchBar.vala"
	quilter_widgets_search_bar_on_replace_entry_activate ((QuilterWidgetsSearchBar*) self);
#line 1638 "SearchBar.c"
}

static void
_quilter_widgets_search_bar_on_replace_entry_activate_gtk_button_clicked (GtkButton* _sender,
                                                                          gpointer self)
{
#line 45 "../src/Widgets/SearchBar.vala"
	quilter_widgets_search_bar_on_replace_entry_activate ((QuilterWidgetsSearchBar*) self);
#line 1647 "SearchBar.c"
}

static void
_quilter_widgets_search_bar_on_replace_all_entry_activate_gtk_button_clicked (GtkButton* _sender,
                                                                              gpointer self)
{
#line 51 "../src/Widgets/SearchBar.vala"
	quilter_widgets_search_bar_on_replace_all_entry_activate ((QuilterWidgetsSearchBar*) self);
#line 1656 "SearchBar.c"
}

static GObject *
quilter_widgets_search_bar_constructor (GType type,
                                        guint n_construct_properties,
                                        GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	QuilterWidgetsSearchBar * self;
	GtkEntry* _tmp0_;
	GtkEntry* _tmp1_;
	GtkEntry* _tmp2_;
	GtkEntry* _tmp3_;
	GtkButton* _tmp4_;
	GtkButton* _tmp5_;
	GtkImage* _tmp6_;
	GtkImage* _tmp7_;
	GtkButton* _tmp8_;
	GtkButton* _tmp9_;
	GtkButton* _tmp10_;
	GtkButton* _tmp11_;
	GtkImage* _tmp12_;
	GtkImage* _tmp13_;
	GtkButton* _tmp14_;
	GtkButton* _tmp15_;
	GtkButton* _tmp16_;
	GtkGrid* _tmp17_;
	GtkGrid* _tmp18_;
	GtkGrid* _tmp19_;
	GtkGrid* _tmp20_;
	GtkStyleContext* _tmp21_;
	GtkGrid* _tmp22_;
	GtkGrid* _tmp23_;
	GtkStyleContext* pvcontext = NULL;
	GtkGrid* _tmp24_;
	GtkStyleContext* _tmp25_;
	GtkStyleContext* _tmp26_;
	GtkStyleContext* _tmp27_;
	GtkGrid* _tmp28_;
	GtkGrid* _tmp29_;
	GtkGrid* _tmp30_;
	GtkGrid* _tmp31_;
	GtkStyleContext* rcontext = NULL;
	GtkGrid* _tmp32_;
	GtkStyleContext* _tmp33_;
	GtkStyleContext* _tmp34_;
	GtkStyleContext* _tmp35_;
	GtkGrid* _tmp36_;
	GtkEntry* _tmp37_;
	GtkGrid* _tmp38_;
	GtkButton* _tmp39_;
	GtkGrid* _tmp40_;
	GtkButton* _tmp41_;
	GtkGrid* _tmp42_;
	GtkGrid* _tmp43_;
	GtkStyleContext* context = NULL;
	GtkStyleContext* _tmp44_;
	GtkStyleContext* _tmp45_;
	GtkStyleContext* _tmp46_;
	GtkGrid* _tmp47_;
	QuilterMainWindow* _tmp48_;
	QuilterWidgetsEditView* _tmp49_;
	QuilterWidgetsEditView* _tmp50_;
	QuilterWidgetsEditView* _tmp51_;
	GtkTextBuffer* _tmp52_;
	GtkTextBuffer* _tmp53_;
	GSettings* _tmp54_;
#line 37 "../src/Widgets/SearchBar.vala"
	parent_class = G_OBJECT_CLASS (quilter_widgets_search_bar_parent_class);
#line 37 "../src/Widgets/SearchBar.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 37 "../src/Widgets/SearchBar.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_WIDGETS_TYPE_SEARCH_BAR, QuilterWidgetsSearchBar);
#line 38 "../src/Widgets/SearchBar.vala"
	_tmp0_ = (GtkEntry*) gtk_entry_new ();
#line 38 "../src/Widgets/SearchBar.vala"
	g_object_ref_sink (_tmp0_);
#line 38 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->replace_entry);
#line 38 "../src/Widgets/SearchBar.vala"
	self->replace_entry = _tmp0_;
#line 39 "../src/Widgets/SearchBar.vala"
	_tmp1_ = self->replace_entry;
#line 39 "../src/Widgets/SearchBar.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp1_, TRUE);
#line 40 "../src/Widgets/SearchBar.vala"
	_tmp2_ = self->replace_entry;
#line 40 "../src/Widgets/SearchBar.vala"
	gtk_entry_set_placeholder_text (_tmp2_, _ ("Replace with…"));
#line 41 "../src/Widgets/SearchBar.vala"
	_tmp3_ = self->replace_entry;
#line 41 "../src/Widgets/SearchBar.vala"
	g_signal_connect_object (_tmp3_, "activate", (GCallback) _quilter_widgets_search_bar_on_replace_entry_activate_gtk_entry_activate, self, 0);
#line 43 "../src/Widgets/SearchBar.vala"
	_tmp4_ = (GtkButton*) gtk_button_new ();
#line 43 "../src/Widgets/SearchBar.vala"
	g_object_ref_sink (_tmp4_);
#line 43 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->replace_tool_button);
#line 43 "../src/Widgets/SearchBar.vala"
	self->priv->replace_tool_button = _tmp4_;
#line 44 "../src/Widgets/SearchBar.vala"
	_tmp5_ = self->priv->replace_tool_button;
#line 44 "../src/Widgets/SearchBar.vala"
	_tmp6_ = (GtkImage*) gtk_image_new_from_icon_name ("edit-find-replace-symbolic", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
#line 44 "../src/Widgets/SearchBar.vala"
	g_object_ref_sink (_tmp6_);
#line 44 "../src/Widgets/SearchBar.vala"
	_tmp7_ = _tmp6_;
#line 44 "../src/Widgets/SearchBar.vala"
	gtk_button_set_image (_tmp5_, (GtkWidget*) _tmp7_);
#line 44 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (_tmp7_);
#line 45 "../src/Widgets/SearchBar.vala"
	_tmp8_ = self->priv->replace_tool_button;
#line 45 "../src/Widgets/SearchBar.vala"
	g_signal_connect_object (_tmp8_, "clicked", (GCallback) _quilter_widgets_search_bar_on_replace_entry_activate_gtk_button_clicked, self, 0);
#line 46 "../src/Widgets/SearchBar.vala"
	_tmp9_ = self->priv->replace_tool_button;
#line 46 "../src/Widgets/SearchBar.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp9_, _ ("Replace\nUse arrows before using."));
#line 48 "../src/Widgets/SearchBar.vala"
	_tmp10_ = (GtkButton*) gtk_button_new ();
#line 48 "../src/Widgets/SearchBar.vala"
	g_object_ref_sink (_tmp10_);
#line 48 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->replace_all_tool_button);
#line 48 "../src/Widgets/SearchBar.vala"
	self->priv->replace_all_tool_button = _tmp10_;
#line 49 "../src/Widgets/SearchBar.vala"
	_tmp11_ = self->priv->replace_all_tool_button;
#line 49 "../src/Widgets/SearchBar.vala"
	_tmp12_ = (GtkImage*) gtk_image_new_from_icon_name ("edit-find-replace-all-symbolic", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
#line 49 "../src/Widgets/SearchBar.vala"
	g_object_ref_sink (_tmp12_);
#line 49 "../src/Widgets/SearchBar.vala"
	_tmp13_ = _tmp12_;
#line 49 "../src/Widgets/SearchBar.vala"
	gtk_button_set_image (_tmp11_, (GtkWidget*) _tmp13_);
#line 49 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (_tmp13_);
#line 50 "../src/Widgets/SearchBar.vala"
	_tmp14_ = self->priv->replace_all_tool_button;
#line 50 "../src/Widgets/SearchBar.vala"
	gtk_button_set_always_show_image (_tmp14_, TRUE);
#line 51 "../src/Widgets/SearchBar.vala"
	_tmp15_ = self->priv->replace_all_tool_button;
#line 51 "../src/Widgets/SearchBar.vala"
	g_signal_connect_object (_tmp15_, "clicked", (GCallback) _quilter_widgets_search_bar_on_replace_all_entry_activate_gtk_button_clicked, self, 0);
#line 52 "../src/Widgets/SearchBar.vala"
	_tmp16_ = self->priv->replace_all_tool_button;
#line 52 "../src/Widgets/SearchBar.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp16_, _ ("Replace All"));
#line 54 "../src/Widgets/SearchBar.vala"
	_tmp17_ = (GtkGrid*) gtk_grid_new ();
#line 54 "../src/Widgets/SearchBar.vala"
	g_object_ref_sink (_tmp17_);
#line 54 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->grid);
#line 54 "../src/Widgets/SearchBar.vala"
	self->grid = _tmp17_;
#line 55 "../src/Widgets/SearchBar.vala"
	_tmp18_ = self->grid;
#line 55 "../src/Widgets/SearchBar.vala"
	gtk_orientable_set_orientation ((GtkOrientable*) _tmp18_, GTK_ORIENTATION_VERTICAL);
#line 56 "../src/Widgets/SearchBar.vala"
	_tmp19_ = self->grid;
#line 56 "../src/Widgets/SearchBar.vala"
	gtk_grid_set_row_spacing (_tmp19_, 6);
#line 57 "../src/Widgets/SearchBar.vala"
	_tmp20_ = self->grid;
#line 57 "../src/Widgets/SearchBar.vala"
	_tmp21_ = gtk_widget_get_style_context ((GtkWidget*) _tmp20_);
#line 57 "../src/Widgets/SearchBar.vala"
	gtk_style_context_add_class (_tmp21_, GTK_STYLE_CLASS_LINKED);
#line 59 "../src/Widgets/SearchBar.vala"
	_tmp22_ = (GtkGrid*) gtk_grid_new ();
#line 59 "../src/Widgets/SearchBar.vala"
	g_object_ref_sink (_tmp22_);
#line 59 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->prev_next_grid);
#line 59 "../src/Widgets/SearchBar.vala"
	self->prev_next_grid = _tmp22_;
#line 60 "../src/Widgets/SearchBar.vala"
	_tmp23_ = self->prev_next_grid;
#line 60 "../src/Widgets/SearchBar.vala"
	gtk_grid_set_row_spacing (_tmp23_, 6);
#line 61 "../src/Widgets/SearchBar.vala"
	_tmp24_ = self->prev_next_grid;
#line 61 "../src/Widgets/SearchBar.vala"
	_tmp25_ = gtk_widget_get_style_context ((GtkWidget*) _tmp24_);
#line 61 "../src/Widgets/SearchBar.vala"
	_tmp26_ = _g_object_ref0 (_tmp25_);
#line 61 "../src/Widgets/SearchBar.vala"
	pvcontext = _tmp26_;
#line 62 "../src/Widgets/SearchBar.vala"
	_tmp27_ = pvcontext;
#line 62 "../src/Widgets/SearchBar.vala"
	gtk_style_context_add_class (_tmp27_, GTK_STYLE_CLASS_LINKED);
#line 63 "../src/Widgets/SearchBar.vala"
	quilter_widgets_search_bar_search_entry_item (self);
#line 64 "../src/Widgets/SearchBar.vala"
	quilter_widgets_search_bar_search_previous_item (self);
#line 65 "../src/Widgets/SearchBar.vala"
	quilter_widgets_search_bar_search_next_item (self);
#line 67 "../src/Widgets/SearchBar.vala"
	_tmp28_ = self->grid;
#line 67 "../src/Widgets/SearchBar.vala"
	_tmp29_ = self->prev_next_grid;
#line 67 "../src/Widgets/SearchBar.vala"
	gtk_grid_attach (_tmp28_, (GtkWidget*) _tmp29_, 0, 0, 1, 1);
#line 69 "../src/Widgets/SearchBar.vala"
	_tmp30_ = (GtkGrid*) gtk_grid_new ();
#line 69 "../src/Widgets/SearchBar.vala"
	g_object_ref_sink (_tmp30_);
#line 69 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->replace_grid);
#line 69 "../src/Widgets/SearchBar.vala"
	self->replace_grid = _tmp30_;
#line 70 "../src/Widgets/SearchBar.vala"
	_tmp31_ = self->replace_grid;
#line 70 "../src/Widgets/SearchBar.vala"
	gtk_grid_set_row_spacing (_tmp31_, 6);
#line 71 "../src/Widgets/SearchBar.vala"
	_tmp32_ = self->replace_grid;
#line 71 "../src/Widgets/SearchBar.vala"
	_tmp33_ = gtk_widget_get_style_context ((GtkWidget*) _tmp32_);
#line 71 "../src/Widgets/SearchBar.vala"
	_tmp34_ = _g_object_ref0 (_tmp33_);
#line 71 "../src/Widgets/SearchBar.vala"
	rcontext = _tmp34_;
#line 72 "../src/Widgets/SearchBar.vala"
	_tmp35_ = rcontext;
#line 72 "../src/Widgets/SearchBar.vala"
	gtk_style_context_add_class (_tmp35_, GTK_STYLE_CLASS_LINKED);
#line 73 "../src/Widgets/SearchBar.vala"
	_tmp36_ = self->replace_grid;
#line 73 "../src/Widgets/SearchBar.vala"
	_tmp37_ = self->replace_entry;
#line 73 "../src/Widgets/SearchBar.vala"
	gtk_container_add ((GtkContainer*) _tmp36_, (GtkWidget*) _tmp37_);
#line 74 "../src/Widgets/SearchBar.vala"
	_tmp38_ = self->replace_grid;
#line 74 "../src/Widgets/SearchBar.vala"
	_tmp39_ = self->priv->replace_tool_button;
#line 74 "../src/Widgets/SearchBar.vala"
	gtk_container_add ((GtkContainer*) _tmp38_, (GtkWidget*) _tmp39_);
#line 75 "../src/Widgets/SearchBar.vala"
	_tmp40_ = self->replace_grid;
#line 75 "../src/Widgets/SearchBar.vala"
	_tmp41_ = self->priv->replace_all_tool_button;
#line 75 "../src/Widgets/SearchBar.vala"
	gtk_container_add ((GtkContainer*) _tmp40_, (GtkWidget*) _tmp41_);
#line 77 "../src/Widgets/SearchBar.vala"
	_tmp42_ = self->grid;
#line 77 "../src/Widgets/SearchBar.vala"
	_tmp43_ = self->replace_grid;
#line 77 "../src/Widgets/SearchBar.vala"
	gtk_grid_attach (_tmp42_, (GtkWidget*) _tmp43_, 0, 1, 1, 1);
#line 79 "../src/Widgets/SearchBar.vala"
	_tmp44_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 79 "../src/Widgets/SearchBar.vala"
	_tmp45_ = _g_object_ref0 (_tmp44_);
#line 79 "../src/Widgets/SearchBar.vala"
	context = _tmp45_;
#line 80 "../src/Widgets/SearchBar.vala"
	_tmp46_ = context;
#line 80 "../src/Widgets/SearchBar.vala"
	gtk_style_context_add_class (_tmp46_, "quilter-searchbar");
#line 82 "../src/Widgets/SearchBar.vala"
	_tmp47_ = self->grid;
#line 82 "../src/Widgets/SearchBar.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp47_);
#line 83 "../src/Widgets/SearchBar.vala"
	_tmp48_ = self->priv->_window;
#line 83 "../src/Widgets/SearchBar.vala"
	_tmp49_ = _tmp48_->edit_view_content;
#line 83 "../src/Widgets/SearchBar.vala"
	_tmp50_ = _g_object_ref0 (_tmp49_);
#line 83 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_view);
#line 83 "../src/Widgets/SearchBar.vala"
	self->priv->text_view = _tmp50_;
#line 84 "../src/Widgets/SearchBar.vala"
	_tmp51_ = self->priv->text_view;
#line 84 "../src/Widgets/SearchBar.vala"
	_tmp52_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp51_);
#line 84 "../src/Widgets/SearchBar.vala"
	_tmp53_ = _g_object_ref0 (_tmp52_);
#line 84 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_buffer);
#line 84 "../src/Widgets/SearchBar.vala"
	self->priv->text_buffer = _tmp53_;
#line 85 "../src/Widgets/SearchBar.vala"
	_tmp54_ = quilter_application_gsettings;
#line 85 "../src/Widgets/SearchBar.vala"
	gtk_search_bar_set_search_mode ((GtkSearchBar*) self, g_settings_get_boolean (_tmp54_, "searchbar"));
#line 37 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (context);
#line 37 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (rcontext);
#line 37 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (pvcontext);
#line 37 "../src/Widgets/SearchBar.vala"
	return obj;
#line 1963 "SearchBar.c"
}

static void
quilter_widgets_search_bar_class_init (QuilterWidgetsSearchBarClass * klass,
                                       gpointer klass_data)
{
#line 20 "../src/Widgets/SearchBar.vala"
	quilter_widgets_search_bar_parent_class = g_type_class_peek_parent (klass);
#line 20 "../src/Widgets/SearchBar.vala"
	g_type_class_adjust_private_offset (klass, &QuilterWidgetsSearchBar_private_offset);
#line 20 "../src/Widgets/SearchBar.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_quilter_widgets_search_bar_get_property;
#line 20 "../src/Widgets/SearchBar.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_quilter_widgets_search_bar_set_property;
#line 20 "../src/Widgets/SearchBar.vala"
	G_OBJECT_CLASS (klass)->constructor = quilter_widgets_search_bar_constructor;
#line 20 "../src/Widgets/SearchBar.vala"
	G_OBJECT_CLASS (klass)->finalize = quilter_widgets_search_bar_finalize;
#line 20 "../src/Widgets/SearchBar.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), QUILTER_WIDGETS_SEARCH_BAR_WINDOW_PROPERTY, quilter_widgets_search_bar_properties[QUILTER_WIDGETS_SEARCH_BAR_WINDOW_PROPERTY] = g_param_spec_object ("window", "window", "window", QUILTER_TYPE_MAIN_WINDOW, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 1984 "SearchBar.c"
}

static void
quilter_widgets_search_bar_instance_init (QuilterWidgetsSearchBar * self,
                                          gpointer klass)
{
#line 20 "../src/Widgets/SearchBar.vala"
	self->priv = quilter_widgets_search_bar_get_instance_private (self);
#line 21 "../src/Widgets/SearchBar.vala"
	self->priv->text_view = NULL;
#line 24 "../src/Widgets/SearchBar.vala"
	self->priv->text_buffer = NULL;
#line 30 "../src/Widgets/SearchBar.vala"
	self->search_context = NULL;
#line 1999 "SearchBar.c"
}

static void
quilter_widgets_search_bar_finalize (GObject * obj)
{
	QuilterWidgetsSearchBar * self;
#line 20 "../src/Widgets/SearchBar.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_WIDGETS_TYPE_SEARCH_BAR, QuilterWidgetsSearchBar);
#line 21 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_view);
#line 22 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->replace_all_tool_button);
#line 23 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->replace_tool_button);
#line 24 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->priv->text_buffer);
#line 25 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->grid);
#line 26 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->prev_next_grid);
#line 27 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->replace_grid);
#line 28 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->replace_entry);
#line 29 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->search_entry);
#line 30 "../src/Widgets/SearchBar.vala"
	_g_object_unref0 (self->search_context);
#line 20 "../src/Widgets/SearchBar.vala"
	G_OBJECT_CLASS (quilter_widgets_search_bar_parent_class)->finalize (obj);
#line 2030 "SearchBar.c"
}

static GType
quilter_widgets_search_bar_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (QuilterWidgetsSearchBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_widgets_search_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterWidgetsSearchBar), 0, (GInstanceInitFunc) quilter_widgets_search_bar_instance_init, NULL };
	GType quilter_widgets_search_bar_type_id;
	quilter_widgets_search_bar_type_id = g_type_register_static (gtk_search_bar_get_type (), "QuilterWidgetsSearchBar", &g_define_type_info, 0);
	QuilterWidgetsSearchBar_private_offset = g_type_add_instance_private (quilter_widgets_search_bar_type_id, sizeof (QuilterWidgetsSearchBarPrivate));
	return quilter_widgets_search_bar_type_id;
}

GType
quilter_widgets_search_bar_get_type (void)
{
	static volatile gsize quilter_widgets_search_bar_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_widgets_search_bar_type_id__volatile)) {
		GType quilter_widgets_search_bar_type_id;
		quilter_widgets_search_bar_type_id = quilter_widgets_search_bar_get_type_once ();
		g_once_init_leave (&quilter_widgets_search_bar_type_id__volatile, quilter_widgets_search_bar_type_id);
	}
	return quilter_widgets_search_bar_type_id__volatile;
}

static void
_vala_quilter_widgets_search_bar_get_property (GObject * object,
                                               guint property_id,
                                               GValue * value,
                                               GParamSpec * pspec)
{
	QuilterWidgetsSearchBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QUILTER_WIDGETS_TYPE_SEARCH_BAR, QuilterWidgetsSearchBar);
#line 20 "../src/Widgets/SearchBar.vala"
	switch (property_id) {
#line 20 "../src/Widgets/SearchBar.vala"
		case QUILTER_WIDGETS_SEARCH_BAR_WINDOW_PROPERTY:
#line 20 "../src/Widgets/SearchBar.vala"
		g_value_set_object (value, quilter_widgets_search_bar_get_window (self));
#line 20 "../src/Widgets/SearchBar.vala"
		break;
#line 2071 "SearchBar.c"
		default:
#line 20 "../src/Widgets/SearchBar.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "../src/Widgets/SearchBar.vala"
		break;
#line 2077 "SearchBar.c"
	}
}

static void
_vala_quilter_widgets_search_bar_set_property (GObject * object,
                                               guint property_id,
                                               const GValue * value,
                                               GParamSpec * pspec)
{
	QuilterWidgetsSearchBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QUILTER_WIDGETS_TYPE_SEARCH_BAR, QuilterWidgetsSearchBar);
#line 20 "../src/Widgets/SearchBar.vala"
	switch (property_id) {
#line 20 "../src/Widgets/SearchBar.vala"
		case QUILTER_WIDGETS_SEARCH_BAR_WINDOW_PROPERTY:
#line 20 "../src/Widgets/SearchBar.vala"
		quilter_widgets_search_bar_set_window (self, g_value_get_object (value));
#line 20 "../src/Widgets/SearchBar.vala"
		break;
#line 2097 "SearchBar.c"
		default:
#line 20 "../src/Widgets/SearchBar.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "../src/Widgets/SearchBar.vala"
		break;
#line 2103 "SearchBar.c"
	}
}

