/* SideBarBox.c generated by valac 0.50.2, the Vala compiler
 * generated from SideBarBox.vala, do not modify */

/*
* Copyright (c) 2018-2021 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <gtk/gtk.h>
#include <glib-object.h>
#include <gtksourceview/gtksource.h>
#include <handy.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>
#include <glib/gi18n-lib.h>
#include <webkit2/webkit2.h>
#include <gee.h>
#include <gio/gio.h>
#include <float.h>
#include <math.h>

#define QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX (quilter_widgets_side_bar_box_get_type ())
#define QUILTER_WIDGETS_SIDE_BAR_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX, QuilterWidgetsSideBarBox))
#define QUILTER_WIDGETS_SIDE_BAR_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX, QuilterWidgetsSideBarBoxClass))
#define QUILTER_WIDGETS_IS_SIDE_BAR_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX))
#define QUILTER_WIDGETS_IS_SIDE_BAR_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX))
#define QUILTER_WIDGETS_SIDE_BAR_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX, QuilterWidgetsSideBarBoxClass))

typedef struct _QuilterWidgetsSideBarBox QuilterWidgetsSideBarBox;
typedef struct _QuilterWidgetsSideBarBoxClass QuilterWidgetsSideBarBoxClass;
typedef struct _QuilterWidgetsSideBarBoxPrivate QuilterWidgetsSideBarBoxPrivate;

#define QUILTER_WIDGETS_TYPE_EDIT_VIEW (quilter_widgets_edit_view_get_type ())
#define QUILTER_WIDGETS_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_EDIT_VIEW, QuilterWidgetsEditView))
#define QUILTER_WIDGETS_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_EDIT_VIEW, QuilterWidgetsEditViewClass))
#define QUILTER_WIDGETS_IS_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_EDIT_VIEW))
#define QUILTER_WIDGETS_IS_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_EDIT_VIEW))
#define QUILTER_WIDGETS_EDIT_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_EDIT_VIEW, QuilterWidgetsEditViewClass))

typedef struct _QuilterWidgetsEditView QuilterWidgetsEditView;
typedef struct _QuilterWidgetsEditViewClass QuilterWidgetsEditViewClass;

#define QUILTER_TYPE_MAIN_WINDOW (quilter_main_window_get_type ())
#define QUILTER_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindow))
#define QUILTER_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindowClass))
#define QUILTER_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_MAIN_WINDOW))
#define QUILTER_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_MAIN_WINDOW))
#define QUILTER_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindowClass))

typedef struct _QuilterMainWindow QuilterMainWindow;
typedef struct _QuilterMainWindowClass QuilterMainWindowClass;
enum  {
	QUILTER_WIDGETS_SIDE_BAR_BOX_0_PROPERTY,
	QUILTER_WIDGETS_SIDE_BAR_BOX_PATH_PROPERTY,
	QUILTER_WIDGETS_SIDE_BAR_BOX_TITLE_PROPERTY,
	QUILTER_WIDGETS_SIDE_BAR_BOX_NUM_PROPERTIES
};
static GParamSpec* quilter_widgets_side_bar_box_properties[QUILTER_WIDGETS_SIDE_BAR_BOX_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block3Data Block3Data;
typedef struct _QuilterMainWindowPrivate QuilterMainWindowPrivate;

#define QUILTER_WIDGETS_TYPE_HEADERBAR (quilter_widgets_headerbar_get_type ())
#define QUILTER_WIDGETS_HEADERBAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_HEADERBAR, QuilterWidgetsHeaderbar))
#define QUILTER_WIDGETS_HEADERBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_HEADERBAR, QuilterWidgetsHeaderbarClass))
#define QUILTER_WIDGETS_IS_HEADERBAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_HEADERBAR))
#define QUILTER_WIDGETS_IS_HEADERBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_HEADERBAR))
#define QUILTER_WIDGETS_HEADERBAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_HEADERBAR, QuilterWidgetsHeaderbarClass))

typedef struct _QuilterWidgetsHeaderbar QuilterWidgetsHeaderbar;
typedef struct _QuilterWidgetsHeaderbarClass QuilterWidgetsHeaderbarClass;

#define QUILTER_WIDGETS_TYPE_PREVIEW (quilter_widgets_preview_get_type ())
#define QUILTER_WIDGETS_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_PREVIEW, QuilterWidgetsPreview))
#define QUILTER_WIDGETS_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_PREVIEW, QuilterWidgetsPreviewClass))
#define QUILTER_WIDGETS_IS_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_PREVIEW))
#define QUILTER_WIDGETS_IS_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_PREVIEW))
#define QUILTER_WIDGETS_PREVIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_PREVIEW, QuilterWidgetsPreviewClass))

typedef struct _QuilterWidgetsPreview QuilterWidgetsPreview;
typedef struct _QuilterWidgetsPreviewClass QuilterWidgetsPreviewClass;

#define QUILTER_WIDGETS_TYPE_SEARCH_BAR (quilter_widgets_search_bar_get_type ())
#define QUILTER_WIDGETS_SEARCH_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_SEARCH_BAR, QuilterWidgetsSearchBar))
#define QUILTER_WIDGETS_SEARCH_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_SEARCH_BAR, QuilterWidgetsSearchBarClass))
#define QUILTER_WIDGETS_IS_SEARCH_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_SEARCH_BAR))
#define QUILTER_WIDGETS_IS_SEARCH_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_SEARCH_BAR))
#define QUILTER_WIDGETS_SEARCH_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_SEARCH_BAR, QuilterWidgetsSearchBarClass))

typedef struct _QuilterWidgetsSearchBar QuilterWidgetsSearchBar;
typedef struct _QuilterWidgetsSearchBarClass QuilterWidgetsSearchBarClass;

#define QUILTER_WIDGETS_TYPE_SIDE_BAR (quilter_widgets_side_bar_get_type ())
#define QUILTER_WIDGETS_SIDE_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_SIDE_BAR, QuilterWidgetsSideBar))
#define QUILTER_WIDGETS_SIDE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_SIDE_BAR, QuilterWidgetsSideBarClass))
#define QUILTER_WIDGETS_IS_SIDE_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_SIDE_BAR))
#define QUILTER_WIDGETS_IS_SIDE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_SIDE_BAR))
#define QUILTER_WIDGETS_SIDE_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_SIDE_BAR, QuilterWidgetsSideBarClass))

typedef struct _QuilterWidgetsSideBar QuilterWidgetsSideBar;
typedef struct _QuilterWidgetsSideBarClass QuilterWidgetsSideBarClass;

#define QUILTER_WIDGETS_TYPE_STATUS_BAR (quilter_widgets_status_bar_get_type ())
#define QUILTER_WIDGETS_STATUS_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_STATUS_BAR, QuilterWidgetsStatusBar))
#define QUILTER_WIDGETS_STATUS_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_STATUS_BAR, QuilterWidgetsStatusBarClass))
#define QUILTER_WIDGETS_IS_STATUS_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_STATUS_BAR))
#define QUILTER_WIDGETS_IS_STATUS_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_STATUS_BAR))
#define QUILTER_WIDGETS_STATUS_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_STATUS_BAR, QuilterWidgetsStatusBarClass))

typedef struct _QuilterWidgetsStatusBar QuilterWidgetsStatusBar;
typedef struct _QuilterWidgetsStatusBarClass QuilterWidgetsStatusBarClass;
typedef struct _QuilterWidgetsSideBarPrivate QuilterWidgetsSideBarPrivate;
typedef struct _QuilterWidgetsEditViewPrivate QuilterWidgetsEditViewPrivate;

#define QUILTER_SERVICES_TYPE_POS_FILES (quilter_services_pos_files_get_type ())
#define QUILTER_SERVICES_POS_FILES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_SERVICES_TYPE_POS_FILES, QuilterServicesPOSFiles))
#define QUILTER_SERVICES_POS_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_SERVICES_TYPE_POS_FILES, QuilterServicesPOSFilesClass))
#define QUILTER_SERVICES_IS_POS_FILES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_SERVICES_TYPE_POS_FILES))
#define QUILTER_SERVICES_IS_POS_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_SERVICES_TYPE_POS_FILES))
#define QUILTER_SERVICES_POS_FILES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_SERVICES_TYPE_POS_FILES, QuilterServicesPOSFilesClass))

typedef struct _QuilterServicesPOSFiles QuilterServicesPOSFiles;
typedef struct _QuilterServicesPOSFilesClass QuilterServicesPOSFilesClass;
enum  {
	QUILTER_WIDGETS_SIDE_BAR_BOX_SAVE_AS_SIGNAL,
	QUILTER_WIDGETS_SIDE_BAR_BOX_NUM_SIGNALS
};
static guint quilter_widgets_side_bar_box_signals[QUILTER_WIDGETS_SIDE_BAR_BOX_NUM_SIGNALS] = {0};

struct _QuilterWidgetsSideBarBox {
	GtkListBoxRow parent_instance;
	QuilterWidgetsSideBarBoxPrivate * priv;
	QuilterWidgetsEditView* ev;
	GtkButton* file_remove_button;
	GtkGrid* file_grid;
	QuilterMainWindow* win;
	gint uid;
};

struct _QuilterWidgetsSideBarBoxClass {
	GtkListBoxRowClass parent_class;
};

struct _QuilterWidgetsSideBarBoxPrivate {
	GtkLabel* file_label;
	GtkLabel* file_name_label;
	gchar* _path;
};

struct _Block3Data {
	int _ref_count_;
	QuilterWidgetsSideBarBox* self;
	QuilterMainWindow* win;
};

struct _QuilterMainWindow {
	HdyApplicationWindow parent_instance;
	QuilterMainWindowPrivate * priv;
	GtkAdjustment* eadj;
	GtkBox* box;
	GtkBox* main_leaf;
	GtkOverlay* overlay_editor;
	GtkButton* focus_overlay_button;
	HdyLeaflet* grid;
	HdyLeaflet* header;
	HdyTitleBar* window_header;
	HdyHeaderBar* welcome_titlebar;
	GtkGrid* main_pane;
	GtkGrid* welcome_view;
	GtkMenuButton* set_font_menu;
	GtkPaned* paned;
	GtkRevealer* titlebar_revealer;
	GtkRevealer* overlay_button_revealer;
	GtkScrolledWindow* edit_view;
	GtkStack* main_stack;
	GtkStack* stack;
	GtkStack* titlebar_stack;
	GtkStack* win_stack;
	GtkSeparator* separator;
	GtkSeparator* separator2;
	QuilterWidgetsEditView* edit_view_content;
	QuilterWidgetsHeaderbar* titlebar;
	QuilterWidgetsPreview* preview_view_content;
	QuilterWidgetsSearchBar* searchbar;
	QuilterWidgetsSideBar* sidebar;
	QuilterWidgetsStatusBar* statusbar;
};

struct _QuilterMainWindowClass {
	HdyApplicationWindowClass parent_class;
};

struct _QuilterWidgetsSideBar {
	GtkRevealer parent_instance;
	QuilterWidgetsSideBarPrivate * priv;
	GtkListBox* column;
	QuilterWidgetsSideBarBox* row;
	QuilterWidgetsSideBarBox* filebox;
	QuilterWidgetsEditView* ev;
	QuilterWidgetsSearchBar* seb;
	QuilterMainWindow* win;
	GtkGrid* files_grid;
	GtkGrid* outline_grid;
	GtkStack* stack;
	GtkTreeStore* store;
	GtkTreeView* view;
	GtkTreeSelection* selection;
	GtkCellRendererText* crt;
	HdyViewSwitcher* stackswitcher;
	GtkScrolledWindow* scrolled_box;
	HdyHeaderBar* header;
	GeeLinkedList* s_files;
};

struct _QuilterWidgetsSideBarClass {
	GtkRevealerClass parent_class;
};

struct _QuilterWidgetsEditView {
	GtkSourceView parent_instance;
	QuilterWidgetsEditViewPrivate * priv;
	GFile* file;
	GtkSourceSearchContext* search_context;
	GtkSourceStyle* srcstyle;
	GtkTextTag* adjfont;
	GtkTextTag* adverbfont;
	GtkTextTag* conjfont;
	GtkTextTag* verbfont;
	GtkTextTag* error_tag;
	QuilterMainWindow* window;
	QuilterServicesPOSFiles* pos;
	gdouble cursor_position;
	GtkSourceBuffer* buffer;
	gchar* scroll_text;
};

struct _QuilterWidgetsEditViewClass {
	GtkSourceViewClass parent_class;
};

static gint QuilterWidgetsSideBarBox_private_offset;
static gpointer quilter_widgets_side_bar_box_parent_class = NULL;
static gint quilter_widgets_side_bar_box_uid_counter;
static gint quilter_widgets_side_bar_box_uid_counter = 0;
extern GSettings* quilter_application_gsettings;

GType quilter_widgets_side_bar_box_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsSideBarBox, g_object_unref)
GType quilter_widgets_edit_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsEditView, g_object_unref)
GType quilter_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterMainWindow, g_object_unref)
QuilterWidgetsSideBarBox* quilter_widgets_side_bar_box_new (QuilterMainWindow* win,
                                                            const gchar* path);
QuilterWidgetsSideBarBox* quilter_widgets_side_bar_box_construct (GType object_type,
                                                                  QuilterMainWindow* win,
                                                                  const gchar* path);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
static void __lambda7_ (Block3Data* _data3_);
GType quilter_widgets_headerbar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsHeaderbar, g_object_unref)
GType quilter_widgets_preview_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsPreview, g_object_unref)
GType quilter_widgets_search_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsSearchBar, g_object_unref)
GType quilter_widgets_side_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsSideBar, g_object_unref)
GType quilter_widgets_status_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsStatusBar, g_object_unref)
gpointer quilter_services_pos_files_ref (gpointer instance);
void quilter_services_pos_files_unref (gpointer instance);
GParamSpec* quilter_services_param_spec_pos_files (const gchar* name,
                                                   const gchar* nick,
                                                   const gchar* blurb,
                                                   GType object_type,
                                                   GParamFlags flags);
void quilter_services_value_set_pos_files (GValue* value,
                                           gpointer v_object);
void quilter_services_value_take_pos_files (GValue* value,
                                            gpointer v_object);
gpointer quilter_services_value_get_pos_files (const GValue* value);
GType quilter_services_pos_files_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterServicesPOSFiles, quilter_services_pos_files_unref)
void quilter_widgets_edit_view_set_modified (QuilterWidgetsEditView* self,
                                             gboolean value);
void quilter_main_window_save_last_files (QuilterMainWindow* self);
static void ___lambda7__gtk_button_clicked (GtkButton* _sender,
                                     gpointer self);
void quilter_widgets_side_bar_box_set_path (QuilterWidgetsSideBarBox* self,
                                            const gchar* value);
gchar* quilter_widgets_side_bar_box_get_path (QuilterWidgetsSideBarBox* self);
gboolean quilter_services_file_manager_is_temp_file (const gchar* path);
gchar* quilter_widgets_side_bar_box_get_title (QuilterWidgetsSideBarBox* self);
void quilter_widgets_side_bar_box_set_title (QuilterWidgetsSideBarBox* self,
                                             const gchar* value);
static void quilter_widgets_side_bar_box_finalize (GObject * obj);
static GType quilter_widgets_side_bar_box_get_type_once (void);
static void _vala_quilter_widgets_side_bar_box_get_property (GObject * object,
                                                      guint property_id,
                                                      GValue * value,
                                                      GParamSpec * pspec);
static void _vala_quilter_widgets_side_bar_box_set_property (GObject * object,
                                                      guint property_id,
                                                      const GValue * value,
                                                      GParamSpec * pspec);

static inline gpointer
quilter_widgets_side_bar_box_get_instance_private (QuilterWidgetsSideBarBox* self)
{
	return G_STRUCT_MEMBER_P (self, QuilterWidgetsSideBarBox_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 60 "../src/Widgets/SideBarBox.vala"
	return self ? g_object_ref (self) : NULL;
#line 337 "SideBarBox.c"
}

static Block3Data*
block3_data_ref (Block3Data* _data3_)
{
#line 60 "../src/Widgets/SideBarBox.vala"
	g_atomic_int_inc (&_data3_->_ref_count_);
#line 60 "../src/Widgets/SideBarBox.vala"
	return _data3_;
#line 347 "SideBarBox.c"
}

static void
block3_data_unref (void * _userdata_)
{
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
#line 60 "../src/Widgets/SideBarBox.vala"
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
#line 357 "SideBarBox.c"
		QuilterWidgetsSideBarBox* self;
#line 60 "../src/Widgets/SideBarBox.vala"
		self = _data3_->self;
#line 60 "../src/Widgets/SideBarBox.vala"
		_g_object_unref0 (_data3_->win);
#line 60 "../src/Widgets/SideBarBox.vala"
		_g_object_unref0 (self);
#line 60 "../src/Widgets/SideBarBox.vala"
		g_slice_free (Block3Data, _data3_);
#line 367 "SideBarBox.c"
	}
}

static void
__lambda7_ (Block3Data* _data3_)
{
	QuilterWidgetsSideBarBox* self;
	gboolean _tmp0_ = FALSE;
	GtkStack* _tmp1_;
#line 91 "../src/Widgets/SideBarBox.vala"
	self = _data3_->self;
#line 92 "../src/Widgets/SideBarBox.vala"
	_tmp1_ = _data3_->win->win_stack;
#line 92 "../src/Widgets/SideBarBox.vala"
	if (_tmp1_ != NULL) {
#line 383 "SideBarBox.c"
		GtkStack* _tmp2_;
#line 92 "../src/Widgets/SideBarBox.vala"
		_tmp2_ = _data3_->win->titlebar_stack;
#line 92 "../src/Widgets/SideBarBox.vala"
		_tmp0_ = _tmp2_ != NULL;
#line 389 "SideBarBox.c"
	} else {
#line 92 "../src/Widgets/SideBarBox.vala"
		_tmp0_ = FALSE;
#line 393 "SideBarBox.c"
	}
#line 92 "../src/Widgets/SideBarBox.vala"
	if (_tmp0_) {
#line 397 "SideBarBox.c"
		QuilterWidgetsSideBar* _tmp3_;
		GtkListBox* _tmp4_;
		GList* _tmp5_;
		GList* _tmp6_;
		gboolean _tmp7_;
#line 93 "../src/Widgets/SideBarBox.vala"
		_tmp3_ = _data3_->win->sidebar;
#line 93 "../src/Widgets/SideBarBox.vala"
		_tmp4_ = _tmp3_->column;
#line 93 "../src/Widgets/SideBarBox.vala"
		_tmp5_ = gtk_container_get_children ((GtkContainer*) _tmp4_);
#line 93 "../src/Widgets/SideBarBox.vala"
		_tmp6_ = _tmp5_;
#line 93 "../src/Widgets/SideBarBox.vala"
		_tmp7_ = _tmp6_ == NULL;
#line 93 "../src/Widgets/SideBarBox.vala"
		(_tmp6_ == NULL) ? NULL : (_tmp6_ = (g_list_free (_tmp6_), NULL));
#line 93 "../src/Widgets/SideBarBox.vala"
		if (_tmp7_) {
#line 417 "SideBarBox.c"
			QuilterWidgetsSideBar* _tmp8_;
			GtkListBox* _tmp9_;
			GtkListBoxRow* _tmp10_;
#line 94 "../src/Widgets/SideBarBox.vala"
			_tmp8_ = _data3_->win->sidebar;
#line 94 "../src/Widgets/SideBarBox.vala"
			_tmp9_ = _tmp8_->column;
#line 94 "../src/Widgets/SideBarBox.vala"
			_tmp10_ = gtk_list_box_get_selected_row (_tmp9_);
#line 94 "../src/Widgets/SideBarBox.vala"
			if (G_TYPE_CHECK_INSTANCE_CAST (_tmp10_, QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX, QuilterWidgetsSideBarBox) != NULL) {
#line 429 "SideBarBox.c"
				QuilterWidgetsSideBar* _tmp11_;
				GtkListBox* _tmp12_;
				GtkListBoxRow* _tmp13_;
				QuilterWidgetsEditView* _tmp14_;
				GtkSourceBuffer* _tmp15_;
				QuilterWidgetsEditView* _tmp16_;
				QuilterWidgetsSideBar* _tmp17_;
				GtkTreeStore* _tmp18_;
				QuilterWidgetsSideBar* _tmp19_;
				GtkListBox* _tmp20_;
				QuilterWidgetsSideBar* _tmp21_;
				GtkListBox* _tmp22_;
				GtkListBoxRow* _tmp23_;
#line 95 "../src/Widgets/SideBarBox.vala"
				_tmp11_ = _data3_->win->sidebar;
#line 95 "../src/Widgets/SideBarBox.vala"
				_tmp12_ = _tmp11_->column;
#line 95 "../src/Widgets/SideBarBox.vala"
				_tmp13_ = gtk_list_box_get_selected_row (_tmp12_);
#line 95 "../src/Widgets/SideBarBox.vala"
				gtk_widget_destroy ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (_tmp13_, QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX, QuilterWidgetsSideBarBox));
#line 96 "../src/Widgets/SideBarBox.vala"
				_tmp14_ = _data3_->win->edit_view_content;
#line 96 "../src/Widgets/SideBarBox.vala"
				_tmp15_ = _tmp14_->buffer;
#line 96 "../src/Widgets/SideBarBox.vala"
				g_object_set ((GtkTextBuffer*) _tmp15_, "text", "", NULL);
#line 97 "../src/Widgets/SideBarBox.vala"
				_tmp16_ = _data3_->win->edit_view_content;
#line 97 "../src/Widgets/SideBarBox.vala"
				quilter_widgets_edit_view_set_modified (_tmp16_, FALSE);
#line 98 "../src/Widgets/SideBarBox.vala"
				_tmp17_ = _data3_->win->sidebar;
#line 98 "../src/Widgets/SideBarBox.vala"
				_tmp18_ = _tmp17_->store;
#line 98 "../src/Widgets/SideBarBox.vala"
				gtk_tree_store_clear (_tmp18_);
#line 99 "../src/Widgets/SideBarBox.vala"
				quilter_main_window_save_last_files (_data3_->win);
#line 100 "../src/Widgets/SideBarBox.vala"
				_tmp19_ = _data3_->win->sidebar;
#line 100 "../src/Widgets/SideBarBox.vala"
				_tmp20_ = _tmp19_->column;
#line 100 "../src/Widgets/SideBarBox.vala"
				_tmp21_ = _data3_->win->sidebar;
#line 100 "../src/Widgets/SideBarBox.vala"
				_tmp22_ = _tmp21_->column;
#line 100 "../src/Widgets/SideBarBox.vala"
				_tmp23_ = gtk_list_box_get_row_at_index (_tmp22_, self->uid - 1);
#line 100 "../src/Widgets/SideBarBox.vala"
				gtk_list_box_select_row (_tmp20_, (GtkListBoxRow*) G_TYPE_CHECK_INSTANCE_CAST (_tmp23_, QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX, QuilterWidgetsSideBarBox));
#line 481 "SideBarBox.c"
			} else {
				GtkStack* _tmp24_;
				GtkStack* _tmp25_;
				QuilterWidgetsSideBar* _tmp26_;
				GSettings* _tmp27_;
#line 102 "../src/Widgets/SideBarBox.vala"
				_tmp24_ = _data3_->win->win_stack;
#line 102 "../src/Widgets/SideBarBox.vala"
				gtk_stack_set_visible_child_name (_tmp24_, "welcome");
#line 103 "../src/Widgets/SideBarBox.vala"
				_tmp25_ = _data3_->win->titlebar_stack;
#line 103 "../src/Widgets/SideBarBox.vala"
				gtk_stack_set_visible_child_name (_tmp25_, "welcome-title");
#line 104 "../src/Widgets/SideBarBox.vala"
				_tmp26_ = _data3_->win->sidebar;
#line 104 "../src/Widgets/SideBarBox.vala"
				gtk_revealer_set_reveal_child ((GtkRevealer*) _tmp26_, FALSE);
#line 105 "../src/Widgets/SideBarBox.vala"
				_tmp27_ = quilter_application_gsettings;
#line 105 "../src/Widgets/SideBarBox.vala"
				g_settings_set_boolean (_tmp27_, "sidebar", FALSE);
#line 503 "SideBarBox.c"
			}
		} else {
			GtkStack* _tmp28_;
			GtkStack* _tmp29_;
			QuilterWidgetsSideBar* _tmp30_;
			GSettings* _tmp31_;
#line 108 "../src/Widgets/SideBarBox.vala"
			_tmp28_ = _data3_->win->win_stack;
#line 108 "../src/Widgets/SideBarBox.vala"
			gtk_stack_set_visible_child_name (_tmp28_, "welcome");
#line 109 "../src/Widgets/SideBarBox.vala"
			_tmp29_ = _data3_->win->titlebar_stack;
#line 109 "../src/Widgets/SideBarBox.vala"
			gtk_stack_set_visible_child_name (_tmp29_, "welcome-title");
#line 110 "../src/Widgets/SideBarBox.vala"
			_tmp30_ = _data3_->win->sidebar;
#line 110 "../src/Widgets/SideBarBox.vala"
			gtk_revealer_set_reveal_child ((GtkRevealer*) _tmp30_, FALSE);
#line 111 "../src/Widgets/SideBarBox.vala"
			_tmp31_ = quilter_application_gsettings;
#line 111 "../src/Widgets/SideBarBox.vala"
			g_settings_set_boolean (_tmp31_, "sidebar", FALSE);
#line 526 "SideBarBox.c"
		}
	}
}

static void
___lambda7__gtk_button_clicked (GtkButton* _sender,
                                gpointer self)
{
#line 91 "../src/Widgets/SideBarBox.vala"
	__lambda7_ (self);
#line 537 "SideBarBox.c"
}

QuilterWidgetsSideBarBox*
quilter_widgets_side_bar_box_construct (GType object_type,
                                        QuilterMainWindow* win,
                                        const gchar* path)
{
	QuilterWidgetsSideBarBox * self = NULL;
	Block3Data* _data3_;
	QuilterMainWindow* _tmp0_;
	QuilterMainWindow* _tmp1_;
	gint _tmp2_;
	GtkStyleContext* sbr_context = NULL;
	GtkStyleContext* _tmp3_;
	GtkStyleContext* _tmp4_;
	GtkLabel* _tmp5_;
	GtkLabel* _tmp6_;
	GtkLabel* _tmp7_;
	GtkLabel* _tmp8_;
	GtkLabel* _tmp9_;
	GtkStyleContext* _tmp10_;
	GtkLabel* _tmp11_;
	GtkLabel* _tmp12_;
	GtkLabel* _tmp13_;
	GtkLabel* _tmp14_;
	GtkStyleContext* _tmp15_;
	GtkImage* file_icon = NULL;
	GtkImage* _tmp16_;
	GtkButton* _tmp17_;
	GtkButton* _tmp18_;
	GtkButton* _tmp19_;
	GtkButton* _tmp20_;
	GtkButton* _tmp21_;
	GtkStyleContext* file_remove_button_style_context = NULL;
	GtkButton* _tmp22_;
	GtkStyleContext* _tmp23_;
	GtkStyleContext* _tmp24_;
	GtkButton* _tmp25_;
	GtkImage* _tmp26_;
	GtkImage* _tmp27_;
	GtkButton* _tmp28_;
	GtkBox* file_labels_box = NULL;
	GtkBox* _tmp29_;
	GtkStyleContext* flb_context = NULL;
	GtkStyleContext* _tmp30_;
	GtkStyleContext* _tmp31_;
	GtkLabel* _tmp32_;
	GtkLabel* _tmp33_;
	GtkGrid* _tmp34_;
	GtkGrid* _tmp35_;
	GtkGrid* _tmp36_;
	GtkGrid* _tmp37_;
	GtkGrid* _tmp38_;
	GtkGrid* _tmp39_;
	GtkButton* _tmp40_;
	GtkGrid* _tmp41_;
#line 60 "../src/Widgets/SideBarBox.vala"
	g_return_val_if_fail (win != NULL, NULL);
#line 60 "../src/Widgets/SideBarBox.vala"
	_data3_ = g_slice_new0 (Block3Data);
#line 60 "../src/Widgets/SideBarBox.vala"
	_data3_->_ref_count_ = 1;
#line 60 "../src/Widgets/SideBarBox.vala"
	_tmp0_ = _g_object_ref0 (win);
#line 60 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (_data3_->win);
#line 60 "../src/Widgets/SideBarBox.vala"
	_data3_->win = _tmp0_;
#line 60 "../src/Widgets/SideBarBox.vala"
	self = (QuilterWidgetsSideBarBox*) g_object_new (object_type, NULL);
#line 60 "../src/Widgets/SideBarBox.vala"
	_data3_->self = g_object_ref (self);
#line 61 "../src/Widgets/SideBarBox.vala"
	_tmp1_ = _g_object_ref0 (_data3_->win);
#line 61 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (self->win);
#line 61 "../src/Widgets/SideBarBox.vala"
	self->win = _tmp1_;
#line 62 "../src/Widgets/SideBarBox.vala"
	_tmp2_ = quilter_widgets_side_bar_box_uid_counter;
#line 62 "../src/Widgets/SideBarBox.vala"
	quilter_widgets_side_bar_box_uid_counter = _tmp2_ + 1;
#line 62 "../src/Widgets/SideBarBox.vala"
	self->uid = _tmp2_;
#line 63 "../src/Widgets/SideBarBox.vala"
	gtk_list_box_row_set_activatable ((GtkListBoxRow*) self, TRUE);
#line 64 "../src/Widgets/SideBarBox.vala"
	_tmp3_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 64 "../src/Widgets/SideBarBox.vala"
	_tmp4_ = _g_object_ref0 (_tmp3_);
#line 64 "../src/Widgets/SideBarBox.vala"
	sbr_context = _tmp4_;
#line 65 "../src/Widgets/SideBarBox.vala"
	gtk_style_context_add_class (sbr_context, "quilter-sidebar-box");
#line 67 "../src/Widgets/SideBarBox.vala"
	_tmp5_ = (GtkLabel*) gtk_label_new ("");
#line 67 "../src/Widgets/SideBarBox.vala"
	g_object_ref_sink (_tmp5_);
#line 67 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (self->priv->file_name_label);
#line 67 "../src/Widgets/SideBarBox.vala"
	self->priv->file_name_label = _tmp5_;
#line 68 "../src/Widgets/SideBarBox.vala"
	_tmp6_ = self->priv->file_name_label;
#line 68 "../src/Widgets/SideBarBox.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp6_, GTK_ALIGN_START);
#line 69 "../src/Widgets/SideBarBox.vala"
	_tmp7_ = self->priv->file_name_label;
#line 69 "../src/Widgets/SideBarBox.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp7_, TRUE);
#line 70 "../src/Widgets/SideBarBox.vala"
	_tmp8_ = self->priv->file_name_label;
#line 70 "../src/Widgets/SideBarBox.vala"
	gtk_label_set_ellipsize (_tmp8_, PANGO_ELLIPSIZE_END);
#line 71 "../src/Widgets/SideBarBox.vala"
	_tmp9_ = self->priv->file_name_label;
#line 71 "../src/Widgets/SideBarBox.vala"
	_tmp10_ = gtk_widget_get_style_context ((GtkWidget*) _tmp9_);
#line 71 "../src/Widgets/SideBarBox.vala"
	gtk_style_context_add_class (_tmp10_, "title");
#line 73 "../src/Widgets/SideBarBox.vala"
	_tmp11_ = (GtkLabel*) gtk_label_new ("");
#line 73 "../src/Widgets/SideBarBox.vala"
	g_object_ref_sink (_tmp11_);
#line 73 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (self->priv->file_label);
#line 73 "../src/Widgets/SideBarBox.vala"
	self->priv->file_label = _tmp11_;
#line 74 "../src/Widgets/SideBarBox.vala"
	_tmp12_ = self->priv->file_label;
#line 74 "../src/Widgets/SideBarBox.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp12_, GTK_ALIGN_START);
#line 75 "../src/Widgets/SideBarBox.vala"
	_tmp13_ = self->priv->file_label;
#line 75 "../src/Widgets/SideBarBox.vala"
	gtk_label_set_ellipsize (_tmp13_, PANGO_ELLIPSIZE_START);
#line 76 "../src/Widgets/SideBarBox.vala"
	_tmp14_ = self->priv->file_label;
#line 76 "../src/Widgets/SideBarBox.vala"
	_tmp15_ = gtk_widget_get_style_context ((GtkWidget*) _tmp14_);
#line 76 "../src/Widgets/SideBarBox.vala"
	gtk_style_context_add_class (_tmp15_, "subtitle");
#line 78 "../src/Widgets/SideBarBox.vala"
	_tmp16_ = (GtkImage*) gtk_image_new_from_icon_name ("markdown-symbolic", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
#line 78 "../src/Widgets/SideBarBox.vala"
	g_object_ref_sink (_tmp16_);
#line 78 "../src/Widgets/SideBarBox.vala"
	file_icon = _tmp16_;
#line 80 "../src/Widgets/SideBarBox.vala"
	_tmp17_ = (GtkButton*) gtk_button_new ();
#line 80 "../src/Widgets/SideBarBox.vala"
	g_object_ref_sink (_tmp17_);
#line 80 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (self->file_remove_button);
#line 80 "../src/Widgets/SideBarBox.vala"
	self->file_remove_button = _tmp17_;
#line 81 "../src/Widgets/SideBarBox.vala"
	_tmp18_ = self->file_remove_button;
#line 81 "../src/Widgets/SideBarBox.vala"
	gtk_button_set_always_show_image (_tmp18_, TRUE);
#line 82 "../src/Widgets/SideBarBox.vala"
	_tmp19_ = self->file_remove_button;
#line 82 "../src/Widgets/SideBarBox.vala"
	gtk_widget_set_valign ((GtkWidget*) _tmp19_, GTK_ALIGN_CENTER);
#line 83 "../src/Widgets/SideBarBox.vala"
	_tmp20_ = self->file_remove_button;
#line 83 "../src/Widgets/SideBarBox.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp20_, GTK_ALIGN_CENTER);
#line 84 "../src/Widgets/SideBarBox.vala"
	_tmp21_ = self->file_remove_button;
#line 84 "../src/Widgets/SideBarBox.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp21_, _ ("Remove file from sidebar"));
#line 85 "../src/Widgets/SideBarBox.vala"
	_tmp22_ = self->file_remove_button;
#line 85 "../src/Widgets/SideBarBox.vala"
	_tmp23_ = gtk_widget_get_style_context ((GtkWidget*) _tmp22_);
#line 85 "../src/Widgets/SideBarBox.vala"
	_tmp24_ = _g_object_ref0 (_tmp23_);
#line 85 "../src/Widgets/SideBarBox.vala"
	file_remove_button_style_context = _tmp24_;
#line 86 "../src/Widgets/SideBarBox.vala"
	gtk_style_context_add_class (file_remove_button_style_context, GTK_STYLE_CLASS_FLAT);
#line 87 "../src/Widgets/SideBarBox.vala"
	gtk_style_context_add_class (file_remove_button_style_context, "quilter-sidebar-button");
#line 88 "../src/Widgets/SideBarBox.vala"
	gtk_style_context_add_class (file_remove_button_style_context, "mini-circular-button");
#line 89 "../src/Widgets/SideBarBox.vala"
	_tmp25_ = self->file_remove_button;
#line 89 "../src/Widgets/SideBarBox.vala"
	_tmp26_ = (GtkImage*) gtk_image_new_from_icon_name ("window-close-symbolic", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
#line 89 "../src/Widgets/SideBarBox.vala"
	g_object_ref_sink (_tmp26_);
#line 89 "../src/Widgets/SideBarBox.vala"
	_tmp27_ = _tmp26_;
#line 89 "../src/Widgets/SideBarBox.vala"
	gtk_button_set_image (_tmp25_, (GtkWidget*) _tmp27_);
#line 89 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (_tmp27_);
#line 91 "../src/Widgets/SideBarBox.vala"
	_tmp28_ = self->file_remove_button;
#line 91 "../src/Widgets/SideBarBox.vala"
	g_signal_connect_data (_tmp28_, "clicked", (GCallback) ___lambda7__gtk_button_clicked, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
#line 116 "../src/Widgets/SideBarBox.vala"
	_tmp29_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 3);
#line 116 "../src/Widgets/SideBarBox.vala"
	g_object_ref_sink (_tmp29_);
#line 116 "../src/Widgets/SideBarBox.vala"
	file_labels_box = _tmp29_;
#line 117 "../src/Widgets/SideBarBox.vala"
	_tmp30_ = gtk_widget_get_style_context ((GtkWidget*) file_labels_box);
#line 117 "../src/Widgets/SideBarBox.vala"
	_tmp31_ = _g_object_ref0 (_tmp30_);
#line 117 "../src/Widgets/SideBarBox.vala"
	flb_context = _tmp31_;
#line 118 "../src/Widgets/SideBarBox.vala"
	gtk_style_context_add_class (flb_context, "quilter-flb");
#line 119 "../src/Widgets/SideBarBox.vala"
	_tmp32_ = self->priv->file_name_label;
#line 119 "../src/Widgets/SideBarBox.vala"
	gtk_box_pack_start (file_labels_box, (GtkWidget*) _tmp32_, TRUE, TRUE, (guint) 0);
#line 120 "../src/Widgets/SideBarBox.vala"
	_tmp33_ = self->priv->file_label;
#line 120 "../src/Widgets/SideBarBox.vala"
	gtk_box_pack_start (file_labels_box, (GtkWidget*) _tmp33_, TRUE, TRUE, (guint) 0);
#line 122 "../src/Widgets/SideBarBox.vala"
	_tmp34_ = (GtkGrid*) gtk_grid_new ();
#line 122 "../src/Widgets/SideBarBox.vala"
	g_object_ref_sink (_tmp34_);
#line 122 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (self->file_grid);
#line 122 "../src/Widgets/SideBarBox.vala"
	self->file_grid = _tmp34_;
#line 123 "../src/Widgets/SideBarBox.vala"
	_tmp35_ = self->file_grid;
#line 123 "../src/Widgets/SideBarBox.vala"
	gtk_grid_set_column_spacing (_tmp35_, 12);
#line 124 "../src/Widgets/SideBarBox.vala"
	_tmp36_ = self->file_grid;
#line 124 "../src/Widgets/SideBarBox.vala"
	g_object_set ((GtkWidget*) _tmp36_, "margin", 6, NULL);
#line 125 "../src/Widgets/SideBarBox.vala"
	_tmp37_ = self->file_grid;
#line 125 "../src/Widgets/SideBarBox.vala"
	gtk_grid_attach (_tmp37_, (GtkWidget*) file_icon, 0, 0, 1, 1);
#line 126 "../src/Widgets/SideBarBox.vala"
	_tmp38_ = self->file_grid;
#line 126 "../src/Widgets/SideBarBox.vala"
	gtk_grid_attach (_tmp38_, (GtkWidget*) file_labels_box, 1, 0, 1, 1);
#line 127 "../src/Widgets/SideBarBox.vala"
	_tmp39_ = self->file_grid;
#line 127 "../src/Widgets/SideBarBox.vala"
	_tmp40_ = self->file_remove_button;
#line 127 "../src/Widgets/SideBarBox.vala"
	gtk_grid_attach (_tmp39_, (GtkWidget*) _tmp40_, 2, 0, 1, 1);
#line 129 "../src/Widgets/SideBarBox.vala"
	_tmp41_ = self->file_grid;
#line 129 "../src/Widgets/SideBarBox.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp41_);
#line 130 "../src/Widgets/SideBarBox.vala"
	gtk_widget_set_margin_bottom ((GtkWidget*) self, 6);
#line 131 "../src/Widgets/SideBarBox.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 132 "../src/Widgets/SideBarBox.vala"
	quilter_widgets_side_bar_box_set_path (self, path);
#line 60 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (flb_context);
#line 60 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (file_labels_box);
#line 60 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (file_remove_button_style_context);
#line 60 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (file_icon);
#line 60 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (sbr_context);
#line 60 "../src/Widgets/SideBarBox.vala"
	block3_data_unref (_data3_);
#line 60 "../src/Widgets/SideBarBox.vala"
	_data3_ = NULL;
#line 60 "../src/Widgets/SideBarBox.vala"
	return self;
#line 818 "SideBarBox.c"
}

QuilterWidgetsSideBarBox*
quilter_widgets_side_bar_box_new (QuilterMainWindow* win,
                                  const gchar* path)
{
#line 60 "../src/Widgets/SideBarBox.vala"
	return quilter_widgets_side_bar_box_construct (QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX, win, path);
#line 827 "SideBarBox.c"
}

gchar*
quilter_widgets_side_bar_box_get_path (QuilterWidgetsSideBarBox* self)
{
	gchar* result;
	const gchar* _tmp0_;
	gchar* _tmp1_;
#line 32 "../src/Widgets/SideBarBox.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 33 "../src/Widgets/SideBarBox.vala"
	_tmp0_ = self->priv->_path;
#line 33 "../src/Widgets/SideBarBox.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 33 "../src/Widgets/SideBarBox.vala"
	result = _tmp1_;
#line 33 "../src/Widgets/SideBarBox.vala"
	return result;
#line 846 "SideBarBox.c"
}

void
quilter_widgets_side_bar_box_set_path (QuilterWidgetsSideBarBox* self,
                                       const gchar* value)
{
	gchar* _tmp0_;
	const gchar* _tmp1_;
#line 35 "../src/Widgets/SideBarBox.vala"
	g_return_if_fail (self != NULL);
#line 36 "../src/Widgets/SideBarBox.vala"
	_tmp0_ = g_strdup (value);
#line 36 "../src/Widgets/SideBarBox.vala"
	_g_free0 (self->priv->_path);
#line 36 "../src/Widgets/SideBarBox.vala"
	self->priv->_path = _tmp0_;
#line 37 "../src/Widgets/SideBarBox.vala"
	_tmp1_ = self->priv->_path;
#line 37 "../src/Widgets/SideBarBox.vala"
	if (quilter_services_file_manager_is_temp_file (_tmp1_)) {
#line 867 "SideBarBox.c"
		GtkLabel* _tmp2_;
#line 38 "../src/Widgets/SideBarBox.vala"
		_tmp2_ = self->priv->file_name_label;
#line 38 "../src/Widgets/SideBarBox.vala"
		gtk_label_set_label (_tmp2_, _ ("New File"));
#line 873 "SideBarBox.c"
	} else {
		GtkLabel* _tmp3_;
		const gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
#line 40 "../src/Widgets/SideBarBox.vala"
		_tmp3_ = self->priv->file_name_label;
#line 40 "../src/Widgets/SideBarBox.vala"
		_tmp4_ = self->priv->_path;
#line 40 "../src/Widgets/SideBarBox.vala"
		_tmp5_ = g_path_get_basename (_tmp4_);
#line 40 "../src/Widgets/SideBarBox.vala"
		_tmp6_ = _tmp5_;
#line 40 "../src/Widgets/SideBarBox.vala"
		gtk_label_set_label (_tmp3_, _tmp6_);
#line 40 "../src/Widgets/SideBarBox.vala"
		_g_free0 (_tmp6_);
#line 891 "SideBarBox.c"
	}
#line 35 "../src/Widgets/SideBarBox.vala"
	g_object_notify_by_pspec ((GObject *) self, quilter_widgets_side_bar_box_properties[QUILTER_WIDGETS_SIDE_BAR_BOX_PATH_PROPERTY]);
#line 895 "SideBarBox.c"
}

gchar*
quilter_widgets_side_bar_box_get_title (QuilterWidgetsSideBarBox* self)
{
	gchar* result;
	GtkLabel* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
#line 46 "../src/Widgets/SideBarBox.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 47 "../src/Widgets/SideBarBox.vala"
	_tmp0_ = self->priv->file_label;
#line 47 "../src/Widgets/SideBarBox.vala"
	_tmp1_ = gtk_label_get_label (_tmp0_);
#line 47 "../src/Widgets/SideBarBox.vala"
	_tmp2_ = _tmp1_;
#line 47 "../src/Widgets/SideBarBox.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 47 "../src/Widgets/SideBarBox.vala"
	result = _tmp3_;
#line 47 "../src/Widgets/SideBarBox.vala"
	return result;
#line 920 "SideBarBox.c"
}

void
quilter_widgets_side_bar_box_set_title (QuilterWidgetsSideBarBox* self,
                                        const gchar* value)
{
	const gchar* _tmp0_;
#line 49 "../src/Widgets/SideBarBox.vala"
	g_return_if_fail (self != NULL);
#line 50 "../src/Widgets/SideBarBox.vala"
	_tmp0_ = self->priv->_path;
#line 50 "../src/Widgets/SideBarBox.vala"
	if (quilter_services_file_manager_is_temp_file (_tmp0_)) {
#line 934 "SideBarBox.c"
		GtkLabel* _tmp1_;
#line 51 "../src/Widgets/SideBarBox.vala"
		_tmp1_ = self->priv->file_label;
#line 51 "../src/Widgets/SideBarBox.vala"
		gtk_label_set_label (_tmp1_, _ ("No header…"));
#line 940 "SideBarBox.c"
	} else {
		GtkLabel* _tmp2_;
#line 53 "../src/Widgets/SideBarBox.vala"
		_tmp2_ = self->priv->file_label;
#line 53 "../src/Widgets/SideBarBox.vala"
		gtk_label_set_label (_tmp2_, value);
#line 947 "SideBarBox.c"
	}
#line 49 "../src/Widgets/SideBarBox.vala"
	g_object_notify_by_pspec ((GObject *) self, quilter_widgets_side_bar_box_properties[QUILTER_WIDGETS_SIDE_BAR_BOX_TITLE_PROPERTY]);
#line 951 "SideBarBox.c"
}

static void
quilter_widgets_side_bar_box_class_init (QuilterWidgetsSideBarBoxClass * klass,
                                         gpointer klass_data)
{
#line 20 "../src/Widgets/SideBarBox.vala"
	quilter_widgets_side_bar_box_parent_class = g_type_class_peek_parent (klass);
#line 20 "../src/Widgets/SideBarBox.vala"
	g_type_class_adjust_private_offset (klass, &QuilterWidgetsSideBarBox_private_offset);
#line 20 "../src/Widgets/SideBarBox.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_quilter_widgets_side_bar_box_get_property;
#line 20 "../src/Widgets/SideBarBox.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_quilter_widgets_side_bar_box_set_property;
#line 20 "../src/Widgets/SideBarBox.vala"
	G_OBJECT_CLASS (klass)->finalize = quilter_widgets_side_bar_box_finalize;
#line 20 "../src/Widgets/SideBarBox.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), QUILTER_WIDGETS_SIDE_BAR_BOX_PATH_PROPERTY, quilter_widgets_side_bar_box_properties[QUILTER_WIDGETS_SIDE_BAR_BOX_PATH_PROPERTY] = g_param_spec_string ("path", "path", "path", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 20 "../src/Widgets/SideBarBox.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), QUILTER_WIDGETS_SIDE_BAR_BOX_TITLE_PROPERTY, quilter_widgets_side_bar_box_properties[QUILTER_WIDGETS_SIDE_BAR_BOX_TITLE_PROPERTY] = g_param_spec_string ("title", "title", "title", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 20 "../src/Widgets/SideBarBox.vala"
	quilter_widgets_side_bar_box_signals[QUILTER_WIDGETS_SIDE_BAR_BOX_SAVE_AS_SIGNAL] = g_signal_new ("save-as", QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 974 "SideBarBox.c"
}

static void
quilter_widgets_side_bar_box_instance_init (QuilterWidgetsSideBarBox * self,
                                            gpointer klass)
{
#line 20 "../src/Widgets/SideBarBox.vala"
	self->priv = quilter_widgets_side_bar_box_get_instance_private (self);
#line 983 "SideBarBox.c"
}

static void
quilter_widgets_side_bar_box_finalize (GObject * obj)
{
	QuilterWidgetsSideBarBox * self;
#line 20 "../src/Widgets/SideBarBox.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX, QuilterWidgetsSideBarBox);
#line 21 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (self->priv->file_label);
#line 22 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (self->priv->file_name_label);
#line 23 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (self->ev);
#line 24 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (self->file_remove_button);
#line 25 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (self->file_grid);
#line 26 "../src/Widgets/SideBarBox.vala"
	_g_object_unref0 (self->win);
#line 30 "../src/Widgets/SideBarBox.vala"
	_g_free0 (self->priv->_path);
#line 20 "../src/Widgets/SideBarBox.vala"
	G_OBJECT_CLASS (quilter_widgets_side_bar_box_parent_class)->finalize (obj);
#line 1008 "SideBarBox.c"
}

static GType
quilter_widgets_side_bar_box_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (QuilterWidgetsSideBarBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_widgets_side_bar_box_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterWidgetsSideBarBox), 0, (GInstanceInitFunc) quilter_widgets_side_bar_box_instance_init, NULL };
	GType quilter_widgets_side_bar_box_type_id;
	quilter_widgets_side_bar_box_type_id = g_type_register_static (gtk_list_box_row_get_type (), "QuilterWidgetsSideBarBox", &g_define_type_info, 0);
	QuilterWidgetsSideBarBox_private_offset = g_type_add_instance_private (quilter_widgets_side_bar_box_type_id, sizeof (QuilterWidgetsSideBarBoxPrivate));
	return quilter_widgets_side_bar_box_type_id;
}

GType
quilter_widgets_side_bar_box_get_type (void)
{
	static volatile gsize quilter_widgets_side_bar_box_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_widgets_side_bar_box_type_id__volatile)) {
		GType quilter_widgets_side_bar_box_type_id;
		quilter_widgets_side_bar_box_type_id = quilter_widgets_side_bar_box_get_type_once ();
		g_once_init_leave (&quilter_widgets_side_bar_box_type_id__volatile, quilter_widgets_side_bar_box_type_id);
	}
	return quilter_widgets_side_bar_box_type_id__volatile;
}

static void
_vala_quilter_widgets_side_bar_box_get_property (GObject * object,
                                                 guint property_id,
                                                 GValue * value,
                                                 GParamSpec * pspec)
{
	QuilterWidgetsSideBarBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX, QuilterWidgetsSideBarBox);
#line 20 "../src/Widgets/SideBarBox.vala"
	switch (property_id) {
#line 20 "../src/Widgets/SideBarBox.vala"
		case QUILTER_WIDGETS_SIDE_BAR_BOX_PATH_PROPERTY:
#line 20 "../src/Widgets/SideBarBox.vala"
		g_value_take_string (value, quilter_widgets_side_bar_box_get_path (self));
#line 20 "../src/Widgets/SideBarBox.vala"
		break;
#line 20 "../src/Widgets/SideBarBox.vala"
		case QUILTER_WIDGETS_SIDE_BAR_BOX_TITLE_PROPERTY:
#line 20 "../src/Widgets/SideBarBox.vala"
		g_value_take_string (value, quilter_widgets_side_bar_box_get_title (self));
#line 20 "../src/Widgets/SideBarBox.vala"
		break;
#line 1055 "SideBarBox.c"
		default:
#line 20 "../src/Widgets/SideBarBox.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "../src/Widgets/SideBarBox.vala"
		break;
#line 1061 "SideBarBox.c"
	}
}

static void
_vala_quilter_widgets_side_bar_box_set_property (GObject * object,
                                                 guint property_id,
                                                 const GValue * value,
                                                 GParamSpec * pspec)
{
	QuilterWidgetsSideBarBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QUILTER_WIDGETS_TYPE_SIDE_BAR_BOX, QuilterWidgetsSideBarBox);
#line 20 "../src/Widgets/SideBarBox.vala"
	switch (property_id) {
#line 20 "../src/Widgets/SideBarBox.vala"
		case QUILTER_WIDGETS_SIDE_BAR_BOX_PATH_PROPERTY:
#line 20 "../src/Widgets/SideBarBox.vala"
		quilter_widgets_side_bar_box_set_path (self, g_value_get_string (value));
#line 20 "../src/Widgets/SideBarBox.vala"
		break;
#line 20 "../src/Widgets/SideBarBox.vala"
		case QUILTER_WIDGETS_SIDE_BAR_BOX_TITLE_PROPERTY:
#line 20 "../src/Widgets/SideBarBox.vala"
		quilter_widgets_side_bar_box_set_title (self, g_value_get_string (value));
#line 20 "../src/Widgets/SideBarBox.vala"
		break;
#line 1087 "SideBarBox.c"
		default:
#line 20 "../src/Widgets/SideBarBox.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "../src/Widgets/SideBarBox.vala"
		break;
#line 1093 "SideBarBox.c"
	}
}

