/* StatusBar.c generated by valac 0.50.2, the Vala compiler
 * generated from StatusBar.vala, do not modify */

/*
* Copyright (C) 2017-2021 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <gtk/gtk.h>
#include <glib-object.h>
#include <gtksourceview/gtksource.h>
#include <handy.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>

#define QUILTER_WIDGETS_TYPE_STATUS_BAR (quilter_widgets_status_bar_get_type ())
#define QUILTER_WIDGETS_STATUS_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_STATUS_BAR, QuilterWidgetsStatusBar))
#define QUILTER_WIDGETS_STATUS_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_STATUS_BAR, QuilterWidgetsStatusBarClass))
#define QUILTER_WIDGETS_IS_STATUS_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_STATUS_BAR))
#define QUILTER_WIDGETS_IS_STATUS_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_STATUS_BAR))
#define QUILTER_WIDGETS_STATUS_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_STATUS_BAR, QuilterWidgetsStatusBarClass))

typedef struct _QuilterWidgetsStatusBar QuilterWidgetsStatusBar;
typedef struct _QuilterWidgetsStatusBarClass QuilterWidgetsStatusBarClass;
typedef struct _QuilterWidgetsStatusBarPrivate QuilterWidgetsStatusBarPrivate;

#define QUILTER_TYPE_MAIN_WINDOW (quilter_main_window_get_type ())
#define QUILTER_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindow))
#define QUILTER_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindowClass))
#define QUILTER_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_MAIN_WINDOW))
#define QUILTER_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_MAIN_WINDOW))
#define QUILTER_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_MAIN_WINDOW, QuilterMainWindowClass))

typedef struct _QuilterMainWindow QuilterMainWindow;
typedef struct _QuilterMainWindowClass QuilterMainWindowClass;
enum  {
	QUILTER_WIDGETS_STATUS_BAR_0_PROPERTY,
	QUILTER_WIDGETS_STATUS_BAR_NUM_PROPERTIES
};
static GParamSpec* quilter_widgets_status_bar_properties[QUILTER_WIDGETS_STATUS_BAR_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define QUILTER_WIDGETS_TYPE_WORD_COUNT (quilter_widgets_word_count_get_type ())
#define QUILTER_WIDGETS_WORD_COUNT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_WIDGETS_TYPE_WORD_COUNT, QuilterWidgetsWordCount))
#define QUILTER_WIDGETS_WORD_COUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_WIDGETS_TYPE_WORD_COUNT, QuilterWidgetsWordCountClass))
#define QUILTER_WIDGETS_IS_WORD_COUNT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_WIDGETS_TYPE_WORD_COUNT))
#define QUILTER_WIDGETS_IS_WORD_COUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_WIDGETS_TYPE_WORD_COUNT))
#define QUILTER_WIDGETS_WORD_COUNT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_WIDGETS_TYPE_WORD_COUNT, QuilterWidgetsWordCountClass))

typedef struct _QuilterWidgetsWordCount QuilterWidgetsWordCount;
typedef struct _QuilterWidgetsWordCountClass QuilterWidgetsWordCountClass;
#define _quilter_widgets_word_count_unref0(var) ((var == NULL) ? NULL : (var = (quilter_widgets_word_count_unref (var), NULL)))
typedef struct _QuilterWidgetsWordCountPrivate QuilterWidgetsWordCountPrivate;
typedef struct _QuilterWidgetsParamSpecWordCount QuilterWidgetsParamSpecWordCount;

struct _QuilterWidgetsStatusBar {
	GtkRevealer parent_instance;
	QuilterWidgetsStatusBarPrivate * priv;
	GtkActionBar* actionbar;
	GtkLabel* linecount_label;
	GtkLabel* wordcount_label;
	GtkMenuButton* preview_type_menu;
	GtkMenuButton* track_type_menu;
	GtkSourceBuffer* buf;
	GtkRadioButton* track_words;
	GtkRadioButton* track_lines;
	GtkRadioButton* track_rtc;
	QuilterMainWindow* window;
};

struct _QuilterWidgetsStatusBarClass {
	GtkRevealerClass parent_class;
};

struct _QuilterWidgetsStatusBarPrivate {
	gint WPM;
};

struct _QuilterWidgetsWordCount {
	GTypeInstance parent_instance;
	volatile int ref_count;
	QuilterWidgetsWordCountPrivate * priv;
};

struct _QuilterWidgetsWordCountClass {
	GTypeClass parent_class;
	void (*finalize) (QuilterWidgetsWordCount *self);
};

struct _QuilterWidgetsWordCountPrivate {
	gint _words;
	gint _lines;
};

struct _QuilterWidgetsParamSpecWordCount {
	GParamSpec parent_instance;
};

static gint QuilterWidgetsStatusBar_private_offset;
static gpointer quilter_widgets_status_bar_parent_class = NULL;
extern GSettings* quilter_application_gsettings;
static gint QuilterWidgetsWordCount_private_offset;
static gpointer quilter_widgets_word_count_parent_class = NULL;

GType quilter_widgets_status_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsStatusBar, g_object_unref)
GType quilter_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterMainWindow, g_object_unref)
QuilterWidgetsStatusBar* quilter_widgets_status_bar_new (GtkSourceBuffer* buf);
QuilterWidgetsStatusBar* quilter_widgets_status_bar_construct (GType object_type,
                                                               GtkSourceBuffer* buf);
static void __lambda11_ (QuilterWidgetsStatusBar* self);
void quilter_widgets_status_bar_update_wordcount (QuilterWidgetsStatusBar* self);
static void ___lambda11__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                             gpointer self);
static void __lambda12_ (QuilterWidgetsStatusBar* self);
void quilter_widgets_status_bar_update_linecount (QuilterWidgetsStatusBar* self);
static void ___lambda12__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                             gpointer self);
static void __lambda13_ (QuilterWidgetsStatusBar* self);
void quilter_widgets_status_bar_update_readtimecount (QuilterWidgetsStatusBar* self);
static void ___lambda13__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                             gpointer self);
gpointer quilter_widgets_word_count_ref (gpointer instance);
void quilter_widgets_word_count_unref (gpointer instance);
GParamSpec* quilter_widgets_param_spec_word_count (const gchar* name,
                                                   const gchar* nick,
                                                   const gchar* blurb,
                                                   GType object_type,
                                                   GParamFlags flags);
void quilter_widgets_value_set_word_count (GValue* value,
                                           gpointer v_object);
void quilter_widgets_value_take_word_count (GValue* value,
                                            gpointer v_object);
gpointer quilter_widgets_value_get_word_count (const GValue* value);
GType quilter_widgets_word_count_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterWidgetsWordCount, quilter_widgets_word_count_unref)
QuilterWidgetsWordCount* quilter_widgets_status_bar_get_count (QuilterWidgetsStatusBar* self);
gint quilter_widgets_word_count_get_words (QuilterWidgetsWordCount* self);
gint quilter_widgets_word_count_get_lines (QuilterWidgetsWordCount* self);
QuilterWidgetsWordCount* quilter_widgets_word_count_new (gint words,
                                                         gint lines);
QuilterWidgetsWordCount* quilter_widgets_word_count_construct (GType object_type,
                                                               gint words,
                                                               gint lines);
static void quilter_widgets_status_bar_finalize (GObject * obj);
static GType quilter_widgets_status_bar_get_type_once (void);
static void quilter_widgets_word_count_set_words (QuilterWidgetsWordCount* self,
                                           gint value);
static void quilter_widgets_word_count_set_lines (QuilterWidgetsWordCount* self,
                                           gint value);
static void quilter_widgets_word_count_finalize (QuilterWidgetsWordCount * obj);
static GType quilter_widgets_word_count_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

static inline gpointer
quilter_widgets_status_bar_get_instance_private (QuilterWidgetsStatusBar* self)
{
	return G_STRUCT_MEMBER_P (self, QuilterWidgetsStatusBar_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 36 "../src/Widgets/StatusBar.vala"
	return self ? g_object_ref (self) : NULL;
#line 195 "StatusBar.c"
}

static void
__lambda11_ (QuilterWidgetsStatusBar* self)
{
	GSettings* _tmp0_;
#line 45 "../src/Widgets/StatusBar.vala"
	_tmp0_ = quilter_application_gsettings;
#line 45 "../src/Widgets/StatusBar.vala"
	g_settings_set_string (_tmp0_, "track-type", "words");
#line 46 "../src/Widgets/StatusBar.vala"
	quilter_widgets_status_bar_update_wordcount (self);
#line 208 "StatusBar.c"
}

static void
___lambda11__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                        gpointer self)
{
#line 44 "../src/Widgets/StatusBar.vala"
	__lambda11_ ((QuilterWidgetsStatusBar*) self);
#line 217 "StatusBar.c"
}

static void
__lambda12_ (QuilterWidgetsStatusBar* self)
{
	GSettings* _tmp0_;
#line 51 "../src/Widgets/StatusBar.vala"
	_tmp0_ = quilter_application_gsettings;
#line 51 "../src/Widgets/StatusBar.vala"
	g_settings_set_string (_tmp0_, "track-type", "lines");
#line 52 "../src/Widgets/StatusBar.vala"
	quilter_widgets_status_bar_update_linecount (self);
#line 230 "StatusBar.c"
}

static void
___lambda12__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                        gpointer self)
{
#line 50 "../src/Widgets/StatusBar.vala"
	__lambda12_ ((QuilterWidgetsStatusBar*) self);
#line 239 "StatusBar.c"
}

static void
__lambda13_ (QuilterWidgetsStatusBar* self)
{
	GSettings* _tmp0_;
#line 57 "../src/Widgets/StatusBar.vala"
	_tmp0_ = quilter_application_gsettings;
#line 57 "../src/Widgets/StatusBar.vala"
	g_settings_set_string (_tmp0_, "track-type", "rtc");
#line 58 "../src/Widgets/StatusBar.vala"
	quilter_widgets_status_bar_update_readtimecount (self);
#line 252 "StatusBar.c"
}

static void
___lambda13__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                        gpointer self)
{
#line 56 "../src/Widgets/StatusBar.vala"
	__lambda13_ ((QuilterWidgetsStatusBar*) self);
#line 261 "StatusBar.c"
}

QuilterWidgetsStatusBar*
quilter_widgets_status_bar_construct (GType object_type,
                                      GtkSourceBuffer* buf)
{
	QuilterWidgetsStatusBar * self = NULL;
	GtkSourceBuffer* _tmp0_;
	GtkActionBar* _tmp1_;
	GtkStyleContext* sb_context = NULL;
	GtkActionBar* _tmp2_;
	GtkStyleContext* _tmp3_;
	GtkStyleContext* _tmp4_;
	GtkStyleContext* _tmp5_;
	GtkRadioButton* _tmp6_;
	GtkRadioButton* _tmp7_;
	GtkRadioButton* _tmp8_;
	GtkRadioButton* _tmp9_;
	GtkRadioButton* _tmp10_;
	GtkRadioButton* _tmp11_;
	GtkRadioButton* _tmp12_;
	GtkRadioButton* _tmp13_;
	GtkGrid* track_type_grid = NULL;
	GtkGrid* _tmp14_;
	GtkGrid* _tmp15_;
	GtkGrid* _tmp16_;
	GtkGrid* _tmp17_;
	GtkGrid* _tmp18_;
	GtkGrid* _tmp19_;
	GtkRadioButton* _tmp20_;
	GtkGrid* _tmp21_;
	GtkRadioButton* _tmp22_;
	GtkGrid* _tmp23_;
	GtkRadioButton* _tmp24_;
	GtkGrid* _tmp25_;
	GtkPopover* track_type_menu_pop = NULL;
	GtkPopover* _tmp26_;
	GtkPopover* _tmp27_;
	GtkGrid* _tmp28_;
	GtkMenuButton* _tmp29_;
	GtkMenuButton* _tmp30_;
	GtkMenuButton* _tmp31_;
	GtkPopover* _tmp32_;
	GtkMenuButton* _tmp33_;
	GtkStyleContext* menu_context = NULL;
	GtkMenuButton* _tmp34_;
	GtkStyleContext* _tmp35_;
	GtkStyleContext* _tmp36_;
	GtkStyleContext* _tmp37_;
	GtkStyleContext* _tmp38_;
	GtkActionBar* _tmp39_;
	GtkMenuButton* _tmp40_;
	GSettings* _tmp41_;
	gchar* _tmp42_;
	gchar* _tmp43_;
	gboolean _tmp44_;
	GtkActionBar* _tmp53_;
	GSettings* _tmp54_;
#line 35 "../src/Widgets/StatusBar.vala"
	g_return_val_if_fail (buf != NULL, NULL);
#line 35 "../src/Widgets/StatusBar.vala"
	self = (QuilterWidgetsStatusBar*) g_object_new (object_type, NULL);
#line 36 "../src/Widgets/StatusBar.vala"
	_tmp0_ = _g_object_ref0 (buf);
#line 36 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->buf);
#line 36 "../src/Widgets/StatusBar.vala"
	self->buf = _tmp0_;
#line 37 "../src/Widgets/StatusBar.vala"
	gtk_widget_set_valign ((GtkWidget*) self, GTK_ALIGN_END);
#line 38 "../src/Widgets/StatusBar.vala"
	_tmp1_ = (GtkActionBar*) gtk_action_bar_new ();
#line 38 "../src/Widgets/StatusBar.vala"
	g_object_ref_sink (_tmp1_);
#line 38 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->actionbar);
#line 38 "../src/Widgets/StatusBar.vala"
	self->actionbar = _tmp1_;
#line 40 "../src/Widgets/StatusBar.vala"
	_tmp2_ = self->actionbar;
#line 40 "../src/Widgets/StatusBar.vala"
	_tmp3_ = gtk_widget_get_style_context ((GtkWidget*) _tmp2_);
#line 40 "../src/Widgets/StatusBar.vala"
	_tmp4_ = _g_object_ref0 (_tmp3_);
#line 40 "../src/Widgets/StatusBar.vala"
	sb_context = _tmp4_;
#line 41 "../src/Widgets/StatusBar.vala"
	_tmp5_ = sb_context;
#line 41 "../src/Widgets/StatusBar.vala"
	gtk_style_context_add_class (_tmp5_, "statusbar");
#line 43 "../src/Widgets/StatusBar.vala"
	_tmp6_ = (GtkRadioButton*) gtk_radio_button_new_with_label (NULL, _ ("Words"));
#line 43 "../src/Widgets/StatusBar.vala"
	g_object_ref_sink (_tmp6_);
#line 43 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->track_words);
#line 43 "../src/Widgets/StatusBar.vala"
	self->track_words = _tmp6_;
#line 44 "../src/Widgets/StatusBar.vala"
	_tmp7_ = self->track_words;
#line 44 "../src/Widgets/StatusBar.vala"
	g_signal_connect_object ((GtkToggleButton*) _tmp7_, "toggled", (GCallback) ___lambda11__gtk_toggle_button_toggled, self, 0);
#line 49 "../src/Widgets/StatusBar.vala"
	_tmp8_ = self->track_words;
#line 49 "../src/Widgets/StatusBar.vala"
	_tmp9_ = (GtkRadioButton*) gtk_radio_button_new_with_label_from_widget (_tmp8_, _ ("Lines"));
#line 49 "../src/Widgets/StatusBar.vala"
	g_object_ref_sink (_tmp9_);
#line 49 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->track_lines);
#line 49 "../src/Widgets/StatusBar.vala"
	self->track_lines = _tmp9_;
#line 50 "../src/Widgets/StatusBar.vala"
	_tmp10_ = self->track_lines;
#line 50 "../src/Widgets/StatusBar.vala"
	g_signal_connect_object ((GtkToggleButton*) _tmp10_, "toggled", (GCallback) ___lambda12__gtk_toggle_button_toggled, self, 0);
#line 55 "../src/Widgets/StatusBar.vala"
	_tmp11_ = self->track_words;
#line 55 "../src/Widgets/StatusBar.vala"
	_tmp12_ = (GtkRadioButton*) gtk_radio_button_new_with_label_from_widget (_tmp11_, _ ("Reading Time"));
#line 55 "../src/Widgets/StatusBar.vala"
	g_object_ref_sink (_tmp12_);
#line 55 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->track_rtc);
#line 55 "../src/Widgets/StatusBar.vala"
	self->track_rtc = _tmp12_;
#line 56 "../src/Widgets/StatusBar.vala"
	_tmp13_ = self->track_rtc;
#line 56 "../src/Widgets/StatusBar.vala"
	g_signal_connect_object ((GtkToggleButton*) _tmp13_, "toggled", (GCallback) ___lambda13__gtk_toggle_button_toggled, self, 0);
#line 61 "../src/Widgets/StatusBar.vala"
	_tmp14_ = (GtkGrid*) gtk_grid_new ();
#line 61 "../src/Widgets/StatusBar.vala"
	g_object_ref_sink (_tmp14_);
#line 61 "../src/Widgets/StatusBar.vala"
	track_type_grid = _tmp14_;
#line 62 "../src/Widgets/StatusBar.vala"
	_tmp15_ = track_type_grid;
#line 62 "../src/Widgets/StatusBar.vala"
	g_object_set ((GtkWidget*) _tmp15_, "margin", 12, NULL);
#line 63 "../src/Widgets/StatusBar.vala"
	_tmp16_ = track_type_grid;
#line 63 "../src/Widgets/StatusBar.vala"
	gtk_grid_set_row_spacing (_tmp16_, 12);
#line 64 "../src/Widgets/StatusBar.vala"
	_tmp17_ = track_type_grid;
#line 64 "../src/Widgets/StatusBar.vala"
	gtk_grid_set_column_spacing (_tmp17_, 12);
#line 65 "../src/Widgets/StatusBar.vala"
	_tmp18_ = track_type_grid;
#line 65 "../src/Widgets/StatusBar.vala"
	gtk_orientable_set_orientation ((GtkOrientable*) _tmp18_, GTK_ORIENTATION_VERTICAL);
#line 66 "../src/Widgets/StatusBar.vala"
	_tmp19_ = track_type_grid;
#line 66 "../src/Widgets/StatusBar.vala"
	_tmp20_ = self->track_words;
#line 66 "../src/Widgets/StatusBar.vala"
	gtk_container_add ((GtkContainer*) _tmp19_, (GtkWidget*) _tmp20_);
#line 67 "../src/Widgets/StatusBar.vala"
	_tmp21_ = track_type_grid;
#line 67 "../src/Widgets/StatusBar.vala"
	_tmp22_ = self->track_lines;
#line 67 "../src/Widgets/StatusBar.vala"
	gtk_container_add ((GtkContainer*) _tmp21_, (GtkWidget*) _tmp22_);
#line 68 "../src/Widgets/StatusBar.vala"
	_tmp23_ = track_type_grid;
#line 68 "../src/Widgets/StatusBar.vala"
	_tmp24_ = self->track_rtc;
#line 68 "../src/Widgets/StatusBar.vala"
	gtk_container_add ((GtkContainer*) _tmp23_, (GtkWidget*) _tmp24_);
#line 69 "../src/Widgets/StatusBar.vala"
	_tmp25_ = track_type_grid;
#line 69 "../src/Widgets/StatusBar.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp25_);
#line 71 "../src/Widgets/StatusBar.vala"
	_tmp26_ = (GtkPopover*) gtk_popover_new (NULL);
#line 71 "../src/Widgets/StatusBar.vala"
	g_object_ref_sink (_tmp26_);
#line 71 "../src/Widgets/StatusBar.vala"
	track_type_menu_pop = _tmp26_;
#line 72 "../src/Widgets/StatusBar.vala"
	_tmp27_ = track_type_menu_pop;
#line 72 "../src/Widgets/StatusBar.vala"
	_tmp28_ = track_type_grid;
#line 72 "../src/Widgets/StatusBar.vala"
	gtk_container_add ((GtkContainer*) _tmp27_, (GtkWidget*) _tmp28_);
#line 74 "../src/Widgets/StatusBar.vala"
	_tmp29_ = (GtkMenuButton*) gtk_menu_button_new ();
#line 74 "../src/Widgets/StatusBar.vala"
	g_object_ref_sink (_tmp29_);
#line 74 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->track_type_menu);
#line 74 "../src/Widgets/StatusBar.vala"
	self->track_type_menu = _tmp29_;
#line 75 "../src/Widgets/StatusBar.vala"
	_tmp30_ = self->track_type_menu;
#line 75 "../src/Widgets/StatusBar.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp30_, _ ("Set Tracking Type"));
#line 76 "../src/Widgets/StatusBar.vala"
	_tmp31_ = self->track_type_menu;
#line 76 "../src/Widgets/StatusBar.vala"
	_tmp32_ = track_type_menu_pop;
#line 76 "../src/Widgets/StatusBar.vala"
	gtk_menu_button_set_popover (_tmp31_, _tmp32_);
#line 77 "../src/Widgets/StatusBar.vala"
	_tmp33_ = self->track_type_menu;
#line 77 "../src/Widgets/StatusBar.vala"
	gtk_button_set_label ((GtkButton*) _tmp33_, "");
#line 79 "../src/Widgets/StatusBar.vala"
	_tmp34_ = self->track_type_menu;
#line 79 "../src/Widgets/StatusBar.vala"
	_tmp35_ = gtk_widget_get_style_context ((GtkWidget*) _tmp34_);
#line 79 "../src/Widgets/StatusBar.vala"
	_tmp36_ = _g_object_ref0 (_tmp35_);
#line 79 "../src/Widgets/StatusBar.vala"
	menu_context = _tmp36_;
#line 80 "../src/Widgets/StatusBar.vala"
	_tmp37_ = menu_context;
#line 80 "../src/Widgets/StatusBar.vala"
	gtk_style_context_add_class (_tmp37_, "quilter-menu");
#line 81 "../src/Widgets/StatusBar.vala"
	_tmp38_ = menu_context;
#line 81 "../src/Widgets/StatusBar.vala"
	gtk_style_context_add_class (_tmp38_, GTK_STYLE_CLASS_FLAT);
#line 83 "../src/Widgets/StatusBar.vala"
	_tmp39_ = self->actionbar;
#line 83 "../src/Widgets/StatusBar.vala"
	_tmp40_ = self->track_type_menu;
#line 83 "../src/Widgets/StatusBar.vala"
	gtk_action_bar_pack_end (_tmp39_, (GtkWidget*) _tmp40_);
#line 85 "../src/Widgets/StatusBar.vala"
	_tmp41_ = quilter_application_gsettings;
#line 85 "../src/Widgets/StatusBar.vala"
	_tmp42_ = g_settings_get_string (_tmp41_, "track-type");
#line 85 "../src/Widgets/StatusBar.vala"
	_tmp43_ = _tmp42_;
#line 85 "../src/Widgets/StatusBar.vala"
	_tmp44_ = g_strcmp0 (_tmp43_, "words") == 0;
#line 85 "../src/Widgets/StatusBar.vala"
	_g_free0 (_tmp43_);
#line 85 "../src/Widgets/StatusBar.vala"
	if (_tmp44_) {
#line 86 "../src/Widgets/StatusBar.vala"
		quilter_widgets_status_bar_update_wordcount (self);
#line 506 "StatusBar.c"
	} else {
		GSettings* _tmp45_;
		gchar* _tmp46_;
		gchar* _tmp47_;
		gboolean _tmp48_;
#line 87 "../src/Widgets/StatusBar.vala"
		_tmp45_ = quilter_application_gsettings;
#line 87 "../src/Widgets/StatusBar.vala"
		_tmp46_ = g_settings_get_string (_tmp45_, "track-type");
#line 87 "../src/Widgets/StatusBar.vala"
		_tmp47_ = _tmp46_;
#line 87 "../src/Widgets/StatusBar.vala"
		_tmp48_ = g_strcmp0 (_tmp47_, "lines") == 0;
#line 87 "../src/Widgets/StatusBar.vala"
		_g_free0 (_tmp47_);
#line 87 "../src/Widgets/StatusBar.vala"
		if (_tmp48_) {
#line 88 "../src/Widgets/StatusBar.vala"
			quilter_widgets_status_bar_update_linecount (self);
#line 526 "StatusBar.c"
		} else {
			GSettings* _tmp49_;
			gchar* _tmp50_;
			gchar* _tmp51_;
			gboolean _tmp52_;
#line 89 "../src/Widgets/StatusBar.vala"
			_tmp49_ = quilter_application_gsettings;
#line 89 "../src/Widgets/StatusBar.vala"
			_tmp50_ = g_settings_get_string (_tmp49_, "track-type");
#line 89 "../src/Widgets/StatusBar.vala"
			_tmp51_ = _tmp50_;
#line 89 "../src/Widgets/StatusBar.vala"
			_tmp52_ = g_strcmp0 (_tmp51_, "rtc") == 0;
#line 89 "../src/Widgets/StatusBar.vala"
			_g_free0 (_tmp51_);
#line 89 "../src/Widgets/StatusBar.vala"
			if (_tmp52_) {
#line 90 "../src/Widgets/StatusBar.vala"
				quilter_widgets_status_bar_update_readtimecount (self);
#line 546 "StatusBar.c"
			}
		}
	}
#line 93 "../src/Widgets/StatusBar.vala"
	gtk_revealer_set_transition_type ((GtkRevealer*) self, GTK_REVEALER_TRANSITION_TYPE_SLIDE_UP);
#line 94 "../src/Widgets/StatusBar.vala"
	_tmp53_ = self->actionbar;
#line 94 "../src/Widgets/StatusBar.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp53_);
#line 95 "../src/Widgets/StatusBar.vala"
	_tmp54_ = quilter_application_gsettings;
#line 95 "../src/Widgets/StatusBar.vala"
	gtk_revealer_set_reveal_child ((GtkRevealer*) self, g_settings_get_boolean (_tmp54_, "statusbar"));
#line 35 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (menu_context);
#line 35 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (track_type_menu_pop);
#line 35 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (track_type_grid);
#line 35 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (sb_context);
#line 35 "../src/Widgets/StatusBar.vala"
	return self;
#line 570 "StatusBar.c"
}

QuilterWidgetsStatusBar*
quilter_widgets_status_bar_new (GtkSourceBuffer* buf)
{
#line 35 "../src/Widgets/StatusBar.vala"
	return quilter_widgets_status_bar_construct (QUILTER_WIDGETS_TYPE_STATUS_BAR, buf);
#line 578 "StatusBar.c"
}

void
quilter_widgets_status_bar_update_wordcount (QuilterWidgetsStatusBar* self)
{
	QuilterWidgetsWordCount* wc = NULL;
	QuilterWidgetsWordCount* _tmp0_;
	GtkMenuButton* _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
#line 98 "../src/Widgets/StatusBar.vala"
	g_return_if_fail (self != NULL);
#line 99 "../src/Widgets/StatusBar.vala"
	_tmp0_ = quilter_widgets_status_bar_get_count (self);
#line 99 "../src/Widgets/StatusBar.vala"
	wc = _tmp0_;
#line 100 "../src/Widgets/StatusBar.vala"
	_tmp1_ = self->track_type_menu;
#line 100 "../src/Widgets/StatusBar.vala"
	_tmp2_ = quilter_widgets_word_count_get_words (wc);
#line 100 "../src/Widgets/StatusBar.vala"
	_tmp3_ = _tmp2_;
#line 100 "../src/Widgets/StatusBar.vala"
	_tmp4_ = g_strdup_printf ("%i", _tmp3_);
#line 100 "../src/Widgets/StatusBar.vala"
	_tmp5_ = _tmp4_;
#line 100 "../src/Widgets/StatusBar.vala"
	_tmp6_ = g_strconcat (_ ("Words: "), _tmp5_, NULL);
#line 100 "../src/Widgets/StatusBar.vala"
	_tmp7_ = _tmp6_;
#line 100 "../src/Widgets/StatusBar.vala"
	gtk_button_set_label ((GtkButton*) _tmp1_, _tmp7_);
#line 100 "../src/Widgets/StatusBar.vala"
	_g_free0 (_tmp7_);
#line 100 "../src/Widgets/StatusBar.vala"
	_g_free0 (_tmp5_);
#line 98 "../src/Widgets/StatusBar.vala"
	_quilter_widgets_word_count_unref0 (wc);
#line 621 "StatusBar.c"
}

void
quilter_widgets_status_bar_update_linecount (QuilterWidgetsStatusBar* self)
{
	QuilterWidgetsWordCount* lc = NULL;
	QuilterWidgetsWordCount* _tmp0_;
	GtkMenuButton* _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
#line 103 "../src/Widgets/StatusBar.vala"
	g_return_if_fail (self != NULL);
#line 104 "../src/Widgets/StatusBar.vala"
	_tmp0_ = quilter_widgets_status_bar_get_count (self);
#line 104 "../src/Widgets/StatusBar.vala"
	lc = _tmp0_;
#line 105 "../src/Widgets/StatusBar.vala"
	_tmp1_ = self->track_type_menu;
#line 105 "../src/Widgets/StatusBar.vala"
	_tmp2_ = quilter_widgets_word_count_get_lines (lc);
#line 105 "../src/Widgets/StatusBar.vala"
	_tmp3_ = _tmp2_;
#line 105 "../src/Widgets/StatusBar.vala"
	_tmp4_ = g_strdup_printf ("%i", _tmp3_);
#line 105 "../src/Widgets/StatusBar.vala"
	_tmp5_ = _tmp4_;
#line 105 "../src/Widgets/StatusBar.vala"
	_tmp6_ = g_strconcat (_ ("Lines: "), _tmp5_, NULL);
#line 105 "../src/Widgets/StatusBar.vala"
	_tmp7_ = _tmp6_;
#line 105 "../src/Widgets/StatusBar.vala"
	gtk_button_set_label ((GtkButton*) _tmp1_, _tmp7_);
#line 105 "../src/Widgets/StatusBar.vala"
	_g_free0 (_tmp7_);
#line 105 "../src/Widgets/StatusBar.vala"
	_g_free0 (_tmp5_);
#line 103 "../src/Widgets/StatusBar.vala"
	_quilter_widgets_word_count_unref0 (lc);
#line 664 "StatusBar.c"
}

void
quilter_widgets_status_bar_update_readtimecount (QuilterWidgetsStatusBar* self)
{
	QuilterWidgetsWordCount* rtc = NULL;
	QuilterWidgetsWordCount* _tmp0_;
	gfloat rt = 0.0F;
	gint _tmp1_;
	gint _tmp2_;
	GtkMenuButton* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
#line 108 "../src/Widgets/StatusBar.vala"
	g_return_if_fail (self != NULL);
#line 109 "../src/Widgets/StatusBar.vala"
	_tmp0_ = quilter_widgets_status_bar_get_count (self);
#line 109 "../src/Widgets/StatusBar.vala"
	rtc = _tmp0_;
#line 110 "../src/Widgets/StatusBar.vala"
	_tmp1_ = quilter_widgets_word_count_get_words (rtc);
#line 110 "../src/Widgets/StatusBar.vala"
	_tmp2_ = _tmp1_;
#line 110 "../src/Widgets/StatusBar.vala"
	rt = (gfloat) (_tmp2_ / self->priv->WPM);
#line 111 "../src/Widgets/StatusBar.vala"
	g_print ("%f", (gdouble) rt);
#line 112 "../src/Widgets/StatusBar.vala"
	_tmp3_ = self->track_type_menu;
#line 112 "../src/Widgets/StatusBar.vala"
	_tmp4_ = g_strdup_printf ("%g", rt);
#line 112 "../src/Widgets/StatusBar.vala"
	_tmp5_ = _tmp4_;
#line 112 "../src/Widgets/StatusBar.vala"
	_tmp6_ = g_strconcat (_ ("Reading Time: "), _tmp5_, NULL);
#line 112 "../src/Widgets/StatusBar.vala"
	_tmp7_ = _tmp6_;
#line 112 "../src/Widgets/StatusBar.vala"
	_tmp8_ = g_strconcat (_tmp7_, "m", NULL);
#line 112 "../src/Widgets/StatusBar.vala"
	_tmp9_ = _tmp8_;
#line 112 "../src/Widgets/StatusBar.vala"
	gtk_button_set_label ((GtkButton*) _tmp3_, _tmp9_);
#line 112 "../src/Widgets/StatusBar.vala"
	_g_free0 (_tmp9_);
#line 112 "../src/Widgets/StatusBar.vala"
	_g_free0 (_tmp7_);
#line 112 "../src/Widgets/StatusBar.vala"
	_g_free0 (_tmp5_);
#line 108 "../src/Widgets/StatusBar.vala"
	_quilter_widgets_word_count_unref0 (rtc);
#line 720 "StatusBar.c"
}

QuilterWidgetsWordCount*
quilter_widgets_status_bar_get_count (QuilterWidgetsStatusBar* self)
{
	GtkTextIter start = {0};
	GtkTextIter end = {0};
	GtkSourceBuffer* _tmp0_;
	GtkTextIter _tmp1_ = {0};
	GtkTextIter _tmp2_ = {0};
	gint lines = 0;
	GtkSourceBuffer* _tmp3_;
	gint words = 0;
	GtkSourceBuffer* _tmp4_;
	GtkTextIter _tmp5_;
	GtkTextIter _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar** _tmp9_;
	gchar** _tmp10_;
	gchar** _tmp11_;
	gint _tmp11__length1;
	gint _tmp12_;
	QuilterWidgetsWordCount* _tmp13_;
	QuilterWidgetsWordCount* result = NULL;
#line 115 "../src/Widgets/StatusBar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 117 "../src/Widgets/StatusBar.vala"
	_tmp0_ = self->buf;
#line 117 "../src/Widgets/StatusBar.vala"
	gtk_text_buffer_get_bounds ((GtkTextBuffer*) _tmp0_, &_tmp1_, &_tmp2_);
#line 117 "../src/Widgets/StatusBar.vala"
	start = _tmp1_;
#line 117 "../src/Widgets/StatusBar.vala"
	end = _tmp2_;
#line 118 "../src/Widgets/StatusBar.vala"
	_tmp3_ = self->buf;
#line 118 "../src/Widgets/StatusBar.vala"
	lines = gtk_text_buffer_get_line_count ((GtkTextBuffer*) _tmp3_);
#line 119 "../src/Widgets/StatusBar.vala"
	_tmp4_ = self->buf;
#line 119 "../src/Widgets/StatusBar.vala"
	_tmp5_ = start;
#line 119 "../src/Widgets/StatusBar.vala"
	_tmp6_ = end;
#line 119 "../src/Widgets/StatusBar.vala"
	_tmp7_ = gtk_text_buffer_get_text ((GtkTextBuffer*) _tmp4_, &_tmp5_, &_tmp6_, FALSE);
#line 119 "../src/Widgets/StatusBar.vala"
	_tmp8_ = _tmp7_;
#line 119 "../src/Widgets/StatusBar.vala"
	_tmp10_ = _tmp9_ = g_strsplit (_tmp8_, " ", 0);
#line 119 "../src/Widgets/StatusBar.vala"
	_tmp11_ = _tmp10_;
#line 119 "../src/Widgets/StatusBar.vala"
	_tmp11__length1 = _vala_array_length (_tmp9_);
#line 119 "../src/Widgets/StatusBar.vala"
	_tmp12_ = _vala_array_length (_tmp9_);
#line 119 "../src/Widgets/StatusBar.vala"
	_tmp11_ = (_vala_array_free (_tmp11_, _tmp11__length1, (GDestroyNotify) g_free), NULL);
#line 119 "../src/Widgets/StatusBar.vala"
	_g_free0 (_tmp8_);
#line 119 "../src/Widgets/StatusBar.vala"
	words = _tmp12_;
#line 121 "../src/Widgets/StatusBar.vala"
	_tmp13_ = quilter_widgets_word_count_new (words, lines);
#line 121 "../src/Widgets/StatusBar.vala"
	result = _tmp13_;
#line 121 "../src/Widgets/StatusBar.vala"
	return result;
#line 790 "StatusBar.c"
}

static void
quilter_widgets_status_bar_class_init (QuilterWidgetsStatusBarClass * klass,
                                       gpointer klass_data)
{
#line 20 "../src/Widgets/StatusBar.vala"
	quilter_widgets_status_bar_parent_class = g_type_class_peek_parent (klass);
#line 20 "../src/Widgets/StatusBar.vala"
	g_type_class_adjust_private_offset (klass, &QuilterWidgetsStatusBar_private_offset);
#line 20 "../src/Widgets/StatusBar.vala"
	G_OBJECT_CLASS (klass)->finalize = quilter_widgets_status_bar_finalize;
#line 803 "StatusBar.c"
}

static void
quilter_widgets_status_bar_instance_init (QuilterWidgetsStatusBar * self,
                                          gpointer klass)
{
#line 20 "../src/Widgets/StatusBar.vala"
	self->priv = quilter_widgets_status_bar_get_instance_private (self);
#line 33 "../src/Widgets/StatusBar.vala"
	self->priv->WPM = 200;
#line 814 "StatusBar.c"
}

static void
quilter_widgets_status_bar_finalize (GObject * obj)
{
	QuilterWidgetsStatusBar * self;
#line 20 "../src/Widgets/StatusBar.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_WIDGETS_TYPE_STATUS_BAR, QuilterWidgetsStatusBar);
#line 21 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->actionbar);
#line 22 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->linecount_label);
#line 23 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->wordcount_label);
#line 24 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->preview_type_menu);
#line 25 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->track_type_menu);
#line 26 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->buf);
#line 27 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->track_words);
#line 28 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->track_lines);
#line 29 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->track_rtc);
#line 30 "../src/Widgets/StatusBar.vala"
	_g_object_unref0 (self->window);
#line 20 "../src/Widgets/StatusBar.vala"
	G_OBJECT_CLASS (quilter_widgets_status_bar_parent_class)->finalize (obj);
#line 845 "StatusBar.c"
}

static GType
quilter_widgets_status_bar_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (QuilterWidgetsStatusBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_widgets_status_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterWidgetsStatusBar), 0, (GInstanceInitFunc) quilter_widgets_status_bar_instance_init, NULL };
	GType quilter_widgets_status_bar_type_id;
	quilter_widgets_status_bar_type_id = g_type_register_static (gtk_revealer_get_type (), "QuilterWidgetsStatusBar", &g_define_type_info, 0);
	QuilterWidgetsStatusBar_private_offset = g_type_add_instance_private (quilter_widgets_status_bar_type_id, sizeof (QuilterWidgetsStatusBarPrivate));
	return quilter_widgets_status_bar_type_id;
}

GType
quilter_widgets_status_bar_get_type (void)
{
	static volatile gsize quilter_widgets_status_bar_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_widgets_status_bar_type_id__volatile)) {
		GType quilter_widgets_status_bar_type_id;
		quilter_widgets_status_bar_type_id = quilter_widgets_status_bar_get_type_once ();
		g_once_init_leave (&quilter_widgets_status_bar_type_id__volatile, quilter_widgets_status_bar_type_id);
	}
	return quilter_widgets_status_bar_type_id__volatile;
}

static inline gpointer
quilter_widgets_word_count_get_instance_private (QuilterWidgetsWordCount* self)
{
	return G_STRUCT_MEMBER_P (self, QuilterWidgetsWordCount_private_offset);
}

QuilterWidgetsWordCount*
quilter_widgets_word_count_construct (GType object_type,
                                      gint words,
                                      gint lines)
{
	QuilterWidgetsWordCount* self = NULL;
#line 129 "../src/Widgets/StatusBar.vala"
	self = (QuilterWidgetsWordCount*) g_type_create_instance (object_type);
#line 130 "../src/Widgets/StatusBar.vala"
	quilter_widgets_word_count_set_words (self, words);
#line 131 "../src/Widgets/StatusBar.vala"
	quilter_widgets_word_count_set_lines (self, lines);
#line 129 "../src/Widgets/StatusBar.vala"
	return self;
#line 890 "StatusBar.c"
}

QuilterWidgetsWordCount*
quilter_widgets_word_count_new (gint words,
                                gint lines)
{
#line 129 "../src/Widgets/StatusBar.vala"
	return quilter_widgets_word_count_construct (QUILTER_WIDGETS_TYPE_WORD_COUNT, words, lines);
#line 899 "StatusBar.c"
}

gint
quilter_widgets_word_count_get_words (QuilterWidgetsWordCount* self)
{
	gint result;
#line 126 "../src/Widgets/StatusBar.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 126 "../src/Widgets/StatusBar.vala"
	result = self->priv->_words;
#line 126 "../src/Widgets/StatusBar.vala"
	return result;
#line 912 "StatusBar.c"
}

static void
quilter_widgets_word_count_set_words (QuilterWidgetsWordCount* self,
                                      gint value)
{
#line 126 "../src/Widgets/StatusBar.vala"
	g_return_if_fail (self != NULL);
#line 126 "../src/Widgets/StatusBar.vala"
	self->priv->_words = value;
#line 923 "StatusBar.c"
}

gint
quilter_widgets_word_count_get_lines (QuilterWidgetsWordCount* self)
{
	gint result;
#line 127 "../src/Widgets/StatusBar.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 127 "../src/Widgets/StatusBar.vala"
	result = self->priv->_lines;
#line 127 "../src/Widgets/StatusBar.vala"
	return result;
#line 936 "StatusBar.c"
}

static void
quilter_widgets_word_count_set_lines (QuilterWidgetsWordCount* self,
                                      gint value)
{
#line 127 "../src/Widgets/StatusBar.vala"
	g_return_if_fail (self != NULL);
#line 127 "../src/Widgets/StatusBar.vala"
	self->priv->_lines = value;
#line 947 "StatusBar.c"
}

static void
quilter_widgets_value_word_count_init (GValue* value)
{
#line 125 "../src/Widgets/StatusBar.vala"
	value->data[0].v_pointer = NULL;
#line 955 "StatusBar.c"
}

static void
quilter_widgets_value_word_count_free_value (GValue* value)
{
#line 125 "../src/Widgets/StatusBar.vala"
	if (value->data[0].v_pointer) {
#line 125 "../src/Widgets/StatusBar.vala"
		quilter_widgets_word_count_unref (value->data[0].v_pointer);
#line 965 "StatusBar.c"
	}
}

static void
quilter_widgets_value_word_count_copy_value (const GValue* src_value,
                                             GValue* dest_value)
{
#line 125 "../src/Widgets/StatusBar.vala"
	if (src_value->data[0].v_pointer) {
#line 125 "../src/Widgets/StatusBar.vala"
		dest_value->data[0].v_pointer = quilter_widgets_word_count_ref (src_value->data[0].v_pointer);
#line 977 "StatusBar.c"
	} else {
#line 125 "../src/Widgets/StatusBar.vala"
		dest_value->data[0].v_pointer = NULL;
#line 981 "StatusBar.c"
	}
}

static gpointer
quilter_widgets_value_word_count_peek_pointer (const GValue* value)
{
#line 125 "../src/Widgets/StatusBar.vala"
	return value->data[0].v_pointer;
#line 990 "StatusBar.c"
}

static gchar*
quilter_widgets_value_word_count_collect_value (GValue* value,
                                                guint n_collect_values,
                                                GTypeCValue* collect_values,
                                                guint collect_flags)
{
#line 125 "../src/Widgets/StatusBar.vala"
	if (collect_values[0].v_pointer) {
#line 1001 "StatusBar.c"
		QuilterWidgetsWordCount * object;
		object = collect_values[0].v_pointer;
#line 125 "../src/Widgets/StatusBar.vala"
		if (object->parent_instance.g_class == NULL) {
#line 125 "../src/Widgets/StatusBar.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1008 "StatusBar.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 125 "../src/Widgets/StatusBar.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1012 "StatusBar.c"
		}
#line 125 "../src/Widgets/StatusBar.vala"
		value->data[0].v_pointer = quilter_widgets_word_count_ref (object);
#line 1016 "StatusBar.c"
	} else {
#line 125 "../src/Widgets/StatusBar.vala"
		value->data[0].v_pointer = NULL;
#line 1020 "StatusBar.c"
	}
#line 125 "../src/Widgets/StatusBar.vala"
	return NULL;
#line 1024 "StatusBar.c"
}

static gchar*
quilter_widgets_value_word_count_lcopy_value (const GValue* value,
                                              guint n_collect_values,
                                              GTypeCValue* collect_values,
                                              guint collect_flags)
{
	QuilterWidgetsWordCount ** object_p;
	object_p = collect_values[0].v_pointer;
#line 125 "../src/Widgets/StatusBar.vala"
	if (!object_p) {
#line 125 "../src/Widgets/StatusBar.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 1039 "StatusBar.c"
	}
#line 125 "../src/Widgets/StatusBar.vala"
	if (!value->data[0].v_pointer) {
#line 125 "../src/Widgets/StatusBar.vala"
		*object_p = NULL;
#line 1045 "StatusBar.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 125 "../src/Widgets/StatusBar.vala"
		*object_p = value->data[0].v_pointer;
#line 1049 "StatusBar.c"
	} else {
#line 125 "../src/Widgets/StatusBar.vala"
		*object_p = quilter_widgets_word_count_ref (value->data[0].v_pointer);
#line 1053 "StatusBar.c"
	}
#line 125 "../src/Widgets/StatusBar.vala"
	return NULL;
#line 1057 "StatusBar.c"
}

GParamSpec*
quilter_widgets_param_spec_word_count (const gchar* name,
                                       const gchar* nick,
                                       const gchar* blurb,
                                       GType object_type,
                                       GParamFlags flags)
{
	QuilterWidgetsParamSpecWordCount* spec;
#line 125 "../src/Widgets/StatusBar.vala"
	g_return_val_if_fail (g_type_is_a (object_type, QUILTER_WIDGETS_TYPE_WORD_COUNT), NULL);
#line 125 "../src/Widgets/StatusBar.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 125 "../src/Widgets/StatusBar.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 125 "../src/Widgets/StatusBar.vala"
	return G_PARAM_SPEC (spec);
#line 1076 "StatusBar.c"
}

gpointer
quilter_widgets_value_get_word_count (const GValue* value)
{
#line 125 "../src/Widgets/StatusBar.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QUILTER_WIDGETS_TYPE_WORD_COUNT), NULL);
#line 125 "../src/Widgets/StatusBar.vala"
	return value->data[0].v_pointer;
#line 1086 "StatusBar.c"
}

void
quilter_widgets_value_set_word_count (GValue* value,
                                      gpointer v_object)
{
	QuilterWidgetsWordCount * old;
#line 125 "../src/Widgets/StatusBar.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QUILTER_WIDGETS_TYPE_WORD_COUNT));
#line 125 "../src/Widgets/StatusBar.vala"
	old = value->data[0].v_pointer;
#line 125 "../src/Widgets/StatusBar.vala"
	if (v_object) {
#line 125 "../src/Widgets/StatusBar.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, QUILTER_WIDGETS_TYPE_WORD_COUNT));
#line 125 "../src/Widgets/StatusBar.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 125 "../src/Widgets/StatusBar.vala"
		value->data[0].v_pointer = v_object;
#line 125 "../src/Widgets/StatusBar.vala"
		quilter_widgets_word_count_ref (value->data[0].v_pointer);
#line 1108 "StatusBar.c"
	} else {
#line 125 "../src/Widgets/StatusBar.vala"
		value->data[0].v_pointer = NULL;
#line 1112 "StatusBar.c"
	}
#line 125 "../src/Widgets/StatusBar.vala"
	if (old) {
#line 125 "../src/Widgets/StatusBar.vala"
		quilter_widgets_word_count_unref (old);
#line 1118 "StatusBar.c"
	}
}

void
quilter_widgets_value_take_word_count (GValue* value,
                                       gpointer v_object)
{
	QuilterWidgetsWordCount * old;
#line 125 "../src/Widgets/StatusBar.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QUILTER_WIDGETS_TYPE_WORD_COUNT));
#line 125 "../src/Widgets/StatusBar.vala"
	old = value->data[0].v_pointer;
#line 125 "../src/Widgets/StatusBar.vala"
	if (v_object) {
#line 125 "../src/Widgets/StatusBar.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, QUILTER_WIDGETS_TYPE_WORD_COUNT));
#line 125 "../src/Widgets/StatusBar.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 125 "../src/Widgets/StatusBar.vala"
		value->data[0].v_pointer = v_object;
#line 1139 "StatusBar.c"
	} else {
#line 125 "../src/Widgets/StatusBar.vala"
		value->data[0].v_pointer = NULL;
#line 1143 "StatusBar.c"
	}
#line 125 "../src/Widgets/StatusBar.vala"
	if (old) {
#line 125 "../src/Widgets/StatusBar.vala"
		quilter_widgets_word_count_unref (old);
#line 1149 "StatusBar.c"
	}
}

static void
quilter_widgets_word_count_class_init (QuilterWidgetsWordCountClass * klass,
                                       gpointer klass_data)
{
#line 125 "../src/Widgets/StatusBar.vala"
	quilter_widgets_word_count_parent_class = g_type_class_peek_parent (klass);
#line 125 "../src/Widgets/StatusBar.vala"
	((QuilterWidgetsWordCountClass *) klass)->finalize = quilter_widgets_word_count_finalize;
#line 125 "../src/Widgets/StatusBar.vala"
	g_type_class_adjust_private_offset (klass, &QuilterWidgetsWordCount_private_offset);
#line 1163 "StatusBar.c"
}

static void
quilter_widgets_word_count_instance_init (QuilterWidgetsWordCount * self,
                                          gpointer klass)
{
#line 125 "../src/Widgets/StatusBar.vala"
	self->priv = quilter_widgets_word_count_get_instance_private (self);
#line 125 "../src/Widgets/StatusBar.vala"
	self->ref_count = 1;
#line 1174 "StatusBar.c"
}

static void
quilter_widgets_word_count_finalize (QuilterWidgetsWordCount * obj)
{
	QuilterWidgetsWordCount * self;
#line 125 "../src/Widgets/StatusBar.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_WIDGETS_TYPE_WORD_COUNT, QuilterWidgetsWordCount);
#line 125 "../src/Widgets/StatusBar.vala"
	g_signal_handlers_destroy (self);
#line 1185 "StatusBar.c"
}

static GType
quilter_widgets_word_count_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { quilter_widgets_value_word_count_init, quilter_widgets_value_word_count_free_value, quilter_widgets_value_word_count_copy_value, quilter_widgets_value_word_count_peek_pointer, "p", quilter_widgets_value_word_count_collect_value, "p", quilter_widgets_value_word_count_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (QuilterWidgetsWordCountClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_widgets_word_count_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterWidgetsWordCount), 0, (GInstanceInitFunc) quilter_widgets_word_count_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType quilter_widgets_word_count_type_id;
	quilter_widgets_word_count_type_id = g_type_register_fundamental (g_type_fundamental_next (), "QuilterWidgetsWordCount", &g_define_type_info, &g_define_type_fundamental_info, 0);
	QuilterWidgetsWordCount_private_offset = g_type_add_instance_private (quilter_widgets_word_count_type_id, sizeof (QuilterWidgetsWordCountPrivate));
	return quilter_widgets_word_count_type_id;
}

GType
quilter_widgets_word_count_get_type (void)
{
	static volatile gsize quilter_widgets_word_count_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_widgets_word_count_type_id__volatile)) {
		GType quilter_widgets_word_count_type_id;
		quilter_widgets_word_count_type_id = quilter_widgets_word_count_get_type_once ();
		g_once_init_leave (&quilter_widgets_word_count_type_id__volatile, quilter_widgets_word_count_type_id);
	}
	return quilter_widgets_word_count_type_id__volatile;
}

gpointer
quilter_widgets_word_count_ref (gpointer instance)
{
	QuilterWidgetsWordCount * self;
	self = instance;
#line 125 "../src/Widgets/StatusBar.vala"
	g_atomic_int_inc (&self->ref_count);
#line 125 "../src/Widgets/StatusBar.vala"
	return instance;
#line 1221 "StatusBar.c"
}

void
quilter_widgets_word_count_unref (gpointer instance)
{
	QuilterWidgetsWordCount * self;
	self = instance;
#line 125 "../src/Widgets/StatusBar.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 125 "../src/Widgets/StatusBar.vala"
		QUILTER_WIDGETS_WORD_COUNT_GET_CLASS (self)->finalize (self);
#line 125 "../src/Widgets/StatusBar.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1235 "StatusBar.c"
	}
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gint i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gint
_vala_array_length (gpointer array)
{
	gint length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

