import Foundation

/// Compiled phrase sets for the optional writing-style checks.
///
/// Keeping these expressions separate from the syntax highlighter makes the
/// editor's Markdown rules easier to scan and lets the phrase vocabulary grow
/// without making the rendering code harder to maintain.
@MainActor
enum MarkdownStyleCheckerExpressions {
    private static let clichePhrases: [String] = [
        "all walks of life",
        "at the end of the day",
        "avoid like the plague",
        "better late than never",
        "calm before the storm",
        "diamond in the rough",
        "easy as pie",
        "few and far between",
        "fit as a fiddle",
        "in the nick of time",
        "in this day and age",
        "last but not least",
        "light at the end of the tunnel",
        "needle in a haystack",
        "read between the lines",
        "the rest is history",
        "think outside the box",
        "time will tell",
        "tip of the iceberg",
        "when all is said and done",
        "a dime a dozen",
        "a picture is worth a thousand words",
        "a word to the wise",
        "actions speak louder than words",
        "add insult to injury",
        "all things considered",
        "an ounce of prevention",
        "another day another dollar",
        "back to square one",
        "back to the drawing board",
        "barking up the wrong tree",
        "beat around the bush",
        "bend over backwards",
        "best of both worlds",
        "bite the bullet",
        "blessing in disguise",
        "boil the ocean",
        "break a leg",
        "break the ice",
        "bring to the table",
        "burn the midnight oil",
        "by the same token",
        "call it a day",
        "can of worms",
        "chip on your shoulder",
        "close but no cigar",
        "cold hard facts",
        "come full circle",
        "common ground",
        "compare apples to oranges",
        "cover all the bases",
        "cross that bridge when we come to it",
        "crystal clear",
        "cut to the chase",
        "deep dive",
        "devil's advocate",
        "don't put all your eggs in one basket",
        "down to the wire",
        "drop in the bucket",
        "elephant in the room",
        "every cloud has a silver lining",
        "face the music",
        "fair and square",
        "from the ground up",
        "get the ball rolling",
        "get your ducks in a row",
        "give it a shot",
        "go the extra mile",
        "grass is always greener",
        "green light",
        "hands down",
        "hang in there",
        "hard pill to swallow",
        "head over heels",
        "hear it through the grapevine",
        "hit the ground running",
        "hit the nail on the head",
        "in a nutshell",
        "in broad daylight",
        "in hot water",
        "in the driver's seat",
        "in the long run",
        "in the same boat",
        "it takes two to tango",
        "jump on the bandwagon",
        "keep an eye on",
        "keep your eyes peeled",
        "kick the can down the road",
        "kill two birds with one stone",
        "know the ropes",
        "leave no stone unturned",
        "let the cat out of the bag",
        "level playing field",
        "low-hanging fruit",
        "make a long story short",
        "miss the boat",
        "move the needle",
        "once in a blue moon",
        "on the same page",
        "open a can of worms",
        "out of the blue",
        "outside the box",
        "par for the course",
        "piece of cake",
        "play devil's advocate",
        "put a spin on",
        "put your best foot forward",
        "raise the bar",
        "read the writing on the wall",
        "reinvent the wheel",
        "rock the boat",
        "run like clockwork",
        "rule of thumb",
        "safe and sound",
        "see eye to eye",
        "speak of the devil",
        "stand the test of time",
        "state of the art",
        "steal someone's thunder",
        "step up to the plate",
        "straight from the horse's mouth",
        "sweep under the rug",
        "take it to the next level",
        "take the bull by the horns",
        "the bottom line",
        "the best thing since sliced bread",
        "the big picture",
        "the calm before the storm",
        "the elephant in the room",
        "the last straw",
        "the powers that be",
        "the tip of the iceberg",
        "throw in the towel",
        "throw out the baby with the bathwater",
        "through thick and thin",
        "toe the line",
        "touch base",
        "turn over a new leaf",
        "under the weather",
        "up in the air",
        "walk a fine line",
        "water under the bridge",
        "weather the storm",
        "whole nine yards",
        "wild goose chase",
        "win-win situation",
        "you can't judge a book by its cover",
        "a level playing field",
        "a match made in heaven",
        "a needle in a haystack",
        "a perfect storm",
        "a recipe for disaster",
        "a rough patch",
        "a shot in the dark",
        "a slippery slope",
        "a step in the right direction",
        "a storm in a teacup",
        "a taste of your own medicine",
        "a tough nut to crack",
        "a turning point",
        "a wake-up call",
        "all in the same boat",
        "all roads lead to Rome",
        "at the drop of a hat",
        "at your fingertips",
        "back against the wall",
        "behind the scenes",
        "bigger fish to fry",
        "by leaps and bounds",
        "change of heart",
        "clear as mud",
        "come rain or shine",
        "cost an arm and a leg",
        "cut corners",
        "dead in the water",
        "draw a line in the sand",
        "easier said than done",
        "every now and then",
        "fit the bill",
        "fly under the radar",
        "from time to time",
        "go down in history",
        "go with the flow",
        "in full swing",
        "in the same vein",
        "jump through hoops",
        "keep the wolves from the door",
        "know it like the back of your hand",
        "leave well enough alone",
        "make ends meet",
        "on thin ice",
        "pull out all the stops",
        "put two and two together",
        "rise to the occasion",
        "see the light",
        "sit on the fence",
        "speak volumes",
        "the writing on the wall",
        "throw caution to the wind",
        "turn a blind eye",
        "up to speed",
        "wear many hats",
        "when push comes to shove",
        "you name it"
    ]

    private static let redundancyPhrases: [String] = [
        "absolutely essential",
        "actual fact",
        "advance planning",
        "basic fundamentals",
        "close proximity",
        "each and every",
        "end result",
        "final outcome",
        "free gift",
        "future plans",
        "new innovation",
        "past experience",
        "past history",
        "PIN number",
        "revert back",
        "repeat again",
        "sudden surprise",
        "unexpected surprise",
        "added bonus",
        "advance warning",
        "all of",
        "as for example",
        "assembled together",
        "at the present time",
        "attach together",
        "autobiography of my life",
        "bare bones",
        "biography of her life",
        "brief moment",
        "brief summary",
        "burning fire",
        "cease and desist",
        "circle around",
        "classify into groups",
        "collaborate together",
        "combine together",
        "consensus of opinion",
        "continue on",
        "currently being",
        "currently now",
        "depreciate in value",
        "descend down",
        "different variations",
        "divide up",
        "down below",
        "drop down",
        "empty space",
        "enclosed inside",
        "equally as",
        "estimated roughly",
        "exact same",
        "export out",
        "fall down",
        "few in number",
        "filled to capacity",
        "first and foremost",
        "for a period of",
        "for the purpose of",
        "foreign imports",
        "former ex",
        "freeze up",
        "gather together",
        "general consensus",
        "general public",
        "go back",
        "go forward",
        "grow in size",
        "had done previously",
        "has got",
        "he is a person who",
        "hear with one's own ears",
        "honest truth",
        "how to",
        "in close proximity",
        "in close quarters",
        "in the process of",
        "input into",
        "join together",
        "joint collaboration",
        "keep on",
        "located in",
        "look back in retrospect",
        "major breakthrough",
        "merge together",
        "mix together",
        "mutual cooperation",
        "mutual agreement",
        "natural instinct",
        "new beginning",
        "new creation",
        "new recruit",
        "null and void",
        "off of",
        "one and the same",
        "period of time",
        "personally, I",
        "plan ahead",
        "planned ahead",
        "positive benefit",
        "postpone until later",
        "preplan in advance",
        "present incumbent",
        "previously before",
        "protest against",
        "protrude out",
        "reason why",
        "refer back",
        "return back",
        "rise up",
        "safe haven",
        "same identical",
        "separate entities",
        "separate out",
        "shorter in length",
        "shout out",
        "skilled expert",
        "small in size",
        "still remains",
        "sum total",
        "surrounded all around",
        "surrounding circumstances",
        "temporary reprieve",
        "three a.m. in the morning",
        "tiny little",
        "true facts",
        "twelve midnight",
        "twelve noon",
        "ultimate end",
        "unanimous agreement",
        "usual custom",
        "visible to the eye",
        "wait for",
        "whether or not",
        "written down",
        "your own personal",
        "absolutely certain",
        "advance forward",
        "annual anniversary",
        "at this point in time",
        "basic necessity",
        "blatantly obvious",
        "brief in duration",
        "completely unanimous",
        "cooperate together",
        "could possibly",
        "currently existing",
        "each separate",
        "earlier before",
        "entirely complete",
        "exactly identical",
        "first began",
        "fully satisfy",
        "important essentials",
        "individual person",
        "integrate together",
        "introductory opening",
        "invited guests",
        "last final",
        "later on",
        "new and innovative",
        "original source",
        "outward appearance",
        "over and above",
        "past memories",
        "perfectly clear",
        "private industry",
        "proceed forward",
        "raise up",
        "regular routine",
        "reliable dependability",
        "return again",
        "revolve around",
        "round in shape",
        "sufficient enough",
        "surrounded on all sides",
        "very unique",
        "visible eyesight",
        "whole entire",
        "written record",
        "yet still",
        "adequate enough",
        "alternative choice",
        "as a matter of fact",
        "completely eliminate",
        "continue to remain",
        "eliminate altogether",
        "empty void",
        "exactly the same",
        "finished completely",
        "full and complete",
        "in the affirmative",
        "may perhaps",
        "never before",
        "new release",
        "one single",
        "originally created",
        "reassemble again",
        "recur again",
        "reflected back",
        "repeat the same",
        "still continue",
        "still persists",
        "unexpected emergency",
        "with reference to",
        "young child"
    ]

    private static let fillerPhrases: [String] = [
        "actually",
        "basically",
        "in my opinion",
        "in order to",
        "it is important to note that",
        "just",
        "kind of",
        "literally",
        "really",
        "simply",
        "somewhat",
        "sort of",
        "very",
        "you know",
        "at this point",
        "as you know",
        "by the way",
        "for example",
        "for instance",
        "in a sense",
        "in general",
        "in particular",
        "in other words",
        "in some ways",
        "in terms of",
        "it seems",
        "it appears",
        "of course",
        "needless to say",
        "more or less",
        "to be honest",
        "to be clear",
        "to be fair",
        "to be sure",
        "that said",
        "with that said",
        "having said that",
        "I think",
        "I believe",
        "I feel",
        "I would say",
        "I suppose",
        "I guess",
        "I mean",
        "you could say",
        "as a matter of fact",
        "as far as I know",
        "as far as I can tell",
        "as it were",
        "at the end of the day",
        "at the same time",
        "at this stage",
        "at this moment",
        "at this time",
        "by and large",
        "for the most part",
        "for what it is worth",
        "generally speaking",
        "in a way",
        "in any case",
        "in any event",
        "in essence",
        "in effect",
        "in fact",
        "in reality",
        "in truth",
        "more importantly",
        "on the other hand",
        "on the whole",
        "overall",
        "perhaps",
        "possibly",
        "probably",
        "rather",
        "quite",
        "relatively",
        "somehow",
        "technically",
        "ultimately",
        "usually",
        "whatever",
        "where possible",
        "as mentioned before",
        "as previously mentioned",
        "as noted above",
        "as noted earlier",
        "as stated above",
        "as stated earlier",
        "as we have seen",
        "as you can see",
        "as you might expect",
        "as a reminder",
        "for clarity",
        "for completeness",
        "for context",
        "for reference",
        "for now",
        "for the moment",
        "in conclusion",
        "in summary",
        "in short",
        "in brief",
        "in closing",
        "to conclude",
        "to summarize",
        "to sum up",
        "first of all",
        "to begin with",
        "to start with",
        "before we begin",
        "at the outset",
        "in the beginning",
        "last but not least",
        "finally",
        "secondly",
        "thirdly",
        "next",
        "then",
        "after all",
        "again",
        "also",
        "additionally",
        "besides",
        "furthermore",
        "moreover",
        "nevertheless",
        "nonetheless",
        "still",
        "however",
        "therefore",
        "thus",
        "so",
        "well",
        "okay",
        "alright",
        "look",
        "listen",
        "now",
        "anyway",
        "anyhow",
        "indeed",
        "obviously",
        "clearly",
        "naturally",
        "as expected",
        "it goes without saying",
        "it should be noted that",
        "it is worth noting that",
        "it is worth mentioning that",
        "one might argue",
        "one could argue",
        "it could be argued",
        "it is possible that",
        "it is likely that",
        "there is a chance that",
        "in my view",
        "from my perspective",
        "from my point of view",
        "in my experience",
        "as I see it",
        "if you will",
        "so to speak",
        "so-called",
        "in a manner of speaking",
        "in some respects",
        "in this regard",
        "in this case",
        "in that case",
        "in the meantime",
        "at the moment",
        "for the time being",
        "until then",
        "just about",
        "almost",
        "nearly",
        "kindly",
        "perhaps maybe",
        "maybe perhaps",
        "a little bit",
        "a bit",
        "in a little while",
        "as soon as possible",
        "at your earliest convenience",
        "if possible",
        "if necessary",
        "when possible",
        "where appropriate",
        "as needed",
        "and so on",
        "and so forth",
        "et cetera",
        "etcetera",
        "or something",
        "or whatever",
        "and things like that",
        "and the like",
        "for lack of a better word",
        "for want of a better word",
        "to put it simply",
        "to put it another way",
        "what I mean is",
        "what I am saying is",
        "the fact is",
        "the thing is",
        "the point is",
        "the truth is",
        "as a result",
        "because of this",
        "due to this",
        "in light of this",
        "with regard to",
        "with respect to",
        "in relation to",
        "in connection with",
        "on account of",
        "for this reason",
        "under these circumstances",
        "in the event that",
        "in the case of",
        "in the process of",
        "for the purpose of",
        "in an effort to",
        "with the aim of",
        "in an attempt to",
        "in the interest of",
        "at the present time",
        "at this point in time"
    ]

    static let clicheExpression = phraseExpression(clichePhrases)
    static let redundancyExpression = phraseExpression(redundancyPhrases)
    static let fillerExpression = phraseExpression(fillerPhrases)

    private static func phraseExpression(_ phrases: [String]) -> NSRegularExpression? {
        let alternatives = phrases
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
            .sorted { $0.count > $1.count }
            .map {
                NSRegularExpression.escapedPattern(for: $0)
                    .replacingOccurrences(of: " ", with: #"[\t ]+"#)
            }
            .joined(separator: "|")

        guard !alternatives.isEmpty else { return nil }

        let pattern = #"(?i)(?<![\p{L}\p{N}_])(?:"# +
            alternatives +
            #")(?![\p{L}\p{N}_])"#
        return try? NSRegularExpression(pattern: pattern)
    }
}
