/* AppSettings.c generated by valac 0.50.2, the Vala compiler
 * generated from AppSettings.vala, do not modify */

/*-
 * Copyright (c) 2017-2020 Lains
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib-object.h>
#include <glib.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>

#define QUILTER_TYPE_CONSTANTS (quilter_constants_get_type ())
#define QUILTER_CONSTANTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QUILTER_TYPE_CONSTANTS, QuilterConstants))
#define QUILTER_CONSTANTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QUILTER_TYPE_CONSTANTS, QuilterConstantsClass))
#define QUILTER_IS_CONSTANTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QUILTER_TYPE_CONSTANTS))
#define QUILTER_IS_CONSTANTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QUILTER_TYPE_CONSTANTS))
#define QUILTER_CONSTANTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QUILTER_TYPE_CONSTANTS, QuilterConstantsClass))

typedef struct _QuilterConstants QuilterConstants;
typedef struct _QuilterConstantsClass QuilterConstantsClass;
typedef struct _QuilterConstantsPrivate QuilterConstantsPrivate;
typedef struct _QuilterParamSpecConstants QuilterParamSpecConstants;

struct _QuilterConstants {
	GTypeInstance parent_instance;
	volatile int ref_count;
	QuilterConstantsPrivate * priv;
};

struct _QuilterConstantsClass {
	GTypeClass parent_class;
	void (*finalize) (QuilterConstants *self);
};

struct _QuilterParamSpecConstants {
	GParamSpec parent_instance;
};

static gpointer quilter_constants_parent_class = NULL;

gpointer quilter_constants_ref (gpointer instance);
void quilter_constants_unref (gpointer instance);
GParamSpec* quilter_param_spec_constants (const gchar* name,
                                          const gchar* nick,
                                          const gchar* blurb,
                                          GType object_type,
                                          GParamFlags flags);
void quilter_value_set_constants (GValue* value,
                                  gpointer v_object);
void quilter_value_take_constants (GValue* value,
                                   gpointer v_object);
gpointer quilter_value_get_constants (const GValue* value);
GType quilter_constants_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (QuilterConstants, quilter_constants_unref)
#define QUILTER_CONSTANTS_NARROW_MARGIN 1
#define QUILTER_CONSTANTS_MEDIUM_MARGIN 8
#define QUILTER_CONSTANTS_WIDE_MARGIN 16
#define QUILTER_CONSTANTS_NARROW_SPACING 1
#define QUILTER_CONSTANTS_MEDIUM_SPACING 4
#define QUILTER_CONSTANTS_WIDE_SPACING 8
#define QUILTER_CONSTANTS_SMALL_FONT 1
#define QUILTER_CONSTANTS_MEDIUM_FONT 2
#define QUILTER_CONSTANTS_BIG_FONT 3
#define QUILTER_CONSTANTS_TYPEWRITER_POSITION 0.55
QuilterConstants* quilter_constants_new (void);
QuilterConstants* quilter_constants_construct (GType object_type);
static void quilter_constants_finalize (QuilterConstants * obj);
static GType quilter_constants_get_type_once (void);

QuilterConstants*
quilter_constants_construct (GType object_type)
{
	QuilterConstants* self = NULL;
#line 19 "../src/Constants/AppSettings.vala"
	self = (QuilterConstants*) g_type_create_instance (object_type);
#line 19 "../src/Constants/AppSettings.vala"
	return self;
#line 94 "AppSettings.c"
}

QuilterConstants*
quilter_constants_new (void)
{
#line 19 "../src/Constants/AppSettings.vala"
	return quilter_constants_construct (QUILTER_TYPE_CONSTANTS);
#line 102 "AppSettings.c"
}

static void
quilter_value_constants_init (GValue* value)
{
#line 19 "../src/Constants/AppSettings.vala"
	value->data[0].v_pointer = NULL;
#line 110 "AppSettings.c"
}

static void
quilter_value_constants_free_value (GValue* value)
{
#line 19 "../src/Constants/AppSettings.vala"
	if (value->data[0].v_pointer) {
#line 19 "../src/Constants/AppSettings.vala"
		quilter_constants_unref (value->data[0].v_pointer);
#line 120 "AppSettings.c"
	}
}

static void
quilter_value_constants_copy_value (const GValue* src_value,
                                    GValue* dest_value)
{
#line 19 "../src/Constants/AppSettings.vala"
	if (src_value->data[0].v_pointer) {
#line 19 "../src/Constants/AppSettings.vala"
		dest_value->data[0].v_pointer = quilter_constants_ref (src_value->data[0].v_pointer);
#line 132 "AppSettings.c"
	} else {
#line 19 "../src/Constants/AppSettings.vala"
		dest_value->data[0].v_pointer = NULL;
#line 136 "AppSettings.c"
	}
}

static gpointer
quilter_value_constants_peek_pointer (const GValue* value)
{
#line 19 "../src/Constants/AppSettings.vala"
	return value->data[0].v_pointer;
#line 145 "AppSettings.c"
}

static gchar*
quilter_value_constants_collect_value (GValue* value,
                                       guint n_collect_values,
                                       GTypeCValue* collect_values,
                                       guint collect_flags)
{
#line 19 "../src/Constants/AppSettings.vala"
	if (collect_values[0].v_pointer) {
#line 156 "AppSettings.c"
		QuilterConstants * object;
		object = collect_values[0].v_pointer;
#line 19 "../src/Constants/AppSettings.vala"
		if (object->parent_instance.g_class == NULL) {
#line 19 "../src/Constants/AppSettings.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 163 "AppSettings.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 19 "../src/Constants/AppSettings.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 167 "AppSettings.c"
		}
#line 19 "../src/Constants/AppSettings.vala"
		value->data[0].v_pointer = quilter_constants_ref (object);
#line 171 "AppSettings.c"
	} else {
#line 19 "../src/Constants/AppSettings.vala"
		value->data[0].v_pointer = NULL;
#line 175 "AppSettings.c"
	}
#line 19 "../src/Constants/AppSettings.vala"
	return NULL;
#line 179 "AppSettings.c"
}

static gchar*
quilter_value_constants_lcopy_value (const GValue* value,
                                     guint n_collect_values,
                                     GTypeCValue* collect_values,
                                     guint collect_flags)
{
	QuilterConstants ** object_p;
	object_p = collect_values[0].v_pointer;
#line 19 "../src/Constants/AppSettings.vala"
	if (!object_p) {
#line 19 "../src/Constants/AppSettings.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 194 "AppSettings.c"
	}
#line 19 "../src/Constants/AppSettings.vala"
	if (!value->data[0].v_pointer) {
#line 19 "../src/Constants/AppSettings.vala"
		*object_p = NULL;
#line 200 "AppSettings.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 19 "../src/Constants/AppSettings.vala"
		*object_p = value->data[0].v_pointer;
#line 204 "AppSettings.c"
	} else {
#line 19 "../src/Constants/AppSettings.vala"
		*object_p = quilter_constants_ref (value->data[0].v_pointer);
#line 208 "AppSettings.c"
	}
#line 19 "../src/Constants/AppSettings.vala"
	return NULL;
#line 212 "AppSettings.c"
}

GParamSpec*
quilter_param_spec_constants (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags)
{
	QuilterParamSpecConstants* spec;
#line 19 "../src/Constants/AppSettings.vala"
	g_return_val_if_fail (g_type_is_a (object_type, QUILTER_TYPE_CONSTANTS), NULL);
#line 19 "../src/Constants/AppSettings.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 19 "../src/Constants/AppSettings.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 19 "../src/Constants/AppSettings.vala"
	return G_PARAM_SPEC (spec);
#line 231 "AppSettings.c"
}

gpointer
quilter_value_get_constants (const GValue* value)
{
#line 19 "../src/Constants/AppSettings.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QUILTER_TYPE_CONSTANTS), NULL);
#line 19 "../src/Constants/AppSettings.vala"
	return value->data[0].v_pointer;
#line 241 "AppSettings.c"
}

void
quilter_value_set_constants (GValue* value,
                             gpointer v_object)
{
	QuilterConstants * old;
#line 19 "../src/Constants/AppSettings.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QUILTER_TYPE_CONSTANTS));
#line 19 "../src/Constants/AppSettings.vala"
	old = value->data[0].v_pointer;
#line 19 "../src/Constants/AppSettings.vala"
	if (v_object) {
#line 19 "../src/Constants/AppSettings.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, QUILTER_TYPE_CONSTANTS));
#line 19 "../src/Constants/AppSettings.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 19 "../src/Constants/AppSettings.vala"
		value->data[0].v_pointer = v_object;
#line 19 "../src/Constants/AppSettings.vala"
		quilter_constants_ref (value->data[0].v_pointer);
#line 263 "AppSettings.c"
	} else {
#line 19 "../src/Constants/AppSettings.vala"
		value->data[0].v_pointer = NULL;
#line 267 "AppSettings.c"
	}
#line 19 "../src/Constants/AppSettings.vala"
	if (old) {
#line 19 "../src/Constants/AppSettings.vala"
		quilter_constants_unref (old);
#line 273 "AppSettings.c"
	}
}

void
quilter_value_take_constants (GValue* value,
                              gpointer v_object)
{
	QuilterConstants * old;
#line 19 "../src/Constants/AppSettings.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QUILTER_TYPE_CONSTANTS));
#line 19 "../src/Constants/AppSettings.vala"
	old = value->data[0].v_pointer;
#line 19 "../src/Constants/AppSettings.vala"
	if (v_object) {
#line 19 "../src/Constants/AppSettings.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, QUILTER_TYPE_CONSTANTS));
#line 19 "../src/Constants/AppSettings.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 19 "../src/Constants/AppSettings.vala"
		value->data[0].v_pointer = v_object;
#line 294 "AppSettings.c"
	} else {
#line 19 "../src/Constants/AppSettings.vala"
		value->data[0].v_pointer = NULL;
#line 298 "AppSettings.c"
	}
#line 19 "../src/Constants/AppSettings.vala"
	if (old) {
#line 19 "../src/Constants/AppSettings.vala"
		quilter_constants_unref (old);
#line 304 "AppSettings.c"
	}
}

static void
quilter_constants_class_init (QuilterConstantsClass * klass,
                              gpointer klass_data)
{
#line 19 "../src/Constants/AppSettings.vala"
	quilter_constants_parent_class = g_type_class_peek_parent (klass);
#line 19 "../src/Constants/AppSettings.vala"
	((QuilterConstantsClass *) klass)->finalize = quilter_constants_finalize;
#line 316 "AppSettings.c"
}

static void
quilter_constants_instance_init (QuilterConstants * self,
                                 gpointer klass)
{
#line 19 "../src/Constants/AppSettings.vala"
	self->ref_count = 1;
#line 325 "AppSettings.c"
}

static void
quilter_constants_finalize (QuilterConstants * obj)
{
	QuilterConstants * self;
#line 19 "../src/Constants/AppSettings.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QUILTER_TYPE_CONSTANTS, QuilterConstants);
#line 19 "../src/Constants/AppSettings.vala"
	g_signal_handlers_destroy (self);
#line 336 "AppSettings.c"
}

static GType
quilter_constants_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { quilter_value_constants_init, quilter_value_constants_free_value, quilter_value_constants_copy_value, quilter_value_constants_peek_pointer, "p", quilter_value_constants_collect_value, "p", quilter_value_constants_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (QuilterConstantsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) quilter_constants_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QuilterConstants), 0, (GInstanceInitFunc) quilter_constants_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType quilter_constants_type_id;
	quilter_constants_type_id = g_type_register_fundamental (g_type_fundamental_next (), "QuilterConstants", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return quilter_constants_type_id;
}

GType
quilter_constants_get_type (void)
{
	static volatile gsize quilter_constants_type_id__volatile = 0;
	if (g_once_init_enter (&quilter_constants_type_id__volatile)) {
		GType quilter_constants_type_id;
		quilter_constants_type_id = quilter_constants_get_type_once ();
		g_once_init_leave (&quilter_constants_type_id__volatile, quilter_constants_type_id);
	}
	return quilter_constants_type_id__volatile;
}

gpointer
quilter_constants_ref (gpointer instance)
{
	QuilterConstants * self;
	self = instance;
#line 19 "../src/Constants/AppSettings.vala"
	g_atomic_int_inc (&self->ref_count);
#line 19 "../src/Constants/AppSettings.vala"
	return instance;
#line 371 "AppSettings.c"
}

void
quilter_constants_unref (gpointer instance)
{
	QuilterConstants * self;
	self = instance;
#line 19 "../src/Constants/AppSettings.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 19 "../src/Constants/AppSettings.vala"
		QUILTER_CONSTANTS_GET_CLASS (self)->finalize (self);
#line 19 "../src/Constants/AppSettings.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 385 "AppSettings.c"
	}
}

